### ISSUE TITLE
FOG Dev trunk fails install/upgrade when behind a proxy - PPA PUBKEY fail at install.

### ISSUE THREAD

**Issue by ubergeeken** [FOGProject/fogproject#103]
Hi folks,
I'm a long time FOG user and found an issue when using the SVN/GIT trunk release. 
Installation on a system that had a raw (no proxy/firewall) connection is able to reach out during the installation and pull down all packages, without issue. 
When testing the installation behind a corporate proxy, the first phase of "Adding needed repository" the process will fail out. I've also setup a clean Squid proxy as a test to see if there was anything mysterious about the 3rd party corporate proxy  - same issue.
I've done a little tweeking and now have it making it through some of the installation, BUT as it goes through the list of packages, when it gets to the first package that needs to be pulled down from the internet via APT (on the Ubuntu server) it fails. 
In this case, the first package that is not installed locally is php5-mcrypt. 

I then try to install php5-mcrypt manually with the typical "apt-get install php5-mcrypt" and I get a warning that all of the dependencies can not be verified "WARNING: The following dependencies can not be authenticated!"

A quick "apt-get update" and I get an error that states:
    W: GPG error: http://ppa.launchpad.net trusty InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 4F4EA0AAES267A6C"

#################
I've worked from a clean install and an upgrade type test and the trunks consistently fail in the same way. 

What packages are in the ppa.launchpad.net that are not available in the public archives?

Is there a step missing in the install scripts to pull the public key?

For a while I though that there might be a non-APT function trying to reach out to the internet, but I setup APT, GIT and SVN to point to the proxy. 
I've verified that APT, GIT and SVN all are able to reach through the proxy and in fact, I upgraded Ubuntu 12.04 to 14.04 LTS with all patches through the same proxy, without issue. 
########################

systems tested on:
Ubuntu 12.04 LTS, 14.04 LTS, 16.04 LTS
Virtual machines with 8 cores,  16GB Ram and 400GB of storage
Scripts all run as root via "sudo su"
VMware ESXi 6.0 and 5.5 in production networks
Proxmox 4.x in test lab

Regards,
Ubergeeken

**Comment by ubergeeken** [comment]
Looking at this a little further....   
The following file is being added to /etc/apt/sources.list.d
      ondrej-php5-5_6-trusty.list
The Debian package PPA in the file is 
      deb http://ppa.launchpad.net/ondrej/php5-5.6/ubuntu trusty main
If I comment this out, I can manually install the packages.
I seem to be running into an issue getting the PUBKEY for this PPA through any of the proxies. 

Thoughts?

**Comment by ghooper90** [comment]
You might want to continue this in the fog forum to get better exposure. 

But with that said, I run my fog servers behind corporate proxies. In my case I use RHEL/Centos for the fog servers so I have to do 2 steps (I know they don't directly translate to Ubuntu). 

1) Add a line to yum.conf proxy=http://192.168.1.100:3128 
2) Update /etc/bashrc and add in 
export http_proxy=http://192.168.1.100:3128 
export https_proxy=http://192.168.1.100:3128 
export ftp_proxy=http://192.168.1.100:3128 
export no_proxy="localhost,127.0.0.1,<fog_server_ip_address>" 

Then logout and back in. After that the fog installer scripts should access the internet without issue. 

Geo 

----- Original Message -----

**Comment by mastacontrola** [comment]
closing as this is related to the proxy issue which is all capable of being edited/adjusted per each config.

Mind you, the .fogsettings file can also hold those variables for you as that file is loaded before any major work begins.
