### ISSUE TITLE
minor - bandwidth graph

### ISSUE THREAD

**Issue by TheSchnak** [FOGProject/fogproject#106]
default is 2 minutes for polling, when selecting a new polling interval the graph updates multiple times in the normal 5sec polling interval. repeatedly changing the graph size results in polling several times a second.

**Comment by mastacontrola** [comment]
Changing the graph size?  I don't know that you can change the size, or you mean changing the options on the top?

**Comment by TheSchnak** [comment]
Not the size. The duration that the graph shows. 2m -1hr. Also happens when
switching between transmitted and recieved. This was in the chrome browser
i have not tried the others.

**Comment by mastacontrola** [comment]
I understood what you meant this time around.

I've updated the code base.  Bandwidth will not update on clicks, and relevant timings will still remain.
