### ISSUE TITLE
Image Change Log

### ISSUE THREAD

**Issue by RobertDavidson** [FOGProject/fogproject#107]
We have been using a heavily modified fog version 0.32 and plan to move 1.3 as soon as soon as a stable release comes out. One thing I find myself wanting is an image change log within the fog UI. This would help us keep track of our image changes that take place (for us quarterly) and also inform our end users of "what's new/different". It would also be nice from the registration screen for the end user to print the change log to screen OR have a front end (non authenticated) section of the fog site show these change log for each image.

Just a suggestion if it's not already in there.

Great project guys, love FOG!

**Comment by mastacontrola** [comment]
I think I follow what you're requesting, but I'm not sure there's a good approach.

Your best bet for tracking, I suppose, would be to simply update the Description parameter when you push a new update to the image.  Yes it's more work on you.  There's not really a good way to determine what's changed between images because the data is copied at the block level, which means we're ultimately unaware of changes in files.  The best we could do is provide a checksum difference, of which I know somebody is working on a plugin for already.

I know it's not the answer you were probably looking for, and I'm always open to other suggestions if you'd be so kind.

**Comment by RobertDavidson** [comment]
Sorry I didn't express my thoughts clearly. In fact we are actually already using the description field to hold our change log notes, but end users cannot see it. I wasn't speaking of doing a bit by bit comparison.

Instead it would be nice somewhere on the image page to submit change logs through a simple form:
For example:

May 19, 2016
- Installed Windows Updates
- Updated: Java, Flash, Kaspersky, Chrome, Reader
- Added firewall exception for remote services
- Uninstalled Quicktime (No longer being updated by Apple)

Then you submit it and it would record it to a table with the timestamp, username, etc. This table could then be used to look as historical image changes or Select TOP(1) most recent entry for if the end user is wanting to see the change log from the registration screen.

**Comment by mastacontrola** [comment]
What about making a plugin that creates the table and form for you?  You can tie that plugin with other elements, which I may need to make a few edits for as needed, but it would allow expansion of the FOG System.  I know our plugin system is a bit complex initially, but I'm almost always available to help and assist as best I can.  Were you aware we had a plugin system?  Under the trunk version (what will hopefully soon become 1.3.0) the plugins are quite nice I think.  A little refining sure, but still they're pretty good at adapting the needs of one user, and allow a potential for the betterment of the FOG system in whole.

**Comment by RobertDavidson** [comment]
I had no idea there was a plugin system. We have made adjustments to the 0.32 code as needed in the past, but I'm looking forward to this.

**Comment by mastacontrola** [comment]
To "see" the plugins, go to FOG Configuration Page->FOG Settings->Plugin System.

Enable the checkbox for FOG_PLUGINSYS_ENABLE or something like that.

Then you'll see a new menu icon appear.  Click on that icon and you'll be presented with all the current plugins.  Accesscontrol is not good, and I'm thinking about removing the "menu" items it enables.

Example doesn't do anything, it's literally just a place kind of like a "template".  Most often, however, I use a working plugin to copy and edit as needed.

Let me know if you need any help please.

**Comment by RobertDavidson** [comment]
Wow didn't even know that was there. I enabled it, but don't see much just "capone"

**Comment by mastacontrola** [comment]
What version did you install, or are you still running 0.32?

**Comment by RobertDavidson** [comment]
Still running 0.32. I can spin up a VM tomorrow and install 1.30 trunk.

**Comment by mastacontrola** [comment]
Please, you'll see a TON more stuff and hopefully like it.

**Comment by RobertDavidson** [comment]
Is there an issue with the install script on Ubuntu 16.04? 

Enter new UNIX password: Retype new UNIX password: passwd: password updated successfully
Failed to stop FOGMulticastManager.service: Unit FOGMulticastManager.service not loaded.
Failed to stop FOGImageReplicator.service: Unit FOGImageReplicator.service not loaded.
Failed to stop FOGSnapinReplicator.service: Unit FOGSnapinReplicator.service not loaded.
Failed to stop FOGScheduler.service: Unit FOGScheduler.service not loaded.
Failed to stop FOGPingHosts.service: Unit FOGPingHosts.service not loaded.
Synchronizing state of mysql.service with SysV init with /lib/systemd/systemd-sysv-install...
Executing /lib/systemd/systemd-sysv-install enable mysql
● mysql.service - MySQL Community Server
   Loaded: loaded (/lib/systemd/system/mysql.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2016-06-23 11:28:02 CDT; 2s ago
  Process: 3598 ExecStartPost=/usr/share/mysql/mysql-systemd-start post (code=exited, status=0/SUCCESS)
  Process: 3592 ExecStartPre=/usr/share/mysql/mysql-systemd-start pre (code=exited, status=0/SUCCESS)
 Main PID: 3597 (mysqld)
    Tasks: 28
   Memory: 132.7M
      CPU: 223ms
   CGroup: /system.slice/mysql.service
           └─3597 /usr/sbin/mysqld

Jun 23 11:28:01 CISD-FOG systemd[1]: Starting MySQL Community Server...
Jun 23 11:28:02 CISD-FOG systemd[1]: Started MySQL Community Server.
Failed to stop php5-fpm.service: Unit php5-fpm.service not loaded.

**Comment by mastacontrola** [comment]
Follow this first please:

https://wiki.fogproject.org/wiki/index.php?title=Ubuntu_16.04

**Comment by mastacontrola** [comment]
Any luck or information yet?

**Comment by darksidemilk** [comment]
So concerning image change logs. Something integrated into fog would be pretty cool but I already do it outside of fog. This may sound a bit complicated to set up, but once it's set up it works beautifully and elegantly.

I have a private github repo that I store scripts and change logs in.
The github repo is synced hourly to a linux samba share on one of my file servers. So I can always quickly access my repo contents locally.
I have a image prep script I run before I upload an image, and within that script it copies the most recent version of the related image log to C:\ImageVersion.log. I name each log according to the hostname of the VM I make the image on. Then a batch script can easily parse the hostname into the title and violia. 

As complicated as that may sound. It's actually pretty simple. You have one shared storage area where you make image logs. And before a image is uploaded, the latest version of the change log is copied to it in a location accessible to end users. And a master version is accessible to you from anywhere. You can also quickly compare a user's image version with the current one this way.

Granted, if this same idea was integrated into fog, it would be pretty cool. Not sure how many of my users would take advantage of it, but still cool.

As for the image prep script, I intend to post it in the not too distant future to https://forums.fogproject.org/

**Comment by RobertDavidson** [comment]
I decided to go back to 14.04. The install went smooth, however I'm having permissions problems when mounting our NAS instead of using storage nodes. I will check back in once we get the permission issue worked out.

**Comment by mastacontrola** [comment]
Do you have any other follow up for this?  Would you be kind enough to register (if not already registered) for the forums and see if multiple people could help comment, suggest, tweak, etc...?  I ask this cause while we are more than happy to help, sometimes the forums are much Faster.

**Comment by mastacontrola** [comment]
I'm closing this issue request for now.  If you still would like to get help with this, please comment here, or ask the forums.  I'm almost always on the forums and there's many others there who may be able to help with what you're needing as well.
