### ISSUE TITLE
[Enhancements] Automate IP change.

### ISSUE THREAD

**Issue by wwwanaya** [FOGProject/fogproject#108]
Hello FOG team,

I'm using FOG in a isolated network right now. And I'm performing some testing to before deploy it on my whole network. So, I have change the IP a couple of times. 

I consider should be good have one script to do it. 
Just like [vicidial](https://github.com/h4ck3rm1k3/vicidial-asterisk-gui/blob/master/bin/ADMIN_update_server_ip.pl). 

Steps towards to make it more automate. 
Sound quite simple save the current IP in a variable, make the changes on the DB, and Update the `dhcpd.conf` and `default.ipxe` (I had twice headache to find out this) with bash.

Right now I save my changes on default.ipxe with the variable ${next-server}. and it works as rock! 

Note: I'm not sure from where `${next-server}` came, but should came from dhcpd.conf?

Hopefully this help. You're doing a great job with this.

Regards,
Kevin.

**Comment by wayneworkman** [comment]
Hello, @wwwanaya 

I've created a little package that runs on Fedora & CentOS that makes FOG 1.3.0 completely mobile, and able to accept DHCP and work on any network for BIOS systems via dnsmasq. Recently I've helped a fellow from the fog forums to implement this within his school district. It worked well for him. Find the link here, and please contact me with any questions: 
[FOGUpdateIP](https://github.com/wayneworkman/FOGUpdateIP)

**Comment by mastacontrola** [comment]
I've updated the script a bit with @wayneworkman today.  While it's still a bit on the Redhat side, converting to be more distro agnostic shouldn't be too hard.

I'm going to close this issue as this other project will most certainly help assist in updating the IP's, albeit not quite fully automated.
