### ISSUE TITLE
Wrong link to Capture Task

### ISSUE THREAD

**Issue by ponsfrilus** [FOGProject/fogproject#110]
Fog Info:
Running Version 8405
SVN Revision: 5829

How to reproduce:
  1. Task Management
  1. List All Hosts
  1. Click the Capture icon of an host
=> The created task is "Quick Deploy" instead of "Capture"

![gifrecord_2016-07-04_135741](https://cloud.githubusercontent.com/assets/176002/16559784/a649a254-41ef-11e6-880f-ec21ba92b8db.gif)

**Comment by mastacontrola** [comment]
This was not a wrong "link" persay.  The proper task type was still being used, but the task name was defaulted to "quick depoy" as you saw.  I've since corrected this.
