### ISSUE TITLE
PHP white screen on Arch Linux (1.3.0-dev)

### ISSUE THREAD

**Issue by jabesga** [FOGProject/fogproject#112]
Hi, I'm getting a white death screen when installing the Development (1.3.0-dev) version on Arch Linux.

I've enabled the PHP error reporting and I get:
`
Fatal error: Uncaught Error: Call to undefined function _() in /srv/http/fog/commons/text.php:13 Stack trace: #0 /srv/http/fog/commons/base.inc.php(8): require() #1 /srv/http/fog/management/index.php(5): require('/srv/http/fog/c...') #2 {main} thrown in /srv/http/fog/commons/text.php on line 13`

But I don't get to understand what's wrong with the file text.php.

**Comment by mastacontrola** [comment]
https://bbs.archlinux.org/viewtopic.php?id=102838

**Comment by mastacontrola** [comment]
_( ) is a function referencing PHP Gettext.  This is most likely not enabled in your php.ini file.

Please enable and restart http and php-fpm services.  All should then work properly.

**Comment by jabesga** [comment]
Exactly. The PHP extension was disabled. Thanks!

**Comment by mastacontrola** [comment]
I'll check the code base for the arch installation see if I can automate this a bit more.
