### ISSUE TITLE
FOG is unable to communicate with the database on Arch Linux

### ISSUE THREAD

**Issue by jabesga** [FOGProject/fogproject#113]
I'm getting the message:

> 
Your database connection appears to be invalid. FOG is unable to communicate with the database. There are many reasons why this could be the case. Please check your credentials in /srv/http/fog/lib/fog/config.class.php. Also confirm that the database is indeed running. If credentials are correct, and the Database service is running, check to ensure your filesystem has enough space.

My file srv/http/fog/lib/fog/config.class.php contains:

```
    private static function db_settings() {
        define('DATABASE_TYPE','mysql'); // mysql or oracle
        define('DATABASE_HOST','127.0.0.1');
        define('DATABASE_NAME','fog');
        define('DATABASE_USERNAME','root');
        define('DATABASE_PASSWORD',"root");
    }
```

Also, the mysql service is running and I can access to the database successfully with the command:

```
mysql -u root -proot -h 127.0.0.1 -D fog  
```

What could be happening?

P.S: I'm using MariaDB, Server version: 10.1.14-MariaDB MariaDB Server

**Comment by mastacontrola** [comment]
My guess, php-pdo and/or php-mysqli are not enabled?

**Comment by jabesga** [comment]
They are enabled.

**Comment by mastacontrola** [comment]
Then what are you seeing in error logs?

**Comment by jabesga** [comment]
Error logs where?

**Comment by mastacontrola** [comment]
I imagine in /var/log/httpd,

However arch is strange.  I don't know the exact paths off the top of my head.

I want to say /var/log/httpd/error_log

**Comment by jabesga** [comment]
I was asking because there is where I was looking for. I don't see anything weird (apart of the query returning false)

```
192.168.2.232 - - [18/Jul/2016:19:15:27 +0200] "GET /fog/status/dbrunning.php?node=schema HTTP/1.1" 200 34
192.168.2.232 - - [18/Jul/2016:19:16:57 +0200] "GET /fog/status/dbrunning.php?node=schema HTTP/1.1" 200 34
192.168.2.232 - - [18/Jul/2016:19:17:05 +0200] "GET /fog/status/dbrunning.php?node=schema HTTP/1.1" 200 34
192.168.2.232 - - [18/Jul/2016:19:26:51 +0200] "GET /fog/status/dbrunning.php?node=schema HTTP/1.1" 200 34
192.168.2.232 - - [18/Jul/2016:19:27:10 +0200] "GET /fog/status/dbrunning.php?node=schema HTTP/1.1" 200 34
```

**Comment by mastacontrola** [comment]
That appears to be the access_log, not the error log.

**Comment by mastacontrola** [comment]
I'm creating an arch system to test with.

**Comment by jabesga** [comment]
I don't have an error log file. I've deleted it and I don't generate errors when making the request.

**Comment by mastacontrola** [comment]
I don't know how to help you then.

Error logs should be there and be telling us what's going on.

What's the output of:

`df -h`

**Comment by jabesga** [comment]
```
Filesystem      Size  Used Avail Use% Mounted on
dev             1.9G     0  1.9G   0% /dev
run             1.9G 1000K  1.9G   1% /run
/dev/sda2       917G   14G  857G   2% /
tmpfs           1.9G  1.5M  1.9G   1% /dev/shm
tmpfs           1.9G     0  1.9G   0% /sys/fs/cgroup
tmpfs           1.9G  2.9M  1.9G   1% /tmp
/dev/sda1       511M   27M  485M   6% /boot
tmpfs           385M   16K  385M   1% /run/user/120
tmpfs           385M   16K  385M   1% /run/user/1000
```

**Comment by mastacontrola** [comment]
Did you have to enable the pdo/mysqli extensions like you had to with gettext?

**Comment by jabesga** [comment]
This are my extensions in php.ini
```
;extension=bcmath.so
;extension=bz2.so
;extension=calendar.so
extension=curl.so
;extension=dba.so
;extension=enchant.so
;extension=exif.so
extension=ftp.so
extension=gd.so
extension=gettext.so
;extension=gmp.so
;extension=iconv.so
;extension=imap.so
;extension=intl.so
;extension=ldap.so
extension=mcrypt.so
extension=mysqli.so
;extension=odbc.so
;zend_extension=opcache.so
;extension=pdo_dblib.so
extension=pdo_mysql.so
;extension=pdo_odbc.so
;extension=pdo_pgsql.so
;extension=pdo_pgsql.so
;extension=pdo_sqlite.so
;extension=pgsql.so
;extension=pspell.so
;extension=shmop.so
;extension=snmp.so
;extension=soap.so
extension=sockets.so
;extension=sqlite3.so
;extension=sysvmsg.so
;extension=sysvsem.so
;extension=sysvshm.so
;extension=tidy.so
;extension=xmlrpc.so
;extension=xsl.so
extension=zip.so
```

and this my compiled in modules:

```
> $ php -m | grep -i pdo                                                                                                                             
PDO
pdo_mysql

```

**Comment by jabesga** [comment]
If it helps, seems that FOG is using the _pdodb.class.php_ instead of the _mysql.class.php_

**Comment by jabesga** [comment]
I solved changing the line in /fog/lib/db/databasemanager.class.php:

`self::$DB = FOGCore::getClass('PDODB'); `

by:

`self::$DB = FOGCore::getClass('MySQL'); `

However, I don't know why it was using that mode.

**Comment by mastacontrola** [comment]
I don't recommend using MySQL class any longer.  It's there solely as an in case.

I was driving home so unable to respond sooner.  For that I'm sorry.

Please change back to PDODB.

**Comment by jabesga** [comment]
I changed back to PDODB.

And now it connects to the DB...

**Comment by mastacontrola** [comment]
That's really strange.

I saw the same issues, but just told it to reboot.  It almost seemed that it was failing because php-fpm wasn't running? Odd that it's working after first going to MySQL class.

**Comment by jabesga** [comment]
I've deleted everything related to FOGProject and started the process of installation again.

This time everything works like a charm. I don't think I can replicate the problem again.

Anyway, thanks for your time @mastacontrola

**Comment by mastacontrola** [comment]
Closed the issue.

So others who may run into this, all I did was make sure the pdo_mysql and mysqli extensions were enabled.  Once done, I restarted the system.  I am under the wonderance if php-fpm service just had a quirk in timing?  It seems odd that it wasn't working, then magically started working.

When in doubt, please stop http and php-fpm, then start php-fpm and http.  If you still see the same issue, try restarting the server.  If all else fails, please try as @jabesga did and change class to mysql, then back to pdodb.  Maybe it just needs an established connection first (which seems really strange).
