### ISSUE TITLE
Storage Nodes not being registered automatically upon installation

### ISSUE THREAD

**Issue by wayneworkman** [FOGProject/fogproject#116]
I've deleted my storage node from Storage Management via the web interface, and then ran the installer on the storage node as usual, it has the correct fogstorage credentials already within /opt/fog/.fogsettings. The storage node did not automatically register itself inside Storage Management.

**Comment by mastacontrola** [comment]
Just tested, removed node from FOG, re-ran installer, all worked perfectly.

**Comment by mastacontrola** [comment]
Apparently my testing was incorrect.  I must've had a double type for it.

There was a typo in the fogverified variable.  This will be available in RC-5
