### ISSUE TITLE
What happend to "FOG_PXE_IMAGE_DNSADDRESS"

### ISSUE THREAD

**Issue by Nightreaver** [FOGProject/fogproject#117]
We've got the following problem.
We need to change the DNS that is served through DHCP to a custom one. Because to have to work around our existing infrastructure and need to set an IP for a storage-node based on the network/subnet. and this is handled by a separate DNS server.

In older versions of fog there was a Setting for DNS, now its gone.
I still can find "FOG_PXE_IMAGE_DNSADDRESS" in schema.php and schema-modify.php but no where else.

Is there a way to overwrite DNS in the "init" image?

**Comment by mastacontrola** [comment]
This setting, in 1.3.0/Trunk/Dev versions of FOG are not, any longer, used.  The init's automatically obtain DNS from the DHCP server as is normally performed for most environments.  The setting you see in the schema is from days past when that setting was used, and get's removed later on in the schema information.

I'd recommend setting your DHCP Server to hand out the proper DNS information to the subnet as needed.  If you're setting an IP address for the storage node, though, DNS would not need to be used anyway, as it's passing information directly, it's not having to lookup the IP associated to a name.

**Comment by Nightreaver** [comment]
The thing is that if we want to reimage about 50 hosts a once, having one storage node for all networks would cause a lot of traffic going through our firewall, this is why we've setup a separate storage node with 2x 10Gbit tengi-ports.
The storage node has one IP in each network, eg 
192.168.100.253 , delivered to hosts inside 192.168.100.0 network
also for 192.168.101.0 the node is 192.168.101.253 and so on. 

The the storage node is resolved by name, and the name "fogstor001" is resolved to the "native" ip in each subnet.

afaik, we have no option to serve this with our windows server dns. and if we pass the dns request from our windows dns to our bind9 dns, it is always resolved using the ip address of our windows dns, making the whole thing useless.

any best practices for this situation?

**Comment by mastacontrola** [comment]
To my knowledge, Windows DHCP can handle what dns is pointed for it's particular subnet.  However, as you have (in the example at least) three subnets, you'd be best to be using VLAN's. (Assuming you're not already).

These VLAN's should be able to communicate with the "Central" DHCP server, which that DHCP server is forwarding to specify DNS (if I'm understanding the current layout).

What this means, is you would need to know the realm of which the system is calling from.  The easiest way I can say is to simply use Windows DNS and have the records show to all three IP's at the same time.

In /etc/hosts this might looklike:

192.168.100.xxx (whatever fogstor001 resolves to here)
192.168.101.xxx (whatever fogstor001 resolves to here)


SO in your case, .253 is resolving to the same host on both subnets.

You would have a dns entry for the 192.168.100.253 resolving to fogstor001 on the 192.168.100.0 network and a dns entry for the 192.168.101.253 resolving to fogstor001 on the 192.168.101.0 network.

Hopefully this helps.  In either case, you may need to look at the Windows Server anyway and it shouldn't be too hard to figure out.
