### ISSUE TITLE
PHP Fatal error:  Call to undefined function mcrypt_get_iv_size() in /var/www/html/fog/lib/fog/fogbase.class.php

### ISSUE THREAD

**Issue by alismayilov** [FOGProject/fogproject#118]
I have upgraded my Ubuntu server to 16.04, pull latest fogproject code from github and successfully installed fog. Fog works partially after this upgrade. For example, I can login and I can check all images. But when I check hosts, I got blank page. I checked apache2 error log. It says: 
`[Mon Aug 15 15:16:43.045214 2016] [:error] [pid 25755] [client 192.168.0.1:47032] PHP Fatal error:  Call to undefined function mcrypt_get_iv_size() in /var/www/html/fog/lib/fog/fogbase.class.php on line 417, referer: http://192.168.0.1/fog/management/index.php?node=host&sub=list
[Mon Aug 15 15:16:43.045312 2016] [:error] [pid 25755] [client 192.168.0.1:47032] PHP Stack trace:, referer: http://192.168.0.1/fog/management/index.php?node=host&sub=list
[Mon Aug 15 15:16:43.045327 2016] [:error] [pid 25755] [client 192.168.0.1:47032] PHP   1. {main}() /var/www/html/fog/management/index.php:0, referer: http://192.168.0.1/fog/management/index.php?node=host&sub=list
[Mon Aug 15 15:16:43.045336 2016] [:error] [pid 25755] [client 192.168.0.1:47032] PHP   2. FOGPageManager->render() /var/www/html/fog/management/index.php:23, referer: http://192.168.0.1/fog/management/index.php?node=host&sub=list
[Mon Aug 15 15:16:43.045345 2016] [:error] [pid 25755] [client 192.168.0.1:47032] PHP   3. HostManagementPage->edit() /var/www/html/fog/lib/fog/fogpagemanager.class.php:72, referer: http://192.168.0.1/fog/management/index.php?node=host&sub=list
[Mon Aug 15 15:16:43.045369 2016] [:error] [pid 25755] [client 192.168.0.1:47032] PHP   4. FOGBase->aesdecrypt() /var/www/html/fog/lib/pages/hostmanagementpage.class.php:272, referer: http://192.168.0.1/fog/management/index.php?node=host&sub=list
`
Is this an issue, or I did something wrong?

**Comment by mastacontrola** [comment]
Can you try installing: `php7.0-mcrypt`

**Comment by alismayilov** [comment]
It was already installed.
 `# sudo apt-get install php7.0-mcrypt
Reading package lists... Done
Building dependency tree       
Reading state information... Done
php7.0-mcrypt is already the newest version (7.0.9-1+deb.sury.org~xenial+1).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
`

**Comment by mastacontrola** [comment]
If you run:  `php7.0enmod mcrypt`?

**Comment by alismayilov** [comment]
php7.0enmod: command not found

**Comment by mastacontrola** [comment]
Try:

`apt-get install mcrypt`

Restart apache2?

**Comment by alismayilov** [comment]
I found problem. Apparently, php7.0 installed, but apache2 was using php5.6. I disabled php5.6, delete php5.conf and php5.load files. Enabled php7.0. It works now.  You can close this issue. Sorry it was my mistake.

**Comment by mastacontrola** [comment]
no problem.  I was looking to see what was happening, but as always there's a few quirks here and there.
