### ISSUE TITLE
Call to a member function getMasterStorageNode() on null

### ISSUE THREAD

**Issue by Nightreaver** [FOGProject/fogproject#119]
Hello

I hit a problem today.

The error comes up when i want to *force* capture a host.
The host gets stuck at "attempt to check in... failed"
 I can see an error in apache error log

```
 PHP Fatal error:  Call to a member function getMasterStorageNode() on null in /var/www/html/fog/lib/reg-task/taskqueue.class.php on line 28
```

When I check the php file I can find  
`else if ($this->Task->isForced())` a few lines above the error-line L#28, so tried a capture job *without* "forcing" it, and it works.

So what is different in these two jobs? regarding on how they get the master storage node?
We have 1 default storage group, with one storage node which is checked as master-node.

Cheers

**Comment by mastacontrola** [comment]
The Line:
`if ($this->Task->isCapture()) $this->StorageNode = $this->Image->StorageGroup->getMasterStorageNode();` Is wrong, and that's my bad, though looking at the working-RC-9 this doesn't appear to be occurring any more.

This line should read:
`if ($this->Task->isCapture()) $this->StorageNode = $this->Image->getStorageGroup()->getMasterStorageNode();`

If you make that change to line 28 does this fix the issue as it stands for you now?

**Comment by Nightreaver** [comment]
I can update to RC-9 tmr or change the line, keep you updated

**Comment by Nightreaver** [comment]
Looks good! thanks

**Comment by mastacontrola** [comment]
I'm going to close the issue then.
