### ISSUE TITLE
Fog install/update overwrites apache2 config

### ISSUE THREAD

**Issue by Nightreaver** [FOGProject/fogproject#120]
Hello.. it's me again!

I've setup our server and decided to do an update. During the update you are delivering an apache2 config in '001-fog.conf' this always overwrites the local changes I had to make for our SSL.

Can you put the apache2 ssl config for FOG in an optional config file, so its not overwritten every time I do an update?

Even if it might not break anything, the SSL path's look like ' SSLCertificateChainFile /var/www/html/fog//management/other/ca.cert.der' with double //

Regards

**Comment by darksidemilk** [comment]
You could also have an update script like this one on the forums that backs up any custom configurations and restores them after the update. You’ll have to alter it a bit for your ssl but the examples should help. It’s a bit old at this point so read over it carefully. https://forums.fogproject.org/topic/6331/automating-git-updates-for-fog Hope that helps.

**Comment by mastacontrola** [comment]
I've added initial potential to allow you to enter your own private key.  Fog's other systems are kind of dependent on the declared public key locations, which should have limited impact to your requirements.

The flag is sslprivkey and it will be added to the fogsettings file.  You can make this inline as a part of your initial install by simply prepending the command with:

`sslprivkey='/path/to/your/privatekeyfile' ./installfog.sh -y`

You don't need to do this every time.  You also can simply add sslprivkey='/path/to/your/privatekeyfile' to the fogsettings file.

Of course this is untested but theoretically should work as ultimately it's the defining bit.

Hopefully this will help with what you're needing.

**Comment by Nightreaver** [comment]
Is this practical?
For my apache2 ssl config I need the cert, the key and the chain, maybe other settings in the future.
I think is easier to tell fog to _not_ include ssl in the default `001-fog.conf` so I can have my separate `001-fog-ssl.conf` beside this.

**Comment by mastacontrola** [comment]
SSL Information is not required in the vhost information.

So Unless you're installing with enforcing the ssl status, you should be able to have your own 001-fog-ssl.conf already without impacting anything else.

I recreate the files only because we need to know what is setup and ensure all is proper.  You can setup your own, of course, but in your case you've already defined an ssl conf.  Just turn off the fogsettings ssl information and reinstall.  It will no longer be setting up SSL information (in the same way) on the typical fog.conf file.

**Comment by Nightreaver** [comment]
Okay, yes, this is what I wanted, but actually I have non-ssl & ssl in fog.conf.
So I can disable this in .fogsettings? 

with `sslpath=''` or how?

**Comment by mastacontrola** [comment]
The ssl shouldn't matter.

At least not from that file.  Unless you're doing NamedVirtualHosts?

**Comment by Nightreaver** [comment]
No, I mean you said 
"So Unless you're installing with enforcing the ssl status..."
"Just turn off the fogsettings ssl information and reinstall. It will no longer be setting up SSL information (in the same way) on the typical fog.conf file."

 I don't do/want that. How do I skip/turn off ssl install with .fogsettings?

**Comment by mastacontrola** [comment]
If you look at the fog generated config in the main server stuff (non SSL) is the rewrite rules commented? The SSL stuff isn't so what I may do when I get home is just comment the SSL config portion out as well.  Then it should be relatively simple as all you should have to do is rerun the installer as you normally would.

**Comment by Nightreaver** [comment]
Rewrite rules are commented out, yes.
Would be cool

thanks

**Comment by mastacontrola** [comment]
Added preventative measures.

Should only create ssl config info IF forcehttps is enabled.

**Comment by Nightreaver** [comment]
works! awesome

**Comment by mastacontrola** [comment]
Thanks for keeping us posted.
