### ISSUE TITLE
Error on creating task

### ISSUE THREAD

**Issue by Nightreaver** [FOGProject/fogproject#124]
Hey again.

When I create a deploy task I see the message in a red box

```
Failed to create tasking to some or all

HOST Failed to start tasking type Deploy
No snapins associated with this host
```

That's true, we don't have any snapins, never had.
The deploy task is created anyways

**Comment by mastacontrola** [comment]
Sorry it took so long.

I've fixed this for RC-10 (thanks for reporting).

I've also fixed it so if a snapin tasking is attempting to be created, but there are no snapins, the task itself will be cancelled as tasks are created before the snapin taskings are created (Task->SnapinJob->SnapinTasks) is the formula.
