### ISSUE TITLE
automatically created storage-node entries invalid

### ISSUE THREAD

**Issue by Nightreaver** [FOGProject/fogproject#125]
Hello

I'm on `working-RC-10` branch now.
I installed a new storage and with this the storage always registers itself on the main fog node in "Storage Management".
So I have two storage-nodes in the list now. 
But whenever I want to edit the new node, I'll get the message `Storage ID # is not valid`. 
From the Gui I can see that the node has no default group assigned to it. But it can't assign a group because i can't click it.

Regards

**Comment by mastacontrola** [comment]
I can't seem to replicate.  The fact that it's not creating a valid node is a bit troubling, as indicated by no I'd or name after the # in the message you're seeing.

**Comment by mastacontrola** [comment]
Unfortunately I cannot test more thoroughly until I get home today so it may be a bit before I can confirm for sure.

**Comment by Nightreaver** [comment]
So it sais `Storage ID 4 is not valid` , # was just intended a placeholder

**Comment by mastacontrola** [comment]
How did you create the new node?

**Comment by mastacontrola** [comment]
Tested on working-RC-10 appears to allow me to edit.  Closing for now, please let me know otherwise.

Thank you,
