### ISSUE TITLE
PXE client DNS resolution changed?

### ISSUE THREAD

**Issue by Nightreaver** [FOGProject/fogproject#127]
Hello

We talked a while ago about handling the DNS within different subnets.
It worked until RC-9, and now its just returning the main ip of the server whatever I do.
The entry in Storage-Management has the DNS name in the IP field, but when client attempts to mount the NFS its already using the (wrong) IP address.
Older versions used the server-name here so I think something has changed here.

When I run the deploy task as a debug task I get the overview of the variables including the "NFS path", and also this is already using the (wrong)  IP address.

So I want to know, who is doing the DNS resolution now, and when?
For me it feels like it comes from the FOG main node or so?!

Regards

**Comment by mastacontrola** [comment]
DNS resolution has not changed. What did change was the setup so the DNS call to a hostname is setup when the server calls to load the page.  I can correct this again as if I'm understanding it you have the same hostname pointing at different IPS based on the network it's loading from?

**Comment by Nightreaver** [comment]
The thing is that the DNS server which is populated via DHCP doesn't have a DNS entry for our storage node, but something resolves the IP. So if I don't "hack", the DNS name could not be resolved.

With RC-8 I ve overridden it in fog.mount, but now it comes from somewhere else (already magically) resolved.

And if the main-server is resolving the IP for the client (which might be an option looking at `FOG_USE_SLOPPY_NAME_LOOKUPS`) then my whole setup is useless. Because it will return the same ip no matter what subnet my client is in.

**Comment by mastacontrola** [comment]
I'll fix the boot menu so it doesn't try to resolve up first again.  I think I was just trying to be proactive so for that I'm sorry the fix is actually quite simoke

**Comment by Nightreaver** [comment]
Ah, no worries
I really appreciate the time, effort and patience you show here :)

**Comment by mastacontrola** [comment]
DNS issues should be fixed (I'm not resolving the name any more.)

**Comment by Nightreaver** [comment]
yes, fixed, works like charm again!

**Comment by mastacontrola** [comment]
No probablem sorry about breaking it before.
