### ISSUE TITLE
Question to dhcpd sample

### ISSUE THREAD

**Issue by Nightreaver** [FOGProject/fogproject#128]
Hello again, i've got a question regarding your sample dhcpd config.

when I use these few lines from your sample config

```
    class "Legacy" {
        match if substring(option vendor-class-identifier, 0, 20) = "PXEClient:Arch:00000";
        filename "undionly.kkpxe";
    }
    class "UEFI-32-2" {
        match if substring(option vendor-class-identifier, 0, 20) = "PXEClient:Arch:00002";
        filename "i386-efi/ipxe.efi";
    }
```
tftp breaks

but when I use these lines ( which do the same just in one class  I think)

```
class "pxeclient" 
{
                                                   
    match if substring (option vendor-class-identifier, 0, 9) = "PXEClient";

    if substring (option vendor-class-identifier, 15, 5) = "00000"{
        filename "undionly.kkpxe";
    }
    elsif substing (option vendor-class-identifier, 15, 5) = "00002"{
        filename "i386-efi/ipxe.efi";
    }
}
```

it works. I don't seen any real difference in your or my, it's just that you'rs is not working.
IFor my understanding the do the same stuff in different ways.

the vendor string is ` "PXEClient:Arch:00000"`

Any ideas why?

Regards

**Comment by Nightreaver** [comment]
I also figured out.... when I change bios to UEFI, the vendor string does only slightly change
as stated above (same machine with legacy on/off)
vendor-string  `PXEClient:Arch:00000` for legacy
vendor-string  `PXEClient:Arch:00000:UNDI:002001` for uefi

so your sample file might not catch these as it also delivers "legacy" to uefi clients.
We are using all Dell here, T7810 / Latitude E7450 etc.

**Comment by mastacontrola** [comment]
I've not added any dhcp options quite yet, don't think I forgot about it, but best approach would probably be to leave the "here's how we're going to subclass this" and let you handle your own classes and dhcp configuration options.  This should also help prevent coding issues that might crop in every now again.

Just a thought.

**Comment by wayneworkman** [comment]
If your vendor string for UEFI is saying vendor-string `PXEClient:Arch:00000:UNDI:002001 for uefi` then that machine is not UEFI, but is infact BIOS, as it's identifying as 0.

RFC 4578  excript from [https://tools.ietf.org/html/rfc4578](https://tools.ietf.org/html/rfc4578)

> As of the writing of this document, the following pre-boot
>    architecture types have been requested.
> 
>             Type   Architecture Name
>             ----   -----------------
>               0    Intel x86PC
>               1    NEC/PC98
>               2    EFI Itanium
>               3    DEC Alpha
>               4    Arc x86
>               5    Intel Lean Client
>               6    EFI IA32
>               7    EFI BC
>               8    EFI Xscale
>               9    EFI x86-64
> 
>    This option MUST be present in all DHCP and PXE packets sent by PXE-
>    compliant clients and servers.

**Comment by wayneworkman** [comment]
I've looked over your dhcpd class closely, it is functionally identical to ours.

I think you are having other dhcp issues but aren't aware of them yet. How many DHCP servers are in your environment? Use wireshark to determine this. Far more times than not, people have two or more and forgot to correctly configure one, or have a rogue DHCP server. This can explain the inconsistencies you're seeing.

**Comment by Nightreaver** [comment]
I think this might be an "issue" with UEFI + Legacy Bios.
If have both enabled, I can find UEFI and Legacy vendor strings in my leases file. I think it uses UEFI first, then falls back to Legacy. (I had a similar issue with rEFInd)
I am pretty sure there is no other DHCP running, but I might check sample classes once more when we are done imaging.

I just want to say that defining the classes inside subnet definition might not be a good practice. 
It took me a few hours to figure out the class names are uniquq and can only be used on time.
So if you define them in inside multiple subnets, only (subnet with) the first definition will work.

If you want to use the same class definitions in multiple subnet, define them globally and only set next-server in each subnet.

**Comment by wayneworkman** [comment]
Developmental FOG only builds a dhcpd.conf configuration for a single subnet. It would be complex to try to 'ask questions' during installation about every subnet you might want to serve. In these cases, I would recommend maybe using the fog-built dhcpd.conf file as a template (as you have done), and then turning off `bldhcp` and `dodhcp` inside of the fog server's `/opt/fog/.fogsettings` file, and managing dhcp on the fog server manually after that, as you are doing. It's important to turn those settings to from `yes` or `1` to `no` or `0`, because if you don't the next time you update the fog server it will overwrite your configuration.

**Comment by Nightreaver** [comment]
Yes, it was just a remarkt. Can't be a bad thing if you have it inside "global" by default instead of one subnet?

The DHCP server is seperate from FOG-Server, but I'll note it down. Thanks

**Comment by wayneworkman** [comment]
You're talking about the ARCH classes being global? I can try it out and see if it works.

**Comment by Nightreaver** [comment]
Yes, you should try that, I had serious problems with multiple subnets when
you add the same classesto each of them, only global definition solved the
problem.

2016-09-24 22:19 GMT+02:00 wayneworkman <notifications@github.com>:
