### ISSUE TITLE
UEFI + grub - Could not boot: Exec format error

### ISSUE THREAD

**Issue by Nightreaver** [FOGProject/fogproject#129]
Hello

I switched our PCs to UEFI yesterday and after I got PXE working, I'm stuck at GRUB boot.

From the PXE menu, whenever I pick "boot first HDD" it starts grub.exe and nothing happens, I stays inside PXE menu.  
When I let it boot, (with setting GRUB_FIRST_HDD) it prints an error 
```
http://myhostname/fog/service/ipxe/grub.exe... ok
Could not boot: Exec format error (http://ipxe.org/2e008081)
Could not boot: Exec format error (http://ipxe.org/2e008081)
Could not boot: Exec format error (http://ipxe.org/2e008081)
Chainloading failed [...]
```

Ideas why this is happening?
Legacy works fine!

Regards

**Comment by mastacontrola** [comment]
Grub.exe is not an EFI binary.  I'd recommend changing the EFI exit type and use rEFInd or exit

**Comment by Nightreaver** [comment]
Okay, no problem...
when i use rEFInd
I receive following message

```
NOTE: refind.conf's 'scanfor' line specifies scanning for one or more legacy boot options; however this is not possible because your computer lacks the necessary Compatibility Support Module (CSM) support ro that support is disabled  in your firmware
```

But it think I can modify the refind.conf to my liking?
Side question: this file will be overwritten on update? ;)

**Comment by Nightreaver** [comment]
rEFInd works, when I enable legacy rom "default" works fine or when I change scanfor to `scanfor internal,external` i can also disable legacy option.

Thanks!!

**Comment by mastacontrola** [comment]
I'll setup the refind config, when I get home, to use this.  All I did was copy the file from the internet and put it in place.  One thing I have yet to do is any type of real configuration options for refind and I think it may be a better replacement for the grub stuff as it seems to have more active development.

I'll modify the config to do efi though as I think it is far more useful.
