### ISSUE TITLE
Fog RC11 doesnt recognize csv file

### ISSUE THREAD

**Issue by DerpDarako** [FOGProject/fogproject#133]
Hello,

I want to import all my hosts in FOG. I had csv file from fog 1.2. It didn't work so i thought the data format changed between versions. I tried to add manually 2 hosts and exported them. I got a formated file by fog 1.3, so i tried to change data and still didn't work I thought the problem was about the way to save the file. 

So i just did a simple test, i used export function then tried to import the downloaded file. It still didn't work.
So i think there is a problem in your way to recognize the csv file.

Best regards

**Comment by mastacontrola** [comment]
So confirm the issue, which will be a bit later today that I can fix, I created a backup of my DB and exported my host list.  I then removed all hosts from the system and attempted reimporting.

Here's the issue as I see it.  The Import IS working but is specific to how host imports occur.  My Database does contain the host names and their relevant information, but it does not have the host mac's for those hosts in the database yet.  I will work on fixing that as soon as I can and sorry there is this issue to begin with.

**Comment by mastacontrola** [comment]
When you say recognize, it's saying "File must be a csv?"  Can you try using firefox, or ie to see if it validates it for you?  I saw the same recognition issues while using chrome.  Unfortunately there isn't a simple fix that the php programming can do.

That said, there was still a bug within the import function and associating the mac addresses with the hosts.  This (as well as any other potentially unknowns) has now been addressed in the main code.

To help with the recognition, I might also suggest installing Microsoft Office or OpenOffice.org.  It should update the registry keys in windows to send the proper mimetypes for the files through the browser.

**Comment by mastacontrola** [comment]
https://github.com/FOGProject/fogproject/commit/039d7fdefcf52d38941ab833550dc1421767be68

This is on the working-RC-14 branch currently.  Please install it and see if your proxy information will now work.

Thank you.

**Comment by DerpDarako** [comment]
it's ok.
