### ISSUE TITLE
20 minutes delay after imaging until fog service contacts fog server

### ISSUE THREAD

**Issue by christian-korneck** [FOGProject/fogproject#135]
Hello,

first of all, thanks a lot for the awsome fog project!

I have the problem that after a Windows client got successfully imaged and has been booted for the first time, it will take 20 minutes until the fog service on the client attempts to contact the fog server (and changes the hostname, joins the Active Directory, reboots, etc).

In the client's `fog.log` the 20 minutes delay is visible (see the 20 minutes delay in the time stamps):

```
[...]
 11.10.2016 20:39 Service Starting service
 11.10.2016 20:58 Bus Became bus server
[...]
```

The full `fog.log` is also attached. We've also confirmed through a packet capture from a router that is between the fog server and the fog client that during these 20 minutes that
- that the client already had an active network connection (we're seeing other traffic, i.e. Windows Activation)
- that during these 20 minutes "sleep" time there was no attempt to resolve the DNS name of the fog server and/or to connect to the fog server's IP

Do you have any idea what might be causing this delay?

Thanks,
Christian

**Comment by mastacontrola** [comment]
This this delay consistent or just on initial startup?

**Comment by christian-korneck** [comment]
It only seems to happen on the initial startup after the machine was imaged (before the hostname change) - at further reboots I can't see the delay. After further reboots it looks like:

```
 12.10.2016 21:11 Service Starting service
 12.10.2016 21:11 Bus Became bus server
```

**Comment by mastacontrola** [comment]
What version of the client is installed within the image?

**Comment by christian-korneck** [comment]
I think Fog Service version is `0.11.5`. More details:

```
PS C:\Users\Administrator> Get-ItemProperty HKLM:\Software\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\* | Where{$_.DisplayName -match "Fog"} | select DisplayName, DisplayVersion, Version | Format-Table -AutoSize

DisplayName DisplayVersion Version
----------- -------------- -------
FOG Service 0.11.5          720901

PS C:\Users\Administrator> [System.Diagnostics.FileVersionInfo]::GetVersionInfo("C:\Program Files (x86)\FOG\FOGService.exe").FileVersion
0.0.0.0

PS C:\Users\Administrator> md5.exe "C:\Program Files (x86)\FOG\FOGService.exe"
B9917EC82AE7F68C7984B293FA326C0E
```

**Comment by wayneworkman** [comment]
What OS is the problematic host running? What version of fog is the FOG Server running? Are you using Sysprep? And, we need a full FOG Client log.

**Comment by christian-korneck** [comment]
Hello,

the client image is a Windows 7 Pro x64 SP1 installation and it is indeed sysprepped. The full fog.log [is attached here] (https://github.com/FOGProject/fogproject/files/530391/flog.log.txt).

**Comment by wayneworkman** [comment]
Since you are sysprepping and using the fog client, have you found and followed these instructions? If not, can you please try them? https://wiki.fogproject.org/wiki/index.php?title=FOG_Client#FOG_Client_with_Sysprep

**Comment by jbob182** [comment]
```
 11.10.2016 20:39 Service Starting service
 11.10.2016 20:58 Bus Became bus server
```

Please follow the steps @wayneworkman posted for syprep compatibility. If that does not let me know and I can take a look. More than likely it's an issue with a configuration of your image.

**Comment by mastacontrola** [comment]
@christian-korneck can you please provide an update as to the status of this issue?  I'm not fond of keeping issues opened, and as all we're waiting for is information here, it'd be nice to know of a status so we can provide more suitable help.

**Comment by christian-korneck** [comment]
sorry for the delay (and many thanks for your time and suggestions!). I will verify and test and give you an update asap.

**Comment by wayneworkman** [comment]
How did it go?

**Comment by christian-korneck** [comment]
Apologies for the late response. We've rebuilt our Windows image from scratch (with the sysprep instructions from the wiki in mind) and the issue didn't re-occure. Many thanks for your help.
