### ISSUE TITLE
Multicast doesnt start

### ISSUE THREAD

**Issue by DerpDarako** [FOGProject/fogproject#136]
Hello,

Since I did the upgrade from 1.2. I cannot deploy with multicast.

My computers stuck at the first step "Starting to restore image". I did a test with 2 computes in 1.2 => ok. With last release => not ok.

Fog is not even writing log. So i m not able to provide a lot information.

I stay at your disposable for any others informations

**Comment by mastacontrola** [comment]
Most cases of this is due to the interface on the FOG Server.

For example, if the interface name is eno167777728, but your FOG Server is configured with FOG_NFS_ETH_MONITOR (or whatever it's called in 1.2.0 Fog configuration->Fog settings -- sorry I don't remember any more) set as eth0, the multicast task will not be able to start.

Which log did you check?  The normal log file for the multicast service is located at: /opt/fog/log/multicast.log

**Comment by mastacontrola** [comment]
Also, would you mind updating to one of the RC releases?  We've changed quite a lot and I think you'll find many things you didn't know were problems are now also much better handled and working.

**Comment by DerpDarako** [comment]
I did a git pull... But I didn't get update database page when I get myserver/fog/management..

And fog still display this : Wed Oct 12, 2016 14:38 pm
Running Version 1.3.0-RC-13
SVN Revision: 5962

it seems my update didn't work.

**Comment by mastacontrola** [comment]
It did work.

How did you run the update command?

If you run it with `./installfog.sh -y` it auto accepts and performs the schema updates as needed.

Remember, just because there's an update to be done also does not mean there's going to be a schema update.

**Comment by DerpDarako** [comment]
Yeah, finally, i removed everything. Then did install 1.2 => remove my trunk  => git clone.

Now multicast works. I will see if it deploys swap well.

Btw, proxy settings dont work in this version (it worked with 1.2)

**Comment by mastacontrola** [comment]
How do you mean "Proxy settings don't work"?  By default, localized systems shouldn't be going through proxy, it's the external sides that should.  I don't know how else to make sure things work continuously.

**Comment by DerpDarako** [comment]
When i'm on the logging page. Fog is not able to retrieve informations (current version, last SVN revision...). I set proxy settings it was working in 1.2 but I have never seen it working in 1.3.x

**Comment by mastacontrola** [comment]
What happens if you remove "proxy settings" from the GUI?

**Comment by mastacontrola** [comment]
I'm closing the issue, but please feel free add any additional comments here.

**Comment by DerpDarako** [comment]
I removed ip & port in proxy settings tab. Then i put my informations again and still not working.

I'm sure it's a bug. I'm capturing all traffic from my server to my proxy and there is 0 packet.

**Comment by mastacontrola** [comment]
What I meant about removing the proxy information, is to try while there IS no proxy information defined.

**Comment by DerpDarako** [comment]
I did this test too. didn't work.

**Comment by DerpDarako** [comment]
I will test this patch tomorrow. I keep you updated

**Comment by DerpDarako** [comment]
It works fine now. Thank you :)

**Comment by mastacontrola** [comment]
Due to the statement that it's working, I'm closing this issue.

Thank you,
