### ISSUE TITLE
Multicast not starting again

### ISSUE THREAD

**Issue by DerpDarako** [FOGProject/fogproject#137]
Hello,

I met my previous multicast issue. I tried with RC14 current dev-master branch and RC15 (had to download entire zip cause the merge didn't work). Few days ago I did a multicast deployment i think it was RC13 and ti was working.

I stay at your disposable if you need more informations.

Best regards

**Comment by mastacontrola** [comment]
Are you constantly on the working branches?

It is working under working-RC-15 as I introduced a couple typos on them yesterday.

**Comment by DerpDarako** [comment]
I did the update this morning. So 6 hours ago

**Comment by mastacontrola** [comment]
please pull and re-install.

**Comment by mastacontrola** [comment]
I ask this as I did find a couple issues on working-RC-15 and have been able to fix them.  Also, instead of downloading a zip, you may need to reset your working tree.  Something along the lines of:

```
git reset --hard
git clean -fd
git pull
```
should help.

**Comment by mastacontrola** [comment]
I'm fairly certain this will work.

**Comment by DerpDarako** [comment]
My deployment is still stuck

**Comment by DerpDarako** [comment]
Can i provide log or test something for you?

**Comment by mastacontrola** [comment]
Please.

**Comment by DerpDarako** [comment]
Yeah finally it works. But i had to install from scratch. Thus i cannot use the 1.3 installer.

I have to install 1.2 then i install working-RC-15. I have multicast and proxy. :)
