### ISSUE TITLE
Issue Upgrading to RC-24

### ISSUE THREAD

**Issue by delinski111** [FOGProject/fogproject#139]
Hello,

I previously was on RC11 on dev-branch

I did ```git pull```. It updated several files. I than realized that RC24 was not on that branch

```git checkout working-RC-24```. successfully checked the branch out. Still showing as RC11 on web portal.

than ran ```./install.sh``` from the fog directory. This DID change the software, however, now it shows as ```Version 34```, and is still showing out of date.

At this point, I am not sure what to do next. 

TL:DR: Not sure how to upgrade to RC24 from RC11. Git checkout and ./install.sh did not work.

**Comment by jbob182** [comment]
You're trying to install a development build of a future release candidate, these types of issues are to be expected. 

RC 23 is the current public release.

**Comment by mastacontrola** [comment]
To further clarify, working-RC-XX is (for lack of better description) closed beta of the next RC candidate (or possibly the full release based on other return information.)  It not displaying as RC-24 (or whatever) is to be expected when on any of the "working" labelled branches.  They only get labelled as 1.3.0-RC-XX when we publicly release the RC for use.

**Comment by delinski111** [comment]
Thank you @mastacontrola. That is much more helpful information, and was what I was looking for.

I submitted the ticket, with the intention of learning if that was normal, or an issue with the method in which I upgraded my server.

I appreciate you taking the time to follow up after jbob.
