### ISSUE TITLE
webpage not available

### ISSUE THREAD

**Issue by crcro** [FOGProject/fogproject#141]
Release: 1.3.0 RC 23

there is an & sign on line 110 in file: /var/www/html/fog/commons/init.php that makes the website unavailable.

also a note for centos 6.8 install: by default centos repos have php 5.3.0 but FOG requires > 5.5 (so a third party repo is required).

**Comment by mastacontrola** [comment]
The & is perfectly fine for php 5.4 or higher.

I do install third party repos in an attempt to ensure you will get the proper version we need.

This doesn't appear to be working properly for you it sounds like?

Here's the code if you want to see how I'm attempting it:

https://github.com/FOGProject/fogproject/blob/fb9758a624fa034b8cdda642410c33633b7a4bd3/lib/redhat/config.sh#L20

Here's where we're adding the repos (before attempting to install anything).

https://github.com/FOGProject/fogproject/blob/fb9758a624fa034b8cdda642410c33633b7a4bd3/lib/common/functions.sh#L543

**Comment by crcro** [comment]
I was telling that using ./installingfog.sh everything will be installed (but in case of centos 6.8 x64) with php 5.3. with that & sign on line 110 only a blank page is displayed (thus cannot finishing the install). if you remove that sign the webpage displays something like you have php 5.3.3 but FOG requires at least php 5.5 (in the error logs only the fact that unexpected & character found on line 110 is logged).

**Comment by mastacontrola** [comment]
And what I'm telling you is that it should install the repo that will install php 5.6, in which case the & that you're referring too is perfectly fine.  What it sounds like to me is, for some strange reason, the remi repository isn't installing.

Can you try:

```
yum -y update 'php*' --enablerepo=remi,remi-php56
```

**Comment by crcro** [comment]
[root@fog01 ~]# yum -y update 'php*' --enablerepo=remi,remi-php56
Loaded plugins: fastestmirror
Setting up Update Process
Loading mirror speeds from cached hostfile
epel/metalink                                            |  19 kB     00:00
 * base: mirrors.ulbsibiu.ro
 * epel: mirror.daniel-jost.net
 * extras: mirrors.pidginhost.com
 * updates: mirrors.ulbsibiu.ro
 * webtatic: us-east.repo.webtatic.com
base                                                     | 3.7 kB     00:00
epel                                                     | 4.3 kB     00:00
epel/primary_db                                          | 5.9 MB     00:00
extras                                                   | 3.4 kB     00:00
updates                                                  | 3.4 kB     00:00
webtatic                                                 | 3.6 kB     00:00
No Packages marked for Update
[root@fog01 ~]#

the webtatic.com repo was added by myself

**Comment by mastacontrola** [comment]
I know it's been a couple days since this was looked at. 

Please update to RC-27.  Let me know if you're still having issues.

**Comment by crcro** [comment]
i'll deploy a new setup to make a clean test later today and come back with info.
