### ISSUE TITLE
Something during update 1.3.0 to 1.3.1

### ISSUE THREAD

**Issue by alexandre-lg** [FOGProject/fogproject#153]
Hello,

A strange message appears during the update:

```
 * Setting up storage............................................/lib/common/functions.sh: ligne 1076: /images/dev/postdownloadscripts/fog.postinit: Aucun fichier ou dossier de ce type
OK
```

The script finishes correctly, but is it without consequences?

A big thank you for your work and your availability!

**Comment by Quazz** [comment]
Are you on Ubuntu?

**Comment by marcolefo** [comment]
Hi.

Take a look
https://forums.fogproject.org/topic/9306/postdownloadscripts-not-found-during-installation/3

**Comment by mastacontrola** [comment]
FOG 1.3.2 released which will address this particular issue and one regarding task reboots.

**Comment by alexandre-lg** [comment]
Hello,

Sorry to respond only now, I'm using Debian 8.6.
I just updated in 1.3.2 and it's ok.

Thank you very much for your work!
