### ISSUE TITLE
"ERR_EMPTY_RESPONSE" after selecting "Create New Host" 

### ISSUE THREAD

**Issue by n3ph1ll1m** [FOGProject/fogproject#156]
Apache crashes after selecting "Create New Host" in the Host Management tab, gives an "ERR_EMPTY_RESPONSE" on the management page
On Ubuntu 16.04
apache2-bin 2.4.25

apache2 crashed with SIGSEGV in zend_init_execute_data()

**Comment by mastacontrola** [comment]
Mind installing the working-1.3.5 branch?

I'm hoping to have caught the issue.

**Comment by n3ph1ll1m** [comment]
Yup!  It is fixed in the working-1.3.5 branch!  Thank you!
