### ISSUE TITLE
Dynamic group "all"

### ISSUE THREAD

**Issue by alexandre-lg** [FOGProject/fogproject#158]
Hello,

It would be handy to have a group containing all the workstations. This group would make it possible to deploy snapins on an entire park.
Other dynamic groups might exists, such as a group by "system product" or "host image".

Thank you very much for your work.

**Comment by mastacontrola** [comment]
I'm not certain how to address such a thing currently. I fully understand the request, and while it seems easy, the point of "Groups" was always to be a simple mechanism to mass update hosts. Having a group that contains all hosts is simple enough, but what should we "define" that group as?

This, not being added as core, could be addressed by a plugin though. Maybe you'd be willing to try your hand?  I'm nearly always available to help when and where possible/needed.

**Comment by alexandre-lg** [comment]
I'll look if it's in my skills. Thank you :)
