### ISSUE TITLE
Scheduled snapin: task name

### ISSUE THREAD

**Issue by alexandre-lg** [FOGProject/fogproject#161]
Hello,

![2017-04-05 12_30_41-create single snapin task for uct007 _ host management _ fog _ open source compu](https://cloud.githubusercontent.com/assets/3471351/24804857/22883e26-1bb0-11e7-8628-a11bb62ec98f.png)
![2017-04-05 12_30_54-scheduled tasks _ task management _ fog _ open source computer cloning solution](https://cloud.githubusercontent.com/assets/3471351/24804858/228c467e-1bb0-11e7-9863-92bcc0f36f0b.png)

Is it possible that this reflects a little more the task that will be launched? If the problem is the place, a tooltip over the fly will do.

Thanks.

**Comment by mastacontrola** [comment]
While I most certainly could make it "change" the name, I think the tooltip option is the best route. This way you know what the task is named AND if it's a snapin tasking it will tell you what snapin name is going to be used.

I've added this request to the working branch. This, of course, will only be viable on the scheduled task, as when the task is actually created you will see the snapin tasks under the snapin task name.
