### ISSUE TITLE
wake on lan does not work

### ISSUE THREAD

**Issue by alexanderhaensch** [FOGProject/fogproject#164]
Issuing Wake on Lan in FOG 1.3.5 Does not work as there is no packet emitted on the network interface.

tcpdump -i eth0 -n udp dst portrange 1-20
does not show any activity.

How can we debug this? Is there a php logging facility in FOG.

It would be useful to log something from 
https://github.com/FOGProject/fogproject/blob/07fc22180dd59329946d981f2a0296bd01db271c/packages/web/lib/fog/macaddress.class.php#L340

**Comment by mastacontrola** [comment]
This is a specific tasking causing the issue or in general WOL is not working?

1.3.5 did have an issue with parsing WOL Tasking (specifically) but all other tasks that would require WOL did work.  This issue was addressed with 1.4.0-RC-1.

**Comment by alexanderhaensch** [comment]
no it is the function called in advanced-task -> wake

**Comment by mastacontrola** [comment]
And that is specifically what 1.4.0-RC-1 was released to fix.

**Comment by alexanderhaensch** [comment]
Okay. we will try that

**Comment by alexanderhaensch** [comment]
Updated to  1.4.0-RC-8 and the problem still exists

**Comment by Sebastian-Roth** [comment]
Do you see any packets in tcpdump when sending those with another command line utility like wakeonlan or etherwake?
What if you add some debugging statements in the PHP code and see what error you get. Anything in the apache error logs?

**Comment by mastacontrola** [comment]
"Debugging" would be easiest to simply remove the `@` from the commands in the wake method of the macaddress class.

Any errors will then be written to the php error log.

**Comment by mastacontrola** [comment]
I'm not understanding the Thumbs-down emoji.  RC-1 of 1.4.0 WAS released to fix the Wake Tasking.

**Comment by mastacontrola** [comment]
I've removed the `@` symbols in https://github.com/FOGProject/fogproject/commit/fa5ad0fc71dd791ab406b81ac171b3cac039308a

If you'd like to test it please feel free.
