### ISSUE TITLE
Kernel Update will not download when behind a proxy

### ISSUE THREAD

**Issue by Quinniedid** [FOGProject/fogproject#167]
I have found when trying to access older kernals and download them through the updater it continues to report failed to download. I assume that if using wget it is not using the proxy settings that are already specified in the FOG settings.

**Comment by mastacontrola** [comment]
Kernel downloads are not handled in the same fashion as wget would do things. At what part is this failing for you?

**Comment by Quinniedid** [comment]
I can select a Kernel and even specify the name of the Kernel and then it will switch over to Downloading to which shortly after it will give me a Error: Failed to Connect to Server

**Comment by mastacontrola** [comment]
Can you try without proxy settings?  Can you tell us what version you're having this problem with?

**Comment by Quinniedid** [comment]
I cannot try without proxy as that is beyond my authority to do. I am running 1.3.5

**Comment by mastacontrola** [comment]
I don't mean you should disable the actual proxy, rather remove the items from the fog proxy settings and see if it works that way.  If you're not allowed to do that I understand, just trying to narrow where the problem is.

**Comment by Quinniedid** [comment]
I apologize for miss understanding. I have removed the proxy settings and now it is showing: 
![image](https://cloud.githubusercontent.com/assets/11981080/25918673/8288a1f6-3589-11e7-9794-f4507da45067.png)

**Comment by mastacontrola** [comment]
Okay so you do need proxy then.  Awesome that portion is indeed working.

**Comment by mastacontrola** [comment]
Can you try downloading again and get Apache error log when the failed message comes again?

**Comment by Quinniedid** [comment]
Where can I find the Apache error log?

**Comment by mastacontrola** [comment]
Depends on the os you're using. Typically either `/var/log/apache2/error.log` or `/var/log/httpd/error_log`

**Comment by Quinniedid** [comment]
There is not much in there at all
[error_log.txt](https://github.com/FOGProject/fogproject/files/991239/error_log.txt)

**Comment by mastacontrola** [comment]
I'm suspecting part of the problem is the tests I have in place.

Please try:
```
wget -O /var/www/fog/lib/fog/fogpage.class.php https://raw.githubusercontent.com/FOGProject/fogproject/2486dc9e817502f2b770e17d8d8ac85a57dbf470/packages/web/lib/fog/fogpage.class.php
```
Also, as a safety, can you run:
```
chown -R fog:apache /var/www/fog/service/ipxe
```
If debian change the apache portion to www-data.

**Comment by Quinniedid** [comment]
Looks like that new file fixed it! Thank you for your help! Also I was running on debian.

**Comment by Quinniedid** [comment]
Actually now, this is all that I am getting when going to the management page!
![image](https://cloud.githubusercontent.com/assets/11981080/25925981/5afeb93e-35a9-11e7-833a-dac335ae6d50.png)

**Comment by mastacontrola** [comment]
Can you install the working branch then? 1.3.5 is decent but a bit has changed most likely causing the issue you're seeing, sorry about not recognizing sooner.

**Comment by Quinniedid** [comment]
I am not seeing how I can install the working branch. Would you please give me a quick run through on how to accomplish that?

**Comment by mastacontrola** [comment]
From the git folder run:
```
git checkout working
git pull
cd bin
./installfog.sh -y
```

**Comment by Quinniedid** [comment]
Do I need to backup my database and/or images first, before I run those commands?

**Comment by mastacontrola** [comment]
You should not need to backup. When I refer to the git folder I'm referring to the original folder you cloned the repo to.

Often it would be `cd fogproject`

**Comment by Quinniedid** [comment]
So I built FOG with using the wget and not git so I am not getting any git repositor

**Comment by mastacontrola** [comment]
then open a terminal.

Run:
```
git clone https://github.com/fogproject/fogproject.git /opt/fogproject
cd /opt/fogproject
git checkout working
git pull
cd bin
./installfog.sh -y
```

**Comment by Quinniedid** [comment]
This is what I am getting when I try to do the git pull:
![image](https://cloud.githubusercontent.com/assets/11981080/25960451/334ce8d0-3634-11e7-9c8a-ae7edfa690a2.png)

**Comment by mastacontrola** [comment]
You didn't follow the instructions very well.

First of all, you downloaded the repo to /fog_1.3.5, but you didn't cd to that directory.

Change your stuff to:
```
cd /fog_1.3.5
git checkout working
git pull
cd bin
./installfog.sh -y
```

**Comment by Quinniedid** [comment]
I am sorry. What I was trying to do was override the existing folder that I already had but I am just going to follow your instructions. I moved the /fog_1.3.5 to the opt/fogserver. Ran the git commands successfully and everything is working now. I appreciate the time you have taken to help me get this fixed and my noob knowledge of how this stuff works. Thank you so so much! 👍

**Comment by mastacontrola** [comment]
No problem, this is what I do and patience comes with the territory. If I seem brash, I assure you this isn't my intent.

Glad you got it working and more than happy to help out.
