### ISSUE TITLE
/etc/exports replaced without backup

### ISSUE THREAD

**Issue by rybaha** [FOGProject/fogproject#168]
Fog 1.4.0, Storage Node update from 1.3.5. After update my сustom /etc/exports was replaces without backup copy in /etc/ as it was in 1.3.5..

**Comment by mastacontrola** [comment]
There's an argument you can pass with the installer that will prevent overwriting the exports file.  I believe it's -E but a --help will be far more helpful.

**Comment by Quazz** [comment]
Also you can set blexports='0' in /opt/fog/.fogsettings

**Comment by Sebastian-Roth** [comment]
Just added a more advanced way of backup up config files: https://github.com/FOGProject/fogproject/commit/b4f3295c348164c21e7b37a5eea0b213b840e3e1
