### ISSUE TITLE
Fogproject in a Docker container

### ISSUE THREAD

**Issue by frankyrumple** [FOGProject/fogproject#170]
Just leaving a note to say I have Fog working in a docker container. Still working out some tweaks, but it is deploying and capturing images.

https://github.com/operepo/ope
Sub folder - docker_build_files/ope-fog/
Readme there has information on what I had to do to allow TFTP/NFS to route properly. If you run outside docker-compose you need to provide volumes/ports/permissions/etc... on the command line.

**Comment by mastacontrola** [comment]
Thanks for letting us know. If you need any help hit us up on the forums.
