### ISSUE TITLE
Printer port cannot be configured

### ISSUE THREAD

**Issue by newburns** [FOGProject/fogproject#173]
When I go to update an already configured printer, the printer port and INF File location are now invalid fields.

Before latest SVN update information was:

HP LaserJet Pro M402-M403 n-dne PCL 6
IP_10.1.237.100
C:\Printers\HP_LJ_PRO_M402n\hpdo602a_x64.inf
10.1.237.100

Now those fields are invalid

**Comment by mastacontrola** [comment]
Can you please give us information that can actually please.  Like What version you're currently running? Or What things you've tried, maybe some screenshots.

**Comment by newburns** [comment]
Running Version 1.5.0-RC-6
SVN Revision: 6080
Aug 08, 2017 10:24 am

Preconfigured printer before fog was updated from Version 1.5.0-RC-1
![image](https://user-images.githubusercontent.com/5234107/29079882-f8d83ebc-7c23-11e7-9649-82e969353237.png)

Error after the update. Clicking on the printer to update information:
![image](https://user-images.githubusercontent.com/5234107/29079981-3de478cc-7c24-11e7-845a-e327e4f1ce3b.png)

**Comment by mastacontrola** [comment]
Mind checking out working branch?  I don't know about the port, but I think the inf was updated, but I'll need confirmation otherwise I'll fix them tonight.

**Comment by newburns** [comment]
I'm not sure how to do the working branch.
From bash, I did a git pull in the ../fogproject/ directory.
Then I sh install the ./install.sh file in bin folder.

`fogproject]# git pull
Already up-to-date.`

`fogproject]# git status
# On branch dev-branch
`

**Comment by mastacontrola** [comment]
```
git checkout working
git pull
cd bin
./installfog.sh -y
```

To switch back to dev-branch:
```
git checkout dev-branch
git pull
cd bin
./installfog.sh -y
```

**Comment by newburns** [comment]
The working branch did the same thing.
What should the INF and Port be?
is it supposed to be an actual port number and samba share?
ex: 9100 \\samba\public\share

Or is it supposed to be Port Name and Windows location?
ex: IP_xxx.xxx.xxx.xxx C:/printers/

Also, which branch is the best to use for a semi-production environment?

**Comment by mastacontrola** [comment]
Dev-branch, typically. I don't know about issues until they're brought forward so this is helpful, though if you bring a specific issues and I need to know if it worked, I'll typically ask if you can update so we know if it's fixed for you (in a near moment of certainty.)

**Comment by mastacontrola** [comment]
Should be fixed. I'm closing for now. Let me know if you're still having issues with this after updating.

Thanks for reporting.
