### ISSUE TITLE
single snapin cant be assigned to groups....

### ISSUE THREAD

**Issue by edv-schuster** [FOGProject/fogproject#181]
1.5.0 RC8:

when you try to assign a single snapin to a group of computers, the dropdown-bar for selecting the corresponding snapin is missing.

when you do these steps on a single computer, everything looks normal....

must be a bug, right?

**Comment by mastacontrola** [comment]
I'm not seeing a problem, though I'm working in the `working` branch anyway, maybe I fixed something I didn't see earlier? I don't know, but I cannot seem to replicate the problem currently.
