### ISSUE TITLE
I219-LM NICs left is upset state

### ISSUE THREAD

**Issue by jimdigriz** [FOGProject/fogproject#188]
For a Dell Optiplex 7440 the iPXE process works but Windows 7 is unable to use the network card; the card just flaps up/down and does not send out any packets onto the wire.  It seems that the iPXE that comes with FOG (md5sum: 6831b1e6ee609ab51d22ef3a2ff8b4b4) leaves the card in a state that the drivers baked into Windows 7 cannot recover from.

Fortunately, updating iPXE via a build off rom-o-matic (dated 20170920) resolved the problem, I suspect it was https://github.com/ipxe/ipxe/commit/0588c03772d1fbbeca66362363ec866d745f95ed that actually fixed the problem.

**Comment by mastacontrola** [comment]
Not sure how this is a FOG issue.  What version of FOG are you running that you're seeing this? I keep the ipxe files we use rather updated.

**Comment by jimdigriz** [comment]
Running FOG 1.4.2, released beginning of June.

But as FOG has not had a release since the end of June and more importantly [`ipxe.pxe` has not been updated since May 2017](https://github.com/FOGProject/fogproject/commits/master/packages/tftp/ipxe.pxe) I see it really as a FOG problem :)

**Comment by Sebastian-Roth** [comment]
Sorry but you're looking in the place. The link you posted points to the master branch which is right now on current stable FOG 1.4.4. But we are working on the "working" branch.... see here: https://github.com/FOGProject/fogproject/commits/working/packages/tftp/ipxe.pxe

Anyway this change you posted (0588c03) is from Feb 9, 2016. That should even be in FOG 1.4.4...
