### ISSUE TITLE
Pull Up Host Computer Page Fails

### ISSUE THREAD

**Issue by hkd987** [FOGProject/fogproject#189]
When you go to select a host computer the link dies. 

http://fogserver/fog/management/index.php?node=host&sub=edit&id=328

The above link will be dead after upgrading for all host.

**Comment by mastacontrola** [comment]
Not sure what you mean. What version of FOG? Anything in Apache error logs?

**Comment by hkd987** [comment]
Dev Branch RC-9 upgraded from 1.4.4

no errors in the Apache log file, that I noticed. Looks like it could be a PHP page issue. 

I have since downgraded back to 1.4.4 and the problem has gone away. Thanks for everything you do!

**Comment by mastacontrola** [comment]
I could be wrong but I think what you're describing is fixed in working, though I wasn't aware of there being this problem from RC-9, we have a lot of people using RC-9 now and I'm sure this would've been brought up already.

**Comment by hkd987** [comment]
Ok, maybe it was something else a plug-in or something acting up with it. We have a lot of fog users so I couldn’t mess with it had to down grade very quickly.
