### ISSUE TITLE
Adding new host to group blank out all fields in group 1.5.0 RC-9 

### ISSUE THREAD

**Issue by astrugatch** [FOGProject/fogproject#194]
When adding a new host with no settings to an existing group with settings (serial number, active directory, host image etc) blanks out all the settings that existed in the group. If there are settings and they match they are not over written (though this does defeat the purpose of the groups).

**Comment by mastacontrola** [comment]
That's correct.

Groups work on the basis of "en-mass" updating. To show the values of a particular group, it checks all hosts for the same values. If all hosts in the group have all the same values, the field is populated, if not the field is blanked out. This way you can apply en-mass to all hosts in the group.

There is a plugin to do "persistent groups" however, if you're interested, though You'd need to get on the forums to ask for help with that or at least review the documentation on how it works.

**Comment by pcnate** [comment]
This seems backwards to me... Thanks for pointing out the plugin. I'm very interested in that
