### ISSUE TITLE
Request wipe hdd record

### ISSUE THREAD

**Issue by sacy80** [FOGProject/fogproject#211]
Hi 

Would like to check is there a way I can pull wipe hdd task report from fog server? Something like capture image log?

Thanks alot

**Comment by Sebastian-Roth** [comment]
It's not in the web UI as not many people use FOG to wipe disks.

But the information should be in your database. To get a list similar to what you have for images in the web UI try this:

```
mysql -u root -p fog -e 'SELECT tasks.taskCreateBy,hosts.hostName,tasks.taskCheckIn,tasks.taskTimeElapsed,images.imageName,taskTypes.ttName FROM tasks,hosts,images,taskTypes WHERE tasks.taskTypeID IN (2,18,19,20) AND tasks.taskTypeID=taskTypes.ttID AND tasks.taskHostID=hosts.hostID AND tasks.taskImageID=images.imageID;'
```

I know this is an ugly long command. But I post it as a oneliner so you can simply copy&paste it to your FOG shell and execute.

**Comment by Sebastian-Roth** [comment]
Closing this as there hasn't been an answer yet. Guess this was help enough.
