### ISSUE TITLE
Surface Book - Not working with FOG

### ISSUE THREAD

**Issue by flaviodr** [FOGProject/fogproject#213]
I'm able to boot to FOG Menu using the Surface Book, but when I select the image to deploy the Surface Book gets stuck on a black screen.

If I use the option to debug, the surface gets stuck on the image attached.

![img_4609](https://user-images.githubusercontent.com/32853396/32808485-24e7e04a-c961-11e7-9182-e2d86d33073c.JPG)

**Comment by Sebastian-Roth** [comment]
With FOG version 1.4.4 (which I think you use) you need to go with a different iPXE binary because of a bug. Try setting your DHCP to point to `ipxe7156.efi` for the surface devices.

**Comment by FlavioDR** [comment]
@Sebastian-Roth FOG version 1.4.4 doesn't have the ipxe7156.efi. I will get this file from another FOG version and test it. 
Thanks

**Comment by Sebastian-Roth** [comment]
@FlavioDR Don't know what version you are on but FOG 1.4.4 does have the mentioned binary. See here: https://github.com/FOGProject/fogproject/tree/1.4.4/packages/tftp

**Comment by FlavioDR** [comment]
@Sebastian-Roth using the ipxe7156.efi I get a DHCP error. Please, see the picture below:

![surfacebook](https://user-images.githubusercontent.com/32853396/32848161-c3f3cf30-c9f9-11e7-876c-a3890192b751.jpg)

**Comment by Sebastian-Roth** [comment]
Maybe this will help you: https://forums.fogproject.org/post/92622

Try placing a dump mini switch in between as discussed in that post and see if that helps.

**Comment by FlavioDR** [comment]
Hi,
I also had exactly the same problem with the Surface Pro 4. I was able to solve the problem with the Surface Pro 4 updating the Firmware. However, updating the Surface Book with the last firmware didn't change anything. Would you have a workaround for this problem?

The Firmware version that I had problem was:
system uefi: 106.1281.768
SAM Controller: 103.1226.256
Intel Management Engine: 11.0.15.1003
Touch Firmware: 1.51.250.106.104.239
System Embedded Controller: 103.1158.256

Thanks,

**Comment by Sebastian-Roth** [comment]
Uhhhm, my fault. I though you were talking about a Surface Pro device. I am not into those gadgets much...

Read through this and see if that helps: https://forum.clonedeploy.org/526-surface-book-no-ethernet-driver/2017/6

**Comment by Sebastian-Roth** [comment]
@FlavioDR Did you get this to work with FOG?

**Comment by Sebastian-Roth** [comment]
Closing the issue now as there has not been any response since months...
