### ISSUE TITLE
FOG_Version is incorrect

### ISSUE THREAD

**Issue by IrisDande** [FOGProject/fogproject#214]
Branch dev should be version 1.5.0 instead of 1.4.4
![image](https://user-images.githubusercontent.com/10474048/32844164-4638e3ae-ca54-11e7-8052-ab184ad90a6e.png)

Full release should be 1.5.0
![image](https://user-images.githubusercontent.com/10474048/32845033-5cc7e1f4-ca56-11e7-9ac0-380034b4f88b.png)

**Comment by Sebastian-Roth** [comment]
Why?? FOG 1.5.0 is **NOT** released yet. There actually is no full release called 1.5.0. Time will tell when we are ready for a next official release.

**Comment by IrisDande** [comment]
But binaries1.4.4.zip look like corrupt when unzip and binaries1.5.0.zip can unzip. Could you check this file again
![image](https://user-images.githubusercontent.com/10474048/32845681-f0d563c0-ca57-11e7-8b12-bc3e4ccf54fd.png)

**Comment by mastacontrola** [comment]
As @Sebastian-Roth Stated, FOG 1.5.0 has not been released. The binaries1.5.0.zip file you've downloaded must have been a manual edit to the installfog.sh file to set the version to 1.5.0 as that's how it knows how/what to download.

What branch is this? If I had to guess, you are installing the "master" branch, and the reason binaries1.4.4.zip is not extracting is it's a corrupted download (as indicated more or less by the first message "End-of-central...."
