### ISSUE TITLE
Custom iPXE menu entries starting with a number cause an issue

### ISSUE THREAD

**Issue by Sebastian-Roth** [FOGProject/fogproject#222]
See details here: https://forums.fogproject.org/topic/11239/ipxe-menu-problem/16

So far it looks like the JQuery expression `$('div#'+this.id)...` still finds the right object but is not able to `fadeToggle` the panel content. Removing `not('.panel-heading')` from that call does actually `fadeToggle` the heading but does not bring up the content.

**Comment by mastacontrola** [comment]
Prepended the pxeItem_ to all of the id flags so there will never be a case of the ipxe custom menu items starting with a number. This should be fixed just need confirmation.

**Comment by mastacontrola** [comment]
I'm closing this issue as the initial problem where it was using a number was addressed. If you're still having issues with it, please let me know.
