### ISSUE TITLE
Reduce dependencies like external repositories

### ISSUE THREAD

**Issue by Sebastian-Roth** [FOGProject/fogproject#224]
As lately seen the FOG installer's dependencies to external repos make it a little less reliable. See Wayne's [post here](https://forums.fogproject.org/post/106837).

So I am wondering if we can get rid of some of the external repos now that PHP 7 is more or less main stream.

**Comment by mastacontrola** [comment]
Sorry for taking so long to respond.

We rely on the repo to ensure we have php version 5.6 or higher. Unfortunately, CentOS and Redhat fall victim to being too old in some cases, so removing the requirement may actually cause us more problems than it fixes. Sure a repo might be done for a day or two, but I can't fix a whole code base in that timeframe.

**Comment by Sebastian-Roth** [comment]
@mastacontrola You are totally right there. I spoke before actually checking the PHP versions in CentOS. We still need those repos. Case closed.
