### ISSUE TITLE
PHP 7.2 removes mcrypt

### ISSUE THREAD

**Issue by ase1590** [FOGProject/fogproject#226]
http://php.net/manual/en/migration71.deprecated.php

mcrypt has been removed from PHP core in 7.2 (now live as of nov 2017), causing FOGMulticastManager to spit this error:
<code>PHP Startup: Unable to load dynamic library 'mcrypt.so'</code>

What are the plans moving forward?

**Comment by mastacontrola** [comment]
Please try the branch labeled swapout-mcrypt-with-openssl.

Hopefully the fog client will still operate and we won't have the reliance on mcrypt at all.

**Comment by mastacontrola** [comment]
The working branch should contain the mcrypt to OpenSSL changes if you’d be willing to update and test.  Thank you.

**Comment by mastacontrola** [comment]
Dev-branch now has these changes. We have tested, though more testing could be used. I'm closing this for now. In case you're still having problems please just let us know.
