### ISSUE TITLE
Missing shutdown on group task function

### ISSUE THREAD

**Issue by andyb2000** [FOGProject/fogproject#232]
I think this is a bug, when using group task for wipe, shutdown isn't honoured. It looks like the params to the DB aren't passed at line 713 and 724.
https://github.com/FOGProject/fogproject/blob/33f538da4381dcba2b7d94d7d8367cf8eb8dcd3a/packages/web/lib/fog/group.class.php#L713

Code should look like this:

`                $batchFields = array(
                    'name',
                    'createdBy',
                    'hostID',
                    'stateID',
                    'typeID',
                    'wol',
                    'shutdown',
                );
                $batchTask = array();
                for ($i = 0; $i < $hostCount; ++$i) {
                    $batchTask[] = array(
                        $taskName,
                        $username,
                        $hostIDs[$i],
                        self::getQueuedState(),
                        $TaskType->get('id'),
                        $wol,
                        $shutdown,
                    );
                }
`

**Comment by hu-man** [comment]
Thanks fella :-)
