### ISSUE TITLE
Version info on Login Screen spins and doesn't appear

### ISSUE THREAD

**Issue by astrugatch** [FOGProject/fogproject#234]
On 1.5.0 RC13.
Minor bug but on the login window "Estimated FOG Sites, Latest Version, Latest Dev Version and Latest SVN Version" all have a spinning icon next to them and the information never loads.

**Comment by mastacontrola** [comment]
Is this still an issue? I’m not able to replicate the problem.

**Comment by astrugatch** [comment]
Most recent login the info loaded but I haven’t made any changes. Close this and if it re-emerges I will reopen.

**Comment by mastacontrola** [comment]
I'll add that occasionally the fogproject.org response is lagging or failing (which we have to restart services to fix) so this isn't necessarily a "bug" in the sense of a coding issue, just that the pages being requested are unavailable at the time the information is looked up.
