### ISSUE TITLE
Error to update database when capture is finished

### ISSUE THREAD

**Issue by Pelt10** [FOGProject/fogproject#235]
Hello,

For school project I use fog 1.5.0-RC13 under Fedora 26(Teacher went it...Debian <3) and I getting an error during step where fog need to update database after capture.

I'm try to full reinstall it, location where an password need to be same(view in doc).
Anyone have an idea to fix it ?

![img_20180227_090042](https://user-images.githubusercontent.com/7582586/36830484-12e5b734-1d24-11e8-9b08-6228251b960e.jpg)

**Comment by mastacontrola** [comment]
Most often this issue is because the home folder for the fog user is missing.

Can you check to see that /home/fog exists on the server and is owned by the user fog?

**Comment by Pelt10** [comment]
Yes /home/fog exist and it own by fog user and this folder have permission rwx------

**Comment by Pelt10** [comment]
In /var/log/messages I find this : 
``Mar  2 16:52:50 242FEDO263-FOG audit[13575]: AVC avc:  denied  { name_connect } for  pid=13575 comm="httpd" dest=21 scontext=system_u:system_r:httpd_t:s0 tcontext=system_u:object_r:ftp_port_t:s0 tclass=tcp_socket permissive=0``

It's log when error occured

**Comment by mastacontrola** [comment]
This sounds like SELinux is still enabled?

Can you try:

```
setenforce 0
```

Then retry the capture?

Then have a look here:
https://forums.fogproject.org/topic/6154/selinux-policy

**Comment by mastacontrola** [comment]
Any word?

**Comment by Pelt10** [comment]
I'm not at school today, I will test that tomorrow 😉

**Comment by Pelt10** [comment]
I justed disable SELinux, and it work ! Thanks for your help !
