### ISSUE TITLE
Display task progress in actual percentage

### ISSUE THREAD

**Issue by Linrador** [FOGProject/fogproject#236]
It would be great if the task progress would be displayed in the actual percentage (value.percent in fog.js) instead of pixels. Right now the progress bar is set to 600px max which doesn't fit right.
You'd have to change some CSS to align it correctly.
This would be far more responsive.

Before:
![old](https://user-images.githubusercontent.com/36955322/36846512-424f14c0-1d5b-11e8-9cd5-fbdc1556c1e5.PNG)

After:
![new](https://user-images.githubusercontent.com/36955322/36846511-4231cf5a-1d5b-11e8-81f8-4716a383cbd0.PNG)

**Comment by mastacontrola** [comment]
what should it be set too?

I'm not saying I couldn't figure it out, but your two images appear to indicate you already were able to fix this, so just wondering (makes my having to fiddle around and figure things out iteratively much easier.)

**Comment by Linrador** [comment]
I've been able to fix it myself, indeed. I just thought it would be nice to include this in further releases.

**Comment by mastacontrola** [comment]
I'm not saying it shouldn't be. I'm just asking what was changed.  I'm guessing fog.css was modified for the:
`width: 600px` to `width: 100%`?

**Comment by Linrador** [comment]
Sorry, I quite didn't get you there. You are correct, I changed the fog.css to `width: 100%`. I also set the padding 0, along with some other cosmetic changes like which I can't remember right now, as I'm off work right now.
I also replaced the value.width with value.percent as stated above in fog.js.

If you want to I can provide some additional info on monday.

**Comment by mastacontrola** [comment]
Mind checking out the working-1.5.1 branch and see if that more closes resembles what you were looking for?

**Comment by Linrador** [comment]
Awesome. Will do so on monday. This can be closed.

**Comment by mastacontrola** [comment]
I actually decided to change out the progress bar from that of one we created to one that bootstrap has natively. The same applies, however, that the progress bar should be pretty well developed now.

Thanks for the suggestions.
