### ISSUE TITLE
Chain loading issue

### ISSUE THREAD

**Issue by aveon-rob** [FOGProject/fogproject#237]
Hi everyone.

I have 30 windows 10 pro in the organization. All 30 are running Windows 10 pro x64 UEFI booting. I installed fog server version 1.5.0 in Ubuntu 16.04.4 UEFI in a Hyper-V Virtual machine.

Windows server 2012 R2 is the dhcp server which has been configured with
option 66 pointing to fog server 
option 67 undionly.kpxe
Also created DHCP policy as described in wiki article 
https://wiki.fogproject.org/wiki/index.php?title=BIOS_and_UEFI_Co-Existence#Using_Windows_Server_2012_.28R1_and_later.29_DHCP_Policy

But i get an error message at boot of the client computers.
![20180305_110352](https://user-images.githubusercontent.com/37079001/36992985-c702261a-2069-11e8-9fa4-1187a814c6ab.jpg)

Please note FOG server 1.4.4 had no problems. This issue happened when I updated to version 1.5.0. I have tried installing FOG server 1.5.0 from scratch on a new VM but same issue.

**Comment by Sebastian-Roth** [comment]
@aveon-rob You wanna search the forums for refind to find many people having this issue. Look into editing rEFInd config (`/var/www/fog/service/ipxe/refind.conf`) to adjust parameters like `scanfor` and `scan_delay`, see here: https://forums.fogproject.org/post/108972

**Comment by aveon-rob** [comment]
Thank you very much. This is a great start. Once I have a solution that works for me Ill make to write it here as well.

**Comment by aveon-rob** [comment]
I was able to modify the `/var/www/fog/service/ipxe/refind.conf` on the line `scanfor internal hdbios` I changed it to `scanfor internal`

That resolved the issue with the screen displaying the warning message about EFI and CMS disabled. But now Windows freezes at boot. I can tell it is frozen because it stays there for half hour, maybe longer but I turned off computer and did not wait any longer, also num lock and caps lock lights do not turn on when I press them. All leading me to believe the machine is frozen. I will continue to research what is happening.

![20180306_072602](https://user-images.githubusercontent.com/37079001/37037576-d2cab4e8-210f-11e8-9461-8e7e0cd550a4.jpg)

**Comment by aveon-rob** [comment]
Have solved the issue. Not sure if this apply to all computer brands. I own 15 Lenovo Tiny M73 and 15 Lenovo Tiny M710q

`sudo nano /var/www/fog/service/ipxe/refind.conf`
I change the following line to match these
`scanfor internal`
`#scan_delay`
