### ISSUE TITLE
Reboot or Shutdown after Snapin Deploy

### ISSUE THREAD

**Issue by 005Zenturio** [FOGProject/fogproject#238]
Hi folks,

i'm in trouble :-(

Why there are only two options "Reboot" and "Shtudown" after deployment of a snapin? 
Is it possible to get an "do nothing".

Is there an quick hack to disable the creation of a shutdown/reboot shedule for all snapins?

I use the actual dev-branch. I can't remember that this was the default behavior in earlier versions. 
Should be nothing or shutdown or reboot.

Kind Regards

Andreas

**Comment by Quazz** [comment]
You can just uncheck them.

**Comment by 005Zenturio** [comment]
Hi looks like a Radio Button not like check boxes :-(

Okay, the behavior is like a ckeckbox if you will cklick again the black "hole" will be a whilte "hole". Nice but not intutive. 

Quazz, you are my life safer, thanks men!

Regards

Andreas

**Comment by mastacontrola** [comment]
Checkboxes don't make sense. If you choose reboot, shutdown should be deselected. And vice versa. I don't see this being unintuituve either. I know it's not normal to see but printers work very similarly. Primary can be any printer, but only onr,and none.
