### ISSUE TITLE
Error Fog Install | Ubuntu 16.04.4 LTS | php-mysqlnd

### ISSUE THREAD

**Issue by Megaland90** [FOGProject/fogproject#246]
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.4 LTS
Release:        16.04

Fog Version  1.5.0

**i have an error :**

 * Skipping package:   php-mcrypt..............................(Already Installed)
 * Installing package: php-mysqlnd.............................Failed! (Will try later)
 * Installing package: php-mysqlnd.............................Failed! (Will try later)
 * Skipping package:   sysv-rc-conf............................(Already Installed)
 * Skipping package:   tar.....................................(Already Installed)
 * Skipping package:   tftpd-hpa...............................(Already Installed)
 * Skipping package:   tftp-hpa................................(Already Installed)

**More details :**

Package php-mysqlnd is a virtual package provided by:
  php7.2-mysql 7.2.3-1+ubuntu16.04.1+deb.sury.org+1
  php7.1-mysql 7.1.15-1+ubuntu16.04.1+deb.sury.org+2
  php5.6-mysql 5.6.35-1+ubuntu16.04.1+deb.sury.org+1
  php7.0-mysql 7.0.28-1+ubuntu16.04.1+deb.sury.org+1

thanks in advance !

**Comment by mastacontrola** [comment]
Please edit the:
`/opt/fog/.fogsettings` file.

Remove the `packages`, `php_ver`, and `php_verAdds` lines. Then rerun the installer. It should clean everything up and allow the installation to occur.

**Comment by KryCool** [comment]
I can't see /opt/fog./fogsrttings

**Comment by mastacontrola** [comment]
Well that's because the path `/opt/fog./fogsrttings` doesn't exist.

`/opt/fog/.fogsettings` is the file, typically.

Are you fresh installing or upgrading?

**Comment by KryCool** [comment]
I fresh installing fog but it's error that

**Comment by mastacontrola** [comment]
What is the error?

If you're running the installer for the first time (fresh install) then the fogsettings file will not exist as it has not been generated yet.  So I don't know what you're trying to do or ask at this point.  All you've stated is that you can't see a file.
