### ISSUE TITLE
problem capturing windows 10 audit mode

### ISSUE THREAD

**Issue by apriscatole** [FOGProject/fogproject#249]
Hi,

recently with the new update of fog 1.5.0 and 1.5.1 I have some problems capturing and image of windows 10. The disk /dev/sda is always in an insicure state... Has anyone had problems like mine?

**Comment by apriscatole** [comment]
I have a fog server running ubuntu 16.04.04 installed yesterday, php  7.1.16, I update the kernel image to 4.15.2

**Comment by schmittjoseph** [comment]
I'd recommend posting your issue on our community forums: https://forums.fogproject.org/

Unfortunately we generally don't have enough active members to help out with support tickets on both GitHub and our forums at the same time.

**Comment by mastacontrola** [comment]
I'm not sure on this issue or if it's been addressed on the forums yet. I'm going to close this issue as I'm fairly certain somebody can (or has) fix the issue or at least help lead you in the right direction.
