### ISSUE TITLE
Ubuntu Server 18.04 Install

### ISSUE THREAD

**Issue by rstockholm88** [FOGProject/fogproject#250]
libcurl3 -> libcurl4 installation issue

The following packages have unmet dependencies:
 libcurl3 : Conflicts: libcurl4 but 7.58.0-2ubuntu3.1 is to be installed
 libcurl4 : Conflicts: libcurl3 but 7.58.0-2ubuntu2 is to be installed

**Force install libcurl3**
The following packages will be REMOVED:
  libcurl4 php7.1-curl
The following NEW packages will be installed:
  libcurl3

**Comment by mastacontrola** [comment]
This is already fixed in the working branch. Working will soon become 1.5.3 under master and dev-branch, I just don't have an exact timeframe quite yet.
