### ISSUE TITLE
Selecting multiple hosts and adding to group

### ISSUE THREAD

**Issue by astrugatch** [FOGProject/fogproject#252]
FOG 1.5.4
Ubuntu 16.04
Using persistent group plugins

Selecting multiple hosts and adding them to groups only adds the first in the list to the group. Each ends up needing to be added to the group individually.

**Comment by mastacontrola** [comment]
Is this From the host page, or from the Group -> Edit -> Membership page?

**Comment by astrugatch** [comment]
This is on the Hosts page using the Group Associations panel at the bottom of the page.

**Comment by Sebastian-Roth** [comment]
@astrugatch Kind of late, very sorry for that.

I think we fixed that in cf01c7e4 - so I might close this now.
