### ISSUE TITLE
Date off in dashboard

### ISSUE THREAD

**Issue by PHX-1138** [FOGProject/fogproject#253]
I have noticed that the date is off compared to the system time on the fog dashboard.

![image](https://user-images.githubusercontent.com/17134720/41944998-b2dc0008-795f-11e8-9ab0-a2085d05383a.png)
[mrparle@10-72-101-22 fog]$ date
Tue Jun 26 16:41:26 PDT 2018

**Comment by mastacontrola** [comment]
Sorry about not getting to this sooner.

As discussed in this thread: https://forums.fogproject.org/topic/12147/date-off-in-dashboard-253-github this was not really a bug, rather a server time misconfiguration. It was reporting times to the GUI in local time, but the Server time was in UTC. Once reconfigured for the appropriate timezone, it appears to have started displaying properly.

**Comment by PHX-1138** [comment]
Ya I went to the forums and one of the mods got me the help I need. Didn't know where to go first so, thx. @mastacontrola Mike P <McAfee>
