### ISSUE TITLE
1.5.4 Will not update with the install.sh command

### ISSUE THREAD

**Issue by theotherguy2175** [FOGProject/fogproject#254]
It will act like it is installing the upgrade but the it shows this error:

Installing now everything is updated........................Failed!

**Comment by dguyton** [comment]
Hey there. This rep is new to me, but sounds like a permission issue. Are you referring to the `installfog.sh `bash script? Running as _root_??

**Comment by mastacontrola** [comment]
install.sh doesn't exist as @dguyton has stated. I'm assuming you mean the installfog.sh script.

Typically, I see this error on ubuntu/debian based machines where the /boot directory is full. Can you provide the output of:
`sudo df -h`

**Comment by theotherguy2175** [comment]
root@fogg:~# df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            3.9G     0  3.9G   0% /dev
tmpfs           787M  9.4M  778M   2% /run
/dev/sda2       451G  5.2G  422G   2% /
tmpfs           3.9G  220K  3.9G   1% /dev/shm
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
tmpfs           3.9G     0  3.9G   0% /sys/fs/cgroup
/dev/sda1       511M  3.5M  508M   1% /boot/efi
tmpfs           787M   56K  787M   1% /run/user/1000

**Comment by theotherguy2175** [comment]
I was able to upgrade by doing the manual install from terminal vs just doing the update command

**Comment by theotherguy2175** [comment]
I was able to upgrade by doing the manual install from terminal vs just doing the update command

**Comment by TheDealman** [comment]
Yeah I have the same issue trying to install 1.5.4 on a new vm with 300gig of space. I get a lot of items failing the install

![2018-08-14_15-08-51](https://user-images.githubusercontent.com/9366580/44121237-10431cdc-9fd4-11e8-9d2e-b83b745a308d.png)
![2018-08-14_15-02-55](https://user-images.githubusercontent.com/9366580/44121238-10a5d624-9fd4-11e8-89c9-0ae428c145af.png)

**Comment by Sebastian-Roth** [comment]
@TheDealman Don't think you are seeing the same problem here. Yours is probably more related to ubuntu repository issues - see Wayne's latest comment here: https://forums.fogproject.org/topic/8730/fog-installer-distro-check
