### ISSUE TITLE
Ubuntu 16.04 php-mysqlnd no longer supported

### ISSUE THREAD

**Issue by ghamlin219** [FOGProject/fogproject#255]
im not sure if this is still existing or has been changed, but the most up-to-date version of ubuntu 16.04 no longer carries php-mysqlnd in their repositories.

I fixed this by finding and replacing mysqlnd with mysql in libs/ubuntu/config.sh and other scripts and the installation went through without a hitch after that. this is with PHP 7.1 and the most recent commit.

I'm new to github but i just wanted to put this information out there. I could also be completely wrong, but I tried going back to older versions of PHP no to avail.

**Comment by mastacontrola** [comment]
The installer should take this into consideration already. If it encounters a package that doesn't exist, it will skip that package. In the case of php-mysql/nd it should test a few different methods of installing this package. In particular, php-mysqlnd is no longer really needed as we use the php-pdo package.
