### ISSUE TITLE
Dead Vbox torrent links

### ISSUE THREAD

**Issue by JS-E** [FOGProject/fogproject#256]
Hey,

Just noticed these torrent links are dead [here](https://wiki.fogproject.org/wiki/index.php?title=Running_pre-built_virtual_machines_in_Virtualbox)

Keep up the good work 👍

**Comment by mastacontrola** [comment]
We didn't really maintain the links to begin with. I know they were functional for some period, but I believe they were for 0.27 versions (maybe slightly newer but still -- now -- ancient in comparison.)
