### ISSUE TITLE
Choosing Chinese doesn't work?

### ISSUE THREAD

**Issue by gyohuangxin** [FOGProject/fogproject#257]
Hello, I have installed the Fog's management website. However, I choose the Chinese and it still uses English.
What can I do with it? Thank you very much!

**Comment by mastacontrola** [comment]
Not sure.

I believe you need to generate the locale for zh_CN for the fog server, and you likely need to rerun the installer with the switch to install languages (without the flag set the binaries that handle the translating aren't created.)

Hopefully this helps.

Here's a link to hopefully help you out. Not sure what OS you're running but this should help for most use cases. https://www.thomas-krenn.com/en/wiki/Configure_Locales_in_Ubuntu
