### ISSUE TITLE
lacking sysv-rc-conf on ubuntu 18.04.1

### ISSUE THREAD

**Issue by Nono-m0le** [FOGProject/fogproject#258]
I'm facing this error (using installfog.sh v1.5.4) on a Ubuntu 18.04.1 : 
` * Installing now everything is updated........................Failed!`

The error log indicate : 

```
Package sysv-rc-conf is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'sysv-rc-conf' has no installation candidate
ii  tar            1.29b-2      amd64        GNU version of the tar archiving utility
ii  tftpd-hpa      5.2+20150808-1ubuntu3 amd64        HPA's tftp server
ii  tftp-hpa       5.2+20150808-1ubuntu3 amd64        HPA's tftp client
ii  unzip          6.0-21ubuntu1 amd64        De-archiver for .zip files
ii  vsftpd         3.0.3-9build1 amd64        lightweight, efficient FTP server written for security
ii  wget           1.19.4-1ubuntu2.1 amd64        retrieves files from the web
ii  xinetd         1:2.3.15.3-1 amd64        replacement for inetd with many enhancements
ii  zlib1g:amd64   1:1.2.11.dfsg-0ubuntu2 amd64        compression library - runtime
Reading package lists...
Building dependency tree...
Reading state information...
Package sysv-rc-conf is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'sysv-rc-conf' has no installation candidate
Reading package lists...
Building dependency tree...
Reading state information...
Package sysv-rc-conf is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'sysv-rc-conf' has no installation candidate
```

Is there a way to avoid the installation of this package during the installation ? (not present anymore as SysV isn't supported since ubuntu 17 : https://bugs.launchpad.net/ubuntu/+source/sysv-rc-conf/+bug/1741346 )

**Comment by Nono-m0le** [comment]
By removing "sysv-rc-conf" on line : 62 & 78 on fogproject-1.5.4/lib/ubuntu/config.sh the installation succeed.

I still have a "Database connection unavailable" on the webpage, but this may be linked to something else.
If not, I noticed few "FOGService: XXX - Waiting for mysql to be available" on few /opt/fog/logs/*.log files including; 
```
multicast.log
fogreplicator.log
fogimagesize.log
fogsnapinrep.log
fogscheduler.log
pinghost.log
fogsnapinhash.log
```

**Comment by mastacontrola** [comment]
I'm not quite sure why this is happening. I know we have been testing installs on 18.04 for about 3 months now and not seen any issues (beyond a couple of ubuntu repo issues on occasion).

For the "Database connection unavailable", what's the output of: `df -h`

**Comment by Nono-m0le** [comment]
Hi @mastacontrola not sure why you close this issue as I just retry on a fresh reinstall of Ubuntu 18.04.1 
 and got the exact same behavior ... (previously, I was migrating from Ubuntu 14 to Ubuntu 18)

Could you please confirm we're talking about : 
Ubuntu Server 18.04.1 with FOG 1.5.4 ?
I can assure you that the installation failed, but this time with this error : 
```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 php7.1-mcrypt : Depends: libmcrypt4 but it is not installable
E: Broken packages
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 php7.1-mcrypt : Depends: libmcrypt4 but it is not installable
E: Unable to correct problems, you have held broken packages.

```

**Comment by Sebastian-Roth** [comment]
Add `universe` section to `/etc/apt/sources.list` before running the installer to prevent from `libmcrypt4 but it is not installable` error.

**Comment by Nono-m0le** [comment]
Thanks for this @Sebastian-Roth I'll give it a try tomorrow and let you know the final results (also about the interfaces, discussed in #261 )

**Comment by Sebastian-Roth** [comment]
I just figured what the difference is Ubuntu 18.04 server comes in two different flavors. One is the normal server ISO and the other one is the LIVE server. For 18.04 straight you could still download both versions - [see here](http://old-releases.ubuntu.com/releases/18.04.0/). But seems like since 18.04.1 is out there is only the LIVE server image available anymore. I just installed 18.04.0 plain server and it has the mentioned `universe` section in sources.list

**Comment by Nono-m0le** [comment]
Hi @Sebastian-Roth 
Only the 18.04.1 is LTS, the .0 flavor isn't.

**Comment by abulhol** [comment]
Hi guys and @Sebastian-Roth in particular, I faced the same issue with sysv-rc-conf and found the code that causes this mystery, read the answer here: 
https://forums.fogproject.org/topic/12528/sysv-rc-conf-missing
