### ISSUE TITLE
From the Fog Menu on the Client Wont boot to Disk

### ISSUE THREAD

**Issue by theotherguy2175** [FOGProject/fogproject#259]
When in the fog menu on a client machine, when you select the "Boot from hard disk" option, it doesnt boot. Just reloads the page. I remember this successfully working in the past, so i dont know if it is something as simple as a setting in the web console or what.

**Comment by mastacontrola** [comment]
The boot to disk is set by a global or individual host.  What I mean:

If a host is registered you can tell the host how the boot menu will attempt to release to the first disk.  There are three main kinds in Legacy, GRUB, SANBOOT, and EXIT. (rEFInd may work too but this is more for UEFI.)  If the individual host exit types are not set, it will use the global values found under: FOG Configuration->FOG Settings.

Hopefully this helps.

**Comment by Sebastian-Roth** [comment]
@theotherguy2175 Do you need any more advice on this? I will close this issue soon if we don't get an answer back.

**Comment by theotherguy2175** [comment]
Yeah I'm all set thank you
