### ISSUE TITLE
Multicasting: "This is not the master node" in the storage nodes (with workaround)

### ISSUE THREAD

**Issue by brnnrc** [FOGProject/fogproject#268]
Hi,
I have two master storage nodes (for two groups) and when I reboot these servers, they say Multicasting: "This is not the master node".
If I restart the multicast service, the log begins to say " No tasks found!" as it should be.

I found it works after reboot inserting a sleep in the php script /opt/fog/service/FOGMulticastManager/FOGMulticastManager
...
   $ServiceClass->getBanner();
   sleep(10);
...

**Comment by Sebastian-Roth** [comment]
@brnnrc Sorry for the late reply. Which Linux OS do you use? I guess this has do do with services starting in parallel and the DB not being up properly when the multicast service is starting.

**Comment by brnnrc** [comment]
@Sebastian-Roth I'm using debian 9.5. I think your guess is correct.
Thanks for your reply.

**Comment by Sebastian-Roth** [comment]
@brnnrc I have looked into this and tested but I can't seem to replicate this exact issue. Which version of FOG are you running. We added some checks and DB reconnection about a year ago. So I'd guess you won't have this issue anymore if you upgrade to the latest version.

See my log file here (mysql disabled on startup and then started manually):
```
[11-25-18 5:09:42 pm] FOGService: MulticastManager - Waiting for mysql to be available
[11-25-18 5:09:52 pm] FOGService: MulticastManager - Waiting for mysql to be available
[11-25-18 5:10:02 pm] FOGService: MulticastManager - Waiting for mysql to be available
[11-25-18 5:10:12 pm]  * Starting MulticastManager Service
[11-25-18 5:10:12 pm]  * Checking for new items every 10 seconds
[11-25-18 5:10:12 pm]  * Starting service loop
[11-25-18 5:10:14 pm]  * No new tasks found
```

**Comment by brnnrc** [comment]
@Sebastian-Roth I'm using 1.5.4 version on all nodes.
I double checked and the issue is with the
   $ServiceClass->waitInterfaceReady();
call, before the
   $ServiceClass->waitDbReady();
So, delaying the first one I have got no issues, but the issue raises delaying the second one only.
Thanks
Enrico

**Comment by Sebastian-Roth** [comment]
@brnnrc Ahh, now I see. Thanks for testing the delay at different places in the code. My guess is that in some conditions the `$ServiceClass->waitInterfaceReady();` returns because one of several interfaces is already up but not the interface that has the IP address registered as node within FOG. I can't prove this yet as I am unable to replicate the issue so far. But it makes sense to me and seems like a race condition that we have not thought about enough.

Can you please test the following. Remove the sleep you added to the service start. Then edit `/var/www/html/fog/lib/fog/fogbase.class.php`, jump to line 2226 and comment the first three lines of the `getIPAddress()` function. Make it look like this:
```
    /**
     * Get IP Addresses of the server.
     *
     * @return array
     */
    protected static function getIPAddress()
    {
//        if (count(self::$ips) > 0) {
//            return self::$ips;
//        }
        $output = array();
        exec(
            "/sbin/ip -4 addr | awk -F'[ /]+' '/global/ {print $3}'",
            $IPs,
            $retVal
        );
```
Now reboot the server a couple of times an see if it works properly all the time. Please let me know.

**Comment by brnnrc** [comment]
@Sebastian-Roth It works!
I can't see my (only) ethernet interface in multicast.log but "no tasks found" is listed.

[11-28-18 9:06:32 am] Interface Ready with IP Address: 127.0.0.1
[11-28-18 9:06:32 am] Interface Ready with IP Address: 127.0.1.1
[11-28-18 9:06:32 am]  * Starting MulticastManager Service
[11-28-18 9:06:32 am]  * Checking for new items every 10 seconds
[11-28-18 9:06:32 am]  * Starting service loop
[11-28-18 9:06:34 am]  * **No tasks found!**

Restarting the multicast service instead:

[11-28-18 10:25:41 am] Interface Ready with IP Address: 127.0.0.1
[11-28-18 10:25:41 am] Interface Ready with IP Address: 127.0.1.1
[11-28-18 10:25:41 am] Interface Ready with IP Address: **172.23.24.11**
[11-28-18 10:25:42 am]  * Starting MulticastManager Service
[11-28-18 10:25:42 am]  * Checking for new items every 10 seconds
[11-28-18 10:25:42 am]  * Starting service loop
[11-28-18 10:25:43 am]  * **No tasks found!**

So, your guess is correct, I think. Note: I didn't try a multicast session. Should I do?
Thanks again

**Comment by Sebastian-Roth** [comment]
@brnnrc Ok, seems like we are on the right track with that. I still haven't got a good idea on how we can implement the code to not run the query IP shell commands all the time (because we do this in a loop over and over) but still recognize new interfaces coming up later. Maybe querying `/proc` would. It's not as resource costing but we can still get the rough information on interface count, maybe.

> Note: I didn't try a multicast session. Should I do?

No need to I think.

**Comment by dklann** [comment]
I too was seeing the message "This is not the master node" in _/opt/fog/log/multicast.log_. I applied the change shown above by @Sebastian-Roth  and I no longer see that message in the log file. I have 2 interfaces on my stand-alone Fog server (running Ubuntu 18.04.1): Wifi (wlp3s0, 10.2.3.X/24) for accessing the web interface from other workstations on the network, and Ethernet (enp0s25, 10.5.1.1/24) for imaging workstations.

**Comment by Sebastian-Roth** [comment]
@brnnrc I somehow lost track of this an got reminded of it from a forum post: https://forums.fogproject.org/topic/13223/fog-1-5-6-multicast-problem

Came up with a more appropriate solution to that. Edit `/lib/systemd/system/FOGMulticastManager.service`, goto line 18 that looks like this:
```
After=syslog.target network.target mysql.service
```
Change it to look like this:
```
After=syslog.target network-online.target mysql.service
```
Then reboot your FOG server and check /var/log/fog/fogmulticast.log again.

I will push a fix to `dev-branch`.

**Comment by Sebastian-Roth** [comment]
Hmmm, though I kind of like the solution to wait for the network interfaces to really come online (get an IP) it's not the preferred from a systemd view. See here: https://www.freedesktop.org/wiki/Software/systemd/NetworkTarget/
> If you are a developer, instead of wondering what to do about network.target, please just fix your program to be friendly to dynamically changing network configuration. That way you will make your users happy because things just start to work, and you will get fewer bug reports as your stuff is just rock solid.

Although we are in a situation where users ought to use static IPs and `network-online.target` shouldn't delay for too long I can still see the point here.
