### ISSUE TITLE
Problem wth long/not "normal" interface names in setup script

### ISSUE THREAD

**Issue by lini500** [FOGProject/fogproject#274]
When I enter my network interface name "enx00e04c680427", the setup spills out an error. In the end it fails when configuring the dhcp server.
```
  Would you like to change the default network interface from ?
  If you are not sure, select No. [y/N] y
  What network interface would you like to use? enx00e04c680427
../lib/common/functions.sh: Zeile 149: /8: Syntax Fehler: Operator erwartet. (Fehlerverursachendes Zeichen ist »/8«).
```

**Comment by Sebastian-Roth** [comment]
Thanks for reporting. I am not sure if this is really related to the long interface name. We do see exactly this behavior if there is no IP address configured to the interface when running the installer. Not sure if you are aware of the fact that FOG does not configure the interface for you but you need to do that manually before running the installer.

If you had an IP set for the interface beforehand would you please run the following command and post output here: ` ip -f inet -o addr`

**Comment by lini500** [comment]
Okay sorry, and thanks for the fast reply. The want a cable plugged in at the moment I ran the installer. But I had configured a static IP in the gnome/Ubuntu GUI. I cannot paste any further information here, because I reinstalled with the idea of that would fix the problem.
-------- Ursprüngliche Nachricht --------Von: Sebastian-Roth <notifications@github.com> Datum: 27.11.18  19:56  (GMT+01:00) An: FOGProject/fogproject <fogproject@noreply.github.com> Cc: lini500 <linus_h@web.de>, Author <author@noreply.github.com> Betreff: Re: [FOGProject/fogproject] Problem wth long/not "normal" interface
  names in setup script (#274) Thanks for reporting. I am not sure if this is really related to the long interface name. We do see exactly this behavior if there is no IP address configured to the interface when running the installer. Not sure if you are aware of the fact that FOG does not configure the interface for you but you need to do that manually before running the installer.
If you had an IP set for the interface beforehand would you please run the following command and post output here:  ip -f inet -o addr

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/FOGProject/fogproject","title":"FOGProject/fogproject","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/FOGProject/fogproject"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Sebastian-Roth in #274: Thanks for reporting. I am not sure if this is really related to the long interface name. We do see exactly this behavior if there is no IP address configured to the interface when running the installer. Not sure if you are aware of the fact that FOG does not configure the interface for you but you need to do that manually before running the installer.\r\n\r\nIf you had an IP set for the interface beforehand would you please run the following command and post output here: ` ip -f inet -o addr`"}],"action":{"name":"View Issue","url":"https://github.com/FOGProject/fogproject/issues/274#issuecomment-442175299"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/FOGProject/fogproject/issues/274#issuecomment-442175299",
"url": "https://github.com/FOGProject/fogproject/issues/274#issuecomment-442175299",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [FOGProject/fogproject] Problem wth long/not \"normal\" interface names in setup script (#274)",
"sections": [
{
"text": "",
"activityTitle": "**Sebastian-Roth**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@Sebastian-Roth",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"FOGProject/fogproject\",\n\"issueId\": 274,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"FOGProject/fogproject\",\n\"issueId\": 274\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/FOGProject/fogproject/issues/274#issuecomment-442175299"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 416278617\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by Sebastian-Roth** [comment]
@lini500 said:
> I cannot paste any further information here, because I reinstalled with the idea of that would fix the problem.

What did you install? If it's Linux you can always run the command: `ip -f inet -o addr`

> The want a cable plugged in at the moment I ran the installer.

Not sure if I get this right but it sounds as if you did not have a cable plugged in. If the interface was up that should not be an issue. Should still work. If not taken down by crappy NetworkManager on unplug (not sure about this). BUT you definitely need internet connection to properly install FOG. So from what you say it sounds as if you have two interfaces in that system. One should be internet and you want to install FOG to use the other interface. That's fine, that other interface just needs to be up and have an IP set before running the installer.

**Comment by Sebastian-Roth** [comment]
I just added and renamed an interface on a test system of mine.
```
ip -f inet -o addr
...
3: enx00e04c680427    inet 192.168.1.3/24 brd 192.168.1.255 scope global enx00e04c680427\       valid_lft forever preferred_lft forever
```
Doing an install works perfectly fine choosing that interface with the long name.

```
  Would you like to change the default network interface from ?
  If you are not sure, select No. [y/N] y
  What network interface would you like to use? enx00e04c680427 

  Would you like to setup a router address for the DHCP server? [Y/n] 
  What is the IP address to be used for the router on
```

I am fairly sure your install failed because the interface was either not up or not configured before running the installer.

**Comment by lini500** [comment]
Thanks a lot. The interface was configured, but it was turned off. Now it works!
