### ISSUE TITLE
Improve installer to ask for interface first and also grab hostname

### ISSUE THREAD

**Issue by Sebastian-Roth** [FOGProject/fogproject#277]
Lately I have thought about changing the installer to ask for the interface first (enumerate interface names and let the user decide). This way we can check if interface is properly setup *and* up.

We might also think about grabbing the machines hostname to add to the CN when generating the certificate for HTTPS installs. This might cause a bit more trouble as hostname discovery can be tricky (local hostname vs. DNS entries and so forth).

**Comment by astrugatch** [comment]
Asking for the desired hostname may be better than trying to divine it from the system and it could be a default to use the configured (on the machine) hostname if nothing is entered.

**Comment by mastacontrola** [comment]
Well, as I imagine for most, https isn't very commonly necessary, but I can think of it being extremely useful in today's security conscious  world.

Hostname and IP are the most common mechanisms, but I think Alternate Names, or even adding potential for wildcard could be useful as well.

However, in the generalized state, I think hostname and IP are enough to at least generate our self signed cert. Adding "hidden" options such as `alternate_name="sub1.hostname.org,sub2.hostname.org"` would be a nice approach too. Of course it complicates the installer in that we need to check for these things, but ultimately I think that would be relatively simple and give a feature rich experience.

**Comment by Sebastian-Roth** [comment]
Ok, added two fixes.
