### ISSUE TITLE
Question: which is the right hook to step in during a client poll?

### ISSUE THREAD

**Issue by sctt** [FOGProject/fogproject#284]
Hello,

I'm coding a plugin which has to take decisions based on hosts IP addresses.
As soon as a host appears to be connected to the fog server, the plugin has to get its IP and do the work.

My idea was to take advantage of the polling system by triggering the plugin on every poll request, that's why I decided to use the HOST_INFO_EXPOSE hook, but then I found out that this hook had no longer been used so it would never be processed (is this hook deprecated? why it has been removed?).

Do you have any suggestion on which hook should I use to get this job done? I didn't find anything suitable... 
Should i just restore the HOST_INFO_EXPOSE hook by adding the trigger on the newer requestClientInfo function inside the fogpage class? This seems to me the easier way but maybe I'm missing something here, that's why i'm asking for your opinion about this.

Thank you in advance for your suggestions.

**Comment by sctt** [comment]
thanks @Sebastian-Roth 

does the HOST_CHECKIN event trigger even when the host has not any scheduled task?

the hook/event i need is very generic that's why i couldn't be much specific.
let's say the plugin has to know the host IP address as soon as it appears to be **online** (cause it did a poll request, a checkin or anything else, but whatever it's going to be it has to be reliable: if that hook/event is triggered, the plugin is sure the host is online and the IP is available to do the work, and, on the contrary, if it's not triggered, the plugin is sure the host doesn't appear to be online so it has not to do the work)

if HOST_CHECKIN triggers only if there is a scheduled task, that's not what i need because it's too specific, i need something that will always get triggered when the host asks anything to the fog server, no matter of what it is or what's the outcome of that request.

if there's no hook/event suitable i'm still thinking about restoring that HOST_INFO_EXPOSE trigger... 
i hope i made myself clearer this time, thank you for your support.

**Comment by Sebastian-Roth** [comment]
@sctt Yes, difinitely getting a better picture of what you ask here. AFAIK there is no such hook/event for what you are looking for.

> if there's no hook/event suitable i'm still thinking about restoring that HOST_INFO_EXPOSE trigger...

That hook won't help you at all. It's only triggered on scheduled tasks as well. I can't see of any way you could make it so it does exactly what you are trying to do.

I guess you just need to add an event or hook yourself or possibly find one looking through the code and testing. I am still not sure of the best place to put this. Most probably you will need to use at least two different hooks/events.

I would probably start in the [FOGPage class constructur](https://github.com/FOGProject/fogproject/blob/dev-branch/packages/web/lib/fog/fogpage.class.php#L209). But be aware that each and every request/click to/on the web UI triggers this as well. So you need to find a way to decide weather this is a request you want to look into or just skip ahead. [Line number 243](https://github.com/FOGProject/fogproject/blob/dev-branch/packages/web/lib/fog/fogpage.class.php#L243) is a good example on how to check for machines with the fog-client installed sending a request. Possibly somewhere around [line 2847](https://github.com/FOGProject/fogproject/blob/dev-branch/packages/web/lib/fog/fogpage.class.php#L2847)...

For the rest you get all of it hooking into the boot menu code. So maybe `BOOT_ITEM_NEW_SETTINGS` ([line 309](https://github.com/FOGProject/fogproject/blob/dev-branch/packages/web/lib/fog/bootmenu.class.php#L309) - although this is meant to be used for something else but should still do the job for you. Again here you need to be aware that this is being fired a couple of times on each client booting PXE! Make sure you add thorough checking in your code to skip requests quickly that are either not what you are looking for or subsequent requests of the very same client.

**Comment by sctt** [comment]
@Sebastian-Roth thank you, as you say maybe adding a new event/hook is probably the right way to do this.

let me articulate a little more what i mean for "restoring the HOST_INFO_EXPOSE" cause maybe i've been unclear again or my assumptions about how the system works are not correct.

the idea is to check the host IP during its polling to the server, assuming that:

```
192.168.x.1:80 192.168.x.208 - - [26/Jan/2019:13:34:50 +0100] "GET /fog/management/index.php?sub=requestClientInfo&configure&newService&json HTTP/1.1" 200 655 "-" "-"
192.168.x.1:80 192.168.x.208 - - [26/Jan/2019:13:34:50 +0100] "GET /fog/management/index.php?sub=requestClientInfo&mac=xx:xx:xx:xx:xx:xx%xxxx:xx:xx:xx:xx:xx&newService&json HTTP/1.1" 200 1374 "-" "-"
```

represents a regular request that every host **always** does until it's turned off, i can use this to check the host IP address regularly.

putting it into practice, that means adding a new hook/event (not necessarily called HOST_INFO_EXPOSE) after [line 3002](https://github.com/FOGProject/fogproject/blob/4c804c4dafe966e6de2555efc94d2f4b8aeb7f00/packages/web/lib/fog/fogpage.class.php#L3002).

do you think this could work?
maybe there are situations where the host is not supposed to poll using the requestClientInfo method, please let me know if that's the case.

**Comment by Sebastian-Roth** [comment]
@sctt The clients sends a couple more requests - see the following list I just copied from a log:
```
http://x.x.x.x/fog/management/index.php?sub=requestClientInfo&authorize&newService
http://x.x.x.x/fog/management/index.php?sub=requestClientInfo&configure&newService&json
http://x.x.x.x/fog/management/index.php?sub=requestClientInfo&mac=...&newService&json
http://x.x.x.x/fog/service/getversion.php?clientver&newService&json
http://x.x.x.x/fog/service/getversion.php?newService&json
```
So it's up to you to decide at which point you want to trigger your thing. Should it be even before a client successfully authorizes the communication then you'd go just before [line 3009](https://github.com/FOGProject/fogproject/blob/4c804c4dafe966e6de2555efc94d2f4b8aeb7f00/packages/web/lib/fog/fogpage.class.php#L3009). But this would only happen once the fog-client comes up. As I don't know what exactly you want to do I can't give better information. Might be best to go with line 3002 as you said - this way you get the information on fog-client startup (machine boot) and an update ever couple of minutes.

> do you think this could work?

Depends on what you want but I guess it would work for your case.

> maybe there are situations where the host is not supposed to poll using the requestClientInfo method, please let me know if that's the case.

As I already mentioned two times there are very different situation when a client contacts the FOG server. On startup it usually is set to PXE boot and would therefore request the FOG PXE boot menu (also a HTTP request) that you could use. See my post above for that.

I am going to close this now as this is not really a FOG issue. Feel free to still ask more questions.

**Comment by Sebastian-Roth** [comment]
@sctt You could name it whatever you like. Maybe `REQUEST_CLIENT_INFO` or `FOG_CLIENT_CONTACT`...
