### ISSUE TITLE
MAC address lookup always results in "Unknown"

### ISSUE THREAD

**Issue by jmechalas** [FOGProject/fogproject#291]
All MAC address lookups in fogpage.class.php result in an 'Unknown' because getmacman() is calling:

`filter_input(INPUT_POST, 'prefix')`

It should be:

`filter_input(INPUT_GET, 'prefix')`

**Comment by mastacontrola** [comment]
@jmechalas, thanks for reporting and the suggestion for fixing the problem.

I've added it to the dev-branch.
