### ISSUE TITLE
Add option to change Server IP

### ISSUE THREAD

**Issue by mrpouletcurry** [FOGProject/fogproject#292]
Hello FOG team,

What do you think to add a option to change address IP to server without to rerun the installer ?
I think, specially in the case we don't have access to the internet.

Currently, I use FOG in Ubuntu 18.04

Regards.

PS : If a follow your procedure [Change FOG Server IP Address](https://wiki.fogproject.org/wiki/index.php/Change_FOG_Server_IP_Address), this works. But I need acces to the internet to update

**Comment by mastacontrola** [comment]
This already exists. Just make the modifications directly to the storage node and fog settings that have the old IP address.

Not sure I understand what you're asking.

**Comment by Sebastian-Roth** [comment]
@mrpouletcurry Why do you think internet access is needed to change the IP of your FOG server?

All the information needed to make the changes is in the wiki article you posted. Beside that there is also a script to automate those things: https://github.com/FOGProject/fog-community-scripts/tree/master/updateIP

While I think it's wise to connect a server to the internet every now and then to get fixed and updated packages, there is no need to if changing the IP is all you want to do.

**Comment by Sebastian-Roth** [comment]
@mrpouletcurry Please let us know if you need any further assistance with this. Will close the issue meanwhile as I don't think this should be fixed in the main FOG code. Feel free to still post a comment here. Might even re-open in case.
