### ISSUE TITLE
SSD ist not resizing after deployment

### ISSUE THREAD

**Issue by FloxRoxX** [FOGProject/fogproject#293]
We have a new batch of PC's with WD Green Sata M.2 SSD's that will not resize after imaging is done.
If i exchange the SSD with another brand it is just working fine.
What can cause this Problem ? Iam using version: 1.5.5.3 of FOG.

The SSD is recognized as /dev/sda in the system and i use a GPT partition scheme where sda4 is the Windows installation.

The model of the SSD is the following:
WDS120G2G0B

https://www.amazon.de/dp/B078WYRR9S?m=A3JWKAKR8XB7XF&tag=idealode-am-pk-21&ascsubtag=eUtjboRCo0LKPM0TwNxiAQ

**Comment by Sebastian-Roth** [comment]
@FloxRoxX Please post the contents of the three files `d1.partitions`, `d1.minimum.partitions` and `d1.fixed_size_partitions` that you find in your image directory on your FOG server (usually in `/images/<imagename>/...`

**Comment by Sebastian-Roth** [comment]
@FloxRoxX Please give us the requested information or we can't help you.

**Comment by FloxRoxX** [comment]
> @FloxRoxX Please give us the requested information or we can't help you.

Hi, i can post it tomorrow when i will be at work.

**Comment by FloxRoxX** [comment]
d1.partitions:

```
label: gpt
label-id: 7F8D39DA-AA47-4751-9246-D6B1430047FE
device: /dev/nvme0n1
unit: sectors
first-lba: 34
last-lba: 500118158

/dev/nvme0n1p1 : start=        2048, size=     1021952, type=DE94BBA4-06D1-4D40-A16A-BFD50179D6AC, uuid=A12E985A-9EAF-4275-A113-86EC1B520D70, name="Basic data partition", attrs="RequiredPartition GUID:63"
/dev/nvme0n1p2 : start=     1024000, size=      204800, type=C12A7328-F81F-11D2-BA4B-00A0C93EC93B, uuid=BA3B519D-2FC3-4D54-B015-4A370416F2EF, name="EFI system partition", attrs="GUID:63"
/dev/nvme0n1p3 : start=     1228800, size=       32768, type=E3C9E316-0B5C-4DB8-817D-F92DF00215AE, uuid=9607B20B-6A19-4BB4-BDED-54AC7B9CB939, name="Microsoft reserved partition", attrs="GUID:63"
/dev/nvme0n1p4 : start=     1261568, size=   498856448, type=EBD0A0A2-B9E5-4433-87C0-68B6B72699C7, uuid=E47D44BC-576C-4449-BF9D-7BBB47CA0A4D, name="Basic data partition"

```

d1.minimum.partitions:
```
label: gpt
label-id: 7F8D39DA-AA47-4751-9246-D6B1430047FE
device: /dev/nvme0n1
unit: sectors
first-lba: 34
last-lba: 500118158

/dev/nvme0n1p1 : start=        2048, size=       21404, type=DE94BBA4-06D1-4D40-A16A-BFD50179D6AC, uuid=A12E985A-9EAF-4275-A113-86EC1B520D70, name="Basic data partition", attrs="RequiredPartition GUID:63"
/dev/nvme0n1p2 : start=     1024000, size=      204800, type=C12A7328-F81F-11D2-BA4B-00A0C93EC93B, uuid=BA3B519D-2FC3-4D54-B015-4A370416F2EF, name="EFI system partition", attrs="GUID:63"
/dev/nvme0n1p3 : start=     1228800, size=       32768, type=E3C9E316-0B5C-4DB8-817D-F92DF00215AE, uuid=9607B20B-6A19-4BB4-BDED-54AC7B9CB939, name="Microsoft reserved partition", attrs="GUID:63"
/dev/nvme0n1p4 : start=     1261568, size=    23461048, type=EBD0A0A2-B9E5-4433-87C0-68B6B72699C7, uuid=E47D44BC-576C-4449-BF9D-7BBB47CA0A4D, name="Basic data partition"
```


d1.fixed_size_partitions:
```
:2:3
```

**Comment by Sebastian-Roth** [comment]
@FloxRoxX Sorry for the delayed answer. The outputs you posted look fine from my point of view. What I can imagine is the drive resize is not working might be a true 4096 sector size disk which might upset the math of our expansion algorithms.

Can you elaborate more on what you mean by "will not resize after imaging is done"? Does it deploy properly and the system boots but when looking at it in Windows Disk Management you see that the partition is just s little more the size than you have data on the Windows partition?

**Comment by Quazz** [comment]
Possibly to do with the recently discovered `sfdisk` bug. What do you think @Sebastian-Roth ?

**Comment by Sebastian-Roth** [comment]
@FloxRoxX 
@Quazz is right! Pretty sure this is fixed in the latest init binaries. Download [64 Bit](https://fogproject.org/inits/init.xz) and [32 Bit](https://fogproject.org/inits/init_32.xz) and put those in `/var/www/html/fog/service/ipxe/` dir on your FOG server. Probably good to rename the original ones instead of overwriting.
