### ISSUE TITLE
WebUI recommendations

### ISSUE THREAD

**Issue by veedubbs** [FOGProject/fogproject#298]
Hello.  Love your software!  Just some simple recommendations as we've been using it more and more:

- On the Dashboard tab, on the 'Imaging Over the last 30 days, have two line graphs.  One for deployments and one for captures.

- On the Fog Configuration tab, have the last 7 links on the left (Fog Sourceforge Page to Donate to FOG) open in a new tab so you don't leave the FOG application.

**Comment by Sebastian-Roth** [comment]
@veedubbs Thanks for your nice comment. I pushed a fix the the current development branch to fix the second point you mentioned (7502d9b).

@mastacontrola What's your opinion on the first point? You know the graph things way better than I do.

**Comment by veedubbs** [comment]
Thanks @Sebastian-Roth!  When you say development branch, does that mean 1.6.0?  If so, is there a potential release date for that?

Just curious...

**Comment by Sebastian-Roth** [comment]
@veedubbs No it's the `dev-branch` ([link](https://github.com/FOGProject/fogproject/tree/dev-branch)) where we push forward to the next 1.5.x release. But I am sure this change will also make it's way into the 1.6.x dev branch. But I can't give you a date for any release yet as we don't have much (wo)man power at the moment to push things forward.

**Comment by veedubbs** [comment]
No worries, thanks!

**Comment by mastacontrola** [comment]
I don't know that we keep track of the deployments and captures in such a way, rather it pulls the imagingLog. While it does keep track of basic types in the form of "up" or "down". Adding the second line isn't very simple.

I'll see what I can do in the near future, but don't expect it anytime too soon.

**Comment by Sebastian-Roth** [comment]
@veedubbs Should we keep this issue open?

**Comment by veedubbs** [comment]
No.  I can close it.

Thanks!
