### ISSUE TITLE
Unable to install FOG 1.5.5 on Ubuntu Server 18.04. get error Downloading binaries needed.................................Failed!

### ISSUE THREAD

**Issue by otweena** [FOGProject/fogproject#302]
Unable to install FOG 1.5.5 on Ubuntu Server 18.04. get error Downloading binaries needed.................................Failed!

i do have proxty configure and i do have internet ! any advise
 ?

**Comment by otweena** [comment]
![image](https://user-images.githubusercontent.com/33775537/55244295-fc494680-5251-11e9-9ec9-b2df7449b950.png)

**Comment by Sebastian-Roth** [comment]
@otweena said:
> i do have proxty configure and i do have internet ! any advise

Please post your proxy configuration so we can have a look at it.

At this stage the installer scripts use `curl` to download the binaries from the web. Most probably your proxy configuration is not right.

**Comment by otweena** [comment]
now i succeded to install , after install do i need to set up something or clinets will boot pxe auto ?

**Comment by Sebastian-Roth** [comment]
@otweena PXE depends on BIOS/UEFI setting, nothing we could alter in our software.
