### ISSUE TITLE
Delete a image

### ISSUE THREAD

**Issue by mrpouletcurry** [FOGProject/fogproject#303]
When I go in List All Images » Images and I choose a image to delete.
I check delete files option, and I try it. 
De file is delete but not the entry in database. So Image it's always display in list, but without file, because it was the deleted.

**Comment by Sebastian-Roth** [comment]
@mrpouletcurry Which version of FOG do you use?

**Comment by mrpouletcurry** [comment]
@Sebastian-Roth I use version 1.5.5

**Comment by Sebastian-Roth** [comment]
@mrpouletcurry Sorry for the long delay. Just too many things to work on right now.

So I finally got around to test this and I can't replicate the issue. Tried two times and for me it deletes the entry from the database as well as the files (if checked on delete) just as expected.

Possibly there is an issue within your database. Are you able to create a new image definition in the web UI?

Please run the database maintenance your find in our wiki: https://wiki.fogproject.org/wiki/index.php/Troubleshoot_MySQL#Database_Maintenance_Commands

**Comment by Sebastian-Roth** [comment]
Closing as we have not heard back.
