### ISSUE TITLE
Images on a nfs storage

### ISSUE THREAD

**Issue by christelle29200** [FOGProject/fogproject#305]
Hello
I am completely stuck on an issue for a while now. Il install a FOG serveur and i create a storage node pointing on an external nfs storage. Only apache user have the rights on this storage.
At the begiining i had an error "Could not mount image folder Reason:mounting failed IP/images_nfs/dev/ on /images permissions denied"
- First, in storage management i cannot let the password blank.
So i update in sql:
 update nfsGroupMembers set ngmPass='' WHERE ngmUser='apache';

Now there is another error:

Boot.php HTTP 5xx server error http://ipxe.org/1d0c6598

Is it possible to do what i want to make?

**Comment by junkhacker** [comment]
short answer: no, you can't do it. you're trying to create an NFS share out of an NFS mounted share

**Comment by Sebastian-Roth** [comment]
I am closing this as there is not much we can do. This is a restriction within NFS (or the Linux kernels implementation of that protocol) and we can't change that.
