### ISSUE TITLE
Add support for ARM machines

### ISSUE THREAD

**Issue by parkerberb-nfv** [FOGProject/fogproject#307]
I think we should fully support ARM client machines in FOG.

I have submitted some code related to this in the past: 
[here](https://github.com/FOGProject/fogproject/pull/239)
[and here](https://github.com/FOGProject/fos/pull/10)

I currently use FOG with the above changes to manage my ARM64 based machines, but this takes a few shortcuts. For ARM to be fully supported, we would need:

1) Support for 64 and 32 bit arm kernel and init images, just like the user can currently select with kernel and init to use for their 64 bit / 32 bit x86 machines

2) Reliable detection of system arch. Currently the default.ipxe script relies on cpuid, which is x86 specific: [docs](http://ipxe.org/cmd/cpuid). I fall back on [buildarch](https://ipxe.org/cfg/buildarch), but this is not a perfect solution either. This should identify the host as one of (32-bit x86, 64-bit x86, 32-bit ARM, 64-bit ARM) and use that to grab the correct kernel and init when pxe booting.

3) Bundling of ARM-based grub / refind / ipxe / kernel / initrd. My PR above allows the regular FOS system to build arm based kernel and init, but I am not familiar with how you consume / build everything and bundle it into a FOG release.

**Comment by Sebastian-Roth** [comment]
@parkerberb-nfv Building the ARM inits I just ran into a question that caught me blank. The Buildroot config has many different choices of "Architecture Variants". In the old config we were using `arm926t`. Is this still correct for your machines? Here is the full list:
```
Target Architecture Variant
* armv4 cores
  1. arm920t (BR2_arm920t)
  2. arm922t (BR2_arm922t)
  3. fa526/626 (BR2_fa526)
  4. strongarm sa110/sa1100 (BR2_strongarm)
* armv5 cores
> 5. arm926t (BR2_arm926t)
  6. iwmmxt (BR2_iwmmxt)
  7. xscale (BR2_xscale)
* armv6 cores
  8. arm1136j-s (BR2_arm1136j_s)
  9. arm1136jf-s (BR2_arm1136jf_s)
  10. arm1176jz-s (BR2_arm1176jz_s)
  11. arm1176jzf-s (BR2_arm1176jzf_s)
  12. mpcore (BR2_arm11mpcore)
* armv7a cores
  13. cortex-A5 (BR2_cortex_a5)
  14. cortex-A7 (BR2_cortex_a7)
  15. cortex-A8 (BR2_cortex_a8)
  16. cortex-A9 (BR2_cortex_a9)
  17. cortex-A12 (BR2_cortex_a12)
  18. cortex-A15 (BR2_cortex_a15)
  19. cortex-A15/A7 big.LITTLE (BR2_cortex_a15_a7)
  20. cortex-A17 (BR2_cortex_a17)
  21. cortex-A17/A7 big.LITTLE (BR2_cortex_a17_a7)
  22. pj4 (BR2_pj4)
* armv7m cores
  23. cortex-M3 (BR2_cortex_m3)
  24. cortex-M4 (BR2_cortex_m4)
  25. cortex-M7 (BR2_cortex_m7) (NEW)
* armv8 cores
  26. cortex-A32 (BR2_cortex_a32) (NEW)
  27. cortex-A35 (BR2_cortex_a35) (NEW)
  28. cortex-A53 (BR2_cortex_a53)
  29. cortex-A57 (BR2_cortex_a57)
  30. cortex-A57/A53 big.LITTLE (BR2_cortex_a57_a53)
  31. cortex-A72 (BR2_cortex_a72)
  32. cortex-A72/A53 big.LITTLE (BR2_cortex_a72_a53)
  33. cortex-A73 (BR2_cortex_a73) (NEW)
  34. cortex-A73/A35 big.LITTLE (BR2_cortex_a73_a35) (NEW)
  35. cortex-A73/A53 big.LITTLE (BR2_cortex_a73_a53) (NEW)
  36. exynos-m1 (BR2_exynos_m1) (NEW)
  37. xgene1 (BR2_xgene1) (NEW)
```
Number 5 is current choice.

**Comment by Sebastian-Roth** [comment]
Here comes the list for 64 bit ARM:
```
Target Architecture Variant
* armv8 cores
  1. cortex-A35 (BR2_cortex_a35)
> 2. cortex-A53 (BR2_cortex_a53)
  3. cortex-A57 (BR2_cortex_a57)
  4. cortex-A57/A53 big.LITTLE (BR2_cortex_a57_a53)
  5. cortex-A72 (BR2_cortex_a72)
  6. cortex-A72/A53 big.LITTLE (BR2_cortex_a72_a53)
  7. cortex-A73 (BR2_cortex_a73)
  8. cortex-A73/A35 big.LITTLE (BR2_cortex_a73_a35)
  9. cortex-A73/A53 big.LITTLE (BR2_cortex_a73_a53)
  10. exynos-m1 (BR2_exynos_m1)
  11. falkor (BR2_falkor)
  12. qdf24xx (BR2_qdf24xx)
  13. thunderx (BR2_thunderx)
  14. thunderxt81 (BR2_thunderxt81)
  15. thunderxt83 (BR2_thunderxt83)
  16. thunderxt88 (BR2_thunderxt88)
  17. thunderxt88p1 (BR2_thunderxt88p1)
  18. xgene1 (BR2_xgene1)
* armv8.1a cores
  19. thunderx2t99 (BR2_thunderx2t99)
  20. thunderx2t99p1 (BR2_thunderx2t99p1)
  21. vulcan (BR2_vulcan)
* armv8.2a cores
  22. cortex-A55 (BR2_cortex_a55) (NEW)
  23. cortex-A75 (BR2_cortex_a75) (NEW)
  24. cortex-A75/A55 big.LITTLE (BR2_cortex_a75_a55) (NEW)
* armv8.3a cores
  25. saphira (BR2_saphira) (NEW)
```
Default selection here is number 2.

**Comment by parkerberb-nfv** [comment]
@Sebastian-Roth I did not touch the 32 bit ARM configs, and I don't have any 32 bit ARM machines, so I can't say if that is right or wrong. I can confirm that the default BR_cortex_a53 works for me. My machines are thunderX based, but if the default works why change it :)

**Comment by parkerberb-nfv** [comment]
I finally got around to pulling and doing a clean install of fog, version 1.5.7. 

It appears that my relevant changes in packages/web/lib/fog/bootmenu.class.php were overwritten - There needs to be some check for when the arch is set to "arm" so that the bootloader can be set correctly.

We also are not packaging any arm-based bootloaders, or the arm kernel / init.

**Comment by Sebastian-Roth** [comment]
@parkerberb-nfv Thanks for your reply!

> It appears that my relevant changes in packages/web/lib/fog/bootmenu.class.php were overwritten - There needs to be some check for when the arch is set to "arm" so that the bootloader can be set correctly.

Sorry but I don't get what you say here. Do you mean that bootmenu.class.php was overwritten when you ran the installer on an upgrade? This is always the case. But going back to what you initially wrote I kind of think that I am on the wrong track. Ahhhhh, looking at the latest commits again I see what you mean: 9beb20d4f - when I prepared to add different bootloaders for 32 bit and 64 bit UEFI I removed the ARM stuff back in December 2018 because I had the feeling this was not used anymore. As there are too many other things going on and this topic spans over a long period of time I didn't remember that.

> We also are not packaging any arm-based bootloaders, or the arm kernel / init.

ARM kernels and inits are available but the installer script doesn't copy them. Whooops.

Ok, let's tackle this again. As there are not many people using ARM clients I am wondering if you are ok with me adding a installer switch (e.g. `./installfog.sh --enable-arm`). I am asking because the ARM binaries add a fair bit of download size for everyone while it's seldomly used. If we add this as a command line switch you can enable it if needed.

As well let me ask about the boot loaders. As far as I know this question has never been answered properly. We never had any ARM-based bootloader binaries in the repo. The ones referenced in the code (8935f5a3 - `grub_aa64.exe` and `refind_aa64.efi`) never existed and I am not sure where Tom intended to grab those from. While `refind_aa64.efi` shouldn't be a problem as it is part of the official binary source package provided I am really wondering if there is something like`grub_aa64.exe` available. The binary `grub.exe` we provide for x86/x64 based machines is from GRUB4DOS. I don't even know where the original binary came from and I have no idea if there is something similar that would run on ARM. Well sure there GRUB for ARM, but GRUB4DOS has a kind of different command line interface and behavior than what we'd expect from using up to date GRUB2 PXE capable binary.

To make a long story short: Do you know which bootloader works for your machines?? Can you test `refind_aa64.efi` ([download](https://netcologne.dl.sourceforge.net/project/refind/0.11.4/refind-bin-0.11.4.zip) and unzip) to see if that's working. If not we need to look into using GRUB2 PXE binaries I reckon. Or what about using iPXE's simple EXIT or SANBOOT. Did you try those exit types yet??

**Comment by parkerberb-nfv** [comment]
> Ahhhhh, looking at the latest commits again I see what you mean: 9beb20d - when I prepared to add different bootloaders for 32 bit and 64 bit UEFI I removed the ARM stuff back in December 2018 because I had the feeling this was not used anymore. As there are too many other things going on and this topic spans over a long period of time I didn't remember that.

Yup, it seems like this is the regression. I can submit a fix.

> Ok, let's tackle this again. As there are not many people using ARM clients I am wondering if you are ok with me adding a installer switch (e.g. ./installfog.sh --enable-arm). I am asking because the ARM binaries add a fair bit of download size for everyone while it's seldomly used. If we add this as a command line switch you can enable it if needed.

That seems like a reasonable solution. We could also go with another [y/N] prompt during the installer, but I have no preference.

> We never had any ARM-based bootloader binaries in the repo. The ones referenced in the code (8935f5a - grub_aa64.exe and refind_aa64.efi) never existed and I am not sure where Tom intended to grab those from

I have been using the refind_aa64.efi from here: https://www.rodsbooks.com/refind/getting.html 
This has worked fine for me. I seem to remember having issues finding an arm build of grub that worked for me.

> The binary grub.exe we provide for x86/x64 based machines is from GRUB4DOS. I don't even know where the original binary came from and I have no idea if there is something similar that would run on ARM. Well sure there GRUB for ARM, but GRUB4DOS has a kind of different command line interface and behavior than what we'd expect from using up to date GRUB2 PXE capable binary.

Perhaps that's why I couldn't get grub to work! This is not a big deal in my mind - If its documented and we have a working refind then whatever. I can investigate what it would take to build grub4dos ourselves.

> To make a long story short: Do you know which bootloader works for your machines?? Can you test refind_aa64.efi (download and unzip) to see if that's working. If not we need to look into using GRUB2 PXE binaries I reckon. Or what about using iPXE's simple EXIT or SANBOOT. Did you try those exit types yet??

Yes, refind_aa64.efi works for me. I don't recall testing simple exit or sanboot - I can try these and report back.


We are also going to have to tackle the problem of user configuration. We will need entries under settings > fog configuration > tftp server and settings > fog configuration > fog boot settings. I can dig around and see what that would take

**Comment by Sebastian-Roth** [comment]
@parkerberb-nfv Thanks! I just merged your pull request. We definitely need a bit more. Adding `refind_aa64.efi` (and maybe even a separate `refind_aa64.conf`??).

**Comment by parkerberb-nfv** [comment]
@Sebastian-Roth Thanks for your feedback, I've submitted another PR.

Could I have some insight into the build system you guys use to make your release tarballs? Or are the tarballs just a literal tar of the tagged git repo and then the kernels, etc get downloaded at install time? I think the last thing we need to tie all this up is some documentation somewhere about how all this happens and what the user needs to do for their arm machines to work.

I also want to make it clear that all my contributions thus far have made no attempt to support 32 bit arm machines. Even the raspberry pi is a 64 bit SOC, so I don't really see the use case for a 32 bit arm machine - they don't exist anywhere in the recent desktop or server markets as far as I know. That said, it shouldn't be too hard for someone who cared to add support if they needed it.

**Comment by Sebastian-Roth** [comment]
@parkerberb-nfv Thanks again! I just merged the PR.

The release tarball is pretty just the tagged git repo as you guessed. Kernels, inits and such are downloaded by the installer.

I just pushed a commit (558a01e) that downloads and copies the kernel and init binaries to the right place.

It's interesting to hear that 32 bit ARM is not much in use at all. You'll see that I left out 32 bit ARM stuff in most of the code I changed and I will remove 32 bit ARM from the kernel and init builds as well.

So you should be able to install/upgrade with `./installfog.sh -A` or `/installfog --arm-support` from now on. Note that on upgrades this option only needs to be added the first time. Later on this setting will be stored in `/opt/fog/.fogsettings` just as all the other values are.

**Comment by Sebastian-Roth** [comment]
@parkerberb-nfv Would you find the time to test this?

**Comment by parkerberb-nfv** [comment]
@Sebastian-Roth Sure. I'll have to reinstall from source - I'll get back to you

**Comment by Sebastian-Roth** [comment]
@parkerberb-nfv Any news on this?

Will remove the ARM 32 bit kernel and init now.

**Comment by Sebastian-Roth** [comment]
@parkerberb-nfv Please let us know if you see any issues with the ARM support as it is in the `dev-branch` right now because we will freeze for a new release in the next weeks.

**Comment by Sebastian-Roth** [comment]
@parkerberb-nfv Took us a little longer than I thought but next release is on the door step and I am closing this issue now as we haven't heard back yet. ARM support should work.
