### ISSUE TITLE
Kernel panic issues

### ISSUE THREAD

**Issue by tsgit18** [FOGProject/fogproject#308]
I cannot get any physical or virtual machines, UEFI or Legacy, past the white Fog pxe menu; any options do not work (quick or full host registration etc, even tried manually registering a host but same issue when trying to capture first image). Kernel panic ('xz-compressed' issue). I have tried many different kernel versions, I tried various kernel arguments, I tried manually extracting the .xz files increasing memory limit and using the non-compressed init files (they manually decompress fine) and I tried many other potential solutions but got nowhere today (I am a Linux sysadmin). Now reverting to 348f695. This was a new install of Fog on a CentOS 7 (minimal) ESXi 6.7 guest, and then just now I replicated the issue again on a CentOS 7 (minimal) VMware Fusion guest too. Are the people that are successfully using this version using Debian/Ubuntu perhaps? I will update this issue with the exact error message in the morning (apologies, I have reverted my snapshot and lost it now but the ESXi vm is back in the office still)

**Comment by Sebastian-Roth** [comment]
@tsgit18 Thanks for reporting. Seems like we messed something up here. Which version did you try to install? 1.5.6 or from the latest `dev-branch`??

**Comment by Sebastian-Roth** [comment]
@tsgit18 Please go to the FOG web UI -> FOG Configuration -> FOG Settings -> FTP Server and increase **KERNEL RAMDISK SIZE** from `127000` to `275000`.

**Comment by tomsage** [comment]
You are a legend my friend. I had increased it bit by bit up to 200000 yesterday but obviously didn't go quite far enough! I have just tested this and it's all working perfectly now. Thank you very much.

**Comment by Sebastian-Roth** [comment]
Will close this now as we have addressed this in the code already.
