### ISSUE TITLE
After upgrading from 1.5.5 to 1.5.6 - Kernel update fails

### ISSUE THREAD

**Issue by m-eddington** [FOGProject/fogproject#311]
After upgrading FOG from 1.5.5 to 1.5.6 Kernel update fails with a permission error.
`    Type: 2, File: /var/www/html/fog/lib/fog/fogftp.class.php, Line: 708, Message: ftp_put(): Could not create file., Host: , Username: fog`

According to the changelog:

> Rename fog system account to fogproject and add warning to not use this as your username.

It seems as if this change is not compensated for in all the places within FOG yet. After changing **TFTP FTP USERNAME** to fogproject in FOG System Settings and 
`chown -R fogproject:www-data /var/www/html/fog/service/ipxe/`
fixed the error and kernels are able to be downloaded correctly.

I've encountered the same error on two different FOG servers (Ubuntu 16.04 and Debian 9) both upgraded from 1.5.5 to 1.5.6.

**Comment by Sebastian-Roth** [comment]
@m-eddington Thanks for reporting this. Seems like I have definitely missed something here. Will look into it!

**Comment by Sebastian-Roth** [comment]
> It seems as if this change is not compensated for in all the places within FOG yet. After changing **TFTP FTP USERNAME** to fogproject in FOG System Settings ...

Yeah, definitely looks like I forgot to update this in the schema, my fault! I'll push out a fix soon.

> and `chown -R fogproject:www-data /var/www/html/fog/service/ipxe/` fixed the error and kernels are able to be downloaded correctly.

That's kind of strange as we do the `chown` in the code [ref](https://github.com/FOGProject/fogproject/blob/master/lib/common/functions.sh#L446). Not sure under which circumstances this might not have happened. Can you post/upload the install logs so we can have a look and maybe figure this out?!

**Comment by m-eddington** [comment]
These are the logs from the Ubuntu 16.04 server:
[foginstall.log](https://github.com/FOGProject/fogproject/files/3225783/foginstall.log)
[fog_error_1.5.6.log](https://github.com/FOGProject/fogproject/files/3225785/fog_error_1.5.6.log)

And the Debian 9 server:
[foginstall-2.log](https://github.com/FOGProject/fogproject/files/3225796/foginstall-2.log)
[fog_error_1.5.6-2.log](https://github.com/FOGProject/fogproject/files/3225797/fog_error_1.5.6-2.log)

**Comment by Sebastian-Roth** [comment]
@m-eddington I pushed out a fix yesterday that should address the database settings that I missed in 1.5.6 - 5fc3f548f

We plan to bring out an early new 1.5.7 to fix that problem before too many people run into it.

When doing test installes with all that I never ran into the situation where `/var/www/html/fog/service/ipxe/` wasn't properly owned by `fogproject:www-data` (or `fogproject:apache` for CentOS, tested both).
Thanks for the log files! I had a look through those and couldn't find a hint on why this might have gone wrong. Do you remember how the ownerships were set before you did `chown -R fogproject:www-data /var/www/html/fog/service/ipxe/`?

**Comment by m-eddington** [comment]
Might be me who recalled the steps in the wrong order. It was a last minute fix on a Friday afternoon before heading home. I also did a test install in a VM and didn't have to chown the folder either. So I think it's safe to say the chown step is not needed or was something very specific to our deployment. Especially if no one else has reported it.

**Comment by Sebastian-Roth** [comment]
@m-eddington Thanks heaps for testing and confirming! Closing this now as a fix is pushed to `dev-branch` and we will release soon.
