### ISSUE TITLE
[File not used] /utils/FOGUpdater/jq64

### ISSUE THREAD

**Issue by Nundir** [FOGProject/fogproject#317]
This file is not used in FOG then you can delete it

**Comment by mastacontrola** [comment]
The reason it's hear so in the future we may be able to use json parsing. While you're correct that it isn't in use, there's also the element of adding things so we can use them in the future.

**Comment by Nundir** [comment]
You already use jq32 for json parsing, and this file is here since 2 years and added to fog for nothing since 2 years, you can re-add it later if you really need the 64 and not 32 but I'm not sure it will happen

3MB is not that big, i know, but it's more than needed

**Comment by Sebastian-Roth** [comment]
@Nundir Just pushed a commit to remove jq64. You are right, we can always re-add this if needed.
