### ISSUE TITLE
Multicast doesn't work after upgrade from 1.4.4 to 1.5.6

### ISSUE THREAD

**Issue by Marquise4242** [FOGProject/fogproject#318]
After the upgrade from 1.4.4 to 1.5.6, the delpoy of images works fine, but when using multicast, the client freezes at the Partclone screen.
It says: 
Partclone v0.2.89 http://partclone.org
Starting tom restore image (-) to device (/dev/sda1)
note: Storage Location <ip-address>:/images/, Image name <correct image name>
UDP Sender looks good.

On client Debug mode is not listed and in 1.5.6 i don't know how to enable it.

Please Help

**Comment by Marquise4242** [comment]
Found out how to debug, udp-sender on server and udp-receive on client started, multicast itself works. Maybe Partclone issue?

**Comment by Sebastian-Roth** [comment]
@Marquise4242 Hey, sorry for the long delay. Have been away and still trying to catch up.

Is this still an issue for you. Please take a look at the log file in `/var/log/fog/multicast.log`. Post the full log file here.

**Comment by Sebastian-Roth** [comment]
@Marquise4242 Please add more information here. We can't help you without log files and will close this issue if we don't hear back from you in the next two weeks or so.
