### ISSUE TITLE
Fog on Debian Buster (10)

### ISSUE THREAD

**Issue by supahjan** [FOGProject/fogproject#320]
Tried to install fog1.5.6 on Debian Buster (10) but encounter errors on php, libcurl and mysql. 

Any plans on supporting Debian 10? 

Thank you.

**Comment by Sebastian-Roth** [comment]
@supahjan Sure we will but have not had the time to do so yet.

**Comment by Sebastian-Roth** [comment]
fddac4487 should fix the issue. Please give it a try using `dev-branch` to install.

**Comment by Sebastian-Roth** [comment]
@supahjan If I don't hear back from you in the next days I will just close this as fixed. :-)
