### ISSUE TITLE
Storage Issues Centos 7

### ISSUE THREAD

**Issue by rdmrm4g00** [FOGProject/fogproject#322]
Hi.

No matter what I do when adding storage to FOG it never recognises the full amount available.

IE the disk space remaining is 30GB but if you click on the disk info - remaining is 470GB

I can only use 30GB - I even added another server with storage node with 500gb - this again only sees 50GB - click on the disk - 450GB available on the front screen - 50gb remaining.

What am I doing wrong?

**Comment by Sebastian-Roth** [comment]
@rdmrm4g00 Obviously you figured it out on your own. Do you mind sharing your findings so other users might find this helpful as well?

**Comment by rdmrm4g00** [comment]
HI.

Basically it was a quirk of centos.

I re did the volumes when setting up ..selected manual instead of auto
provision and just gave root volume max size.

I found following the guide and creating images as a mount point didnt work
for me, it was only when increasing root as the script is using root as a
location...that worked.

Thanks anyways

Thanks,

Ross
