### ISSUE TITLE
d1p1.ebr error while deploying image with fog 1.5.7

### ISSUE THREAD

**Issue by adul3** [FOGProject/fogproject#323]
Hi.
Thanks for this great job, and this usefull tool.
I've installed a fresh Debian Strecth server with the release 1.5.7 of FOG yesterday (2019-07-15).
The host capturing works fine. My machines are installed with Win10 1809, two partitions on the disk (windows installation default setting).
When I tried to deploy the image, in unicast or multicast, the first partition has passed but the second has thrown an error saying that the file "d1p1.ebr" was not found, and the host will reboot within 1 minute.
After reboot, the host retried the task, because it was still "in progress" on the server.
I've installed the 1.5.6 version and the same hosts are deploying without any problem.
Some kind of bug in the 1.5.7 ?
Thanks
Best regards

**Comment by Quazz** [comment]
I believe this bug has since been fixed, if you update to 1.5.7 again it should work.

**Comment by Sebastian-Roth** [comment]
@adul3 The issue itself is fixed just as @Quazz correctly said. But to get the new files you need to removed the cached stuff manually for now.

So to fix the issue, run `rm fogproject/tmp/binaries1.5.7.*` and then re-run the installer.
