### ISSUE TITLE
Debian Stretch: PHP5 is not available

### ISSUE THREAD

**Issue by lukebarone** [FOGProject/fogproject#324]
Debian Stretch only has PHP7.x available. The FOG installer is still trying to install PHP5. Is there a plan to allow Stretch to use PHP7 with the FOG installer?

**Comment by Sebastian-Roth** [comment]
@lukebarone This is probably an upgrade, not a fresh install, right??

Please modify `/opt/fog/.fogsettings` manually and change values starting with `php` in there.

**Comment by lukebarone** [comment]
Thank you for your help. It's all good now :)
