### ISSUE TITLE
API: Uncaught Exception: No viable macs to use

### ISSUE THREAD

**Issue by iMikeG6** [FOGProject/fogproject#329]
Hello,

I'm trying to use the API to modify the address macs for my host and I'm always getting this error:

`Uncaught Exception: No viable macs to use in /var/www/html/fog/lib/fog/host.class.php`

Here's: the curl line I'm using:

`curl -g -H 'Content-type: application/json' -H 'fog-api-token:myPrivateAPItoken' -H 'fog-user-token:myPrivateToken' -X PUT http://myserver.local/fog/host/7/edit -d '{ "name":"hostnametest","description":"test","macs":["00:bb:cc:dd:ee:f3"] }'`

The host exist in FOG and its has those values:

Primary mac: 00:bb:cc:dd:ee:ff
No additional mac
name: hostnametest
Tested version: 1.5.7 and 1.6

Here's the raw json ouptut:

`{ "id": "7", "name": "hostnametest", "description": "test", "ip": "", "imageID": "0", "building": "0", "createdTime": "2019-08-17 10:47:33", "deployed": "0000-00-00 00:00:00", "createdBy": "fog", "useAD": "0", "ADDomain": "", "ADOU": "", "ADUser": "", "ADPass": "", "ADPassLegacy": "", "productKey": "", "printerLevel": "", "kernelArgs": "", "kernel": "", "kernelDevice": "", "init": "", "pending": "", "pub_key": "", "sec_tok": "", "sec_time": "0000-00-00 00:00:00", "pingstatus": "", "biosexit": "", "efiexit": "", "enforce": "1", "primac": "00:bb:cc:dd:ee:ff", "imagename": null, "hostscreen": { "id": null, "hostID": null, "width": null, "height": null, "refresh": null, "orientation": null, "other1": null, "other2": null }, "hostalo": { "id": null, "hostID": null, "time": null }, "inventory": { "id": null, "hostID": null, "primaryUser": null, "other1": null, "other2": null, "createdTime": null, "deleteDate": null, "sysman": null, "sysproduct": null, "sysversion": null, "sysserial": null, "sysuuid": null, "systype": null, "biosversion": null, "biosvendor": null, "biosdate": null, "mbman": null, "mbproductname": null, "mbversion": null, "mbserial": null, "mbasset": null, "cpuman": null, "cpuversion": null, "cpucurrent": null, "cpumax": null, "mem": null, "hdmodel": null, "hdserial": null, "hdfirmware": null, "caseman": null, "casever": null, "caseserial": null, "caseasset": null, "memory": "0.00 iB" }, "image": { "imageTypeID": null, "imagePartitionTypeID": null, "id": null, "name": null, "description": null, "path": null, "createdTime": null, "createdBy": null, "building": null, "size": null, "osID": null, "deployed": null, "format": null, "magnet": null, "protected": null, "compress": null, "isEnabled": null, "toReplicate": null, "srvsize": null, "os": { "pluginsTabData": [] }, "imagepartitiontype": { "pluginsTabData": [] }, "imagetype": { "pluginsTabData": [] } }, "macs": [ "00:bb:cc:dd:ee:ff" ]`

I also tried the working-1.6 branch, but still the same error.

Server: Ubuntu 18.04.3 LTS
PHP 7.2.21
apache2

Does anyone of you have an idea ?

Thanks in advance for your help.

**Comment by iMikeG6** [comment]
I figured out that the problem came from the FOGManagerController class, function Destroy in the working-1.6-branch.

I finally ended up using the dev-branch but I had to modify the route.class.php and replace the edit function part to: 

```
$macsToAdd = array_diff(
    (array)$vars->macs,
    $class->getMyMacs()
);
$primac = array_shift($macsToAdd);
$macsToRem = array_diff(
    $class->getMyMacs(),
    (array)$vars->macs
);
$class
    ->removeAddMAC($macsToRem)
    ->addPriMAC($primac)
    ->addAddMAC($macsToAdd);
```
instead of:
```
$macsToAdd = array_diff(
    (array)$vars->macs,
    $class->get('macs')
);
$primac = array_shift($macsToAdd);
$macsToRem = array_diff(
    $class->get('macs'),
    $vars->macs
);
$class
    ->removeAddMAC($macsToRem)
    ->addPriMAC($primac)
    ->addAddMAC($macsToAdd);
```

Now the mac address is properly delete from the database and replaced with the new one.

Hope it's help.

**Comment by Sebastian-Roth** [comment]
@iMikeG6 Thanks heaps for looking into this and finding a solution to your issue and post here! I wasn't able to get into that myself that quick. I tested your fix and will push it to `dev-branch` in a second.
