### ISSUE TITLE
problème with new host and active directory

### ISSUE THREAD

**Issue by sfonteneau** [FOGProject/fogproject#33]
Hello

I found problème with active directory and new host (no with edit host)

When I add a new pc, I do not have a choice of "OR". And the field is replaced by "$ {ad_ou}". (see picture). Thus, the auto complete does not.

![capture du 2015-03-26 10 47 59](https://cloud.githubusercontent.com/assets/5419492/6843847/d279899c-d3a6-11e4-9d19-c8dc110bdb2a.png)

I don't have this problem with the groups, the auto complete feature works.

Sorry for my bad english (i'm french)

Simon

**Comment by mastacontrola** [comment]
My guess is this is version 1.2.0?  This should only happen with this version that I'm aware of.  If it's happening on the current development versions, I'm not seeing the issue and am not able to replicate it.

Please try the development version and see if this helps out.

**Comment by sfonteneau** [comment]
The problem is still present in the version " 1.2.0 " . But it only appears with "Create New Host" . cf pictures
![capture du 2015-07-08 15 05 11](https://cloud.githubusercontent.com/assets/5419492/8570846/82229ed2-2583-11e5-9a80-ebda572f88c5.png)
