### ISSUE TITLE
Missing submenu on Client Settings/Service Configuration page

### ISSUE THREAD

**Issue by Sebastian-Roth** [FOGProject/fogproject#330]
When opening the Client Settings/Service Configuration page of the web UI we get no sub menu on the left side plus an ugly message in the error logs:

```
AH01071: Got error 'PHP message: PHP Warning:  get_class() expects parameter 1 to be object, null given in /var/www/fog/lib/fog/page.class.php on line 568
```

When looking at the `$class` variable it looks like it's properly initialized with a `ServiceConfigurationPage Object` but `$class->obj` **is not set** (should be `Service Object` I suppose??)

**Comment by Sebastian-Roth** [comment]
@mastacontrola Can you confirm there is not meant to be a side menu on the left in the "Client Settings" page? http://fog.server/fog/management/index.php?node=service

**Comment by mastacontrola** [comment]
There is not meant to be a side menu for client page, within 1.5.X. Or 1.6

**Comment by Sebastian-Roth** [comment]
Ok, so it's just an ugly warning in the apache error log. Who ever finds it first can fix it. :-)

**Comment by mastacontrola** [comment]
This issue should now be fixed. Ultimately the object isn't really needed, but forcibly setting it, even if it's not an accurate item, should be enough. This will allow people to generate their own side menu's within the client settings element.
