### ISSUE TITLE
problem instaling ubuntu 18.04 lts

### ISSUE THREAD

**Issue by leonwolv** [FOGProject/fogproject#331]
the installer don't work in Ubuntu 18.04 lts.

**Comment by Sebastian-Roth** [comment]
@leonwolv said:
> the installer don't work in Ubuntu 18.04 lts.

That's not true! We do automated installer tests and Ubuntu 18.04 works perfectly fine: http://fogtesting.theworkmans.us/

There must be something specific in your environment or how you set things up.

Please post the error log (found in `fogproject/bin/error_logs/` directory) here and we should be able to help you.

**Comment by Sebastian-Roth** [comment]
As there was no response yet I am closing this.
