### ISSUE TITLE
Install working on CentOS/RHEL 8

### ISSUE THREAD

**Issue by JarrahG** [FOGProject/fogproject#335]
I've just completed an install on CentOS 8 which is now working correctly. The install required a number of changes to the script, but once these were made, the install and FOG itself seemed to work fine. 

The following changes were required.
Replace the following packages:
* mysql -> mariadb (provides version 10, which works with FOG, unlike mysql 8)
* dhcp -> dhcp-server (name change in the repository)

Remove the requirement for the following repositories:
* remi (including remi-php72 and all others)
* epel

I'm happy to try to clean up the edits and submit them as a pull request if requested. Currently they are not in a releasable state as they are not backwards compatible with CentOS/RHEL 7. 

Thanks.

**Comment by mastacontrola** [comment]
mysql -> mariadb will automatically happen if that's the package that exists.

I already updated the working-1.6 and dev-branch to account for the dhcp-server element.

Based on your suggestion, I've moved the remi and epel repo enabling only for RH/Centos < 8.

Thank you,
