### ISSUE TITLE
Mac address as unique ID ? (thunderbolt adapter issue)

### ISSUE THREAD

**Issue by Yrbua** [FOGProject/fogproject#336]
Hello,

I am currently working on the capture and deployment via fog, especially for macbooks.

My problem is this: macbooks have no ethernet port, I have to use a thunderbolt / ethernet adapter that has a specific mac address.

When I register a host using this adapter, it is created using the mac address as the unique identifier.
And of course, when I'm using this same adapter for another host, fog thinks I've already registered it.

My question is: Can I use another unique identifier than the mac address, or is there a way around this problem?
Or is the only solution to have as many adapters as macbook? (I hope not :) )

Thanks for the help,

**Comment by junkhacker** [comment]
we are aware of the difficulties it creates using the mac address as the unique identifier for clients, however we have not found a good alternative considering the restraints of what information is reliably available in a PXE environment. 

a common method of managing systems (with the fog client) without onboard Ethernet is to register the wifi mac as the host, and registering removable adapters as their own host. you can then create a task to re-image "adapter1" and plug it in to the target system, and remove it when it's finished imaging.

**Comment by Yrbua** [comment]
Thanks for your answer.
I have tried many times to install fog client on macOS Mojave but unfortunately it doesn't work (pinning failed) ...

**Comment by Sebastian-Roth** [comment]
@Yrbua We are aware of both those topics and the later one (fog-client on MacOS) will hopefully be solved in the next release - thanks to @danielbmiller who put in great effort to fix this issue. Find a discussion on this topic in the forum: https://forums.fogproject.org/topic/8803/trouble-installing-smartclient-on-macos-sierra

About the initial question I might reference this to our main topic on unique identifiers #198 and close this one for now.
