### ISSUE TITLE
Prevent from sending the AD password over the wire all the time

### ISSUE THREAD

**Issue by Sebastian-Roth** [FOGProject/fogproject#337]
Half a dozen times we had people asking about ways to prevent from the AD password being stolen from less privileged stuff using the FOG web UI only to do imaging. There is a workaround to that by hiding the password field (https://forums.fogproject.org/post/129269) but it's common practice to simply not set the password field on page load or set as `*********` instead of the actual password.

**Comment by mastacontrola** [comment]
https://github.com/FOGProject/fogproject/commit/7399efb6f4740abc12cf8c13e74ef185ff929b13

This should show the basic idea of how we can mask and protect things overall. No javascript code really needed yay!

How hard would this be to port to 1.5.7.4X series?

Also, I don't know if we should consider this a "bug" as things were working as intended.

**Comment by gplamondon** [comment]
would it be easier to just remove the unmask option?

**Comment by mastacontrola** [comment]
Sure, except that the value can easily be "re-viewed" by simply changing the type to text vs. password.

The changes I've made actually make it much more secure.

**Comment by Sebastian-Roth** [comment]
@mastacontrola Thanks for your great input on this. Just pushed similar changes for `dev-branch`.

Closing this now as auto-close through keyword didn't work.
