### ISSUE TITLE
Storage Node offline

### ISSUE THREAD

**Issue by divyesh-lx** [FOGProject/fogproject#338]
I have noticed that storage node seems to offline on my fog server. I also upgraded fog to newer version.

**Comment by Sebastian-Roth** [comment]
@divyeshgit Can you please give us some more details? Where do you see the storage node being offline? Is it in the FOG Configuration site in the web UI? Which version of FOG do you currently have (right bottom corner on the web UI)? Have you upgraded both the master and the storage node?

**Comment by divyeshgit** [comment]
![ped-](https://user-images.githubusercontent.com/57684899/68787452-6b638780-05f6-11ea-98c5-6894a67dc51c.PNG)
 I have attached some photos. I am using 1.5.6 version.
I'm unable to upgrade storage node and fog version as well.
It's giving me error.

![image](https://user-images.githubusercontent.com/57684899/68787720-ea58c000-05f6-11ea-8e30-f5fe4e60d915.png)

**Comment by divyeshgit** [comment]
I have manged to fix that issue now. I had to remove all php package on server which were not there before cause it's no longer availabe and php7.0 was already there.
As you can see in below image, storage mode now back online.

Thanks
![image](https://user-images.githubusercontent.com/57684899/68800181-71656280-060e-11ea-8be7-a5d31eae6582.png)

**Comment by Sebastian-Roth** [comment]
@divyesh-lx Great to hear you managed to fix this!

Make sure you always keep master node and storage node on the same version!

**Comment by divyesh-lx** [comment]
Just curiosity how can we verify?

**Comment by Sebastian-Roth** [comment]
@divyesh-lx Good point. Try this: `grep FOG_VERSION /var/www/html/fog/lib/fog/system.class.php`

**Comment by divyesh-lx** [comment]
It says I need to define FOG version even I already did that one.
 define('FOG_VERSION', '1.5.7');
        define('FOG_SCHEMA', 267);
        define('FOG_BCACHE_VER', 133);
        define('FOG_SVN_REVISION', 6080);
        define('FOG_CLIENT_VERSION', '0.11.16');
