### ISSUE TITLE
Changing TFTP & WEB Interface IP somehow aren't reflected on the config 

### ISSUE THREAD

**Issue by Nono-m0le** [FOGProject/fogproject#339]
I'm running fog v1.5.7 on a Virtualbox VM and I had to change the network interface type (and IP settings).

After changing the IP for the VM itself (successfully) I tried to change the IP  via the fog web interface on the Fog Settings page.
Somehow, it didn't change the "real" config as I was still able to see the previous IP set on different location, like for the DHCP settings (dhcp server/range in `/etc/dhcp/dhcpd.conf`) and fog config as well `/var/www/fog/lib/fog/config.class.php`

**Comment by Nono-m0le** [comment]
but changing the /opt/fog/.fogsetting and run again the installation works so ... I guess it's "okish" :) Sorry for the noise.

**Comment by Nono-m0le** [comment]
ACtually, it doesn't change the STORAGE ip (which is still set to the old IP, even after runing the installation with the new/good .fogsettings file.

**Comment by Quazz** [comment]
https://wiki.fogproject.org/wiki/index.php/Change_FOG_Server_IP_Address

Those instructions are still accurate I believe; it mentions having to update in several locations.

**Comment by Nono-m0le** [comment]
indeed, miss the part after .fogsettings somehow.
Thanks

**Comment by N3X15** [comment]
Just an FYI, that document now redirects the user to a page that returns a garbled 404 message.

**Comment by Sebastian-Roth** [comment]
@N3X15 Thanks for letting us know!

@darksidemilk Can we make it so this particular URL (https://docs.fogproject.org/en/latest/reference/change_fog_server_ip_address.html) is still valid in the new docs version? Sure I can change this pointer in the wiki no problem but I guess we have posted the docs URL in the forums a fair bit already. Though if it doesn't fit our new structure nicely we don't make a big fuzz but simply change the link in the old wiki.

**Comment by darksidemilk** [comment]
I haven't got the redirect to work as expected just yet, will come back to this
