### ISSUE TITLE
Issue installing Fogproject on Debian 10 Buster Failed

### ISSUE THREAD

**Issue by ratomms** [FOGProject/fogproject#340]
Hello,

I tried to install fog version 1.5.7 on debian 10 buster but I got an issue below :

<pre>*** New option &apos;hostname&apos; since FOG 1.5.6 ***

  Would you like to change the default hostname &gt;MDGCLNZ02&lt;?
  The fully qualified hostname is used for the webserver certificate.
  If you are not sure, select No. [y/N] n

   ######################################################################
   #     FOG now has everything it needs for this setup, but please     #
   #   understand that this script will overwrite any setting you may   #
   #   have setup for services like DHCP, apache, pxe, tftp, and NFS.   #
   ######################################################################
   # It is not recommended that you install this on a production system #
   #        as this script modifies many of your system settings.       #
   ######################################################################
   #             This script should be run by the root user.            #
   #      It will prepend the running with sudo if root is not set      #
   ######################################################################
   #            Please see our wiki for more information at:            #
   ######################################################################
   #             https://wiki.fogproject.org/wiki/index.php             #
   ######################################################################

 * Here are the settings FOG will use:
 * Base Linux: Debian
 * Detected Linux Distribution: Debian GNU/Linux
 * Interface: enp2s0
 * Server IP Address: 10.216.13.66
 * Server Subnet Mask: 255.255.255.192
 * Server Hostname: MDGCLNZ02
 * Installation Type: Normal Server
 * Internationalization: 0
 * Image Storage Location: /images
 * Using FOG DHCP: Yes
 * DHCP router Address: 

 * Are you sure you wish to continue (Y/N) 

<pre> * Checking package: isc-dhcp-server...........................OK
 * Checking package: isolinux..................................OK
 * Checking package: lftp......................................OK
 * Checking package: libapache2-mod-php7.3.....................OK
 * Checking package: libc6.....................................OK
 * Checking package: libcurl4..................................OK
 * Checking package: liblzma-dev...............................OK
 * Checking package: m4........................................OK
 * Checking package: mariadb-client............................OK
 * Checking package: mariadb-server............................OK
 * Checking package: net-tools.................................OK
 * Checking package: nfs-kernel-server.........................OK
 * Checking package: openssh-server............................OK
 * Checking package: php7.3....................................OK
 * Checking package: php7.3-bcmath.............................OK
 * Checking package: php7.3-cli................................OK
 * Checking package: php7.3-curl...............................OK
 * Checking package: php7.3-fpm................................OK
 * Checking package: php7.3-gd.................................OK
 * Checking package: php7.3-json...............................OK
 * Checking package: php7.3-mbstring...........................OK
 * Checking package: php7.3-mysql..............................OK
 * Checking package: php-gettext...............................OK
 * Checking package: sysv-rc-conf..............................OK
 * Checking package: tar.......................................OK
 * Checking package: tftpd-hpa.................................OK
 * Checking package: tftp-hpa..................................OK
 * Checking package: unzip.....................................OK
 * Checking package: vsftpd....................................OK
 * Checking package: wget......................................OK
 * Checking package: xinetd....................................OK
 * Checking package: zlib1g....................................OK

 * Configuring services

 * Setting up fogproject user..................................Failed!
</pre>

</pre>

Thank for your help

**Comment by Sebastian-Roth** [comment]
@ratomms Take a look at the install error log file in `fogproject/bin/error_logs/fog_error_1.5.7.log` and post the last 20 lines of that here.

**Comment by Sebastian-Roth** [comment]
@ratomms Did you get this fixed or do you still need help? I'll close this in the next days if I don't hear back from you.

**Comment by ratomms** [comment]
@Sebastian-Roth I fixed it. I don't know why, 'useadd' commad didn't find in local path, that's why setting up fogproject user failed. We have to set it in PATH env manual.

**Comment by Sebastian-Roth** [comment]
@ratomms Did you run the installer as `sudo ./installfog.sh`?? Most probably causing the issue...

We always recommend to use a proper root shell with env set.. Either use `sudo -i` or `sudo su -`.
