### ISSUE TITLE
FOG install broken on CentOS 8

### ISSUE THREAD

**Issue by parkerberb-nfv** [FOGProject/fogproject#341]
Hi,

I am trying to do a fresh install of latest stable fog on a new centos 8 machine, and I ran into a few issues.

First, I had to manually install php-json because the `/var/www/html/fog/lib/db/pdodb.class.php` file uses `json_encode`, which was undefined until I installed that library. That's an easy fix, though.

More seriously, the mysql version on centos 8 breaks the install script. According to the docs: https://dev.mysql.com/doc/refman/5.7/en/mysql-nutshell.html#mysql-nutshell-deprecations
using an IDENTIFIED BY clause in a GRANT is not longer allowed.

When I ran the install script, I was asked to go to http://my-server/fog/management/index.php . Running the database install script from there and I got an error on this line of SQL: `GRANT ALL ON fog.* TO 'fogstorage'@'%' IDENTIFIED BY 'fs39765979989'` because that is no longer valid SQL.

Current version of mysql on centos8 is 8.0.17

**Comment by ghooper90** [comment]
FOG 1.5.7 and below do not support installing on Centos 8. The upcoming 1.5.8 release will fully support Centos 8. If you installed via the git method you can switch to the dev branch to install 1.5.7.49 or later that does support Centos 8. To switch to the dev branch change into the root of the fogproject directory (typ this is /root/fogproject) and issue the following command. 
git checkout dev-branch

then issue a 
git pull

Then change to the ./bin directory and reinstall fog by running the installfog.sh script. It should install correctly after that.

**Comment by Sebastian-Roth** [comment]
As mentioned we got this sorted in `dev-branch`. More information on this topic in the forums:
https://forums.fogproject.org/topic/13887/blank-install-page
https://forums.fogproject.org/topic/13869/fog-1-5-7-on-centos-8-0
