### ISSUE TITLE
small Bug on the installer with 2 network cards

### ISSUE THREAD

**Issue by Nono-m0le** [FOGProject/fogproject#342]
Hi there, 

I've just installed a fresh 1.5.7 on a Ubuntu 18.04 LTS
During install, got this small issue (because I've 2 network card): 

```
  What type of installation would you like to do? [N/s (Normal/Storage)] N

  We found the following interfaces on your system:
      * enp0s8 - 10.0.X.X/24
      * enp0s3 - 10.0.Y.Y/24

  Would you like to change the default network interface from enp0s8 enp0s3?
  If you are not sure, select No. [y/N] N

   * The network interface named enp0s8 enp0s3 does not exist.

  We found the following interfaces on your system:
      * enp0s8 - 10.0.X.X/24
      * enp0s3 - 10.0.Y.Y/24

  Would you like to change the default network interface from enp0s8 enp0s3?
  If you are not sure, select No. [y/N] y
  What network interface would you like to use? enp0s3

  Would you like to setup a router address for the DHCP server? [Y/n]
```

I guess the default network interface should be either one or the other, but not both, right ?

**Comment by George1422** [comment]
We seen this just recently with debian 10.2 in this thread. The OP wiped the machine before we were able to debug the problem.
https://forums.fogproject.org/topic/13959/another-chainload-error-fog-1-5-7-on-debian-10-2/3

In your case if you issue an
ip addr show 

You can get the name of your imaging network interface and then key it in during the installer and it will mask the issue.

**Comment by Quazz** [comment]
I can't remember, but I think this may have been fixed on dev-branch already.

**Comment by Sebastian-Roth** [comment]
@Nono-m0le I think Quazz is right, this should be fixed in `dev-branch`. See here: https://github.com/FOGProject/fogproject/commit/ca3c2faa312e0bed50f622a3c5cb81de0c2a7d9d

**Comment by Sebastian-Roth** [comment]
Closing this as we haven't heard back.
