### ISSUE TITLE
Allow spaces in hostname

### ISSUE THREAD

**Issue by s3m1s0n1c** [FOGProject/fogproject#343]
Is there a way to allow spaces in host names or does this cause issues?

I want to replace the same names we have in another system for each host to save confusion.

Is it in this function?

  public function isHostnameSafe($hostname = '')
    {
        if (empty($hostname)) {
            $hostname = $this->get('name');
        }
        $pattern = '/^[\w!@#$%^()\\-\'{}\\.~]{1,50}$/';
        return (bool)preg_match($pattern, $hostname);
    }
My regex knowledge is pretty basic

Thanks

**Comment by Sebastian-Roth** [comment]
@s3m1s0n1c May I ask why you would want to use spaces in hostnames? The [specs](https://tools.ietf.org/html/rfc952) are pretty clear about you shouldn't be using blank or space characters as part of a hostname!

While I don't advice you to add spaces I might still give you the hints on how to do it. First start off by learning more about regex by visiting some of the great online regex checker websites: https://regexr.com/ or https://regex101.com/
Put in the regex above and try things out to figure out how it works. Hint: what you are trying to achieve is simple, you only need to add the space character to the regex. 

Be aware that if you use the fog-client on your hosts and hostname changer is enabled for those it will try to rename the hosts and will probably fail or cause trouble.
