### ISSUE TITLE
[FOG 1.6] Autocomplete image path name doesn't work

### ISSUE THREAD

**Issue by Sebastian-Roth** [FOGProject/fogproject#344]
When working on other things in `working-1.6` I noticed that auto-fillling the image path field didn't work. Entering characters in the name field it also started to fill in the image path but stopped fairly soon after the first or second character.

Tested in Firefox 68.2.0esr on Debian Linux. Needs further testing.

**Comment by mastacontrola** [comment]
I’m aware of the issue but not fully sure how best to address it.

**Comment by mastacontrola** [comment]
Finally had a little time to test this and it does indeed seem to be much better.

Thank you,
