### ISSUE TITLE
[FOG 1.6] Database errors

### ISSUE THREAD

**Issue by gplamondon** [FOGProject/fogproject#346]
I am getting database errors when using certain functions on the web interface.
I upgraded from 1.5.7
![alt text](https://i.gyazo.com/f47a8d40b62ee3bd716cb7772a1becf9.png)
![alt text](https://i.gyazo.com/cb1061f10a0fb14c72d7d1232b570424.png)

Sorry, couldn't select the text to paste.

**Comment by mastacontrola** [comment]
Can you do a MySQL lookup for `select * from groups limit 1`

**Comment by mastacontrola** [comment]
Should be fixed in latest as per the commit you see attached.
