### ISSUE TITLE
[FOG 1.6] snapin install order.

### ISSUE THREAD

**Issue by gplamondon** [FOGProject/fogproject#347]
snapins are installing in snapin ID order instead of the name of the snapin. 
with previous versions of fog you could control the order snapins were installed based on the snapin title in fog.  Example:
1 - Adobe Reader
2 - Google Chrome

we have some snapins that must be installed in certain order.

**Comment by mastacontrola** [comment]
I’ll try to look this over during the weekend. I am pretty sure it still sorts on name but will need to confirm.

**Comment by mastacontrola** [comment]
Found and about to push fix for this. Thanks for reporting.
