### ISSUE TITLE
[FOG 1.6] all snapins queued up for all hosts 

### ISSUE THREAD

**Issue by gplamondon** [FOGProject/fogproject#348]
I really don't know where to begin with this one but it happened twice now after doing a git pull.
After running the install I have a ton (7,860) of items queued up in tasks.

![image](https://user-images.githubusercontent.com/8431458/70440514-5f85ac80-1a60-11ea-8e72-4762d79a037d.png)

It took me quite some time to cancel all those tasks in the GUI :)

**Comment by gplamondon** [comment]
I found that it doesn't actually happen until queue  a PC for imaging.

**Comment by Sebastian-Roth** [comment]
@gplamondon Are the tasks surely all snapin tasks? Are those snapins assigned to the host you queue? Do the tasks all have the same name and same timestamp?

**Comment by gplamondon** [comment]
whatever snapins I have assigned to the PC I am imaging get scheduled to all registered hosts with the exact same time stamp.
![image](https://i.gyazo.com/5c723aff425647db27d5237d87e17f9c.png)

**Comment by Sebastian-Roth** [comment]
@gplamondon Timestamp matches the exact time you scheduled the imaging? Just trying to gather all the information for us to be able to replicate and find what's causing this.

**Comment by gplamondon** [comment]
yes, I can reproduce it by selecting advanced task deploy all snapins.
here is a [video](https://drive.google.com/file/d/1KcN6zt_U_eAMyNV2rn7D_s68cYFsE3bb/view?usp=sharing)

**Comment by mastacontrola** [comment]
I'm thinking this is just an SQL seeing all the associated snapins and hosts.

Can you verify the other hosts aren't suddenly trying to install all their snapins?

**Comment by mastacontrola** [comment]
Can you do a pull and see if things are presenting properly now?

**Comment by gplamondon** [comment]
Looks better. but still duplicates.

[video](https://drive.google.com/file/d/1xbTCNQYC3Weq7JADk5ex0B81kMWsA4fb/view?usp=sharing)

**Comment by mastacontrola** [comment]
How many snapins are associated to the host in question?

**Comment by gplamondon** [comment]
for testing right now just 1

**Comment by mastacontrola** [comment]
Hopefully now?

**Comment by gplamondon** [comment]
That worked!

**Comment by gplamondon** [comment]
I think the fix introduced a new bug.  The snapins don't queue up for imaging a host but the deploy all snapins works manually.

**Comment by mastacontrola** [comment]
The fix only impacts the task page. It’s probably a coding issue on the host deploy segment

**Comment by gplamondon** [comment]
Thanks Tom!

**Comment by mastacontrola** [comment]
I've added some better checking for the active snapins page. Please pull and let me know if you're having an issue still or not.

I also hopefully addressed the issue of it trying to display for the task of the host within the main task page.

**Comment by gplamondon** [comment]
This seems to be resolved, Thanks!
