### ISSUE TITLE
[FOG 1.6] Active snapin task managment

### ISSUE THREAD

**Issue by gplamondon** [FOGProject/fogproject#349]
canceling an individual snapin cancels all queued snapins

**Comment by mastacontrola** [comment]
I don't know if what I've change will fix this or not. I'm working on minimal testing capability today.

Please pull and let me know.

Thank you!

**Comment by gplamondon** [comment]
It still cancels all snapin tasks.

**Comment by mastacontrola** [comment]
Is this after pulling and trying? I made quite a few changes in regards to this, though I didn't get to test the cancellation fully. I don't have snapins in use so it's a bit more difficult to test for my side.

I'm pushing another few items to test things as well. Just mostly cleaner handling and what not.

**Comment by gplamondon** [comment]
yes, this is after a pull.

**Comment by mastacontrola** [comment]
This should now be fixed. I ran a few tests and things appear to be working correctly now.

Closing, please let me know if you're still having issues.
