### ISSUE TITLE
[FOG 1.6] Snapin upload problem

### ISSUE THREAD

**Issue by gplamondon** [FOGProject/fogproject#352]
When i try to upload a snapin It says Internal Server Error on the gui.

Here is the /var/log/php-fpm/www-error.log
```
[13-Dec-2019 17:13:36 UTC] PHP Fatal error:  Uncaught Error: Call to a member function chmod() on boolean in /var/www/html/fog/lib/pages/snapinmanagement.page.php:1701
Stack trace:
#0 /var/www/html/fog/lib/pages/snapinmanagement.page.php(1988): SnapinManagement->snapinGeneralPost()
#1 /var/www/html/fog/lib/fog/fogpagemanager.class.php(167): SnapinManagement->editPost()
#2 /var/www/html/fog/management/index.php(53): FOGPageManager->render()
#3 {main}
  thrown in /var/www/html/fog/lib/pages/snapinmanagement.page.php on line 1701
```

**Comment by gplamondon** [comment]
this message is flooding the /var/log/php-fpm/www-error.log every second.
```
[13-Dec-2019 17:14:07 UTC] PHP Fatal error:  Uncaught Error: Class 'ServiceModule' not found in /var/www/html/fog/service/servicemodule-active.php:25
```

**Comment by mastacontrola** [comment]
Do you have machines still using the legacy client?

**Comment by mastacontrola** [comment]
As for the upload issue, it appears the path it's trying to change to doesn't exist. So it's setting the FTP element to false.

Can you please verify that your snapin path exists on the FOG server as well as ensure the path is owned by fogproject:fogproject or fogproject:apache or fogproject:www-data (preferably one of the last two as you are using web calls to upload the files. fogproject:apache for redhat based or fogproject:www-data for debian based.)

Thank you,

**Comment by gplamondon** [comment]
> Do you have machines still using the legacy client?

Not that I am aware of.

**Comment by gplamondon** [comment]
> As for the upload issue, it appears the path it's trying to change to doesn't exist. So it's setting the FTP element to false.
> 
> Can you please verify that your snapin path exists on the FOG server as well as ensure the path is owned by fogproject:fogproject or fogproject:apache or fogproject:www-data (preferably one of the last two as you are using web calls to upload the files. fogproject:apache for redhat based or fogproject:www-data for debian based.)
> 
> Thank you,

the opt/fog/snapin folder was owned by root.  Does the installer do a permissions check because I may have some other permissions out of whack.

**Comment by gplamondon** [comment]
I changed the permissions of the /opt/fog/snapins folder to fogproject.fogproject and I am still getting the error:
![alt text](https://i.gyazo.com/a20576efc2502865857524836878f8b7.png)

**Comment by mastacontrola** [comment]
Can you provide the servers php-Fpm www-error logs?

**Comment by gplamondon** [comment]
`[16-Dec-2019 19:36:42 UTC] PHP Fatal error:  Uncaught Error: Call to a member function chmod() on boolean in /var/www/html/fog/lib/pages/snapinmanagement.page.php:1048
Stack trace:
#0 /var/www/html/fog/lib/fog/fogpagemanager.class.php(167): SnapinManagement->addPost()
#1 /var/www/html/fog/management/index.php(53): FOGPageManager->render()
#2 {main}
  thrown in /var/www/html/fog/lib/pages/snapinmanagement.page.php on line 1048
[16-Dec-2019 19:36:43 UTC] PHP Fatal error:  Uncaught Error: Class 'ServiceModule' not found in /var/www/html/fog/service/servicemodule-active.php:25
Stack trace:
#0 {main}
  thrown in /var/www/html/fog/service/servicemodule-active.php on line 25
`

**Comment by mastacontrola** [comment]
Okay, I've re-added the servicemodule class to address all the messages you're seeing.

That said, i am 100% sure these errors are not causing the failure to upload the files.

Can you set the permissions to:

fogproject:www-data or fogproject:apache and try again? This should allow the chmod command to work properly.

I'd also suggest, if possible, setting the permissions (chmod) to 777 for /opt/fog/snapins

Thank you,

**Comment by gplamondon** [comment]
The problem is with inserting the data into mysql.
The file is uploaded fine.  I have to manually enter the data into MySQL to get new snapins.

**Comment by mastacontrola** [comment]
I understand that, but the reason it's failing to put create the definition is because it's failing to complete the upload process.  I can remove the chmod request but not exactly sure how it will impact things moving forward.

**Comment by mastacontrola** [comment]
Pushed a commit to remove the chdir and chmod attempts on file upload

Mind pulling and testing?

**Comment by gplamondon** [comment]
Sure, I had to do a git reset --hard 013ac6e this moring after a git pull.
The clients were all giving an unable to get subsection... errror.
I will pull and give the exact error if it happens.

**Comment by gplamondon** [comment]
That fixed the snapin issue!
but i am getting:

`------------------------------------------------------------------------------
--------------------------------Authentication--------------------------------
------------------------------------------------------------------------------
 12/23/2019 10:42 AM Client-Info Version: 0.11.16
 12/23/2019 10:42 AM Client-Info OS:      Windows
 12/23/2019 10:42 AM Middleware::Authentication Waiting for authentication timeout to pass
 12/23/2019 10:42 AM Middleware::Communication Download: http://10fogserver/fog/management/other/ssl/srvpublic.crt
 12/23/2019 10:42 AM Data::RSA FOG Server CA cert found
 12/23/2019 10:42 AM Middleware::Authentication Cert OK
 12/23/2019 10:42 AM Middleware::Communication POST URL: http://10fogserver/fog/management/index.php?sub=requestClientInfo&authorize&newService
 12/23/2019 10:42 AM Middleware::Response Success
 12/23/2019 10:42 AM Middleware::Authentication Authenticated


 12/23/2019 10:42 AM Middleware::Communication URL: http://10fogserver/fog/management/index.php?sub=requestClientInfo&configure&newService&json
 12/23/2019 10:42 AM Middleware::Response Success
 12/23/2019 10:42 AM Middleware::Communication URL: http://10fogserver/fog/management/index.php?sub=requestClientInfo&mac=6C:0B:84:E4:53:A2|28:16:AD:49:F1:39|2A:16:AD:49:F1:38|28:16:AD:49:F1:38|28:16:AD:49:F1:3C&newService&json
 12/23/2019 10:42 AM Middleware::Communication ERROR: Could not contact FOG server
 12/23/2019 10:42 AM Middleware::Communication ERROR: The remote server returned an error: (404) Not Found.
 12/23/2019 10:42 AM Middleware::Response Success
 12/23/2019 10:42 AM Middleware::Communication URL: http://10fogserver/fog/service/getversion.php?clientver&newService&json
 12/23/2019 10:42 AM Middleware::Communication URL: http://10fogserver/fog/service/getversion.php?newService&json

 12/23/2019 10:42 AM Service Creating user agent cache
 12/23/2019 10:42 AM Middleware::Response ERROR: Unable to get subsection
 12/23/2019 10:42 AM Middleware::Response ERROR: Object reference not set to an instance of an object.
 12/23/2019 10:42 AM Middleware::Response ERROR: Unable to get subsection
 12/23/2019 10:42 AM Middleware::Response ERROR: Object reference not set to an instance of an object.
 12/23/2019 10:42 AM Middleware::Response ERROR: Unable to get subsection
 12/23/2019 10:42 AM Middleware::Response ERROR: Object reference not set to an instance of an object.
 12/23/2019 10:42 AM Service Initializing modules`

**Comment by mastacontrola** [comment]
Try again now? I just pushed a fix for this, thank you.

**Comment by gplamondon** [comment]
Fixed!
Thanks Tom!
