### ISSUE TITLE
[FOG 1.6] Blank Tasks

### ISSUE THREAD

**Issue by gplamondon** [FOGProject/fogproject#359]
Blank tasks added to the queue.
This seems to happen when adding a snapin to the list via a single snapin.
This has happened before fix 15db487 I just kept forgetting to report it.

![alt text](https://i.gyazo.com/596f8be06899d22a9ebfbd751afea5f1.png)

**Comment by mastacontrola** [comment]
In browser, what happens if you goto:

http://10fogserver/fog/snapintask/active

**Comment by gplamondon** [comment]
I get this:

![alt text](https://i.gyazo.com/50e239a7e8da5bf03854f14ce046b7a6.png)

**Comment by mastacontrola** [comment]
You need to be logged into the GUI first

**Comment by mastacontrola** [comment]
I know it's been a while but is this still an issue?  I have done quite a bit more workings with 1.6 code base and I believe things may just work, but unsure, if you'd be willing to see if this is looking/working better it would help me out a lot. If it's not working, I can fix it probably pretty quickly as long I can replicate the issue.

Thank you!

**Comment by darksidemilk** [comment]
@gplamondon I believe this is fixed in the latest versions of 1.6. If we're wrong about that and you're still experiencing this we'll gladly re-open this and get it figured out.
