### ISSUE TITLE
[FOG 1.6] Wrong variable name

### ISSUE THREAD

**Issue by TommyChris** [FOGProject/fogproject#361]
In this line, "linlux" needs to be "linux":

https://github.com/FOGProject/fogproject/blob/e45329ed01f2358b5268505bd3a49e06849f741c/lib/common/functions.sh#L528

**Comment by Sebastian-Roth** [comment]
@TommyChris Thanks for finding this and letting us know. I had a look at the repo commits to find when and how this was added: https://github.com/FOGProject/fogproject/commit/88eb8ab62d45f426a0e1509d726ca670fe5162da#diff-c7d534e343a3d117623765442be0d709

As we see the line `... add-apt-repository -y universe ...` is being added twice in this function. I suppose we can remove the if/else part but it would need some testing on various versions of Ubuntu to make sure this is not causing any trouble. As far as I remember we noticed that some versions of Ubuntu didn't have the repository `universe` by default and would fail to install PHP properly. But not sure about the details on this. @mastacontrola do you remember this?

**Comment by mastacontrola** [comment]
I remember adding the element to this.

Too me, it makes little sense to do the if/else at all, with the exception being that apparently we only want to do ondrej repositories if ubuntu is 17 or lower.

**Comment by mastacontrola** [comment]
Okay, so the reason there's 2 universe areas, I likely pulled the command to copy it into the if/else, and forgot to remove it when done. It didn't matter any way as I had the typo on the variable name as well. I must've just been in a hurry.

I've removed the first universe entry and fixed the variable name in `working-1.6`

Thank you,
