### ISSUE TITLE
Ubuntu 19.10 Support

### ISSUE THREAD

**Issue by JosephGarrone** [FOGProject/fogproject#362]
Have just been setting FOG up on a 19.10 server (In anticipation of moving to 20.04 permanently come April.

The existing installation appears to work fine with one change:

Comment out [functions.sh:addUbuntuRepo()](https://github.com/FOGProject/fogproject/blob/master/lib/common/functions.sh#L537) and pre-run:
```
sudo add-apt-repository ppa:ondrej/php
sudo apt-get update
```

I suspect the real change needs to be to have another if statement checking for `$OSVersion -gt 19`, and just adding the `ppa:ondrej/php` repository (Similar to the < 18 case, just without the `ppa:ondrej/apache`)

**Comment by Sebastian-Roth** [comment]
@JosephGarrone Thanks for your input on this! Was there any specific error you ran into that made you play with the scripts. While I welcome everyone to fiddle with the code I am wondering why you would add the `ondrej` repo at all? 19.04 has [PHP version 7.2](https://packages.ubuntu.com/disco/php) and 19.10 comes with [PHP 7.3](https://packages.ubuntu.com/eoan/php).

We added the ondrej repo back in the  days when PHP 7 was still very new and not available as official package in most Linux distros. But we try to get away from this and use the official PHP versions that come with the OS itself.

So for Ubuntu 18.04, 18.10, 19.04, 19.10 and all the following releases the installer just does an `add-apt-repository -y universe` because we saw an issue with some 18.04 installs that didn't have that official Ubuntu repo enabled. Nothing more.

**Comment by JosephGarrone** [comment]
The issues I received were:

```
 * Packages to be installed:
        apache2 bc build-essential cpp curl g++ gawk gcc genisoimage gzip htmldoc isolinux lftp libapache2-mod-php7.2 li                                                                                                                                                        fpm php7.2-gd php7.2-json php7.2-ldap php7.2-mbstring php7.2-mysql php7.2-mysqlnd php-gettext sysv-rc-conf tar tftpd-hpa
<!-- Successful lines skipped -->
 * Skipping package: libapache2-mod-php7.2.....................(Does not exist)
<!-- Successful lines skipped -->
 * Skipping package: php7.2....................................(Does not exist)
 * Skipping package: php7.2-bcmath.............................(Does not exist)
 * Skipping package: php7.2-cli................................(Does not exist)
 * Skipping package: php7.2-curl...............................(Does not exist)
 * Skipping package: php7.2-fpm................................(Does not exist)
 * Skipping package: php7.2-gd.................................(Does not exist)
 * Skipping package: php7.2-json...............................(Does not exist)
 * Skipping package: php7.2-ldap...............................(Does not exist)
 * Skipping package: php7.2-mbstring...........................(Does not exist)
 * Skipping package: php7.2-mysql..............................(Does not exist)
 * Skipping package: php7.2-mysqlnd............................(Does not exist)
<!-- Successful lines skipped -->
 * Setting up and starting MySQL...............................Done
 * Backing up user reports.....................................Done
 * Stopping web service........................................Failed! <-- Last line in output
```

Given it is trying to install `php7.2`, I assumed it would be required and went down the `ondrej` repo. If it works with `php7.3` or `php7.4` then I think all that's needed is to modify the installer to attempt to use the `7.(3|4)` packages rather than `7.2`.

**Comment by Sebastian-Roth** [comment]
@JosephGarrone Ahhh I see. The issue (as I see it) is that we still try to install a specific version of PHP - version [7.2 in the case of Ubuntu 18.04 and later](https://github.com/FOGProject/fogproject/blob/master/lib/ubuntu/config.sh#L59).

Now that pretty much all distros moved to PHP 7 we should really try to go back to simply install what comes with the OS by default I reckon. This was we don't need to update the installer for each and every new OS release. I had this on my list of things to do for the next generation of FOG (1.6.x) but as I see this causing problems even before 20.04 is out we might consider fixing that earlier. What do you think @mastacontrola?

I will see how much work this needs.

**Comment by mastacontrola** [comment]
I would agree that we should let the OS define it, though I would be want to be cautious to ensure that we will install at least PHP 5.6 (as some people are still running with CentOS 7/RHEL7 or lesser "lts" linux's.

**Comment by mastacontrola** [comment]
Part of the cause for all of the implicit defining for Ubuntu, however, is due to how Ubuntu is passing the PHP flags around.

At least in Redhat based, for the most part, you have php-fpm, php, etc... for the commands. With ubuntu its:

php7.3 php7.3-fpm php7.3-ldap (for example)

**Comment by Sebastian-Roth** [comment]
Yes, perfectly right. We need to ensure older LTS versions install PHP 5.6 at least.

For the version number used in commands and files I would hope that we find decent commands to get around without actually knowing the version. Similar to what I have added for mysql/mariadb a while ago, e.g.:
```
systemctl list-units | grep -o -e "php.*fpm"
systemctl list-unit-files | grep -v bad | grep -o -e "php.*fpm"
find /etc/php*/ -name "php.ini" | grep "fpm/php.ini"
which phpenmod || which php5enmod
find /etc/php*/ -name "www.conf"
....
```
Just a few examples. I know that changing this needs a fair amount of testing on various distros but we have Wayne's automated tests and could do the rest manually.

It would make the installer a lot less static and prone to issues with newer versions I'd think.

**Comment by Quazz** [comment]
As far as I can tell Rhel7 is forced to PHP 7.2 by the install script currently using the remi repos. That should work even on newer Rhel versions I think. 

Arch by nature should have the near latest versions by default I believe.

So that leaves just Ubuntu to deal with I reckon. I believe one of the problems with ubuntu is that the install names you need to pass need to include the version number, so it's difficult to gloss over that afaik.

**Comment by Sebastian-Roth** [comment]
> So that leaves just Ubuntu to deal with I reckon. I believe one of the problems with ubuntu is that the install names you need to pass need to include the version number, so it's difficult to gloss over that afaik.

I don't think this is actually a problem because in Ubuntu all the versioned PHP packages also have a general named virtual package (`php`, `php-json`, `php-ldap`, `php-mysql` and so on). Check out this package query website: https://packages.ubuntu.com/search?suite=bionic&arch=any&searchon=names&keywords=php-ldap (you can switch between the different Ubuntu versions...)

But on the other hand I see that this is just the beginning of a major cleanup that should not take place in the current version!

**Comment by Sebastian-Roth** [comment]
@JosephGarrone Sorry if you got lost in the discussion here. I hope you saw my comment on using the `dev-branch` because this should work with Ubuntu 19.10!
```
sudo -i
git clone https://github.com/FOGProject/fogproject
cd fogproject
git checkout dev-branch
cd bin
./installfog.sh
```

**Comment by JosephGarrone** [comment]
Cheers, I'll pop it in my notes for my next install.

**Comment by Quazz** [comment]
> > So that leaves just Ubuntu to deal with I reckon. I believe one of the problems with ubuntu is that the install names you need to pass need to include the version number, so it's difficult to gloss over that afaik.
> 
> I don't think this is actually a problem because in Ubuntu all the versioned PHP packages also have a general named virtual package (`php`, `php-json`, `php-ldap`, `php-mysql` and so on). Check out this package query website: https://packages.ubuntu.com/search?suite=bionic&arch=any&searchon=names&keywords=php-ldap (you can switch between the different Ubuntu versions...)
> 
> **But on the other hand I see that this is just the beginning of a major cleanup that should not take place in the current version!**

@Sebastian-Roth 
For installation that makes sense (hopefully the virtual packages select the correct ones anyway), but that still leaves us with an unknown for the commands as per what Tom mentioned. 

By retrieving the php version from the repo; we could insert it into those commands, knowing that it should be the correct one (barring user modifications)

**Comment by Sebastian-Roth** [comment]
@Quazz said:
> By retrieving the php version from the repo; we could insert it into those commands, knowing that it should be the correct one (barring user modifications)

While I really like your idea of grabbing the version information using tools like `apt` I would like to take this one step further. Using the version information in paths like `/etc/php/${php_ver}/fpm/...` will break as soon as this path schema is being changed. Using `find /etc...` should work even if the directory structure is being changed. What do you think?

**Comment by Quazz** [comment]
> @Quazz said:
> 
> > By retrieving the php version from the repo; we could insert it into those commands, knowing that it should be the correct one (barring user modifications)
> 
> While I really like your idea of grabbing the version information using tools like `apt` I would like to take this one step further. Using the version information in paths like `/etc/php/${php_ver}/fpm/...` will break as soon as this path schema is being changed. Using `find /etc...` should work even if the directory structure is being changed. What do you think?

Oooohhh, yes, you're right, that's better since we can just install the virtual packages and then look at what it has actually installed.

**Comment by Sebastian-Roth** [comment]
@Quazz said:
> Oooohhh, yes, you're right, that's better since we can just install the virtual packages and then look at what it has actually installed.

Ahhhh, right. Your comment made me think just about another possible solution. After the package is installed we might even be able to use the package manager information to query for the files: `dpkg -S php.ini | grep ...` or `dpkg -L php-fpm | grep ...`

On the other hand that would make it specific for Debian based distros again. I would rather use `find` to be OS independent in the long run. But noting this here anyway so we have a few ideas when we get back to this topic some time in the future.
