### ISSUE TITLE
Fog forum problem

### ISSUE THREAD

**Issue by ZrytyADHD** [FOGProject/fogproject#363]
Sorry for writing here but i have a problem and can't contact with anyone.
After creating acount on forum I can't confirm my email address. I try to do this on diferent addreses but without sucerss.
My email is maven1987@gmail.com
System is writing about the "Confirmation email sent " but i got nopthing in my mailbox.
Can any body help me ?

**Comment by Sebastian-Roth** [comment]
@ZrytyADHD We just updated the forums a day ago. Maybe there is an issue with the new version. I will take a look.

**Comment by ZrytyADHD** [comment]
Everything working now thank you for help.

**Comment by mastacontrola** [comment]
I caused an issue last night so you may have to retry and re-register. I just don’t want you to think this was intentional or giving you any problems other than we had an issue.
