### ISSUE TITLE
FOG website down

### ISSUE THREAD

**Issue by abulhol** [FOGProject/fogproject#364]
Hi there, maybe this is not the right place to ask, but your website fogproject.org is completely down, and I found no other place to contact you. 
Is it only a temporary issue?
The forum and Wiki are vital places for us.

**Comment by csyperski** [comment]
We are working on it right now, it should be up shortly....

**Comment by abulhol** [comment]
That's cool, at least the forum is back now. 
But the main page https://fogproject.org/ as well as the wiki subdomain give a 404 now.
