### ISSUE TITLE
Install script fails starting DB using systemd under Ubuntu 14.04

### ISSUE THREAD

**Issue by knightsg** [FOGProject/fogproject#368]
The install script attempts to use systemd to manage the DB but Ubuntu 14.04 uses upstart, not systemd.

The error shown during install:

```
 * Setting up and starting MySQL................................./lib/common/functions.sh: line 1007: systemctl: command not found
../lib/common/functions.sh: line 1008: systemctl: command not found
```

**Comment by Sebastian-Roth** [comment]
@knightsg I know you can still use Ubuntu 14.04 with Extended Security Maintenance but it's out of standard support since almost a year. Why would you still want to use Ubuntu 14.04?

If you are keen to get this fixed you can send in a pull request real quick before we release FOG 1.5.8 tomorrow.

**Comment by knightsg** [comment]
Yes, I realise Ubuntu 14 is no longer receiving support - at the time I logged this I was trying this out in a VM under xenserver 6.5 which doesn't support Ubuntu 18; since then I've moved to a physical machine running Ubuntu 18 so TBH I don't have this issue. However, the requirements page on the wiki includes Ubuntu14 as a supported distro so I thought it worth noting here.

**Comment by Sebastian-Roth** [comment]
@knightsg Thanks for mentioning the wiki. We struggle to keep up with all the work on fixing things and keeping documentation up to date with too little people in the team.

I just updated the wiki though there is still a lot that would need updating as well.
