### ISSUE TITLE
Improving MySQL performance/scalability

### ISSUE THREAD

**Issue by Quazz** [FOGProject/fogproject#370]
FOG currently still uses MyISAM for its database tables. This works fine in small environments where not too much simultaneous traffic happens. 

MyISAM doesn't have row level locking, so it locks the entire table for basically anything you do. This can cause significant delays (or even timeouts) in high volume environments.

A user has already tried out changing the table engine to InnoDB, with great success.

https://forums.fogproject.org/topic/14140/bottleneck-on-database/2?_=1582635667708

I had a quick look over the tables and as far as I can tell, they are pretty much fully ready to be converted to InnoDB as they are now. 

That said, such a conversion would also have to go hand in hand with a default mysql config file that makes sense. 

I'm thinking we could have conservative default values (meaning low end target) and then perhaps try to automatically determine if a system needs a 'higher tier' config (changing certain values, using database total size as a rough estimate). Or maybe use `mysqltuner.pl` and use its output?? Just some ideas.

Alternatively, an easier route, would be slightly less conservative defaults and then instructions for how to crank it up using already well established tools such as `mysqltuner.pl` to optimize their MySQL settings for their environment specifically. 

Most important variables for InnoDB (example values for high volume scenario):

`innodb_buffer_pool_size         = 2G   # The most importane one! Determines how much of the tables is kept in RAM`

`innodb-buffer-pool-instances    = 2  # Use 1 instance per 1GB of InnoDB pool size. Not needed under 1G`

`innodb_page_cleaners            = 2 # Use 1 instance per buffer pool instance`

`innodb-file-per-table           = 1 # Forces each table to be its own file. `

`innodb-flush-method             = O_DIRECT # Improves performance on virtually every Linux OS`

`innodb-log-buffer-size          = 128M # Amount of writes to keep in memory before writting to the log file. Should never be larger than innodb-log-file-size. Should not be signficantly smaller than innodb-log-file-size to ensure disk IO doesnt go crazy`

`innodb-log-file-size            = 256M # Size of each log file  (should be innodb-buffer-pool-size / innodb-buffer-pool-instances * innodb_log_files_in_group)`

`innodb_log_files_in_group       = 2 # Total amount of log files`

Perhaps best to slate this for 1.6 though.

**Comment by George1422** [comment]
The mysql/mariadb part of FOG really hasn't been looked at for a very log time. There may be some simple changes that may make a dramatic improvement in the responsiveness of FOG and the Web UI. 

One additional entry for the my.conf would be 
default-storage-engine=innodb

I'm also working on a tutorial for converting an existing FOG database over to innodb. I would really like to get the OP of this thread to help us debug and work through this change over. He/she has obviously some mariadb experience and a somewhat large fog install. https://forums.fogproject.org/topic/14254/high-cpu-usage

Example script to convert over isam to innodb table engines. I've already applied these to my install of fog. I can't tell of any improvements in performance or cpu usage, but I also don't use the FOG client. 

`
ALTER TABLE LDAPServers ENGINE=InnoDB;
ALTER TABLE clientUpdates ENGINE=InnoDB;
ALTER TABLE dirCleaner ENGINE=InnoDB;
ALTER TABLE globalSettings ENGINE=InnoDB;
ALTER TABLE greenFog ENGINE=InnoDB;
ALTER TABLE groupMembers ENGINE=InnoDB;
ALTER TABLE groups ENGINE=InnoDB;
ALTER TABLE history ENGINE=InnoDB;
ALTER TABLE hookEvents ENGINE=InnoDB;
ALTER TABLE hostAutoLogOut ENGINE=InnoDB;
ALTER TABLE hostMAC ENGINE=InnoDB;
ALTER TABLE hostScreenSettings ENGINE=InnoDB;
ALTER TABLE hosts ENGINE=InnoDB;
ALTER TABLE imageGroupAssoc ENGINE=InnoDB;
ALTER TABLE imagePartitionTypes ENGINE=InnoDB;
ALTER TABLE imageTypes ENGINE=InnoDB;
ALTER TABLE images ENGINE=InnoDB;
ALTER TABLE imagingLog ENGINE=InnoDB;
ALTER TABLE inventory ENGINE=InnoDB;
ALTER TABLE ipxeTable ENGINE=InnoDB;
ALTER TABLE keySequence ENGINE=InnoDB;
ALTER TABLE location ENGINE=InnoDB;
ALTER TABLE locationAssoc ENGINE=InnoDB;
ALTER TABLE moduleStatusByHost ENGINE=InnoDB;
ALTER TABLE modules ENGINE=InnoDB;
ALTER TABLE multicastSessions ENGINE=InnoDB;
ALTER TABLE multicastSessionsAssoc ENGINE=InnoDB;
ALTER TABLE nfsFailures ENGINE=InnoDB;
ALTER TABLE nfsGroupMembers ENGINE=InnoDB;
ALTER TABLE nfsGroups ENGINE=InnoDB;
ALTER TABLE notifyEvents ENGINE=InnoDB;
ALTER TABLE os ENGINE=InnoDB;
ALTER TABLE oui ENGINE=InnoDB;
ALTER TABLE plugins ENGINE=InnoDB;
ALTER TABLE powerManagement ENGINE=InnoDB;
ALTER TABLE printerAssoc ENGINE=InnoDB;
ALTER TABLE printers ENGINE=InnoDB;
ALTER TABLE pxeMenu ENGINE=InnoDB;
ALTER TABLE scheduledTasks ENGINE=InnoDB;
ALTER TABLE schemaVersion ENGINE=InnoDB;
ALTER TABLE snapinAssoc ENGINE=InnoDB;
ALTER TABLE snapinGroupAssoc ENGINE=InnoDB;
ALTER TABLE snapinJobs ENGINE=InnoDB;
ALTER TABLE snapinTasks ENGINE=InnoDB;
ALTER TABLE snapins ENGINE=InnoDB;
ALTER TABLE supportedOS ENGINE=InnoDB;
ALTER TABLE taskLog ENGINE=InnoDB;
ALTER TABLE taskStates ENGINE=InnoDB;
ALTER TABLE taskTypes ENGINE=InnoDB;
ALTER TABLE tasks ENGINE=InnoDB;
ALTER TABLE userCleanup ENGINE=InnoDB;
ALTER TABLE userTracking ENGINE=InnoDB;
ALTER TABLE users ENGINE=InnoDB;
ALTER TABLE virus ENGINE=InnoDB;
ALTER TABLE wolbroadcast ENGINE=InnoDB;
`

**Comment by eduardotseoane** [comment]
this is what i do to create this thread:
https://forums.fogproject.org/topic/14140/bottleneck-on-database/2?_=1582635667708

**Comment by Sebastian-Roth** [comment]
@Quazz @George1422 What stage are we at with this I am wondering?

**Comment by Quazz** [comment]
@Sebastian-Roth I'd say there's nothing really stopping us from implementing this. Default config should probably be fine for most installs. (default settings have improved a lot since I last posted here) Those who have issues/want more performance can tune it further. 

Another thing that might be worth looking at are the indexes, though that is a lot more complex of course.

**Comment by Sebastian-Roth** [comment]
@Quazz said:
> Default config should probably be fine for most installs. (default settings have improved a lot since I last posted here)

May I ask what you mean by that? The default if MyISAM? What has improved?

> Another thing that might be worth looking at are the indexes, though that is a lot more complex of course.

Does that add much of performance?

**Comment by George1422** [comment]
Well for MyISAM that data engine uses table level blocking for updates. This becomes a problem when you have 100s of FOG clients hitting the FOG server per minute. The INNODB engine uses row level locking on updates. The INNODB engine is much more efficient at FOG workloads where there are more than 200 clients (guess) checking into the FOG server. With sites less than 200 nodes the myisam engine is sufficient enough. 

In the case of indexing, I think that is something worth exploring. If we indexed frequently looked up terms maybe the mac address and host name fields for the hosts table or any other table that would have many rows where FOG runs on big campuses. In most databases there is an index automatically created on the primary key. But with FOG that does very little good because I don't think the hostid field is ever used for searches, where if we had an index on hostname or mac address those indexes would be more beneficial. We would really need to see what the fog client does when it connects. What queries does it run. That I think is the area where we would see the most benefit for creating additional indexes on certain tables.

**Comment by Quazz** [comment]
> @Quazz said:
> 
> > Default config should probably be fine for most installs. (default settings have improved a lot since I last posted here)
> 
> May I ask what you mean by that? The default if MyISAM? What has improved?
Yes, I mean the defaults for Innodb table settings have improved. A lot of it now smartly configures itself on boot and for others the defaults are more suited to modern situations. 

All this to say that if we switch over to Innodb we don't need an explicit configuration file. Defaults should work in most situations.
> 
> > Another thing that might be worth looking at are the indexes, though that is a lot more complex of course.
> 
> Does that add much of performance?

Depends on the query in question. Though I'm far from a database expert so I'm not the best person to ask about this. 

I think the queries that happen often in high volume situations are the ones that deserve the most examination since even a small different in performance would make a huge difference. 

I haven't taken a proper look at any of that, though, so I can't comment on how urgent or needed it really is, just something to consider

**Comment by mastacontrola** [comment]
I have made the change, quite a few months now, for Innodb to be the standard for working-1.6.

I didn't adjust anything within master/dev-branch to keep the 2 separated. But if there's a a need to make the switch, there's some code example there.

**Comment by Sebastian-Roth** [comment]
@George1422 said:
> We would really need to see what the fog client does when it connects. What queries does it run. That I think is the area where we would see the most benefit for creating additional indexes on certain tables.

The fog-client sends a couple of HTTP requests to the FOG server to push and pull information ([code ref](https://github.com/FOGProject/fog-client/blob/master/Service/FOGSystemService.cs#L51) - as well in line 88, 90, 91). This is being answered within the (FOGPage class code](https://github.com/FOGProject/fogproject/blob/dev-branch/packages/web/lib/fog/fogpage.class.php#L3003). This code calls functions from several other files and classes. Maybe it's easier to look at by enabling and monitoring the SQL query log.

> I have made the change, quite a few months now, for Innodb to be the standard for working-1.6.
> I didn't adjust anything within master/dev-branch to keep the 2 separated. But if there's a a need to make the switch, there's some code example there.

Now are we ready to make this default in `dev-branch` (and the next release) as well?

**Comment by Sebastian-Roth** [comment]
@Quazz @George1422 Would you be able to help me test things before we put that into the next release?

**Comment by Sebastian-Roth** [comment]
@Quazz @George1422 I found some time to do some testing as well as adding the change (7330fbc4c). InnoDB will be the default for new FOG installs from now on.

We won't do an automatic conversation of existing installs though.
