### ISSUE TITLE
Refind compatibility issues/alternative efi boot to hard drive option

### ISSUE THREAD

**Issue by darksidemilk** [FOGProject/fogproject#373]
rEFInd, while a really cool tool, is not universally compatible.
Sometimes when a computer attempts to boot to hard drive from the pxe menu it gets stuck trying to load refind. Sometimes different configurations in the refind.conf file can help, but in a mixed hardware environment it's not uncommon to not be able to find a universal answer.

Some of these hardware compatibility issues have been brought to the attention of the refind developer but he eventually figured that it sounded like a low number of computers, personally I find the opposite. We used to use rEFInd as a custom boot manager built into our images, but it had enough problems that we've moved to grub2win a grub 2 based windows efi compatible solution. I have attempted to add a chain load option to this copy pasting the boot files to the fog webserver to no avail. So while perhaps an efi version of grub2 might be an alternate option I haven't found a way to get that working just yet.

In doing some testing with the ipxe shell and reading their documentation (https://ipxe.org/cmd/exit) the exit command can take parameters of 1 or 0 to send a error (1) or success (0) to the bios/firmware. Theoretically sending the 1 would tell the firmware to try the next boot option. I was able to exit the ipxe shell and boot to my local disk with `exit 0` and `exit 1` where just `exit` goes to black nothingness. I attempted to add this command to the bootmenu options of fog, but it didn't work for me straight through the pxe menu.

I also messed with sanboot a bit, but couldn't find a way to list what local drives the ipxe shell sees. The documented examples of 0x80 0x81 0x82 etc were not recognized.

Point is, there needs to be another option for booting to the hard drive on efi systems when refined doesn't work. There are some possibilities out there.

**Comment by darksidemilk** [comment]
Also posted in forums feature requests https://forums.fogproject.org/topic/14271/alternate-efi-boot-to-hard-drive-option

**Comment by mastacontrola** [comment]
Should be fixed in the latest, closing. Specifically in working-1.6
