### ISSUE TITLE
PXE ADVANCED under Fog Boot Settings, new line does not work

### ISSUE THREAD

**Issue by VietTPham** [FOGProject/fogproject#378]
![image](https://user-images.githubusercontent.com/8483291/77585353-92ce3900-6ea1-11ea-96bc-6359baaf55da.png)

The setting under Fog Boot Settings -> PXE Advanced does not let you do new line in it. I even copied and pasted from a notepad and it still does not paste as new line. Below is a box where new line does work, and you can see the grey dotted corner.

![image](https://user-images.githubusercontent.com/8483291/77585511-d759d480-6ea1-11ea-8d54-c04a3b9cd417.png)

**Comment by Sebastian-Roth** [comment]
@VietTPham What exactly are you trying to do? I would expect you want to add advanced iPXE stuff. Go to FOG Configuration -> iPXE General Configuration -> Advanced Menu settings -> **Advanced menu command**

Be aware that the text field will be hidden/removed in many browsers if you use plugins like AdBlock....

**Comment by VietTPham** [comment]
Looks like it was the adblock.
