### ISSUE TITLE
Limit fog user access

### ISSUE THREAD

**Issue by cspenceiv** [FOGProject/fogproject#38]
Currently the fog user is a normal user. Since it is only used for vstftpd access, we need to look at making it a system user and chroot it to the tftp directory. This will also keep fog from showing up on the user list when logging into a DM.

**Comment by wayneworkman** [comment]
How about no home directory instead?
`adduser --system --no-create-home fog`
`passwd fog`

After deleting the fog user and then settting it up manually like that on Fedora 23, the "node image storage usage" pie graph reports correctly still... I suppose uploading and replication would still work too....

**Comment by wayneworkman** [comment]
Actually, the above steps broke ftp stuff on my servers... I undid it and it started working again... not sure if it was the --system option or the --no-create-home option.

**Comment by mastacontrola** [comment]
It, from what I can see, was the --no-create-home, as the linux subsystem needs a base to start from, not having a home gives the user a / directory as their home which is inaccessible to the user.

**Comment by mastacontrola** [comment]
I'm closing this issue for now.

It's unlikely we'll have a fix for this in time for release of 1.3.0, and as we're moving more to start working on FOG-TOO, it seems this will likely be forgotten about in the long term.

I do agree this would be a great enhancement and would improve security concerns quite a lot however, and I think we have this pretty well covered for our next version.
