### ISSUE TITLE
Newly added host does not appear in UI

### ISSUE THREAD

**Issue by abulhol** [FOGProject/fogproject#381]
We have recently updated from 1.5.5 to 1.5.8. 
The update went fine, but now we cannot properly add new hosts anymore. The issue is similar to #176. 
However, we can actually add the hosts (and there is a message box "Host added"), but it does not show up in the UI afterwards. 
I can see the host in the MySQL table `hosts`, but e.g. in `hostMAC` there is no corresponding entry. 
There are no errors in the Apache error log.

**Comment by Sebastian-Roth** [comment]
@abulhol Please run the DB cleanup stuff and see if that fixes the issue: https://wiki.fogproject.org/wiki/index.php?title=Troubleshoot_MySQL#Database_Maintenance_Commands

**Comment by abulhol** [comment]
@Sebastian-Roth thanks for the advice.
We have tried that out, but it doesn't help. 
Is there some way how I could debug the issue on our side?

**Comment by Sebastian-Roth** [comment]
@abulhol Sorry for the delay! Been mostly offline over Easter. Any chance you could get me a database dump so I can test?

**Comment by abulhol** [comment]
@Sebastian-Roth yes, I can do that. How can I get the dump over to you safely?

**Comment by Sebastian-Roth** [comment]
@abulhol Just sent you a private message via FOG forum chat. See the speech bubble in the top right corner there.

**Comment by Sebastian-Roth** [comment]
@abulhol Ok, did a first "quick" test:
* Fresh CentOS 7 VM (had that snapshoted at hand)
* Installed FOG 1.5.8 (the version you updated to) and let it create the default DB schema.
* Logged into the web UI (so I have access to change the web UI user PW easily as I don't (want to) know yours).
* Imported your DB dump (it does DROP IF EXISTS for every table, so should be a clean "overwrite" of the contents)
* Reset the web UI fog password so I can still login.
* Checked the host list, created a fresh host entry

It is created in the DB and shows up in the web UI. Arghhhhh. So I have not been able to replicate the issue as described. Though I can't really imagine the move from 1.5.5 to 1.5.8 playing much of a role for my test really because you gave me the latest DB dump causing the problem for you...

I will ponder on this a little longer.

**Comment by abulhol** [comment]
@Sebastian-Roth Too bad you could not reproduce at once. I appreciate your efforts! 
I have been thinking and testing a bit further. 
Could it be that when I create a host, some check is done on the MAC address in the background which silently fails? This could explain why the entry in `hosts` is created, but not in `hostMAC`.
Please note that we have custom firewall rules on this server, potentially they are blocking something?

**Comment by Sebastian-Roth** [comment]
@abulhol Sorry for the delay!
> Could it be that when I create a host, some check is done on the MAC address in the background which silently fails?

I'd think this is the case though I am wondering why this is happening in your install while mine doesn't show this symptom with the same database contents.

There are a few checks there:
1. in hostmanagement.class.php where the actual HTTP POST is happening to send the create host request: https://github.com/FOGProject/fogproject/blob/master/packages/web/lib/pages/hostmanagementpage.class.php#L629
2. in host.class.php where a primary MAC address is being added: https://github.com/FOGProject/fogproject/blob/master/packages/web/lib/fog/host.class.php#L1683
3. in host.class.php when the Host object is saved: https://github.com/FOGProject/fogproject/blob/master/packages/web/lib/fog/host.class.php#L301

But all of these places should actually fail with an exception on error and show the message on the web UI.

**Comment by abulhol** [comment]
I debugged the web app on our server and found the following:
I added a syslog command here in `fogbase.class.php`:
`protected static function debug($txt, $data = array())
    {
        syslog(LOG_INFO, $txt);`
If I know call the "Hosts" page, the following error is logged:
` Failed: Error: Required database field is empty`
If I click on one of the hosts, the errors are:
`message repeated 2 times: [ www: Failed: Error: Required database field is empty]
Set failed: Key: spuversion, Error: Invalid key being set
Failed: Error: Required database field is empty
Failed to add Page: Node: %s, Page Class: %s, Error: $s`

I went further into the code to look which "database field is empty", and found that FOGController tells me that it's a field called "name". The stack trace to this is:
`#0 /var/www/fog/lib/fog/host.class.php(624): FOGController->isValid()
 #1 /var/www/fog/lib/pages/hostmanagementpage.class.php(132): Host->isValid()
 #2 /var/www/fog/lib/fog/fogpagemanager.class.php(381): HostManagementPage->__construct()
 #3 [internal function]: FOGPageManager->{closure}('/var/www/fog/li...')
 #4 /var/www/fog/lib/fog/fogpagemanager.class.php(386): array_map(Object(Closure), Array)
 #5 /var/www/fog/lib/fog/fogpagemanager.class.php(79): FOGPageManager->loadPageClasses()
 #6 [internal function]: FOGPageManager->__construct()
 #7 /var/www/fog/lib/fog/fogbase.class.php(481): ReflectionClass->newInstanceArgs(Array)
 #8 /var/www/fog/management/index.php(23): FOGBase::getClass('FOGPageManager')
 #9 {main}`
The object in question is of type "Host". 
So I wonder if there is a "ghost" Host object which I cannot see in the MySQL DB?
Or are these errors not relevant?

By the way, what is also a bit weird are the two columns on the left side of the Hosts table: 
![image](https://user-images.githubusercontent.com/4851778/80077154-66afe180-854d-11ea-81b6-ee77f01b35e0.png)
The red question mark only says "Unknown" if I hover over it. 
But then, this looks exactly the same on a different server where we have a fresh FOG 1.5.7 installation.

**Comment by Sebastian-Roth** [comment]
@abulhol Well done! Let my try to give you some answers and point you further down the road.

> If I now call the "Hosts" page, the following error is logged:
> Failed: Error: Required database field is empty
> ...

Definitely not nice to see this when you enable debug like this but this is not really an issue. In this case an empty Host object is being cast when you open the host management view because this is called for listing the hosts as well as editing a single host's settings. Tom did a great job generalizing a lot of the PHP code but this does cause those kind of error messages sometimes. We might look into getting rid of those at some point but they are definitely not causing your problem. I get the same on my test system having no issue to add a new host.

> By the way, what is also a bit weird are the first and third column on the left side of the Hosts table

The first column is the host description. Hover your mouse over the question mark and you'll see the host description. The third column is showing the status of the host being online or shut down. The check is based in a service running in the background (`FOGPingHosts`) sending a quick TCP connection check on port 445 to see if the host is online and update the DB accordingly. I know some people might argue that port 445 is no open on all machines (Windows firewall or Linux hosts) but it's been like that for a long time and no one really got around to change it to a different check as far as I know. "Unknown" means it cannot detect the OS running on the host. When the host is booted to Windows and things work fine you should see a green (online) Windows icon there.


For further debugging I would suggest you add output statements to `save()` [function of the Host object](https://github.com/FOGProject/fogproject/blob/master/packages/web/lib/fog/host.class.php#L301) (line 304ff). See if it enters the `if ($this->isLoaded('mac'))` part - it really should! Then add more debugging or move it further down to find out where it bails out.

**Comment by Sebastian-Roth** [comment]
@abulhol Any news on this?

**Comment by abulhol** [comment]
@Sebastian-Roth haven't had time to debug further yet, will do so soon.

**Comment by abulhol** [comment]
@Sebastian-Roth I have debugged what you suggested.
The code bails out here:
https://github.com/FOGProject/fogproject/blob/master/packages/web/lib/fog/host.class.php#L336			
I.e. it neither throws an exception, nor does it proceed further down. 
So something must be wrong with:
```
if (count($HostWithMAC)
                && !in_array($this->get('id'), (array)$HostWithMAC)
)
```
I debugged `$HostWithMAC` using `syslog(LOG_INFO, print_r($HostWithMAC, 1));` and it prints:
```
Array#012(#012    [0] => 38#012)
```
PHP version is PHP 7.2.24-0ubuntu0.18.04.4 btw.

**Comment by Sebastian-Roth** [comment]
@abulhol This is really strange. I have installed Ubuntu 18.04 and done a FOG 1.5.5 install with upgrade to 1.5.8 and I still cannot reproduce the issue. Even added manual entries in `hostMAC` table to try and simulate the situation you have with the array (`[0] => 38`) returned in your case.

The only thing I can think of right now is that something might be wrong with your installation. First thing to check is if you really have the web UI files for FOG 1.5.8 in place:
```
ls -al /var/www/
ls -al /var/www/html/
ls -al /var/www/html/fog/
grep FOG_VERSION /var/www/html/fog/lib/fog/system.class.php
```
Please run those commands and post output here.

**Comment by abulhol** [comment]
```
user@myserver:~$ ls -al /var/www/
total 16
drwxr-xr-x  4 root     root     4096 Mar 23 09:52 .
drwxr-xr-x 15 root     root     4096 Oct 22  2019 ..
drwxr-xr-x 11 www-data www-data 4096 Mar 23 09:52 fog
drwxr-xr-x  2 root     root     4096 Oct  9  2019 html
user@myserver:~$ ls -al /var/www/html/
total 20
drwxr-xr-x 2 root root  4096 Oct  9  2019 .
drwxr-xr-x 4 root root  4096 Mar 23 09:52 ..
lrwxrwxrwx 1 root root    13 Oct  9  2019 fog -> /var/www/fog/
-rw-r--r-- 1 root root 10918 Oct  9  2019 index.html
user@myserver:~$ ls -al /var/www/html/fog/
total 412
drwxr-xr-x 11 www-data www-data   4096 Mar 23 09:52 .
drwxr-xr-x  4 root     root       4096 Mar 23 09:52 ..
drwxr-xr-x  2 www-data www-data   4096 Mar 23 09:52 api
drwxr-xr-x  2 www-data www-data   4096 Mar 23 09:52 client
drwxr-xr-x  2 www-data www-data   4096 Mar 23 09:52 commons
-rw-r--r--  1 www-data www-data 370070 Mar 23 09:52 favicon.ico
lrwxrwxrwx  1 www-data www-data     13 Mar 23 09:52 fog -> /var/www/fog/
drwxr-xr-x  2 www-data www-data   4096 Mar 23 09:52 fogdoc
-rw-r--r--  1 www-data www-data    572 Mar 23 09:52 index.php
drwxr-xr-x 13 www-data www-data   4096 Apr 23 09:05 lib
drwxr-xr-x  2 www-data www-data   4096 Mar 23 09:52 maintenance
drwxr-xr-x 10 www-data www-data   4096 Mar 23 09:52 management
drwxr-xr-x  3 www-data www-data   4096 Mar 23 09:52 service
drwxr-xr-x  2 www-data www-data   4096 Mar 23 09:52 status
user@myserver:~$ grep FOG_VERSION /var/www/html/fog/lib/fog/system.class.php
        define('FOG_VERSION', '1.5.8');
```

**Comment by Sebastian-Roth** [comment]
@abulhol Looks good to me. The only difference I see to my test install is the directory `/var/www/html/fog/maintenance/` is still present on your system. The FOG installer is using that and should remove it afterwards. Maybe the installer didn't run through all the way?

Please take a look at `fogproject/bin/error_logs/` directory and post the last 20 lines of all the log files you find in there here.

**Comment by abulhol** [comment]
install.log:
``` * Resetting SSL Permissions...................................OK
 * Setting up Apache virtual host (no SSL).....................OK
 * Starting and checking status of web services................OK
 * Changing permissions on apache log files....................OK
 * Backing up database.........................................Failed

   We were not able to backup the current database! Just press
   [Enter] to proceed anyway or Ctrl+C to stop the installer.

 * You still need to install/update your database schema.
 * This can be done by opening a web browser and going to:

   http://192.168.0.2/fog/management

 * Press [Enter] key when database is updated/installed.
 * Update fogstorage database password.........................Failed!
```
● php7.2-fpm.service - The PHP 7.2 FastCGI Process Manager
   Loaded: loaded (/lib/systemd/system/php7.2-fpm.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2020-03-23 09:52:37 CET; 2s ago
     Docs: man:php-fpm7.2(8)
 Main PID: 1656 (php-fpm7.2)
   Status: "Ready to handle connections"
    Tasks: 6 (limit: 4915)
   CGroup: /system.slice/php7.2-fpm.service
           ├─1656 php-fpm: master process (/etc/php/7.2/fpm/php-fpm.conf)
           ├─1679 php-fpm: pool www
           ├─1682 php-fpm: pool www
           ├─1684 php-fpm: pool www
           ├─1685 php-fpm: pool www
           └─1686 php-fpm: pool www

Mar 23 09:52:37 jbxs2c-relay systemd[1]: Starting The PHP 7.2 FastCGI Process Manager...
Mar 23 09:52:37 jbxs2c-relay systemd[1]: Started The PHP 7.2 FastCGI Process Manager.
--2020-03-23 09:52:39--  http://192.168.0.2//fog//maintenance/backup_db.php
Connecting to 192.168.0.2:80... connected.
HTTP request sent, awaiting response... 500 Internal Server Error
2020-03-23 09:52:40 ERROR 500: Internal Server Error.

mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1142 (42000) at line 1: INSERT, UPDATE command denied to user 'fogstorage'@'localhost' for table 'globalSettings'
```

**Comment by Sebastian-Roth** [comment]
@abulhol Ahh, here we go. I am not sure why the backup failed. Not too much of an issue I would say. But the "Update fogstorage database password" failure is definitely a problem because the setup did not finish to the end.

Did you run the installer like this? `./installfog.sh -y` (don't ask questions)

Can you please upload the full fog_error_1.5.8.log here (or to a file share)?

**Comment by abulhol** [comment]
Done by email

**Comment by Sebastian-Roth** [comment]
@abulhol Thanks. Nothing too obvious in the log. I wanted to make sure there is no "technical" issue with running mysql commands on your system.

So also it doesn't seem you ran into an issue we had with Ubuntu 18.04 when the installer is run with `-y` command line option. But I still think it might be related to database issue.

Please take a look at the database connection settings in PHP config:
```
shell> grep DATABASE /var/www/html/fog/lib/fog/config.class.php
```
as well as in the FOG installer settings file:
```
shell> grep snmysql /opt/fog/.fogsettings
```
Compare those and make sure they match. Then try connecting to the database using those credentials:
```
shell> mysql -u fogmaster -p fog
Password:
...
mysql> quit
```
As well you might want to try to connect to the database via DB root account to make sure you still have access to that:
```
shell> mysql -u root -p fog
Password:
...
mysql> quit
```

**Comment by abulhol** [comment]
The DB connection settings match in the two files, i.e. they both list the same username `fogstorage` and password. 
I don't see a user `fogmaster` in those files, but I noticed that in my MySQL `user` DB, there is such a user:
```
mysql> select user, host from mysql.user;
+------------------+-----------+
| user             | host      |
+------------------+-----------+
| fogstorage       | %         |
| debian-sys-maint | localhost |
| fogmaster        | localhost |
| mysql.session    | localhost |
| mysql.sys        | localhost |
| root             | localhost |
+------------------+-----------+
```
Does that play a role?

**Comment by Sebastian-Roth** [comment]
@abulhol said:
> The DB connection settings match in the two files, i.e. they both list the same username `fogstorage` and password.

I think we found what is causing this. This is what we should have in a default installation in `/opt/fog/.fogsettings`:
```
snmysqluser='fogmaster'
snmysqlpass='...'
snmysqlhost='localhost'
```

This is new in FOG 1.5.8 where before we had used the `root` DB user for database connection. I have no idea how this could happen. You sure you don't have a storage node setup in front of you? `grep installtype /opt/fog/.fogsettings`

So first I suggest you check to see if you can connect to the DB using the DB root account:
```
shell> mysql -u root -p fog
Password:
...
mysql> quit
```
If not, then you need to [reset the DB root password](https://hostadvice.com/how-to/how-to-reset-a-mysql-root-password-on-ubuntu-18-04/) (watch out, spaces in the commands given might be missing). If you can connect to the DB via root on the command line I ask you update `/opt/fog/.fogsettings` and set `snmysqluser='fogmaster'` and then re-run the FOG installer to take care of it.

**Comment by Sebastian-Roth** [comment]
Depending on MySQL version the given tutorial might not work as expected. Try [this one](https://devanswers.co/how-to-reset-mysql-root-password-ubuntu/) of the other commands don't work as expected.

**Comment by Sebastian-Roth** [comment]
@abulhol Sorry, just forgot, you need to re-set the `fogmaster` DB password as well I would think. It got lost somewhere along the way I would think.

**Comment by abulhol** [comment]
I think I see the reason why this happened. 
We indeed don't run a storage node here (`grep installtype /opt/fog/.fogsettings` outputs `installtype='N'`). 
But when we updated, we mistook this here:
```
   The current fogstorage database password does not meet high
   security standards. We will generate a new password and update
   all the settings on this FOG server for you. Please take note
   of the following credentials that you need to manually update
   on all your storage nodes' /opt/fog/.fogsettings configuration
   files and re-run (!) the FOG installer:
```
which does not apply to our node. 
The `.fogsettings` file currently actually contains an `snmysqluser` entry for "root" (with an empty password), and the `fogstorage` user entry with a password. 
Is it enough if I remove the root entry and replace the `fogstorage` with `fogmaster` and a new password in this file + /var/www/html/fog/lib/fog/config.class.php?
Or do I necessarily have to re-run the installer?

**Comment by Sebastian-Roth** [comment]
@abulhol You can edit /var/www/html/fog/lib/fog/config.class.php manually but it will be overwritten whenever you upgrade to the next version (or re-run the current installer). I would suggest you only edit /opt/fog/.fogsettings and let the installer do it's job because otherwise we can't make sure it won't break on the next upgrade again!

Please remove the manually added lines in /opt/fog/.fogsettings and re-run the installer. It should actually get things right for you I reckon!

**Comment by abulhol** [comment]
Awesome, re-running the installer fixed things, and now I can add hosts in the web UI!
Thank you for all the help and your patience!
