### ISSUE TITLE
Partition won't extend after deployment

### ISSUE THREAD

**Issue by Fossil01** [FOGProject/fogproject#382]
Hi,

I'm trying to deploy an Ubuntu image to clients. The SSD is 120GB and the main partition is shrunk to 5GB by FoG when capturing the image. All Good.

Then when I deploy the image it says after Partclone ran that it extended the partitions but after boot I am still left with a 5GB partition and 115-ish GB of free space.

It does show one error before Partclone starts:
inotify_add_watch failed: No such file or directory

See these images:

https://imgur.com/a/scFwogc

**Comment by Sebastian-Roth** [comment]
@Fossil01 Can you please post the contents of the three text files `d1.partitions`, `d1.minimum.partitions` and `d1.fixed_size_partitions` here. Find all those three in the image directory on your FOG server.

**Comment by Fossil01** [comment]
Will have a look when I am in the office tomorrow. The disk type might change sometime so thats why I need the resizable option.

I am using fogproject-1.5.8

**Comment by Fossil01** [comment]
So I re-installed Ubuntu today, just threw everything into one root partition (doesn't really matter anyway for these machines) and made a new image. It looks like everything works now.

Not sure what /dev/sda2 is doing in here (has nothing to do with FoG) but it works. This is after deploying:

```
Disk /dev/sda: 120.0 GB, 120034123776 bytes
255 heads, 63 sectors/track, 14593 cylinders, total 234441648 sectors
Units = sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disk identifier: 0x000c1f02

   Device Boot      Start         End      Blocks   Id  System
/dev/sda1   *        2048   226421247   113209600   83  Linux
/dev/sda2       226423294   234439167     4007937    5  Extended
/dev/sda5       226423296   234439167     4007936   82  Linux swap / Solaris
```

```
Filesystem      Size  Used Avail Use% Mounted on
udev            1.9G  4.0K  1.9G   1% /dev
tmpfs           378M  588K  377M   1% /run
/dev/sda1       107G  2.4G   99G   3% /
none            4.0K     0  4.0K   0% /sys/fs/cgroup
none            5.0M     0  5.0M   0% /run/lock
none            1.9G     0  1.9G   0% /run/shm
none            100M     0  100M   0% /run/user
```
