### ISSUE TITLE
srvsize in API is 0

### ISSUE THREAD

**Issue by abulhol** [FOGProject/fogproject#384]
I am keeping several images for one machine. 
I am using the following API:
`http://<ip>/fog/image/<X>`
to check if image X exists and has been captured. 
For my initial image which I captured manually, the `srvsize` is reported correctly, e.g. "12332950246". 
However, for my other images which I captured using the API, the `srvsize` always stays "0".

**Comment by abulhol** [comment]
By the way, this is a Windows 10 machine with "Multiple Partition Image - Single Disk (Not Resizable)".
Also, I don't understand which information `srvsize` responds to in the UI.

**Comment by Sebastian-Roth** [comment]
@abulhol said:
> However, for my other images which I captured using the API, the srvsize always stays "0".

That's interesting. Which API call do you use to create the image? The image size **on server** is being updated by FOGImageSize service. You might need to restart this services to recognize the newly created images: `systemctl restart FOGImageSize`

> Also, I don't understand which information srvsize responds to in the UI.

It's turned off by default. Go to FOG Configuration -> FOG Settings -> General Settings and enable **FTP IMAGE SIZE**. Then go back to the images listing in the web UI and you will see another column named "Image Size: ON SERVER". The later one is the size of the compressed image files on the server while on the other hand "ON CLIENT" means the size of all partitions (shrunken when resizable) on the client.

**Comment by abulhol** [comment]
@Sebastian-Roth thx! 
Restarting the `FOGImageSize` service helps, the size is reported correctly afterwards. 
I capture images like so:
```
curl -X POST "http://<IP>/fog/host/<imageID>/task" -d '{"taskTypeID": 2}'
```

**Comment by Sebastian-Roth** [comment]
@abulhol Ahh good to hear it was only the size on server value in the DB not yet being updated. I think we can close this as fixed.
