### ISSUE TITLE
Snapin list - "Is Pack" always yes

### ISSUE THREAD

**Issue by vrelk** [FOGProject/fogproject#387]
If you are looking at the "All Snapins" page, everything is listed as "Yes" under the "Is Pack" column, even if it isn't a pack. (Ex. all my .bat files).
Version: 1.5.8

**Comment by Sebastian-Roth** [comment]
@vrelk Thanks for reporting! Just pushed a fix (1f5658b) to `dev-branch`. This will be in the next release. It's a fairly simple fix, so if you are keen to give it a try, just take a look at the commit and manually apply it to your FOG server.
