### ISSUE TITLE
Ubuntu 14.04 LTS support

### ISSUE THREAD

**Issue by robertsjw** [FOGProject/fogproject#39]
There are various problems with Ubuntu 14.04 LTS and Fog with tftp (noted here: https://wiki.fogproject.org/wiki/index.php/Ubuntu_14.04#Enabling_Root_on_Ubuntu).  Given that 14.04 is the most current LTS release for Ubuntu and is over a year old at this point, it would be nice to see support.

**Comment by cspenceiv** [comment]
I just had problems with tftpd-hpa on Debian 7.

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=771441

Looks like tftpd-hpa doesn't like "0.0.0.0:69" but likes ":69".

**Comment by cspenceiv** [comment]
Please edit /etc/default/tftpd-hpa to reflect this change. Otherwise, you can attempt testing the hardcore way and try the latest dev-branch commit eadae1b.

**Comment by robertsjw** [comment]
I made this change, but the host times out when trying to grab tftp://192.168.X.X/default.ipxe after booting.

**Comment by robertsjw** [comment]
I'm able to use tftp from another host on the network to grab default.ipxe just fine

**Comment by cspenceiv** [comment]
Considering issue closed. Turned out to be a tftpd-hpa configuration issue.
