### ISSUE TITLE
Registering accounts on Fog Forum not working.

### ISSUE THREAD

**Issue by shawnpaw** [FOGProject/fogproject#391]
I am trying to get help with our Fog instance. I attempted to create an account on the Fog forum to get help but the captcha is preventing me from creating an account. I tried Chrome and Firefox. No luck. Edge gives me the captcha where I choose the pictures that have specific things in the picture. Firefox and Chrome do not ask at all. Edge still won't let me create an account. This is probably not the right place to voice this issue, but maybe this can be passed along to someone who can fix the issue. I just need to get in so I can get some help with my Fog instance. Thanks.

**Comment by Sebastian-Roth** [comment]
@shawnpaw I've just tested registration captcha with Opera, Chrome and Firefox on Linux. All working fine. Can you please clear your browser cache and try again?

**Comment by shawnpaw** [comment]
No luck. I cleared caches. Tried incognito. Multiple browsers. I still get registration error captcha not verified, are you a robot?

Shawn

Get Outlook for Android<https://aka.ms/ghei36>

**Comment by Sebastian-Roth** [comment]
@mastacontrola We don't seem to have [new users registering over the last five days](https://forums.fogproject.org/users) (as of now) which seems quite unusual. Though I don't see anything obvious in the nodebb logs.

**Comment by Sebastian-Roth** [comment]
I've tried to figure out what's wrong and stumbled upon a possible issue with - (https://stackoverflow.com/questions/39853162/recaptcha-with-content-security-policy) as I got the following message in Chrome's web developers console:
```
Refused to load the script 'https://www.gstatic.com/recaptcha/releases
/ADnAC3ZykfbIOflWgrKNsVVT/recaptcha__en.js' because it violates the following
Content Security Policy directive: "script-src 'nonce-PaGQAeKtpP6b1QSJ2RkgSQ'
'unsafe-inline' 'strict-dynamic' https: http: 'unsafe-eval'". 'strict-dynamic'
is present, so host-based whitelisting is disabled.
```
But I don't think this is actually causing it to fail.

The actual error message "[Captcha not verified, are you a robot?](https://github.com/akhoury/nodebb-plugin-spam-be-gone/blob/master/library.js#L470)" stems from a anti-SPAM plugin we use in nodebb called spam-be-gone which is doing a great job as we'd have dozens of obvious fake registrations (e.g. from kimberley@yuji2310.daisuke36.gleella.buzz) **each day**! So we can't simply turn this off.

As I understand it we don't get a valid response to our captcha request which is using the [simple-recaptcha-new](https://www.npmjs.com/package/simple-recaptcha-new) module. Though I have no idea why that would be.

**Comment by Sebastian-Roth** [comment]
@shawnpaw We just switched to a different captcha mechanism. Please give it a try again.

**Comment by shawnpaw** [comment]
Thank you!!!! I am in. I appreciate you taking the time to help me register for an account. I hope to  become more involved in the community. Thank you again!

Shawn Ward
Windows Systems Admin
CAEDM – College of Engineering
801-422-8120

**Comment by shawnpaw** [comment]
I’m sorry to bother everyone again.

The FogProject site must not like me. I got the email to validate my email. I clicked the link. The site said I was successful at validating my email and that the validation of my email failed at the same time. Not sure how that works. Now when I log in it says my email was not validated and that I can’t chat or post until it is validated. Is there a way to generate a new email to validate my account? I looked and could not find a way in my profile or settings to send the email again. Thanks.

Shawn Ward
Windows Systems Admin
CAEDM – College of Engineering
801-422-8120

**Comment by mastacontrola** [comment]
I'm seeing your account as validated.

**Comment by shawnpaw** [comment]
Thanks. Maybe it just took a little time. I don’t see the message anymore that my email is not validated.

Shawn Ward
Windows Systems Admin
CAEDM – College of Engineering
801-422-8120

**Comment by Sebastian-Roth** [comment]
@shawnpaw Good to hear this has worked out. Closing the topic now. If you still can't post in the forums, let us know here.
