### ISSUE TITLE
FOG Forum Down?

### ISSUE THREAD

**Issue by mountbaldy** [FOGProject/fogproject#396]
Hello!

I realize this is meant for issues with the FOG project, but I noticed I cannot access the FOG Forum.  I tried accessing on two different networks and it fails.  I cannot ping fogproject.org either.  

Just thought I would share!

Cheers,

Joe

**Comment by dgilloch** [comment]
I am having the same issues!

**Comment by Sebastian-Roth** [comment]
@mountbaldy @dgilloch As you all see fogproject.org is is currently down. Sorry for this! We are working on getting it back online. Will keep you posted here.

**Comment by eduardotseoane** [comment]
Ok, thx, but can be enabled the web dirs where are stored the downloading requests on installation? we are on a reinstalling process and it fails continuosly because cant find some  binaries to download...

**Comment by unknownuser26** [comment]
> 
> 
> Ok, thx, but can be enabled the web dirs where are stored the downloading requests on installation? we are on a reinstalling process and it fails continuosly because cant find some binaries to download...

I have the same problem ...

**Comment by Unknown-0** [comment]
I have the same issue, but i have made an install few days ago.
You can bypass the problem by comment de line 2352 to 2394 in the  fogproject-master/lib/common/functions.sh file
And place the files in this zip to  fogproject-master/tmp/
https://drop.infini.fr/r/_0199deers#udBtWl91rpI22CeRM9vUE2uM8YnS9sKGSzLjNqVGQV0=
I hope this can help you

**Comment by mastacontrola** [comment]
While we work to get the site backup, please use the following link for the binaries:

1.5.9-RC1 = https://github.com/FOGProject/fogproject/releases/download/1.5.9-RC1/binaries1.5.9.zip

1.5.8 = https://github.com/FOGProject/fogproject/releases/download/1.5.8/binaries1.5.8.zip

**Comment by redebeer** [comment]
thank you kindly for above info!

**Comment by natespcrepair** [comment]
i ma doing a new install of fog how do i add the binaries to get this working

**Comment by mountbaldy** [comment]
@mastacontrola @Sebastian-Roth Thanks for getting this resolved!
