### ISSUE TITLE
 Offline Site, files needed for fog

### ISSUE THREAD

**Issue by alhack90** [FOGProject/fogproject#397]
Good evening, I noticed now that the site is down and also the downloads, it is possible to make at least momentarily available all the files necessary for the fog including init.xz.
Thanks so much.

**Comment by Sebastian-Roth** [comment]
@alhack90 Take a look at this topic: https://github.com/FOGProject/fogproject/issues/396

mastacontrola posted links where you can download the kernel and init binaries as archive.

Please join the discussion in the other topic. Closing this now.
