### ISSUE TITLE
I can't install fog

### ISSUE THREAD

**Issue by RedPill-linux** [FOGProject/fogproject#398]
I'm using Fedora 32 x64
When I try to install fog, I get this log after: 
Attempting to get release information.......................Done

![Captura de tela de 2020-07-27 11-14-04](https://user-images.githubusercontent.com/60233944/88552454-7df1e580-cffa-11ea-9192-08d924ceaa3b.png)

**Comment by Sebastian-Roth** [comment]
@RedPill-linux Sorry for the late response. We are flat out with other projects at the moment. FOG from the working-1.6 branch should install just fine on Fedora. See our automated installer tests here: http://fogtesting.theworkmans.us/
