### ISSUE TITLE
Feature Request: Quick Host Registration to autojoin AD

### ISSUE THREAD

**Issue by lukebarone** [FOGProject/fogproject#400]
Quick Host Registration should be able to join Active Directory with the default settings.

Currently, I need to add them all to a group, and constantly tell the group to join the domain.

**Comment by Sebastian-Roth** [comment]
@mastacontrola @George1422 What do you think?

**Comment by George1422** [comment]
I'm not sure I fully understand the request. Is this to add AD connection information to the host table during quick registration? If so how if you had multiple domains or OUs would you select which one? Would the persistent group setting plugin work the same to apply the AD settings to the host as its added to the database?

**Comment by lukebarone** [comment]
In my experience (I only started using Quick Host Registration a couple weeks ago when another team member showed me the feature), I have to specify the computer name and image _anyways_, and choose the group for the new computers. There is no option on the settings page to have it automatically join the AD domain using default settings, like with Full Host Registration.

Group settings do no appear to be retroactive - they are snapshots of settings sent to the hosts. For example, if I tell the group **NewComputers** to join AD, only the computers in that group will get that setting applied, then the group forgets about it. If I add more computers to NewComputers (i.e. through Quick Host Registration, or Full Host Registration, but choose not to join AD during this step), then it will not get the settings in the group to join the domain.

My proposal is to add the same option that would appear in Full Host Registration, which is a simple Y/n question, to the Quick Host Registration page.

**Comment by George1422** [comment]
Actually this appears to be easier to do as a one off then expected. No real changes needed to the FOG code, a quick tweak is needed to FOS Linux registration code. Understand this hasn't been tested but its something that you can do on your own (the beauty of FOSS). 

You didn't mention the version of FOG you are using, but assuming you are using the latest release 1.5.8 you can download this file: https://github.com/FOGProject/fos/blob/master/Buildroot/board/FOG/FOS/rootfs_overlay/bin/fog.auto.reg

use notepad++ to edit the file or use a linux editor (don't use windows notepad). 

 insert at line 65

`askme=""
while [[ -z $askme ]]; do
    echo -n "    Would you like this host to join a domain, (using default settings)? (y/N) "
    read askme
    case $askme in
        [Nn]|[Nn][Oo]|"")
            askme="N"
            ;;
        [Yy]|[Yy][Ee][Ss])
            blDoAD=$(echo -n 1 | base64)
            askme="Y"
            ;;
        *)
            askme=""
            echo " * Invalid input, please try again"
            ;;
    esac
done`

this line reference was before you inserted the above code, so you might want to edit this first then insert the above code. 
change line 73 from
`    res=$(curl -Lks --data "sysuuid=${sysuuid}&mac=$mac&productKey=${productKey}" ${web}service/auto.register.php 2>/dev/null)`

to this
`    res=$(curl -Lks --data "sysuuid=${sysuuid}&mac=$mac&productKey=${productKey}doad=${blDoAD}" ${web}service/auto.register.php 2>/dev/null)`

Use copy and paste and live happily. Now save this file and move it to the fog server. Here is a tutorial on how to hot add/patch FOS linux: https://forums.fogproject.org/topic/14278/creating-custom-hostname-default-for-fog-man-reg

This is instructions for creating a custom manual registration, but the concept is exactly the same to apply your custom fog.auto.reg file. 

Now when you pxe boot into FOS linux the post init script will copy over the fog.auto.reg file from the FOG server to the target computer before running it.
