### ISSUE TITLE
fog project 1.5.8 macOS Catalina error got an error clear block

### ISSUE THREAD

**Issue by vincentlioe** [FOGProject/fogproject#403]
wanted to do capture task on a 2015 22 inch imac.
I used exactly the guide from this fos-usb 2a guide.

https://forums.fogproject.org/topic/7727/building-usb-booting-fos-image/21?lang=en-US&page=2
 
got an error clear block xxxxxxxxxxxxxxxxxxxxx out of boundary(xxxxxxxxxx) while partclone is reading the AFPS partition

**Comment by Sebastian-Roth** [comment]
Same topic posted in the forums: https://forums.fogproject.org/topic/14734/clear-block-out-of-boundary

As I don't see much of a chance this can be solved within the FOG code I am closing this issue report here.
