### ISSUE TITLE
Can't fetch MAC addresses behind a proxy

### ISSUE THREAD

**Issue by mechalas** [FOGProject/fogproject#404]
Though FOG allows you to set a proxy server in the FOG configuration menu, the proxy is not used when you attempt to update the MAC list from the configuration page. The issue appears to be the use of fopen() to fetch the URL in [fogconfigurationpage.class.php](https://github.com/FOGProject/fogproject/blob/master/packages/web/lib/pages/fogconfigurationpage.class.php#L1926) without setting a context to define the proxy.

See [Using a proxy server with fopen](https://stackoverflow.com/questions/15285546/using-a-proxy-server-with-fopen)

**Comment by Sebastian-Roth** [comment]
@mechalas Thanks for reporting. Will look into this soon.

**Comment by Sebastian-Roth** [comment]
@mechalas Too bad I have lost track of this request when working on bringing out the new release. I just fixed the issue in the latest commit to `dev-branch` - cff7a50

You can either update to version 1.5.9.1 or manually apply the fix found in the commit diff linked above.

**Comment by Sebastian-Roth** [comment]
@mechalas Obviously wasn't paying full attention when doing this. I forgot to remove the fclose class - now fixed in 70ade00.
