### ISSUE TITLE
Updating database after image capture failed

### ISSUE THREAD

**Issue by jurgeng-ot** [FOGProject/fogproject#406]
Hi,

First thanks for the lovely project. We've been managing our laptops for over a year now successfully.

I have moved our fog server to the cloud so that we can manage end users independent of their location. Also I upgraded from 1.5.7 to 1.5.9.

The existing fog clients connect fine (without reconfiguration) to the new fog server and I can do tasks like roll out snapins or manage printers.

For my office environment I want to have a local storage server to speed up imaging and to avoid having pxe/tftp/nfs etc running via the internet.

I set up a local storage server according to the documentation and made sure that it can connect mysql on the fog server. This goes fine.

I then tested by deploying an image, that also goes well.

But when capturing an image, I get errors after capturing.
The image is captured and stored on the fog storage server in the office: I see under /images/dev an new directory with the mac address and image data written to it, but after the imaging, I get an error:

(this is typed over from a screenshot)
`Updating database.................................Failed
* Error returned: Type 1024, File: /var/www/html/fog/lib/fog/fogftp.class.php, Line: 219, Message: FTP connection failed, Host: 192.168.101.7, Username: fogproject'
* Reattempting to update database..............Failed`
and this repeats a number of time.

The storage server indeed lives in 192.168.101.7 and I am doing the image capture and tests from the same local subnet.

According to the documentation, I checked with an FTP client on anoter machine if I can access the FTP server on the storage server, go to /images, write and delete a file. This works.

I checked passwords in /opt/fog/.fogsettings and compared them to the Fog Web UI, but all passwords and usernames seem to be correct. Also tried to log in with the fogproject username and the password. That works (I get the notice that it's not recommended to use this account).

Do you have any clue?

**Comment by mastacontrola** [comment]
Have you tried connecting using the username/password over FTP?

What OS are you using?

Have you checked firewall/selinux?

**Comment by Sebastian-Roth** [comment]
@jurgeng-ot The error message `Message: FTP connection failed, Host: 192.168.101.7, Username: fogproject'` is not the one we usually see when there is a credential issue. I would think there might be a real connection issue. Have you tried the FTP connection from that very same machine yet? What about passive vs. active FTP? Which one did you try?

**Comment by jurgeng-ot** [comment]
I am using Centos 7 for all hosts.
I have checked firewalld, iptables and selinux: all are off.
I have tried passive and active FTP from another host on the same network, as well as from the same host:
- cd /images
- put somefile
- ls (check)
- delete somefile
- ls (check)
All works fine.

I had enabled logging on vsftpd and noticed this:
- client boots up from the network
- an FTP session is started:

Mon Sep 28 17:19:48 2020 [pid 39401] CONNECT: Client "192.168.101.7"
Mon Sep 28 17:19:48 2020 [pid 39401] FTP response: Client "192.168.101.7", "220 (vsFTPd 3.0.2)"`

- The client writes it's image to /images/dev/mac address (this goes of course via nfs)
- After writing the image I get the error message on the client. No other activity in VSFTPD.

What I have changed on the original configuration is that I have moved the /images directory to /data/images and created a symlink on /images. Don't know if that might cause issues, but I'm not seeing evidence that this could cause trouble.

**Comment by Sebastian-Roth** [comment]
@jurgeng-ot Good you mentioned the symlink. While I have not tested yet I could imagine this causing the issue. Though on the other hand the error message seems strange I would ask you to try the following using a standard FTP client:

* Connect to FOG server
* Create dir /images/dev/abcdef123456
* Upload a binary file (not happening through FTP usually but for a test it's still good to have a file in that dir as well)
* Move directory /images/dev/abcdef123456 to /images/imagename

**Comment by jurgeng-ot** [comment]
I reinstalled the fog storage server as it did not seem to get past a reboot. Don't know what broke it..
After a standard installation, I installed the fog storage server again and I left the images on /image. No symlinks.

Tried uploading an image again, but still the same error.

I tried your FTP action, all went fine, except for the last step. I was unable to move the whole directory with FTP:
`
jurgengoedbloed@onetrail-jg:~$ ftp 192.168.101.7
Connected to 192.168.101.7.
220 (vsFTPd 3.0.2)
Name (192.168.101.7:jurgengoedbloed): fogproject
331 Please specify the password.
Password:
230 Login successful.
Remote system type is UNIX.
Using binary mode to transfer files.
ftp> cd /images
250 Directory successfully changed.
ftp> cd dev
250 Directory successfully changed.
ftp> mkdir abcdef123456
257 "/images/dev/abcdef123456" created
ftp> cd abcdef123456
250 Directory successfully changed.
ftp> lcd /home/jurgengoedbloed/temp
Local directory now /home/jurgengoedbloed/temp
ftp> put capture
local: capture remote: capture
200 PORT command successful. Consider using PASV.
150 Ok to send data.
226 Transfer complete.
4701 bytes sent in 0.00 secs (9.1308 MB/s)
ftp> cd /images
250 Directory successfully changed.
ftp> cd dev
250 Directory successfully changed.
ftp> ls
200 PORT command successful. Consider using PASV.
150 Here comes the directory listing.
drwxrwxrwx    2 0        0            4096 Sep 30 08:34 28f10e311606
drwxr-xr-x    2 1005     1005         4096 Sep 30 08:46 abcdef123456
drwxrwxrwx    2 1005     0            4096 Sep 30 08:26 postinitscripts
226 Directory send OK.
ftp> mv abcdef123456 /images/test
?Invalid command
ftp> rename /images/test/abcdef123456 /images/test
550 RNFR command failed.
`
although manually create a directory and move the file works:
`
ftp> mkdir /images/test
257 "/images/test" created
ftp> cd /images/test/abcdef123456
550 Failed to change directory.
ftp> cd /images/dev/abcdef123456
250 Directory successfully changed.
ftp> rename capture /images/test/capture
350 Ready for RNTO.
250 Rename successful.
`

It seems that after the imaging only this action fails. When I capture the image and afterwards, as root in a shell, move the directory manually:
`
mv /images/dev/28f10e311606 /images/win10prouk
`
and then deploy this image, this works fine.

Hope this gives a clue.

BTW: as I am now able to capture an image with a workaround, this has become less urgent. No need to rush :-)

**Comment by Sebastian-Roth** [comment]
@jurgeng-ot Looking through the whole message again and again I found this:
```
....
ftp> mkdir abcdef123456
257 "/images/dev/abcdef123456" created
...
ftp> rename /images/test/abcdef123456 /images/test
550 RNFR command failed.
```
That one probably fails because /images/dev/abcdef123456 is not /images/test/abcdef123456.

> BTW: as I am now able to capture an image with a workaround, this has become less urgent.

Sure the manual rename/move does work but it'd still be interesting to figure out why this fails in your case.

Please run `ls -al /images/` and `mount` on your FOG server and post output here.

**Comment by jurgeng-ot** [comment]
@Sebastian-Roth  You are right, the rename command was bad.

Tested again with the right FTP commands:

ftp> mkdir /images/dev/abcdef123456
257 "/images/dev/abcdef123456" created
ftp> cd /images/dev/abcdef123456
250 Directory successfully changed.
ftp> put capture
local: capture remote: capture
200 PORT command successful. Consider using PASV.
150 Ok to send data.
226 Transfer complete.
20480 bytes sent in 0.00 secs (275.0880 MB/s)
ftp> cd /images
250 Directory successfully changed.
ftp> rename /images/dev/abcdef123456 /images/test2
350 Ready for RNTO.
250 Rename successful.
ftp> ls /images
200 PORT command successful. Consider using PASV.
150 Here comes the directory listing.
drwxrwxrwx    3 1005     0            4096 Oct 05 10:52 dev
drwxrwxrwx    2 1005     0            4096 Sep 30 08:54 postdownloadscripts
drwxr-xr-x    2 1005     1005         4096 Oct 05 10:51 test2
drwxrwxrwx    2 1005     0            4096 Sep 30 09:09 testje
drwxrwxrwx    2 1005     0            4096 Sep 30 09:19 win10prouk
226 Directory send OK.
ftp> quit
221 Goodbye.

I have moved the /images directory to /data/images, so that it is according to our company standards. Updated /etc/exports, /opt/fog/.fogsettings and reran the installer. Tested with deploying an image, that works fine.

An ls -al /data/images shows this:

[root@office-fogstorage images]# ls -al /data/images/
total 28
drwxrwxrwx. 7 fogproject root       4096  5 okt 12:52 .
drwxrwxrwx. 5 root       root       4096 30 sep 11:16 ..
drwxrwxrwx. 3 fogproject root       4096  5 okt 12:52 dev
-rwxrwxrwx. 1 fogproject root          0 30 sep 10:26 .mntcheck
drwxrwxrwx. 2 fogproject root       4096 30 sep 10:54 postdownloadscripts
drwxr-xr-x  2 fogproject fogproject 4096  5 okt 12:51 test2
drwxrwxrwx. 2 fogproject root       4096 30 sep 11:09 testje
drwxrwxrwx  2 fogproject root       4096 30 sep 11:19 win10prouk

(the test2 directoy is there from the FTP test above).

Output of mount command: 

[root@office-fogstorage images]# mount
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
devtmpfs on /dev type devtmpfs (rw,nosuid,size=929560k,nr_inodes=232390,mode=755)
securityfs on /sys/kernel/security type securityfs (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
tmpfs on /run type tmpfs (rw,nosuid,nodev,mode=755)
tmpfs on /sys/fs/cgroup type tmpfs (ro,nosuid,nodev,noexec,mode=755)
cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/usr/lib/systemd/systemd-cgroups-agent,name=systemd)
pstore on /sys/fs/pstore type pstore (rw,nosuid,nodev,noexec,relatime)
cgroup on /sys/fs/cgroup/net_cls,net_prio type cgroup (rw,nosuid,nodev,noexec,relatime,net_prio,net_cls)
cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (rw,nosuid,nodev,noexec,relatime,cpuacct,cpu)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,nosuid,nodev,noexec,relatime,blkio)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,nosuid,nodev,noexec,relatime,memory)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,nosuid,nodev,noexec,relatime,hugetlb)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,nosuid,nodev,noexec,relatime,devices)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,nosuid,nodev,noexec,relatime,freezer)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,nosuid,nodev,noexec,relatime,perf_event)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,nosuid,nodev,noexec,relatime,pids)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,nosuid,nodev,noexec,relatime,cpuset)
configfs on /sys/kernel/config type configfs (rw,relatime)
/dev/mapper/rootvg-root on / type ext4 (rw,relatime,data=ordered)
/dev/mapper/rootvg-usr on /usr type ext4 (rw,relatime,data=ordered)
systemd-1 on /proc/sys/fs/binfmt_misc type autofs (rw,relatime,fd=26,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=11759)
debugfs on /sys/kernel/debug type debugfs (rw,relatime)
hugetlbfs on /dev/hugepages type hugetlbfs (rw,relatime)
mqueue on /dev/mqueue type mqueue (rw,relatime)
nfsd on /proc/fs/nfsd type nfsd (rw,relatime)
/dev/sda2 on /var type xfs (rw,relatime,attr2,inode64,noquota)
/dev/sda1 on /boot type ext4 (rw,relatime,data=ordered)
/dev/mapper/rootvg-tmp on /tmp type ext4 (rw,relatime,data=ordered)
/dev/mapper/rootvg-home on /home type ext4 (rw,relatime,data=ordered)
/dev/mapper/rootvg-appserver on /appserver type ext4 (rw,relatime,data=ordered)
/dev/mapper/rootvg-data on /data type ext4 (rw,relatime,data=ordered)
sunrpc on /var/lib/nfs/rpc_pipefs type rpc_pipefs (rw,relatime)
tmpfs on /run/user/994 type tmpfs (rw,nosuid,nodev,relatime,size=188228k,mode=700,uid=994,gid=992)

**Comment by Sebastian-Roth** [comment]
@jurgeng-ot said:
> I have moved the /images directory to /data/images, so that it is according to our company standards. Updated /etc/exports, /opt/fog/.fogsettings and reran the installer. Tested with deploying an image, that works fine.

But upload still fails I suppose?!

I would say we should try enable FTP logging as [described here](https://forums.fogproject.org/post/130241) and see what we can figure out this way.

**Comment by jurgeng-ot** [comment]
yes, that still fails.
I have enabled logging on vsftpd, but during the imaging I don't see any FTP activity, other than this:

Tue Oct  6 12:10:08 2020 [pid 11235] CONNECT: Client "192.168.101.7"
Tue Oct  6 12:10:08 2020 [pid 11235] FTP response: Client "192.168.101.7", "220 (vsFTPd 3.0.2)"
Tue Oct  6 12:10:17 2020 [pid 11241] CONNECT: Client "192.168.101.7"
Tue Oct  6 12:10:17 2020 [pid 11241] FTP response: Client "192.168.101.7", "220 (vsFTPd 3.0.2)"
Tue Oct  6 12:10:18 2020 [pid 11243] CONNECT: Client "192.168.101.7"
Tue Oct  6 12:10:18 2020 [pid 11243] FTP response: Client "192.168.101.7", "220 (vsFTPd 3.0.2)"
Tue Oct  6 12:10:27 2020 [pid 11297] CONNECT: Client "192.168.101.7"
Tue Oct  6 12:10:27 2020 [pid 11297] FTP response: Client "192.168.101.7", "220 (vsFTPd 3.0.2)"
Tue Oct  6 12:10:28 2020 [pid 11299] CONNECT: Client "192.168.101.7"
Tue Oct  6 12:10:28 2020 [pid 11299] FTP response: Client "192.168.101.7", "220 (vsFTPd 3.0.2)"

But this seems to be a local service on the fog storage reaching it's own FTP server.
So it seems that the client is not doing any FTP activity at all or is trying a different server.
I can set up a network sniffer to capture client traffic but that will take a day or two.

**Comment by Sebastian-Roth** [comment]
@jurgeng-ot It's correct, the FTP connection is local only. The scripts on the capturing client send a request to the web server running on the FOG server. The PHP code then opens a FTP connection to rename/move the files.

**Comment by Sebastian-Roth** [comment]
@jurgeng-ot Did you get a chance to look into this again. I am very keen to hear if you figured it out.

**Comment by jurgeng-ot** [comment]
No, not yet. I expect to test it next week. As this is not a confirmed bug it's OK if we move this topic to the forums, if you want issues in github only for bugs.

**Comment by Sebastian-Roth** [comment]
@jurgeng-ot We don't have this as strict using issues on github only for bugs. Now that we have it all here on github it's not worth moving it all to the forums I find.

**Comment by jurgeng-ot** [comment]
At last I was able to capture the error with wireshark. I have attached the file.
[capture.zip](https://github.com/FOGProject/fogproject/files/5445850/capture.zip)

the first packets in the capture are the last bits of the uploading of the image (192.168.101.111 is the client, 192.168.101.7 is the local fog storage)
Then you'll see at the end a series of connections made to the fog server (185.170.6.24) from the client (192.168.101.111)

In the capture I'm seeing this response from the fog server 'Message: FTP connection failed, Host: 192.168.101.7, Username: fogproject' (the same as the error on the console). Does that mean that the **fog server** is trying to access the fog storage on FTP? Because that is something I do not have open at the moment in the firewall.

**Comment by Sebastian-Roth** [comment]
@jurgeng-ot Oh my..... I am really sorry but missed the point where you said that your (main) FOG server has moved to the cloud but the storage is in the local subnet. Now that I saw the packet capture with the official IP it hit me.

To answer your question: Yes the FOG server needs to FTP to the storage to move the captured image folder.

Sure this is not going to work unless you have a VPN tunnel setup so the cloud server can FTP to the private IP of your storage.

Too bad FOG wasn't made for such a setup. We are talking about getting rid of the FTP stuff and using SSH commands in FOG 1.6 but that's still some way down the road and you'd still need a port forwarding to allow SSH connection from your cloud server to the internal (192.168.101.7) storage IP.

I guess in your case it's best you manually modify FOG to not attempt to do the image moving and instead just do it yourself. Edit `/var/www/html/fog/lib/reg-task/taskqueue.class.php` and comment [line 447 and 448](https://github.com/FOGProject/fogproject/blob/master/packages/web/lib/reg-task/taskqueue.class.php#L447) to make it look like this:
```
...
            if ($this->Task->isDeploy()) {
                self::$Host
                    ->set('deployed', self::niceDate()->format('Y-m-d H:i:s'));
                $this->_email();
//            } elseif ($this->Task->isCapture()) {
//                $this->_moveUpload();
            }
            $this->Task
                ->set('pct', 100)
                ->set('percent', 100)
                ->set('stateID', self::getCompleteState());
...
```

**Comment by jurgeng-ot** [comment]
@Sebastian-Roth Thanks and no worries. This is a sort of exotic setup.
We don't make much images, I guess only one each year. So a few extra steps are not much work given the fact that FOG already saves us much hours.
