### ISSUE TITLE
Hangs on installation

### ISSUE THREAD

**Issue by vipconsult** [FOGProject/fogproject#41]
new debian wheezy and latest git pull hangs on

Downloading New FOG Client file

I have traced it down to the mysql connect funciton.

Mysql class $this->connect()  seems to hang and it doesn;t allow the script to continue

**Comment by cspenceiv** [comment]
Thanks for the help. We've been tracking this one down for a bit.

**Comment by vipconsult** [comment]
It must be the  php-mysqlnd driver

I installed the php-mysql and it doesn't hang.

**Comment by vipconsult** [comment]
just tried it today and the installations seems fixed
