### ISSUE TITLE
Kernel version displayed?

### ISSUE THREAD

**Issue by imasupersadpanda** [FOGProject/fogproject#417]
While trying to get an endpoint to PXE boot and apply our image, I ended up trying multiple kernel versions before finding one that worked with the new model of Dell Precision 3240 desktop I was deploying (installing them via them through **Fog Configuration** > **Kernel Update**). Is there a way to display precisely which kernel is installed on my Fog server so I can relay that info to others on my team? 

Note: **Fog Configuration** > **Home** > **Kernel Versions** shows nothing:
 ![Screenshot from 2021-01-08 09-07-26](https://user-images.githubusercontent.com/51414781/104030716-6b76fd00-5191-11eb-9acd-20dd792525a6.png)

**Comment by George1422** [comment]
Yes there is an absolute way to confirm. From the fog server linux console change to /var/www/html/fog/service/ipxe directory

In that directory key in file bzImage   it will display the kernel version. 

What  is more confusing is why do you need different kernel versions here? I would be sure to install the linux kernel 5.6.18 so you get the latest hardware support.

**Comment by Sebastian-Roth** [comment]
Closing the issue as we haven't heard back in over a month.
