### ISSUE TITLE
IP address change breaks some components notably snapins FTP settings

### ISSUE THREAD

**Issue by Arrowana** [FOGProject/fogproject#419]
I finished FOG setup and everything seemed alright, after a reset i noticed that links in the management like http://x/fog/management/index.php?node=client had the wrong address, IP address y instead of IP x.

So I followed https://wiki.fogproject.org/wiki/index.php/Change_FOG_Server_IP_Address
Doing all the required changes fixed the link above, i am faced with one last spot that doesn't seem to follow, while trying to create a snapin following https://docs.fogproject.org/en/latest/management/snapin-management.html?highlight=snapin
When clicking add I get an error message:
"Type: 1024, File: /var/www/fog/lib/fog/fogftp.class.php, Line: 219, Message: FTP connection failed, Host: x.y.z, Username: fogproject"

"x.y.z" is the original IP address not the new one I have setup, so it appears like the procedure to change IP address is not complete and leaves the system broken, at least for snapins upload.

**Comment by Arrowana** [comment]
Ok, my mistake, I found out through the code that the host comes from the storage node ip. https://github.com/FOGProject/fogproject/blob/171d63724131c396029992730660497d48410842/packages/web/lib/service/fogservice.class.php#L525

Which I did not change, after changing it, problem fixed.
However, could this be less obscure for a single server setup?

**Comment by Sebastian-Roth** [comment]
@Arrowana said:
> However, could this be less obscure for a single server setup?

With less obscure you probably mean that the IP change needs to be done in several files as well as the database (web UI)!? FOG combines several components and grew over time resulting in a complex "web" of settings to make things work. We try to document what needs to be done when changing the FOG server IP.

If you are keen to streamline this part of FOG you are more than welcome to join the team and work on it.

**Comment by Arrowana** [comment]
> With less obscure you probably mean that the IP change needs to be done in several files as well as the database (web UI)
The file change + web UI is fine to me. My pain comes from the fact that I followed the wiki but still ended up with an incomplete transition to a new IP.

I am not sure what is the right way to go here, but its seems like the minimum would be to an addition to the wiki so that we do not leave this part out.

**Comment by Sebastian-Roth** [comment]
@Arrowana It might not be as clear as I think it is but changing the storage node IP is mentioned in the [wiki article](https://wiki.fogproject.org/wiki/index.php/Change_FOG_Server_IP_Address):
> Update the IP address for the storage node on the FOG system where you changed the IP address _Web Interface -> Storage Management_

If you think this is inappropriate you might have a better way of phrasing things. You are more than welcome to post text changes here. Thought about giving you write access to the wiki as well but we are in the process of moving all the content to [readthedocs](https://docs.fogproject.org/en/latest/). Would you be keen to help us working on that?

**Comment by Arrowana** [comment]
@Sebastian-Roth you are right, it is already written. I missed it being unfamiliar with all components. Should i port the existing "Change FOG server IP address" doc to [readthedocs ](https://docs.fogproject.org/en/latest/)?

**Comment by Sebastian-Roth** [comment]
@Arrowana You should have received an invite for the [fog-docs repo](https://github.com/FOGProject/fog-docs) where we manage the stuff for readthedocs. Would be great if you'd work on converting the old wiki article.

**Comment by Sebastian-Roth** [comment]
@Arrowana Thanks for this! Github didn't inform me about this so I didn't see it until now. You are more than welcome to help moving more of the documentation to readthedocs.

Closing this issue now.
