### ISSUE TITLE
could not mount images folder /bin/fog.download

### ISSUE THREAD

**Issue by cyrmoon** [FOGProject/fogproject#427]
hello, I had this mesage when i tried to apply a images on a pc. "could not mount images folder /bin/fog.download" So I reinstall a other fog with the export database and the images folder, but i have this message again.
I tried with debian 8 and 10 same result.
Any idea? Sorry if it was a precedent issue.

**Comment by Sebastian-Roth** [comment]
@cyrmoon In the error message you see an IP address. First make sure this is the correct IP address of your FOG server.

Do you have FOG installed on hardware or in a VM setup? I ask because with some environments (e.g. Proxmox) you need to do extra steps to enable NFS, which is used by FOG.

Are FOG server and the machine you want to deploy to in the same network subnet? Is there a firewall in between? Did you disable the Debian firewall?

**Comment by cyrmoon** [comment]
hello, It' a fog installed as a vm on proxmox; i have ip address (the ip addresses given by the dhcp server), the message is "XX.XX.XX.242:/images on images failed; Connection Timed out

All machines are on the same subnet, there is a fortigate on the network (but its worked before), and debian firewall is disabled.

![IMG_20210518_081848](https://user-images.githubusercontent.com/34964168/118601696-45eaa780-b7b2-11eb-9c3a-0416a2237bbb.jpg)

**Comment by Sebastian-Roth** [comment]
@cyrmoon Is 172.19.75.242 your FOG server IP?

You mention proxmox. Did you look into the extra steps you need to take to make NFS work in proxmox??

**Comment by cyrmoon** [comment]
No because it worked before, and fog was already on proxmox. But i ll see.

**Comment by Sebastian-Roth** [comment]
@cyrmoon The project you linked does not have anything to do with the FOG project we discuss here. Just a coincidence they use the same name as we do.

I have not used Proxmox myself in a long time. It used to be easier getting NFS to work but with newer versions it seems troublesome. It also depends on if you use OpenVZ or LXC. We have gathered information about this in the [Wiki](https://wiki.fogproject.org/wiki/index.php?title=Installation#LXC) but I am fairly sure it doesn't help with the latest version of Proxmox.

Your best bet is probably this forum post: https://forums.fogproject.org/topic/15176/fog-server-in-lxc-container-under-proxmox-6

**Comment by cyrmoon** [comment]
i ll take a look thnks.

**Comment by Sebastian-Roth** [comment]
@cyrmoon Anything we can still help you with or can we close the issue?

**Comment by cyrmoon** [comment]
Yes u can, it was in fact the Switch which had a sécurity configuration that block pxe.

Télécharger Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________
