### ISSUE TITLE
Current stable release (1.5.9) fails to install on Debian 11 (bullseye)

### ISSUE THREAD

**Issue by smonaica** [FOGProject/fogproject#429]
The OS-detection code in the installer does not recognize Debian 11 ("bullseye"), and so the installation fails on bullseye.

The issues appear to be two-fold:
1. The installer does not know about Debian version 11, so it does not know that PHP on bullseye is version 7.4. So many PHP packages fail to install.
2. Debian 11 no longer has the `php-gettext` package in its repository. The package `php-php-gettext` should be installed instead.

I have submitted a pull-request (#428) that I believe addresses these issues. 

I have tested the equivalent changes in a stable 1.5.9 tar file, and it works on bullseye. Bullseye is currently Debian Testing, but it is soon to be released as Stable, likely within a month or two.

Thanks for your time.

**Comment by Sebastian-Roth** [comment]
@smonaica Thanks for bringing this up and sending the pull request!

Currently we work in the branch called `dev-branch` to add this kind of fixes. @mastacontrola pushed some fixes to account for the gettext changes on Ubuntu in early May: https://github.com/FOGProject/fogproject/commits/dev-branch/lib/common

May I ask you to try out `dev-branch` and use that as a starting poing?

**Comment by smonaica** [comment]
Ok, I tried out the `dev-branch`. It looks like the commit from @mastacontrola has fixed the issue.

**Comment by Sebastian-Roth** [comment]
@smonaica Thanks again for bringing this up! Please let us know if you find other issues.

The FOG project is actually looking for people to help: https://forums.fogproject.org/topic/15371/fog-project-call-for-engagement

Looking forward to see you around!
