### ISSUE TITLE
Add the option to restore an image without host registration. 

### ISSUE THREAD

**Issue by vipconsult** [FOGProject/fogproject#43]
Most of our work involves restoring to single machines so having the ability to restore without host registration will save us a lot of time.

The wiki shows that this is possible , but it is quote outdated so I am not sure if it still functional with the latest release.

https://wiki.fogproject.org/wiki/index.php/Bypass_Host_Registration

anyway I will probably try it in the next few days , but I was wondering if this something that might be added in the core functionality or fog ?

**Comment by mastacontrola** [comment]
This already exists.

From the iPXE Menu, choose the quick image.  You will have to login with your fog gui login and password, but after it's verified you can select whichever image you want to send to the system whether it's registered or not.
