### ISSUE TITLE
Unable to deploy Image

### ISSUE THREAD

**Issue by SimoleS** [FOGProject/fogproject#430]
Hello guys, I'm trying to find a problem with this error last few days, but Im unable to find anything.
### Description
While trying to deploy the image. Particlone will throw an error **zstd: /*stdin*\ unsupported format read image hdr error=0** and exit code is **1 (writeImage)**

Thank you.

**Comment by Sebastian-Roth** [comment]
@SimoleS Which version of FOG do you use? Did you capture the image with this or an older version? Which compression algorithm is selected in the settings of this particular image you are trying to deploy?

**Comment by SimoleS** [comment]
@Sebastian-Roth We are using the latest version 1.5.9 and the image was taken with the latest version too. Regarding selected algorithm option is set to **Particlone zstd**.

**Comment by SimoleS** [comment]
@Sebastian-Roth Little Update. I tried every option in Image Manager, and nothing worked.  Mostly I got **skipping stdin unrecognized format**

**Comment by Sebastian-Roth** [comment]
@SimoleS Are you sure you have not changed from Zstd to Gzip or vice versa after capturing the image?

Please run the following command on your FOG server console/terminal/SSH and post results here:
```
file /images/IMAGENAME/d1p*
```
Instead of `IMAGENAME` put in the name of the image you want to deploy. This should tell us which compression algorithm was used to capture this image.

**Comment by SimoleS** [comment]
@Sebastian-Roth Here is output of command:

`d1p1.img: Zstandard compressed data (v0.8+), Dictionary ID: None
d1p2.img: data
d1p3.img: Zstandard compressed data (v0.8+), Dictionary ID: None
d1p4.img: data`

**Comment by Sebastian-Roth** [comment]
@SimoleS Intersting, the image file for partition one and three seem to be proper Zstd compressed files. Not so for partition two and four. So I guess it deploys the first partition (`/dev/sda1`) correct but then fails on the second one.

I don't think I have seen this happen ever before. I suggest you first check there is enough free space on that drive by running the command `df -h`. Then create a new image definition in the FOG web UI, assign that new image to the host you capture an image from and let it capture the image.

**Comment by Sebastian-Roth** [comment]
@SimoleS Is there anything we can help you with or did you get this solved?

**Comment by SimoleS** [comment]
@Sebastian-Roth Yes, sorry for my inactivity. Our cluster was in a bad state, so some files were wrongly synchronized, and files were corrupted.  

We weren't able to restore some Images. 

Thank you for your assistance. 

I'm closing this ticket.
