### ISSUE TITLE
[dev-branch] Login page still in English

### ISSUE THREAD

**Issue by bristow** [FOGProject/fogproject#432]
As I said on [this thread](https://forums.fogproject.org/post/143757) on the forum, the login page for the FOG interface is always in English, even if you change languages.

This page : 

![Login page](https://forums.fogproject.org/assets/uploads/files/1624309677495-s%C3%A9lection_796.png)

No problem with the stable version 1.5.9.

@Sebastian-Roth thinks it comes from these commits : 

- https://github.com/FOGProject/fogproject/commit/4e9c5a87ba3d938f06861c26cdd2f6e65ca1d812
- https://github.com/FOGProject/fogproject/commit/63a59e870674e619dd39d836c447a606ad2d5b2f
- https://github.com/FOGProject/fogproject/commit/c1cde2f1d0054d19566459e9bc7830519c186e61

Thanks !

**Comment by mastacontrola** [comment]
The default language is defined by the database entry. So, when you change your language from English to French in the Login UI, it's not going to change how the text is displayed until after login.

If you set the default language to french, for example, then when you log off, it should be in french as it's using that default database entry.

**Comment by bristow** [comment]
In fact, I don't have this behavior. I made a little anim gif :

![fog_locale_pb](https://user-images.githubusercontent.com/1156507/123449541-13677200-d5dc-11eb-814a-62e01a597f20.gif)

**Comment by Sebastian-Roth** [comment]
@mastacontrola Thanks for looking into this and fixing it.

@bristow Please test the latest dev-branch version and let us know.

**Comment by bristow** [comment]
Thanks @mastacontrola  for the work on the translation.

It's better but still not perfect.

Concerning the login page, I have to do an F5 to get back to French after a disconnection. Look at this animation: 

![fog_locale_pb2](https://user-images.githubusercontent.com/1156507/123546072-70d5fd00-d75b-11eb-985c-69c2f1285273.gif)

If it's too complicated to correct, it's not serious.

Concerning the translation of the menus, do I open a new issue or do I use this one or the forum?

**Comment by mastacontrola** [comment]
Waht do you mean? The menu's should be translated. Similarly, the login page should be translated as well. There's some minor tweaks I can do to try to fix this entirely, but they're not simple.

**Comment by mastacontrola** [comment]
I have updated so any of the `_( )` strings should now be translated properly. Not all items are translated because a lot of strings lie within the database itself. Not all the strings in the database are on the messages.po because of this. I would love to move all strings to a single file, but it does mean a lot of work to pull those fields out of each of the tables and into a single location, as well as changing out where those fields are pulled and output within the GUI.

**Comment by bristow** [comment]
Thanks for the last correction. The login page is now always in French :+1:  And we can close this issue if you want.

Concerning the menus, here are 2 weird things:

This menu is not translated (it is the only one), I think some strings must be missing _( ) :

![Sélection_999(017)](https://user-images.githubusercontent.com/1156507/123660709-2ffde700-d834-11eb-8d7a-5d5b090a628b.png)

Then, I don't know for this one, if it's in database or not (FOG System Settings in FOG Configuration) ?

 
![Sélection_999(018)](https://user-images.githubusercontent.com/1156507/123660912-5cb1fe80-d834-11eb-9294-16bcd0a82226.png)

**Comment by Sebastian-Roth** [comment]
Closing this as login page works now. Menu is discussed in #435
