### ISSUE TITLE
installation error on debian 11 bullseyes

### ISSUE THREAD

**Issue by fredericpetit02** [FOGProject/fogproject#433]
Hello,

FOG try to install php-gettext but on debian 11 it's php-php-gettext. Manual installation of php-gettext from debian 10 resolve temporary the issue.

**Comment by Sebastian-Roth** [comment]
@fredericpetit02 This is a known issue in FOG 1.5.9 - please use the latest `dev-branch` version on Debian 11. Find more details here: https://github.com/FOGProject/fogproject/issues/429
