### ISSUE TITLE
Fog1.5.9, the php-fpm.service service exited abnormally and could not be started

### ISSUE THREAD

**Issue by osxhu** [FOGProject/fogproject#436]
**OS / Environment**
System vesion:Centos 7.9

**Fog version**：fog v1.5.9

**Installation method**: 
use git command to pull package, and execute install script in Bin folder

**Problems encountered:**
php-fpm.service failed.: Process: 6418 ExecStart=/usr/local/php/sbin/php-fpm --nodaemonize --fpm-config /usr/local/php/etc/php-fpm.conf (code=exited, status=203/EXEC)

**Problem report summary:**
During the normal installation and execution process, I encountered the problem that the PHP FPM service could not be started after many attempts. I tried to uninstall the automatic installation of MariaDB database and php7.2.3, but the repeated installation still failed. The attachment is the complete installation log and error log. Thanks for the hard work of community developers, please help me complete the fog deployment. Thank you very much!

**[fog_error_1.5.9.log](https://github.com/FOGProject/fogproject/files/6748652/fog_error_1.5.9.log)
[foginstall.log](https://github.com/FOGProject/fogproject/files/6748653/foginstall.log)
**
![image](https://user-images.githubusercontent.com/18412762/124135987-eb35b280-dab6-11eb-822c-5ba7b899df8e.png)

**Comment by kibade** [comment]
This is the exact same issue I'm seeing today on Debian Bullseye and fog 1.5.9. What was the fix?

**Comment by Sebastian-Roth** [comment]
@kibade The current fix is to use FOG [dev-branch](https://github.com/FOGProject/fogproject/archive/refs/heads/dev-branch.zip).
