### ISSUE TITLE
[Workin-1.6] Column missing table_id=multicast-sessions-table

### ISSUE THREAD

**Issue by eduardotseoane** [FOGProject/fogproject#437]
Hi, I recently do a fresh install of workin-1.6, it was install 5 min ago, and i have the message error at the end of this message.

DataTables warning: table id=multicast-sessions-table - An SQL error occurred: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'msShutdown' in 'field list'SQL: SELECT `msID`,`msName`,`msName`,`msBasePort`,`msLogPath`,`msImage`,`msClients`,`msSessClients`,`msInterface`,`msStartDateTime`,`msPercent`,`msState`,`msCompleteDateTime`,`msIsDD`,`msNFSGroupID`,`msShutdown`,`msMaxwait`,`msAnon5` FROM `multicastSessions` LEFT OUTER JOIN `taskStates` ON `multicastSessions`.`msState` = `taskStates`.`tsID` AND `multicastSessions`.`msState` IN (3,0,1,2) INNER JOIN `images` ON `multicastSessions`.`msImage` = `images`.`imageID` AND `multicastSessions`.`msImage` = '' ORDER BY `msName` ASC LIMIT 0, 10

**Comment by Sebastian-Roth** [comment]
@eduardotseoane Could this be related to #426.

@mastacontrola Any chance you can look into those two issues?

**Comment by mastacontrola** [comment]
I just looked at fresh install with working-1.6 and it created the database properly with msShutdown and msMaxwait.

I also did a fresh install using the dev-branch and it created the the same fields properly.
