### ISSUE TITLE
FOG installer hangs on "Creating SSL Private Key"

### ISSUE THREAD

**Issue by LifeIsALesson** [FOGProject/fogproject#441]
Hi,
thanks for this awesome project! I'm new to FOG. I'm trying to install FOG in a Ubuntu 20.04 LTS VM. My install hangs at "Creating SSL Private Key". Last lines from the install log:

```
# until this position everything seems fine:
Synchronizing state of php7.4-fpm.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable php7.4-fpm
Generating RSA private key, 4096 bit long modulus (2 primes)
.......++++
...........................................++++
e is 65537 (0x010001)
You are about to be asked to enter information that will be incorporated
into your certificate request.
What you are about to enter is what is called a Distinguished Name or a DN.
There are quite a few fields but you can leave some blank
For some fields there will be a default value,
If you enter '.', the field will be left blank.
-----
Country Name (2 letter code) [AU]:State or Province Name (full name) [Some-State]:Locality Name (eg, city) []:Organization Name (eg, company) [Internet Widgits Pty Ltd]:Organizational Unit Name (eg, section) []:Common Name (e.g. server FQDN or YOUR name) []:Email Address []:Generating RSA private key, 4096 bit long modulus (2 primes)
........................................++++
..........................................................................++++
e is 65537 (0x010001)
**req: Error on line 7 of config file "/opt/fog/snapins/ssl//req.cnf"
140019292865856:error:0E079065:configuration file routines:def_load_bio:missing equal sign:../crypto/conf/conf_def.c:391:line 7**
```

Any advice how to handle this is highly appreciated.

Best regards,
JP

**Comment by LifeIsALesson** [comment]
This issue also occurs at trying to install from the current dev branch.```


 * Creating SSL Private Key....................................Failed!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!! The installer was not able to run all the way to the end as   !!
!! something has caused it to fail. The following few lines are  !!
!! from the error log file which might help us figure out what's !!
!! wrong. Please add this information when reporting an error.   !!
!! As well you might want to take a look at the full error log   !!
!! in /home/mando/fogproject-dev-branch/bin/error_logs/fog_error_1.5.9.111.log !!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

.........++++
.....................++++
e is 65537 (0x010001)
req: Error on line 7 of config file "/opt/fog/snapins/ssl//req.cnf"
140396651472192:error:0E079065:configuration file routines:def_load_bio:missing equal sign:../crypto/conf/conf_def.c:391:line 7
```

last lines in the error log:
```

'SmartInstaller.exe' -> '/var/www/html/fog//client/SmartInstaller.exe'
mysqlnd
Generating RSA private key, 4096 bit long modulus (2 primes)
...++++
......................................++++
e is 65537 (0x010001)
You are about to be asked to enter information that will be incorporated
into your certificate request.
What you are about to enter is what is called a Distinguished Name or a DN.
There are quite a few fields but you can leave some blank
For some fields there will be a default value,
If you enter '.', the field will be left blank.
-----
Country Name (2 letter code) [AU]:State or Province Name (full name) [Some-State]:Locality Name (eg, city) []:Organization Name (eg, company) [Internet Widgits Pty Ltd]:Organizational Unit Name (eg, section) []:Common Name (e.g. server FQDN or YOUR name) []:Email Address []:Generating RSA private key, 4096 bit long modulus (2 primes)
.........++++
.....................++++
e is 65537 (0x010001)
req: Error on line 7 of config file "/opt/fog/snapins/ssl//req.cnf"
140396651472192:error:0E079065:configuration file routines:def_load_bio:missing equal sign:../crypto/conf/conf_def.c:391:line 7
```

**Comment by Sebastian-Roth** [comment]
@LifeIsALesson Take a look at this topics in the forums: https://forums.fogproject.org/topic/15733/installer-issue-interface-ipadress-related-reopend and https://forums.fogproject.org/topic/15729/installer-issue-interface-ipadress-related

Most probably you have a simular situation with a special IP configuration. Run `ip addr show` and post results here. The FOG installer does not support setups with a secondary IP on the interface.

**Comment by LifeIsALesson** [comment]
Please ignore and close this one. The issue was caused by some off network interface config after switching from DHCP to statically assigned IP.

**Comment by LifeIsALesson** [comment]
THANKS!
