### ISSUE TITLE
Add Devuan for Installation

### ISSUE THREAD

**Issue by Ryushin** [FOGProject/fogproject#442]
Please add support for Devuan.  I see support for Ubuntu, Debian, and Mint.  I'm going to modify lib/ubuntu/config.sh to see if I can get it to work.

**Comment by Sebastian-Roth** [comment]
Sure we can talk about support for Devuan. Will you be the maintainer of this part of the installer script?

**Comment by Sebastian-Roth** [comment]
@Ryushin We'll close this request as there hasn't been any rely yet. You are still more than welcome to help us add support for Devuan. Let us know and we'll re-open this issue report.
