### ISSUE TITLE
Incompatibility with newer macOS versions.

### ISSUE THREAD

**Issue by ZVNexus** [FOGProject/fogproject#444]
PXE boot is no longer supported, so what alternative is there now?

**Comment by Sebastian-Roth** [comment]
* USB boot iPXE
* iPXE on hard drive (EFI partition)
* CD/DVD iPXE

**Comment by ZVNexus** [comment]
I was ideally looking for something that can be done with zero user interaction so dozens of them can be formatted at once just plug and it starts going

**Comment by Sebastian-Roth** [comment]
> I was ideally looking for something that can be done with zero user interaction so dozens of them can be formatted at once just plug and it starts going

In this cas I suggest you look into "installing iPXE on hard drive (EFI partition)". Let us know if you need some help with it.
