### ISSUE TITLE
 v1.5.9

### ISSUE THREAD

**Issue by ludo453** [FOGProject/fogproject#448]
Hello, while installing error on php-gettext even when installing manually.

**Comment by Sebastian-Roth** [comment]
Would be great to get some more information on what version of FOG you are using (1.5.9 a.k.a latest release as of now **or** `dev-branch` **or** any other version) as well as the Linux OS and version you use.

If I had to guess you are trying to install FOG 1.5.9 on Debian 10.

Searching github and the forums you can come up with numerious posts on this topic:
https://github.com/FOGProject/fogproject/search?q=gettext&type=issues
https://forums.fogproject.org/search?term=php-gettext&in=posts&matchWords=all&sortBy=timestamp&sortDirection=desc&showAs=posts

Get back to us on this if non of the information found is of any help.

**Comment by ludo453** [comment]
Hi so yes I am on the master version V1.5.9 and also yes on debian 10, I will look on the forum for your link thank you.
