### ISSUE TITLE
[fog-devel] Installer have problem with installing gettext in Debian Bullseye

### ISSUE THREAD

**Issue by roland-rollo** [FOGProject/fogproject#449]
I previously installed fog on Debian Buster without problem, but when I try it on Bullseye it shows me this
```
Skipping package: php7.4-gettext............................(Does not exist)
```
In Bulsseye repository I see this
```bash
php-php-gettext/stable 1.0.12-4 all
  read gettext MO files directly, without requiring anything other than PHP
```
Is there way to better detect correct package name, without editing distribution script for debian/ubuntu?

**Comment by Sebastian-Roth** [comment]
@roland-rollo Which version of FOG did you use?

I am pretty sure we can remove `php*-gettext` from the scripts package list altogehter. See here: https://forums.fogproject.org/post/142943 (an follow up posts)

**Comment by roland-rollo** [comment]
Latest fog-devel branch, 1.5.9.114, commit 4d750fc09337bbec2ac69a279ee93de994c04ada

**Comment by Sebastian-Roth** [comment]
@roland-rollo This commit was meant to update the installer for Ubuntu 21.10. Still need to look into removing `php*-gettext` completely.

**Comment by roland-rollo** [comment]
Thanks for clarification.
