### ISSUE TITLE
Bug when download image multicast hang after checking in

### ISSUE THREAD

**Issue by jmorda** [FOGProject/fogproject#45]
Hi, multicast download stuck after "checking in" looping in displaying "*(xx sec)" but all is ok in unicast or upload mode. All was OK some days ago.

**Comment by mastacontrola** [comment]
SVN 3699 Pushed to fix this issue.  Again it was an invalid syntax.  Basically using $this inside a file that is not a class, so this doesn't pertain to anything.

**Comment by jmorda** [comment]
Awesome !
