### ISSUE TITLE
Question: Are you interested in a re-write/organization of installfog.sh?

### ISSUE THREAD

**Issue by knotapun** [FOGProject/fogproject#450]
I'm a fledgling developer, and I'm looking for proof-of-competency work that isn't closed source or protected by an NDA. I'm a fan and user of the project, and would like to know if it would be desirable for installfog.sh to be cleaned up and re-organized.

I don't want to start on such an undertaking if the work has absolutely no chance of being integrated, because the maintainers don't want it, or don't want to proof-read my code. I understand that the quality of the changes will determine the answer in the case that it is desired, however.

If you don't think installfog.sh needs maintenance/clean-up, is there other work that I could perform that would be desired? I have a deep understanding of many aspects of computers.

**Comment by Sebastian-Roth** [comment]
@knotapun You request is very welcome! The installer scripts could use a maintenance/clean-up for sure. Though we also have a fair amount of other things on the list and if you are keen to look into other areas we'd welcome that too.

Why is your first interest in the installer scripts? Do you have a found knowledge of bash scripting?

We use bash scripting in what we call the FOS (FOG OS) inits - the basic Linux OS that does all the heavy work when capturing and deploying an image. There are a couple of things that one could add (LVM support, NFSv4 support and/or switching to a entire different protocol like SSH, ...).

**Comment by knotapun** [comment]
There's three reasons I want to work on installfog.sh. First, I've read quite a bit of it. Second, it's at the front of the project, the implications of any changes are fairly clear making it at least appear fairly safe. Third, I need more bash experience.

I'm not that fond of bash, the scripting is kind of clunky, but that's just how some things go, especially when they're as old and foundational as bash, and they're expected to work with something like VT100.  

I'm interested in trying to add other features like LVM, or SSH but I'll need to read through more of the existing code base first. Would the project be accepting of code written in Rust?

**Comment by Sebastian-Roth** [comment]
@knotapun Beside the bash side of things you also need a fair amount of kowledge and practice with the different Linux distros we currently support. Knowing the ins and outs of package management as well as service configurations is needed to get things right. Not wanting to keep you from getting into it but I just try to be fair. There is more to it than bash. On the other hand it's hell a lot easier than Linux driver development or that sort of thing. So don't worry.

One main thing that we keep dragging along is that the scripts need updating on pretty much every new release of a Linux OS version (be it Debian, Ubuntu or RHEL/CentOS). Sometimes packages get renamed but also we went into kind of a trap when we started to install specific PHP version packages on Ubuntu and Debian. That was needed in times when PHP 7 came out and the distros didn't provide official packages yet. So we added external repos like REMI and pinned PHP versions. I was hoping we can get rid of most of that stuff but we never got to that as of now.

The second major thing from my point of view is the command line options. Maybe that's an easier starting poing compared to the package stuff above. Some command line options simply don't work (as expected). I have not tested those in a very long time but as no one has worked on this I'd think it's still the case - e.g. try out `--startrange` and `--endrange`.

While writing this there is another issue coming to my mind. For quite some time we use symbolic links to link `/var/www/fog/` to `/var/www/html/fog/`. This was added a long time ago (way before I joined) to handle differences in Apache DocRoot settings defaulting to different paths in various distros. I am not sure we actually need that anymore and I know it's causing problems, e.g. run the installer on Ubuntu Linux (any version I think) up to the point where it tells you to open the web browser and update the DB schema. If you hit ENTER to early here without having updated the schema it will run into an error on the next step and stop. Now you just re-run the installer and it will leave you with two installs of the PHP files, one in `/var/www/fog/` and one in `/var/www/html/fog/`. While the web UI and FOG will still work it causes trouble when people manually update kernels or something like that.

This is great example of how the installer can cause things that don't show up right away and cause trouble in the long run.

One important thing is that we are currently in a stage where we work on two different versions. You find those in different branches. It's not great code management but that's what we are at right now. While [master](https://github.com/FOGProject/fogproject/tree/master) is always the state of the latest official release (1.5.9 currently )we use [dev-branch](https://github.com/FOGProject/fogproject/tree/dev-branch) for all changes towards the current 1.5.x version and [working-1.6](https://github.com/FOGProject/fogproject/tree/working-1.6) for the upcoming 1.6.x version. Changes on the installer scripts need to go into both as we want to prevent the two development branches from diverging even more. So you'd use `dev-branch` (or `working-1.6` for whatever you like better) to commit your changes and we need to mirror changes over to the other branch as well as soon as they are ready to go - usually by using `git cherry-pick`.

I guess starting with the installer is great and we might get to the FOS stuff later on.

> Would the project be accepting of code written in Rust?

Let us know which part you think adding Rust code or re-writing things in Rust will be favourable and we'll discuss things.

**Comment by Sebastian-Roth** [comment]
@knotapun Hope I did not put too much pressure on you bringing up all those things. Here is another minor issue one could take a good look at: https://github.com/FOGProject/fogproject/issues/449 (removing `php*-gettext` from the packages list altogether)

**Comment by knotapun** [comment]
You didn't scare me, it's just a busy time of year and I recently started a job. I'm still looking into the DHCP issue, but I'll gladly look at the issue you pointed out, too! Thank you for suggesting specific issues to address, that makes it easier to focus. 

Hope you had a good holiday weekend.

**Comment by Sebastian-Roth** [comment]
@knotapun Yes indeed had great holidays back then. But it's been extremely busy since then.

Did you get to look into the stuff mentioned above (#449 at first) yet?

Hope you had a good start to the new year.

**Comment by knotapun** [comment]
Yes, I have. I'm currently looking at the scripts. The first part of this seems simple enough, remove the package from fresh install scripts. That was easy. I've removed these from my local copy. Now I'm just trying to understand if there's any changes I would need to make for existing installs to ensure that it's marked as no longer needed.

**Comment by knotapun** [comment]
I've spent a decent amount of today looking at the code, and will submit a PR after I complete a little bit of testing. There's a decent amount of code within the `lib/ubuntu/functions.sh` that references `gettext`, which I want to make sure I get right. I just need to test it, and then I'll make a PR.

**Comment by Sebastian-Roth** [comment]
@knotapun Great! Thanks for looking into this. Do you know how to test gettext is still working? This forum discussion might be helpful: https://forums.fogproject.org/topic/15370/dev-branch-1-5-9-79-installing-package-php-gettext-failed-has-to-use-x-switch-to-get-it-to-work

**Comment by Sebastian-Roth** [comment]
@knotapun Don't forget to send the PR against `dev-branch`. :-)

**Comment by ggiesen** [comment]
@knotapun perhaps you might be able to roll #458 into your work as well? :)

**Comment by Sebastian-Roth** [comment]
@knotapun I am trying to get things going for our [next milestone](https://github.com/FOGProject/fogproject/milestone/4). Would be great to have you aboard with that too. I am closing this issue now and hope to see you around. Feel free to send in new pull requests.

**Comment by knotapun** [comment]
That works, Thank you. I'm still looking at the scripts, including the request from the gentleman before. You'll be receiving more substantive pulls soon, including a few dev quality of life scripts.

**Comment by Sebastian-Roth** [comment]
@knotapun Don't worry about #458, I fixed that one the other day already.
