### ISSUE TITLE
Install error at Database config using PHP 8.0

### ISSUE THREAD

**Issue by ChicagoJay** [FOGProject/fogproject#454]
Fresh install of dev branch on brand new Ubuntu 21.10 impish Server fails install when waiting for user to hit [enter] after database is updated/installed.  Management interface gives error 500.

**Comment by Sebastian-Roth** [comment]
@ChicagoJay This is still work in progress as FOG is not fully compatible with PHP 8.0 yet.

While you are free to use whatever Linux OS and version you want I am wondering if you might think about using a different one. You might want to take a look at @Wayne-Workman's great [install stats](https://fog-external-reporting-results.theworkmans.us/) as well as the latest [auto installer tests](http://fogtesting.theworkmans.us/). You can add AlmaLinux 8 and RockyLinux 8 to this list as I have tested those manually lately using `dev-branch`.

**Comment by ChicagoJay** [comment]
Ubuntu 20.04 seems to have worked, thanks.
