### ISSUE TITLE
[dev-branch] fails on Ubuntu 21.10 in databasemanager.class.php implode()

### ISSUE THREAD

**Issue by jessegit** [FOGProject/fogproject#456]
Ubuntu 21.10 has PHP 8.0 that has deprecated some args for implode.

` Uncaught TypeError: implode(): Argument #2 ($array) must be of type ?array, string given in /var/www/html/fog/lib/db/databasemanager.class.php:47`

Fix for me was
```
-        $noDBpattern = '#'.implode($noDBpattern, "|").'#';
+        $noDBpattern = '#'.implode("|", $noDBpattern).'#';
```

**Comment by Sebastian-Roth** [comment]
@jessegit Thanks for letting us know. This is a known issue and we are working on it.

**Comment by jessegit** [comment]
and another one, at `packages/web/lib/db/mysqldump.class.php`:
```
-        $colStmt = implode($colStmt, ",");
+        $colStmt = implode(",", $colStmt);
```
