### ISSUE TITLE
Fully-automated installation possible?

### ISSUE THREAD

**Issue by ggiesen** [FOGProject/fogproject#459]
I'm trying to automate provisioning of the FOG project server, which means there can be no interactive elements.

I've been able to bypass a number of the interactive elements by generating a .fogsettings file, and I've modified the install script to get past a few:

Comment out the following two lines:
https://github.com/FOGProject/fogproject/blob/171d63724131c396029992730660497d48410842/bin/installfog.sh#L398-L399

but I'm still working on other steps, such as:

1) Prompt for database root password (there doesn't appear to be any way to pass this in the config or command line arguments)
2) Install/update database schema (I haven't yet found a way to do this from the CLI, although I could probably use curl to trigger it)

I haven't been at this very long, but I'm wondering if I'm reinventing the wheel here. Is there a documented way of doing a completely non-interactive installation of FOG server?

**Comment by Sebastian-Roth** [comment]
@ggiesen Using "pre-configuration" through `.fogsettings` is a good way to go I would say. Though I can imagine this is not helping in all cases. For example the `checkSELinux` and `checkFirewall` functions cannot be satisfied by `.fogsettings` but instead you can make sure to disable SELinux and the firewall beforehand. In case you want to enable those you can do that afterwards again. Kind of a workaround instead of messing with the script.

The other thing you want to look at is using the command line switch `-y` when running the installer script. That way it will assume default answers for all installer questions and also do the schema update for you.

I think you can get around the database root password prompt by setting up the DB to allow for local connections through `unix_socket` for root: https://mariadb.com/kb/en/authentication-plugin-unix-socket/

**Comment by ggiesen** [comment]
The following is what I've come up with and seems to work so far. Accepts a -R argument that specifies the path to a file containing the MySQL root password:

```
diff -urN a/bin/installfog.sh b/bin/installfog.sh
--- a/bin/installfog.sh 2020-09-13 23:00:12.000000000 +0000
+++ b/bin/installfog.sh 2022-02-21 08:30:58.388669588 +0000
@@ -66,9 +66,11 @@
     echo -e "\t-T    --no-tftpbuild\t\tDo not rebuild the tftpd config file"
     echo -e "\t-F    --no-vhost\t\tDo not overwrite vhost file"
     echo -e "\t-A    --arm-support\t\tInstall kernel and initrd for ARM platforms"
+    echo -e "\t-R    --mysql-root-password\tSpecify the path to a file containing"
+    echo -e "\t                           \tthe MySQl root password"
     exit 0
 }
-optspec="h?odEUHSCKYyXxTPFAf:c:-:W:D:B:s:e:b:N:"
+optspec="h?odEUHSCKYyXxTPFAf:c:-:W:D:B:s:e:b:N:R:"
 while getopts "$optspec" o; do
     case $o in
         -)
@@ -182,6 +184,9 @@
                 arm-support)
                     sarmsupport=1
                     ;;
+                mysql-root-password)
+                    snmysqlrootpassfile=$OPTARG
+                    ;;
                 *)
                     if [[ $OPTERR == 1 && ${optspec:0:1} != : ]]; then
                         echo "Unknown option: --${OPTARG}"
@@ -296,6 +301,9 @@
         A)
             sarmsupport=1
             ;;
+        R)
+            snmysqlrootpassfile=$OPTARG
+            ;;
         N)
             if [[ -z $OPTARG ]]; then
                 echo "Please specify a database name"
@@ -395,8 +403,8 @@
 fi
 displayBanner
 echo -e "   Version: $version Installer/Updater\n"
-checkSELinux
-checkFirewall
+#checkSELinux
+#checkFirewall
 case $doupdate in
     1)
         if [[ -f $fogpriorconfig ]]; then
@@ -449,6 +457,9 @@
 [[ -z $bootfilename ]] && bootfilename="undionly.kpxe"
 [[ -n $smysqldbname ]] && mysqldbname=$smysqldbname

+if [[ -n $snmysqlrootpassfile ]]; then
+    read -r snmysqlrootpass < $snmysqlrootpassfile
+fi
 [[ ! $doupdate -eq 1 || ! $fogupdateloaded -eq 1 ]] && . ../lib/common/input.sh
 # ask user input for newly added options like hostname etc.
 . ../lib/common/newinput.sh
diff -urN a/lib/common/functions.sh b/lib/common/functions.sh
--- a/lib/common/functions.sh   2020-09-13 23:00:12.000000000 +0000
+++ b/lib/common/functions.sh   2022-02-21 08:31:51.120890702 +0000
@@ -1161,8 +1161,8 @@
                 echo
                 echo "   Database root password: $snmysqlrootpass"
                 echo
-                echo "   Press [Enter] to procede..."
-                read -rs procede
+                echo "   Press [Enter] to proceed..."
+                read -rs proceed
                 echo
                 echo
             fi
@@ -1189,15 +1189,17 @@
     # If we reach this point it's clear that this install is not setup with
     # unpriviledged DB users yet and we need to have root DB access now.
     if [[ $connect_as_root -ne 0 ]]; then
-        echo
-        echo "   To improve the overall security the installer will create an"
-        echo "   unpriviledged database user account for FOG's database access."
-        echo "   Please provide the database *root* user password. Be asured"
-        echo "   that this password will only be used while the FOG installer"
-        echo -n "   is running and won't be stored anywhere: "
-        read -rs snmysqlrootpass
-        echo
-        echo
+        if [[ -z $snmysqlrootpass ]]; then
+            echo
+            echo "   To improve the overall security the installer will create an"
+            echo "   unpriviledged database user account for FOG's database access."
+            echo "   Please provide the database *root* user password. Be asured"
+            echo "   that this password will only be used while the FOG installer"
+            echo -n "   is running and won't be stored anywhere: "
+            read -rs snmysqlrootpass
+            echo
+            echo
+        fi
         mysql $sqloptionsroot --password="${snmysqlrootpass}" --execute="quit" >/dev/null 2>&1
         if [[ $? -ne 0 ]]; then
             echo "   Unable to connect to the database using the given password!"
```

It doesn't have any error checking on the file, but it seems to work at least for my use case.

**Comment by Sebastian-Roth** [comment]
@ggiesen Thanks for your input on this. Though I am not too sure I like the idea of having the DB root password in a plain text file. Sure it's only temporary but still. What else could we come up with to make this work for you out of the box in one of the next releases? Did you look into [my comment](https://github.com/FOGProject/fogproject/issues/459#issuecomment-1046331476) on using `unix_socket`?

As well `checkSELinux` and `checkFirewall` don't need to be commented if you turn those off beforehand.

**Comment by matthewadams** [comment]
Just seeing this now as I've just begun using fog.  I also need this.  @ggiesen any chance of a PR for this?

**Comment by Cwavs** [comment]
I'm looking into automating the install too, the -y flag seems to assume the default of not disabling the firewall or selinux, which makes a lot of sense. That said it does feel odd that there is no way to override these options manually, other than to disable them yourself.  For the project I'm working on I'd like to be able to install fog largely unattended, and I think I'm pretty close to doing so. While I could write my own stuff to detect and disable the firewall and selinux, it feels a little redundant when it's already in the installer.

Is there any chance we could get an override flag to request they be disabled regardless of the -y flag? Happy to open a new issue on this.

**Comment by darksidemilk** [comment]
After the initial install upgrades are unattended with -y. I believe you can use /opt/fog/.fogsettings to make it unattended. I would also look at our install validation repo here https://github.com/FOGProject/fogproject-install-validation

Those are all silent installs as I understand it. @rluzuriaga might know more about those automations.

**Comment by Cwavs** [comment]
Yes, those are the things I've been doing thus far, but there is no way to specify anything for the firewall or selinux options in an unattended fashion. As far as I can tell you either have to handle that part yourself or run without -y and answer the prompt. I've had a quick look over the install validation repo, but I can't see it doing anything to tackle selinux or the firewall specifically, perhaps the distrobox containers being used don't have the firewall or selinux set up by default?

So far as I can tell this is the only thing stopping the install from being truly unattended, unless you as mentioned, handle the firewall or selinux yourself.

**Comment by rluzuriaga** [comment]
@Cwavs Your are right in assuming that the distrobox containers don't have the firewall and selinux set up by default. I have had it in my to-do list for a while to modify the installer so that we can automate it better, just haven't had the time.

**Comment by Cwavs** [comment]
Thanks for confirming. I was wondering, could you point me to where the part of the script that handles them is? I'm wondering if the best option right now would be to extract that code and then manually run it myself. That way I'm not reinventing the wheel, but I at least have a partial solution until one gets properly implemented.

**Comment by rluzuriaga** [comment]
https://github.com/FOGProject/fogproject/blob/5f7a5006191427ade261feff70586be043756d8d/lib/common/functions.sh#L901

https://github.com/FOGProject/fogproject/blob/5f7a5006191427ade261feff70586be043756d8d/lib/common/functions.sh#L931

These functions check and disable is the user enters Yes.
You can extract the code and manually run it, the installer won't re-enable them.

**Comment by Cwavs** [comment]
Thanks, that's a great help!
