### ISSUE TITLE
Make installer work for Ubuntu 22.04 LTS (Jammy Jellyfish)

### ISSUE THREAD

**Issue by Sebastian-Roth** [FOGProject/fogproject#462]
Currently only the daily desktop [ISO is available](https://cdimage.ubuntu.com/daily-live/current/) to far but that's a good point in time to start looking into what's missing to run FOG in Ubuntu 22.04 LTS (Jammy Jellyfish).

**Comment by ChicagoJay** [comment]
Just for giggles, I installed Jammy Jellyfish Desktop and tried to do a git install.  It's definitely still looking for PHP 7.1.

**Comment by Sebastian-Roth** [comment]
@ChicagoJay Pushed a couple of fixes over the last weeks. You should be fine to use FOG (`dev-branch`!!) on Ubuntu 22.04 now.
