### ISSUE TITLE
Pull kernel and init update information from github directly

### ISSUE THREAD

**Issue by Sebastian-Roth** [FOGProject/fogproject#463]
Instead of hosting kernel/init and the update information on our website we want to have it all hosted on github.

https://forums.fogproject.org/topic/16044/fog-kernels-and-inits-moving-to-github

**Comment by Sebastian-Roth** [comment]
One major step is done in eb46949b. We might look into adding a FOS init updater to the web UI as well but we might keep that for the next release as well.

**Comment by mastacontrola** [comment]
This has been incorporated thanks to @rluzuriaga and brought into 1.6

**Comment by mastacontrola** [comment]
Not sure if I can just close it for 1.6, so closing, but if this doesn't close it out for 1.6 or it closes it out for a different thing, then please feel free to reopen.
