### ISSUE TITLE
203 tasks does not run. 0 storage free.  

### ISSUE THREAD

**Issue by cavazquez** [FOGProject/fogproject#465]
Hi! i have this problem.
![Captura de pantalla de 2022-03-19 11-53-02](https://user-images.githubusercontent.com/4699299/159126218-510559dd-5eaf-488e-9216-c2c2813eb456.png)
![Captura de pantalla de 2022-03-19 11-53-27](https://user-images.githubusercontent.com/4699299/159126220-a4e6d03a-107f-46bb-8d33-ba0ba6a535a3.png)
![Captura de pantalla de 2022-03-19 11-56-45](https://user-images.githubusercontent.com/4699299/159126222-e011545f-d118-4298-94ef-120f47c55d97.png)

**Comment by cavazquez** [comment]
Is it possible that the cause is that the network was cut for a second?

**Comment by cavazquez** [comment]
ahh getTotalSupportClients  -  Queue - Used... The fog dont support cut progress.

**Comment by Sebastian-Roth** [comment]
@cavazquez I am not sure I understand how this problem occurred. Did you schedule manual wake on lan tasks or is this a scheduled task setup on your FOG server?

**Comment by cavazquez** [comment]
Hi! In my old job i had 120 computer and 0 problem. In my new job i have 480 and today the error occurred again

**Comment by cavazquez** [comment]
IF I have 10 tasks with taskStateId=1 they are subtracted from Free Slots?

**Comment by cavazquez** [comment]
It should happen if it is in 2

 2 | Checked In  | PC has checked in and is in queue for imaging                      |       2 | pause

**Comment by Sebastian-Roth** [comment]
@cavazquez Can you please describe in more detail what exactly you do that is causing this problem?

**Comment by cavazquez** [comment]
1.5.9 . my english skills do not allow me . maybe we should close the issues
