### ISSUE TITLE
[DEV-BRANCH] PHP8 named parameters cause havoc in 1.5.9.137

### ISSUE THREAD

**Issue by jessegit** [FOGProject/fogproject#466]
Running 1.5.9.137 on ubuntu 21.10 (PHP8), creating a snapin fails.
Apache errorlog:
```
Got error 'PHP message: PHP Fatal error:  
 Uncaught TypeError: spl_object_id(): Argument #1 ($object) must be of type object, resource given in /var/www/fog/lib/fog/fogftp.class.php:451\n
Stack trace:\n
#0 /var/www/fog/lib/fog/fogftp.class.php(451): spl_object_id()\n
#1 /var/www/fog/lib/fog/fogftp.class.php(223): FOGFTP->login()\n
#2 /var/www/fog/lib/pages/snapinmanagementpage.class.php(811): FOGFTP->connect()\n
#3 /var/www/fog/lib/fog/fogpagemanager.class.php(220): SnapinManagementPage->addPost()\n
#4 /var/www/fog/management/index.php(54): FOGPageManager->render()\n
#5 {main}\n  
  thrown in /var/www/fog/lib/fog/fogftp.class.php on line 451', referer: http://1.2.3.4/fog/management/index.php?node=snapin&sub=add
```

Cause seems to be PHP8 named parameters, especially with call_user_func_array(). (see https://php.watch/versions/8.0/named-parameters#named-params-call_user_func_array)

My workaround was to downgrade to php 7.4.

**Comment by Sebastian-Roth** [comment]
@jessegit Thanks for reporting this issue. We are currently working on [PHP8 support](https://forums.fogproject.org/topic/16135/php-8-support). Will work on a fix and push that soon!

**Comment by Sebastian-Roth** [comment]
@jessegit Now that I took a closer look at this I am not sure why you think this is something about `call_user_func_array()` as we don't use that in that part of the code (FOGFTP class) and hardly anywhere else.

I reworked this part to make it work with PHP 7 and 8 I hope. Would you mind testing 1.5.9.138?

**Comment by jessegit** [comment]
Uhm... looking at it now, I wonder too. I did trace many problems and I might have mixed things up. But I'm pretty sure there was a probable call_user_func_array() problem, too.

I gave PHP8/1.5.9.138 a try, the snapin create seems to work now, at least for simple/default case. (It also seemed to work with PHP7/1.5.9.138 and 137).
