### ISSUE TITLE
[DEV-BRANCH] PHP7 1.5.9.138 snapins do not seem to work

### ISSUE THREAD

**Issue by jessegit** [FOGProject/fogproject#467]
ubuntu 20.04 (PHP7), dev-branch 1.5.9.138 (and 137)

(I think) I know ~what I'm doing (worked previously for the past 5-7 years), and I've gone through the newbie mistakes (and with this, all the un/re/install, reset things, add deploy etc. things, and googled if there are any new gotchas since the last time I did imaging with fog).

Snapins do not work for me. I can add them, edit them, assign them to groups and hosts, make tasks for groups and hosts for all or single snapins and they appear in task list but the client will just say there are no snapins. I can do other things through the client link, like reboot and memory check, so that should not be a problem.

The only half-suspicious thing is is that I transplanted certificates from another fog installation on a PHP8 system (also 138/139, /opt/fog/snapins/ssl and /var/www/html/fog/management/other/ssl/srvpublic.crt) with all the required reboots and blahs.

The biggest problem here is not really the fact that it's not working, it's the fact that it's not debuggable. Client logs just say 'no snapins' and the server just waits for the client to act. No real reason why things do not work, and not documentation how it should work or how to debug it.

Unfortunately I only have till Saturday to debug this (and even at that, only random stints to test with a fog client)

**Comment by Sebastian-Roth** [comment]
@jessegit Anything in the apache / PHP-FPM logs on the FOG server while the fog-client queries the information?

**Comment by Sebastian-Roth** [comment]
@jessegit @JRWR Figured it out and pushed a fix (FOG 1.5.9.139). Thanks for using dev-branch and reporting this issue here!!
