### ISSUE TITLE
FOG Forum password reset not sending e-mails

### ISSUE THREAD

**Issue by morganwillcock** [FOGProject/fogproject#475]
Hi,

I've been trying to recover the password on my forum account but but the reset mechanism does not seem to send any mail.

I e-mailed the publicly listed email address contact@fogproject.org but the address does not seem to be deliverable.
> 550 5.1.1 <contact@fogproject.org> User unknown

I am opening an issue here because I cannot find any other contact point.

Thanks,
Morgan

**Comment by Sebastian-Roth** [comment]
@morganwillcock Thanks for letting us know. I am looking into the issue and will update as soon as possible.

**Comment by morganwillcock** [comment]
Unfortunately it still doesn't send me a password reset e-mail.
This is my account if it that helps at all: https://forums.fogproject.org/user/morgan

**Comment by Sebastian-Roth** [comment]
@morganwillcock I just manually triggered a password reset for your account. Did that arrive?

**Comment by morganwillcock** [comment]
That worked. I received the e-mail and I've reset the password. I then changed the e-mail address in my account settings and it sent the verification e-mail to the new address.

So possibly the problem is only with a user initiating a reset of their own password?

**Comment by Sebastian-Roth** [comment]
I did test resetting the password of my own account and it worked just fine. Closing this for now.
