### ISSUE TITLE
Install failing on Debian, php-gettext

### ISSUE THREAD

**Issue by Paulie420** [FOGProject/fogproject#484]
The installer script fails at what I think is the very end;

-----
 * Updating packages as needed.................................OK
 * Installing now everything is updated........................Failed!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!! The installer was not able to run all the way to the end as   !!
!! something has caused it to fail. The following few lines are  !!
!! from the error log file which might help us figure out what's !!
!! wrong. Please add this information when reporting an error.   !!
!! As well you might want to take a look at the full error log   !!
!! in /home/paulie420/Downloads/fogproject-1.5.9/bin/error_logs/fog_error_1.5.9.log !!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

E: Unable to locate package php-gettext
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package php-gettext
-----

I do notice that Debian has a package called php-php-gettext... anyone know of how to get around/past this? As-is, when I navigate to the fogproject machines IP, I just see a stock Apache2 debian page.

**Comment by Sebastian-Roth** [comment]
@Paulie420 With current Debian you need to use the latest [dev-branch](https://github.com/FOGProject/fogproject/archive/refs/heads/dev-branch.zip) version of FOG.
