### ISSUE TITLE
I guess this really 'cool' project is now dead?

### ISSUE THREAD

**Issue by TheBigBear** [FOGProject/fogproject#486]
Looking at the activity here and the age of the last release and all, I guess this has run its course and has been abandoned? Or is it still used and serving it's purpose without needing new releases?

**Comment by Yarli** [comment]
No its still very active. A lot of people here have recently been working on a new beta release too.

**Comment by Yarli** [comment]
> @Quazz and @Yarli, ok, thanks, I stand corrected. So is the `dev branch` quite useable and somewhat stable to use day to day then?

I would try to avoid using the dev branch for production and wait for an official stable release. Going by the work being done by the good guys here, I would say one is imminent but I could not tell you when.

The developers will be constantly working on and submitting to the dev branch therefore there could be issues within it until they are fully tested. I run 2 environments at work, my production one and a sandbox one with 1 VM which I target for imaging etc. I only use the dev branch on the sandbox one only.

Of course you are welcome to use the dev branch, test it and report back any issues that you may run into but I would advise not using it as a replacement for your current stable version.

**Comment by Sebastian-Roth** [comment]
@TheBigBear Open source projects can only be alive with people working on it as well as using it. Many people use or wanna use FOG but hardly any one takes on the development. You are most welcome to join the forces.

By the way, a fair amount of people use `dev branch` - currently all version numbers in the form of 1.5.9.**X** - see https://fog-external-reporting-results.fogproject.us/
