### ISSUE TITLE
"Chainloading Failed" Error when using EXIT method for drive boot

### ISSUE THREAD

**Issue by Piotr86PL** [FOGProject/fogproject#487]
Hello!

I've encountered an issue - "EXIT" method in FOG PXE Menu is not correctly working. It is an issue which I further described on FOG Forums [here](https://forums.fogproject.org/topic/16375/chainloading-failed-when-using-exit-method-for-drive-boot), but I decided to write it here for better tracking of the issue (A forum post can easily get lost among other posts). To sumarize everything said on forum. The issue here is happening because of incorrect syntax in the [iPXE script](https://github.com/FOGProject/fogproject/blob/master/src/ipxe/src/ipxescript) which is embedded directly into iPXE binary.

This line
`:netboot`
`chain tftp://${next-server}/default.ipxe ||
prompt --key s --timeout 10000 Chainloading failed, hit 's' for the iPXE shell; reboot in 10 seconds && shell || reboot`

should look like this
`:chainloadfailed`
`prompt --key s --timeout 10000 Chainloading failed, hit 's' for the iPXE shell; reboot in 10 seconds && shell || reboot`

`:netboot`
`chain tftp://${next-server}/default.ipxe || goto chainloadfailed`

That is my way to correct this issue, while still having the error message working in situations when it should be triggered (like actual chainload error, not usage of the "exit" command).

**Comment by Sebastian-Roth** [comment]
Thanks for bringing it up and also sending in the  pull request #489 as well as testing things.
