### ISSUE TITLE
Refactor the web interface

### ISSUE THREAD

**Issue by Magelfik** [FOGProject/fogproject#491]
I see this project is using "raw" PHP. 

Would it be interesting to rewrite the web UI so that it uses a framework (Symfony/Laravel or so) so that it becomes "more standard" ?

I'm asking this question because we're currently using Fog but we feel it has a few missing features. I would be happy to add them, but only if I can use a framework that is compatible with Fog.

Thanks in advance for your answers.

**Comment by Sebastian-Roth** [comment]
@Magelfik The project development has slowed down over the last two years as people have less time.

While moving to a framework sounds interesting for several reasons it's probably going to be a big challenge with the very limited development being done at the moment.

It's up to you to get involved and push things forward if you like.

**Comment by George1422** [comment]
That has been actually one of my wants for a while now. Understand I have no control over the direction of the project but using a standard web ui framework would be ideal for maintaining it. As Sebastian said with the limited developer resources the project has at the moment it would be difficult. Other thoughts I had (as a Moderator) would be to decouple the API from the Web UI and have the Web UI make API calls for FOG to function. This way we could ensure the API interface is as robust as using the web ui, because the web ui would be forced to use the API to make fog function. But still the project is lacking a strong web ui developer to make the front in pretty and robust.

**Comment by Magelfik** [comment]
I do not currently have much time at my disposal, but I would be very happy to give it a try. This would make the installation step quite more complex, but it would push the web part to today’s standards.

I was thinking of a self consuming API, indeed. This is quite easy to do. I will begin to scan the code and port it to Laravel.

**Comment by George1422** [comment]
> I will begin to scan the code and port it to Laravel.

When I had a bit more ambition I was looking at laravel as the web platform to create a supervisor FOG server that could manage multiple individual fog servers from a single console. But I got in over my head and skill level so I decided to keep the remaining hairs on my head and focus my efforts in other directions. If you have the time, the entire fog community would appreciate the efforts in moving FOG forward.

**Comment by cosmicvibes** [comment]
Time is always an issue, but the thoughts I read here are ones that have been rattling in my head for a while now. While I would not consider myself an  "expert" - I have written and maintain a number of internal Laravel projects so would be willing to look at least lending a supporting role here, if we can come up with an action plan.

**Comment by jetbalsa** [comment]
> @Magelfik The project development has slowed down over the last two years as people have less time.
> 
> While moving to a framework sounds interesting for several reasons it's probably going to be a big challenge with the very limited development being done at the moment.
> 
> It's up to you to get involved and push things forward if you like.

Its one of the few things people don't think about is long term support. @Sebastian-Roth looks to be the main code contributor these last few months. Do not take a Laravel rewrite lightly. If the code maintainers cannot easily use Laravel and doesn't have the cycles to sit down and learn it. Someone will need to do long term support on it. Its a major commitment and should not be taken lightly.

Sorry for being a Debby Downer.  But these cycles might be better spent elsewhere. Keep up the great work @Sebastian-Roth

**Comment by Magelfik** [comment]
You're not ! I appreciate your honesty and I though about it as well.

Plus, laravel's not easy to install as it is currently. I am not sure, but
perhaps a rewrite isn't the way to go...



Le mer. 21 sept. 2022 à 14:06, Forrest Fuqua ***@***.***> a
écrit :

**Comment by Sebastian-Roth** [comment]
@jetbalsa You have a good point there. I totally agree with long term support being a major issue. I keep on hoping that people get more involved in developing but it's not happening so far. You are all very welcome!

@Magelfik Should we keep this topic open?

**Comment by Magelfik** [comment]
Perhaps closing it for the time being is better.

I will open a new one if new ideas come up :-)

Thanks !

Le mer. 21 sept. 2022 à 22:50, Sebastian-Roth ***@***.***> a
écrit :
