### ISSUE TITLE
Could not find /etc/php/7.2/fpm/php.ini!

### ISSUE THREAD

**Issue by adamreed90** [FOGProject/fogproject#498]
**When attempting to upgrade my FOG, on dev-branch.** 

**Error:** 
Could not find /etc/php/7.2/fpm/php.ini! 

![image](https://user-images.githubusercontent.com/16042069/194589391-6c9025f6-b802-4236-9a2d-fec8d1a1162b.png)

**Log Files:**
[foginstall.log](https://github.com/FOGProject/fogproject/files/9735136/foginstall.log)
[tGoo-.log](https://github.com/FOGProject/fogproject/files/9735137/tGoo-.log)

**Comment by Sebastian-Roth** [comment]
@adamreed90 This should be fixed with commit c5fdea5c. Thanks for reporting.

**Comment by adamreed90** [comment]
Thank you this solved it! 👍
