### ISSUE TITLE
MBR too big ... bug in backup mbr procedure (all versions i suppose)

### ISSUE THREAD

**Issue by jmorda** [FOGProject/fogproject#50]
Hi,

Reporting that MBR is normaly 512 bytes long but the MBR backup procedure save all before the first partition, so it results that if first partition begin at 32kb, d1.mbr is 32kb, if it begins a 50mb, d1.mbr will be 50mb, etc... it results problems restoring partitions. I'm agree that in normal conditions, partition does not have to start so far but in reality, it's sometime different...

**Comment by cspenceiv** [comment]
Potentially fixed with commit 6ee2a6c.
