### ISSUE TITLE
Change how the client mounts the nfs server to allow nfs4

### ISSUE THREAD

**Issue by cavazquez** [FOGProject/fogproject#501]
If the client mounts / instead of /images it allows to use nfs 4.2 because /images has fsid is 0
![Captura de pantalla de 2022-10-13 23-04-12](https://user-images.githubusercontent.com/4699299/195745235-a679ecae-3ca2-46e5-8327-e07997408256.png)

**Comment by Sebastian-Roth** [comment]
@cavazquez Can you please explain in more detail why this should be done and where exactly.

There is a feature request on [switching to NFSv4 in the forums](https://forums.fogproject.org/topic/14791/feature-request-for-fog-1-6-x-configure-image-capture-to-use-nfsv4-instead-of-nfsv3) but no one has worked on this for more than a year.

If you are keen to make a move to NFSv4 you are more than welcome to. But I am sure there is way more to it then just changing the mount call.
