### ISSUE TITLE
Postinstall scripts

### ISSUE THREAD

**Issue by Yandaho** [FOGProject/fogproject#508]
Hello ! 

I have a Fog, and i want to do some actions with the postinstall scripts. I tried many times, but when the clon is finished, there is no scripts appear to be in use. 
Can someone have a solution, or just some tips ?

Thanks !

PS : Sorry for my bad english :/

**Comment by George1422** [comment]
If you look in the fog forum, in the tutorial section you will see how to activate a post install script: https://forums.fogproject.org/topic/11126/using-fog-postinstall-scripts-for-windows-driver-injection-2017-ed  Understand this one is for windows and specifically for copying over drivers to the target computer during the post install script action. The important points for you is to look how to hook your script into the post install action/script. Also add liberal comments to your custom scripts. You can also insert the debugPause commands. Then when you schedule a deployment task in debug mode you will be dropped to the FOS Linux command prompt. Key in the world `fog` and the script will start running, pausing at each debugPause command along the deployment process. The post install script will run just after the partclone sections are done. If you added an echo command followed by a debugPause command at the beginning of your script, you will know when your script starts to run. If you find a bug in your script, hit ctrl-c to exit the deployment script, fix your issue and then reissue `fog` to restart the deployment from the beginning again. As long as you don't let the install script run to the end you can keep repeating the `fog` ctrl-c bits until you fix the issue without having to create a new debug deployment task with the FOG UI.

**Comment by Sebastian-Roth** [comment]
@Yandaho Please let us know if you need further assistance. Can we close the issue report otherwise?

**Comment by Yandaho** [comment]
I don't have any time actually for test this but i will look about that, in this week and tell you if it's good ! Thanks a lot
