### ISSUE TITLE
Debian Bullseye installs DHCP packages when "no" is given for DHCP

### ISSUE THREAD

**Issue by wayneworkman** [FOGProject/fogproject#510]
See this forum thread for details: https://forums.fogproject.org/topic/16565/installing-1-5-9-on-debian-bullseye-fails/2

When using dev-branch on Debian Bullseye, you say "no" for setting up DHCP, the installation script still installs the DHCP packages but does not configure or enable a DHCP server.

The bug is that the DHCP packages are installed but should not be.

**Comment by Sebastian-Roth** [comment]
I am pretty sure it has been like that for a long time. Not specific to Debian but on all distros and versions I reckon.

The very same is true for other packages on storage nodes (e.g. mariadb/mysql, FOGImageReplication service installed and activated by default).

So I am wondering if it's worth adding more logic to the installer script to prevent from installing dhcpd?

**Comment by lukebarone** [comment]
I'll take a crack at this if no one else is working on it.

**Comment by Sebastian-Roth** [comment]
This is fixed, thanks to @lukebarone.
