### ISSUE TITLE
PHP Warning for host.class.php script

### ISSUE THREAD

**Issue by Piotr86PL** [FOGProject/fogproject#512]
Maybe not a serious error but it would be worth correcting. If more than 1 MAC address is assigned to a Host, the following warning appears in the PHP log:

`[05-Nov-2022 15:55:17 UTC] PHP Warning:  Host::{closure}(): Argument #1 ($mac) must be passed by reference, value given in /var/www/html/fog/lib/fog/host.class.php on line 172`

**Comment by Sebastian-Roth** [comment]
@Piotr86PL Thanks, this is fixed in 1.5.9.219...
