### ISSUE TITLE
Either DHCP failled or we were unable to access https://192.168.0.106/fog//index php for connection testing

### ISSUE THREAD

**Issue by Godoy21** [FOGProject/fogproject#516]
Hello, I have an error when restoring or inventorying a host. I can boot normally and even enter the FOG Project screen but if I try to deploy or restore an image it gives me this error.

Either DHCP failled or we were unable to access https://192.168.0.106/fog//index 
php for connection testing.
udhcpc started v1.31.1
udhcpc sending discover
udhcpc sending discover
udhcpc sending discover
udhcpc no lease. failing
No DHCP response on interface enp3s0. skipping it.
Failed to get an IP via DHCP! Tried on interface(s): enp3s0
Please check your network setup and try again

![WhatsApp Image 2022-11-14 at 13 21 07](https://user-images.githubusercontent.com/91966151/201714878-e3894946-24be-4dce-aa1d-47952bcd69be.jpeg)

**Comment by George1422** [comment]
Upgrade your FOS Linux kernel to 5.15.x first. If that doesn't work and you still get the same results we can debug more. From the FOG UI->FOG Configuration->Kernel update

Also knowing the hardware (computer) if it doesn't work will help too.

**Comment by Godoy21** [comment]
I did the process as you said but it was not successful. I've tested it on different hardware, both desktop and notebook.
For example in notebooks
Dell Vostro 3510
Dell Vostro 3500
Desktop
Dell Optplex 390
Dell Optplex 380

**Comment by George1422** [comment]
I have a feeling that the fos linux kernel didn't get updated for some reason. From the FOG server linux console key in 
file /var/www/html/fog/service/ipxe/bzImage
It should report the linux kernel version. All of the systems you mentioned should work with 5.15.x series kernel. They will not work with the 4.19.x series kernels. 

Just looking again, the 390 and 380 are really old hardware (I first read them as 3080 and 3090). They should work with 4.19.x versions of FOS linux kernel. What version of FOG are you using?

I also see from your picture that you are using https:// how did you enable this? Using the FOG installer?

**Comment by Sebastian-Roth** [comment]
@Godoy21 Is 192.168.0.106 your FOG server IP?

In the picture we see it actually say "no lease, failing". So I would think it's not a driver issue. On the other hand it's strange because to get to that point means the machine PXE booted and got an IP via DHCP two times in a row already (BIOS/UEFI and iPXE).

**Comment by Godoy21** [comment]
> Tenho a sensação de que o kernel fos linux não foi atualizado por algum motivo. A partir da chave do console linux do servidor FOG no arquivo /var/www/html/fog/service/ipxe/bzImage Deve informar a versão do kernel linux. Todos os sistemas que você mencionou devem funcionar com o kernel da série 5.15.x. Eles não funcionarão com os kernels da série 4.19.x.
> 
> Olhando novamente, o 390 e o 380 são realmente hardware antigo (eu os li pela primeira vez como 3080 e 3090). Eles devem funcionar com versões 4.19.x do kernel Linux FOS. Qual versão do FOG você está usando?
> 
> Também vejo pela sua foto que você está usando https:// como você habilitou isso? Usando o instalador do FOG?

![image](https://user-images.githubusercontent.com/91966151/202207447-216bd16f-4f8a-4553-81b4-3f2a5a7fb093.png)
Actually checking the way you sent me, it's in version 4.19. I performed the update on the web page and it appeared that it had been a success. How can I be updating via the linux console?

I'm using Fog in version 1.5.9.

I believe that HTTPS was activated during the installation because neither a configuration was made on the apache server, neither before nor after the installation of FOG.

But I remember that I had not selected https during the installation.

**Comment by Godoy21** [comment]
> @Godoy21192.168.0.106 é o IP do seu servidor FOG?
> 
> Na foto, vemos realmente dizer "sem aluguel, falhando". Então eu acho que não é um problema de driver. Por outro lado, é estranho porque chegar a esse ponto significa que a máquina PXE inicializou e obteve um IP via DHCP duas vezes seguidas (BIOS/UEFI e iPXE).

Yes, it recognizes the ipxe, it even arrives at the FOG menu in Deploy, it authenticates me in fog and shows the images that it has on the server. But when running the task it gives this error.

**Comment by Godoy21** [comment]
I did the whole process he successfully updated the kernel but it still wasn't. I will try to reinstall fog now on Ubuntu 20 to see

> Version 4.19.9 should still support the 380, but lets get that updated anyway so you can have modern computer support. If the auto update process doesn't work (which kind of makes me think you are using FOG 1.4.x for some reason). You can manually download the kernels from here: https://github.com/FOGProject/fos/releases move them (bzImage and bzImage32) to the path I provided before. Remember that linux is case important. If the kernel update doesn't address your issue (it will address others so its something you should do) we need to work down the path that Sebastian mentioned.

I did the whole process he successfully updated the kernel but it still wasn't. I will try to reinstall fog now on Ubuntu 20 to see

**Comment by Godoy21** [comment]
![WhatsApp Image 2022-11-17 at 10 19 38](https://user-images.githubusercontent.com/91966151/202457392-13f1a64f-2f9b-4caf-9a52-818b9cd8a40f.jpeg)

Same mistake.
Could it be because of php-gettext?

**Comment by Godoy21** [comment]
![image](https://user-images.githubusercontent.com/91966151/202457684-cdea4e9a-2e58-4368-a350-c5df34b8877e.png)

**Comment by George1422** [comment]
OK I want you to switch over to the Dev branch of FOG 1.5.9.110 or later. 
Change into the local git repo on you fog server. Then issue:
git checkout dev-branch
git pull
cd bin
./installfog.sh

Then install the dev branch that has fixes for the gettext issue. You will need to redownload the latest FOS Linux kernel once again. FOG Web ui->Fog Configuration->Kernel update

If that still doesn't fix the issue then we can step into debug mode on the target computer to try to understand why you  see these messages. We are a long way from being out of luck with this install.

**Comment by George1422** [comment]
Just as an after thought (and thinking about Sebastian's post). If you plug an already configured windows computer into the same network jack as the one from the error message, do you get an IP address on that windows computer?

**Comment by Godoy21** [comment]
I did several tests and made no progress. I'm thinking that the problem could be my MPLS. because here at the factory we have 3 poles that are connected by MPLS and the Fog VM is in a different plant from the PFSense VM (DHCP)

**Comment by Sebastian-Roth** [comment]
@Godoy21 While we can't be sure I kind of doubt the MPLS is causing the problem described here. As I said before: to get to this stage the client successfully got an IP via DHCP twice before. So why should the MPLS mess with the third round of DHCP?

On the other hand this doesn't help you. I suggest you look into capturing the DHCP traffic. The easiest step is using [pfSense to capture the traffic](https://docs.netgate.com/pfsense/en/latest/diagnostics/packetcapture/webgui.html). Enable "Promiscuous Mode", set "Protocol" to UDP and "Port" to `67|68|4011`. Make sure you quickly boot up the client in question while capturing because you'll probably see others requesting DHCP as well. Stop the capture as soon as you see the "no lease" error. Then hit the "Download Capture" button, open that file in Wireshark and see if you can make sense of it. Let us know if you need help with this.

**Comment by Sebastian-Roth** [comment]
@Godoy21 Anything we can still help you with?
