### ISSUE TITLE
[Feature req] Support F2FS

### ISSUE THREAD

**Issue by bence98** [FOGProject/fogproject#517]
I installed Linux to an NVMe drive, and I heard that EXT4 is not great for flash-based media, so I chose to use F2FS as my root partition instead. Now I can't image it with FOG, as it fails with "No resizable partitions found".
Using FOG 1.5.9, FOS kernel 5.15.68 on amd64 arch.

**Comment by George1422** [comment]
FOG uses partclone for imaging (same as clonezilla) so FOG is limited to supported operating systems as Partclone supports. https://partclone.org/usage/partclone.php#:~:text=Partclone%20supported%20file%20system%20include,)%20and%20MINIX(MINIX3).  Beyond that FOG does not supported all of the filesystems that partclone supports either. Your only hope for cloning these unsupported file systems with FOG is by using RAW mode, that does a sector by sector block copy.

**Comment by bence98** [comment]
It is possible to copy the partition with Partclone.image, when I edited out the check for NTFS or EXT4 partitions being present from the `fog.upload` script, it uploaded fine. However, a proper F2FS support would be better (`resize.f2fs` etc.)

**Comment by Quazz** [comment]
@bence98 Can you create an issue at https://github.com/FOGProject/fos ? That's the boot environment OS for FOG, this one is for the WebGUI.

**Comment by Sebastian-Roth** [comment]
Closing this in favour of the newly opened request in the fos repo, thanks.
