### ISSUE TITLE
FOGCrypt

### ISSUE THREAD

**Issue by crbarahona** [FOGProject/fogproject#52]
I may be misunderstanding something here, but there appears to be no documentation on the Passkey in FOGCrypt. Since there's a config file, and this certainly must be symmetric encryption, the Passkey must be meant to change so that the AD password can only be decrypted by the correct people. Doesn't that mean, though, that the Passkey would need to be changed in the FOG Client as well? I haven't found anywhere to set that.

**Comment by mastacontrola** [comment]
This is not the case.

The passkey is only symmetrical to itself from the fog server. This is only for ADPass.  The Key that the client sends out is shared for 30 minutes.  The client is telling us what it expects the decryption key to be.  At this point, it stores the key and creates a security token.  After a period of time the aes key the client created earlier is reset.  As it is reset, the security token validates this is indeed the same host.  If that security token is wrong, it will not send any data to the host.

Hopefully this makes sense.  We no longer need the key to be a part of the installer.

**Comment by mastacontrola** [comment]
Also, directly referencing the FOGCrypt and what I call the "legacy" client, is exactly as you originally stated.  What I stated above is only related to the new client.

**Comment by crbarahona** [comment]
That makes sense for communication between FOG Server and the FOG Client, but I'm still unclear about the passkey part of FOGCrypt. It looks like that's meant to be changed as the default passkey is "FOG-OpenSource-Imaging". From what you described, FOG Server decrypts the encrypted password with it's own copy of the symetric passkey (FOG-OpenSource-Imaging) and re-encrypts it with some kind of dynamic (maybe asymetric?) key when communicating with FOG Client.
It's still clear though, that FOG is saving the FOGCrypt encrypted password, and somewhere has a way to decrypt it with "FOG-OpenSource-Imaging". So isn't that still vulnerable as it's a known key?

**Comment by crbarahona** [comment]
I might just be missing the place to set that within FOG.

**Comment by jbob182** [comment]
You're mixing the legacy client with the beta client. The legacy client is several years old; the server does not decrypt the AD password, it simply stores the encrypted blob and sends it out to clients which have the passkey compiled in them. It is not secure as you have noticed. 

The beta client on the other hand takes a much more secure approach. A plain text version of the AD password is entered into FOG and is on-the-fly encrypted and stored in the database. When ready to ship it out to clients, it decrypts the value in the database and encrypts it with the client's AES key.

**Comment by crbarahona** [comment]
Oh alright. That's definitely what I was looking for. I realized, I'm using 1.2.0 stable release, which is probably old judging by the changelog here. I didn't notice FOG Client mentioned in the changelog, so I hadn't approached that yet.
I still don't quite understand why there's a config file that allows changes to the passkey, if it's not meant to be changed, though.
