### ISSUE TITLE
Add the ability to set the max-wait globally for all partitions

### ISSUE THREAD

**Issue by Magelfik** [FOGProject/fogproject#521]
Hi there,

We've had problems with multicast since we deployed fog. I believe I finally found the problem : 

https://github.com/Magelfik/fogproject/edit/master/packages/web/lib/service/multicasttask.class.php#L659

The timeout is currently only applied for the first partition and then it defaults to 10 secondes. We have images where 10 seconds is not sufficient (probably because of size), and syncing takes more than 10 secondes. This results in fogged hosts being dropped mid-multicast.

My MR suggests a correction https://github.com/FOGProject/fogproject/pull/520

Please let me know if this seems like a sound solution. My school lab would be very grateful to see it patched into the latest fog release.

**Comment by Sebastian-Roth** [comment]
@Magelfik I remember times when FOS used to wait the same amount of time at the start and in between each partition. Back then I was fed up with waiting and asked the developers to change it to wait 10 seconds between partitions. Can't find the forum topic anymore.

We should definitely change this value if it's causing problems.

**Comment by Sebastian-Roth** [comment]
@George1422 @wayneworkman I'd appreciate a comment from your side on this as well. Usually the wait time between partitions does not play a role if all machines catch up with the multicast session. But if one drops out the wait time between partitions will be way longer (10 **minutes** by default but can be configured in FOG Settings in the web UI).

**Comment by Magelfik** [comment]
> @George1422 @wayneworkman I'd appreciate a comment from your side on this as well. Usually the wait time between partitions does not play a role if all machines catch up with the multicast session. But if one drops out the wait time between partitions will be way longer (10 **minutes** by default but can be configured in FOG Settings in the web UI).

What I’ve seen from the source code is that it’s 10 seconds, not minutes. Fog accepts minutes, and then converts them into seconds by a simple * 60.
However the time between partitions is hardcoded to 10, not minutes but seconds (the *60 is not applied). Perhaps I misunderstood ?

> @Magelfik What about making it `$maxwait * 6` to make it default to one minute in between partitions? I know it's kind of a crude logic.

I am up for anything. Right now we’ve removed the ternary operator and multicast works fine. But I understand waiting for all computers to sync up between each partition can be tedious. 60 seconds should be fine for most cases, but perhaps it’s worth removing the currently hard-coded value and adding a config option somewhere for the future.
Anyway, I’m more than happy to see it go from 10 to 60 :)

**Comment by Sebastian-Roth** [comment]
@Magelfik said:
> ...
> Perhaps I misunderstood ?

I did a double post. Please re-read my answers and I am sure you understand why I said something about 10 minutes to  be the default even between partitions (that was in the past...).

**Comment by Magelfik** [comment]
Ah yes, I see. Sorry about that.

**Comment by Sebastian-Roth** [comment]
@Magelfik Sorry for the delay. I would really like to get this merged in. Are you fine with using `$maxwait * 60` wait time for the first partition and `$maxwait * 6` for the remaining partitons? If yes, then please update the pull request and I'll merge it in. As well you might increase the last part of the version number in [system.class.php](https://github.com/FOGProject/fogproject/blob/dev-branch/packages/web/lib/fog/system.class.php#L56) by one.

**Comment by Magelfik** [comment]
No problem.We had trouble with other values than my PR, so I would suggest keeping my changes as they are.I will update the version as well.Le 12 déc. 2022 à 20:40, Sebastian-Roth ***@***.***> a écrit :﻿
@Magelfik Sorry for the delay. I would really like to get this merged in. Are you fine with using $maxwait * 60 wait time for the first partition and $maxwait * 6 for the remaining partitons? If yes, then please update the pull request and I'll merge it in. As well you might increase the last part of the version number in system.class.php by one.

**Comment by Sebastian-Roth** [comment]
@Magelfik I am not sure it's wise to use `$maxwait * 60` between partitions as well. If just one client **can't join** the multicast session the process will be delayed by `$maxwait * 60 * ($partition_count-1)` (10 minutes per partition by default).

**Comment by Magelfik** [comment]
I should be able to update #520 this week.

$maxwait * 6 sounds more than fair.

If this doesn't work, we'll know where this is coming from anyway.
–––––––––––––––––––––
Théo PIRKL
For confidential matters, please use the following GPG key : Théo Pirkl <
***@***.***> (157DFF10B677DFC0)


Le mer. 14 déc. 2022 à 10:03, Sebastian-Roth ***@***.***> a
écrit :

**Comment by Magelfik** [comment]
Welp, life got in the way.

I'll try to find some time tomorrow to push those changes. Sorry :(
–––––––––––––––––––––
Théo PIRKL
For confidential matters, please use the following GPG key : Théo Pirkl <
***@***.***> (157DFF10B677DFC0)

**Comment by Magelfik** [comment]
Hi @Sebastian-Roth, I have pushed the changes as discussed.

**Comment by Sebastian-Roth** [comment]
PR #521 merged.
