### ISSUE TITLE
ubuntu bionic and later package php-gettext now called php-php-gettext

### ISSUE THREAD

**Issue by dmick** [FOGProject/fogproject#525]
I don't know why, and I don't know if it also affects Debian and/or Mint, but I know this much.

**Comment by lukebarone** [comment]
I'll take a look at this during the week, and see if I can get a working solution.

**Comment by dmick** [comment]
FWIW, there are multiple subsequent problems with at least Ubuntu jammy; php version 8.1, apparently something to do with php.ini that I haven't sorted yet, etc.  I realize it's not a supported release, but I was trying.

**Comment by Sebastian-Roth** [comment]
This is known for FOG 1.5.9 the latest official release as of now. But it's fixed in [FOG dev-branch](https://github.com/FOGProject/fogproject/archive/dev-branch.zip) which is pretty stable and usable even if it's not a release yet. You will be able to easily update from dev-branch to the next upcoming release.



Am 18. Dezember 2022 04:32:30 MEZ schrieb Dan Mick ***@***.***>:

**Comment by dmick** [comment]
Struggled for a while the dev-branch with what appears to still be an instance of https://docs.gz.ro/node/294, and manually used the workaround there (uninstall all the php packages, and reinstall them).  I have no idea why that made a difference, but it allowed the fog server to complete its installation program.  When apache/php were throwing that error, the .so in question was installed; I'm assuming it was some problem with one of the many .ini files, but I don't know.

I also found https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=715493

**Comment by Sebastian-Roth** [comment]
@dmick I suggest you start from scratch. Just install plain Ubuntu bionic and then use the FOG dev-branch installer and off you go.

**Comment by dmick** [comment]
not a bad idea, but bionic is ancient, two LTSes old, and due to reasons beyond my control reinstalling this host was not easy, so I was trying to get it to work on jammy.  I think I might have done so, and I hope the team has a chance to move forward to a modern ubuntu (I know it's pain, so no guilt/pressure at all).

**Comment by Sebastian-Roth** [comment]
@dmick That's good to hear! So do you still need our help? I am just missing information on what exactly fails to be able to help.

**Comment by dmick** [comment]
well it still experiences the problem noted above without manual intervention, namely php complains (in apache's error.log):
`PHP Warning:  PHP Startup: Unable to load dynamic library 'pdo_mysql.so' (tried: /usr/lib/php/20210902/pdo_mysql.so (/usr/lib/php/20210902/pdo_mysql.so: undefined symbol: pdo_parse_params), /usr/lib/php/20210902/pdo_mysql.so.so (/usr/lib/php/20210902/pdo_mysql.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0`

That .so file was present when the failures were happening.  I've no idea why the failure happens, or why the workaround in https://docs.gz.ro/node/294 mentioned above fixes it, but apparently both those are true with the default installation path from dev-branch.

**Comment by dmick** [comment]
(and I realize this is now probably a separate issue)

**Comment by Sebastian-Roth** [comment]
@dmick Did you get this solved? Check out the FOG installer tests - all the Ubuntu versions 18.04, 20.04, 22.04 ought to install just fine: https://fogtesting.fogproject.us/

Maybe try this: https://stackoverflow.com/a/64661113

I can only imagine you have different versions of PHP and PHP modules installed. Please run `dpkg -l | grep php` and post output here.

**Comment by Sebastian-Roth** [comment]
@dmick Should we keep this topic open?

**Comment by dmick** [comment]
I'm sorry; I thought I'd responded.  The workaround in https://stackoverflow.com/a/64661113 is indeed what I applied, as I mentioned above, but it seemed to be necessary.  The machine where I was doing this experimentation has been reallocated, so I'm afraid I can't test more at the moment.  I guess you can close this if you wish.
