### ISSUE TITLE
Fix dev-branch installer to work on Debian Testing ("Bookworm")

### ISSUE THREAD

**Issue by stevemoca** [FOGProject/fogproject#531]
The FOG installer in dev-branch can install FOG server on Debian Testing ("Bookworm"), when invoked as follows:

    linuxReleaseName=Debian OSVersion=12 OSMinorVersion=0 ./installfog.sh

Unfortunately, the installer installs the `sysv-rc-conf` package, which breaks systemd. This prevents the FOG service units from working, effectively crippling the FOG server.

I have created a pull request (#530) that proposes a simple solution: Modify the installer to not install `sysv-rc-conf` on Debian hosts. This works because `sysv-rc-conf` is not used on Debian hosts anyway, since service control is done using systemd tooling.

**Comment by Sebastian-Roth** [comment]
@stevemoca Thanks for this issue report an the pull request!

> Unfortunately, the installer installs the `sysv-rc-conf` package, which breaks systemd. This prevents the FOG service units from working, effectively crippling the FOG server.

Can you provide some more details on the issues `sysv-rc-conf` is causing, e.g. error messages?

I have thought about removing the legacy SystemV stuff completely but have not had the time to do so. Now that we seem to run into trouble with this it might be time to do so. I am not sure if any current Linux OS still uses SystemV, Dabian and Ubuntu definitely don't use it since many years.

**Comment by Sebastian-Roth** [comment]
@stevemoca said:
> After a reboot, the init (PID 1) process is no longer systemd.

Good heavens! I didn't expect that to happen. Thanks heaps for bringing this issue up and your detailed description. We highly appreciate this.

> I will have a look and see what I can do, but I'm not promising anything!

As mentioned in the PR code review I suggest we get the initial problem fixed for bookworm and later on remove the rest.

**Comment by Sebastian-Roth** [comment]
@stevemoca PR merged, thanks again.

**Comment by ejgr-mtsiw** [comment]
This is happening on working-1.6 branch. Installing on Debian 12 GNOME resulted in the (silent) removal of many system packages resulting in a broken system. Just like @stevemoca the system looked normal until I tried rebooting...

The workaround was to install from master (1.5) and then checkout working-1.6 and upgrade. The upgrade doesn't try to install sysv-rc-conf.
