### ISSUE TITLE
 Stopping web service........................................Failed! Debian 11

### ISSUE THREAD

**Issue by DubbelF34140** [FOGProject/fogproject#532]
Hello I have a problem with the installation of Fog when I launch the installation at the end the Web service does not stop which stops the installation. I have checked the operation of the service it is functional I do not understand Can you help me ?
![image](https://user-images.githubusercontent.com/57435130/211159344-70f3333c-bb2b-4700-b8a1-d9892b4a6ad2.png)

**Comment by lukebarone** [comment]
Is this a new install or an upgrade? 

Are you using the master branch or the dev branch?

**Comment by DubbelF34140** [comment]
It's a new installation and I use the branch downloaded with the command :
"git clone https://github.com/FOGProject/fogproject.git"

**Comment by lukebarone** [comment]
switch to the dev branch and run the installer again

git checkout dev-branch
cd bin
.\installfog.sh

**Comment by DubbelF34140** [comment]
The installation went further but it stopped with this error :
" ERROR 1146 (42S02) at line 1: Table 'fog.globalSettings' doesn't exist "

**Comment by lukebarone** [comment]
OK, if this is a new install, then also run `rm /opt/fog/.fogsettings` to remove the old config file, then run the installer again.

**Comment by DubbelF34140** [comment]
I don't have the .fogsettings file in the /opt/fog/ folder . I just have snapins folder .

**Comment by lukebarone** [comment]
Then something else is wrong. Can you attach the `fogproject/bin/error_logs/*.log` files?

**Comment by DubbelF34140** [comment]
[fog_error_1.5.9.235.log](https://github.com/FOGProject/fogproject/files/10366820/fog_error_1.5.9.235.log)

**Comment by lukebarone** [comment]
This is definitely weird. Is this a fresh Debian-based install? Or was this server in use doing other things already?

If you run `mysql`, do you get logged in right away? If so, run the following:

```
SHOW DATABASES;
USE fog;
SHOW TABLES;
```

**Comment by DubbelF34140** [comment]
It is a freshly installed virtual machine under debian and here is the result of the commands:
![image](https://user-images.githubusercontent.com/57435130/211163369-fdfbe375-655a-451c-a5cd-f7a076d02632.png)

**Comment by lukebarone** [comment]
All I can suggest that's left is to run `DROP fog;` in the MySQL console, run `rm /opt/fog/.fogsettings` (even if you don't see it), and re-run the FOG installer. If it's still broken, then we'll need to spend a bit more time on the installer script.

**Comment by lukebarone** [comment]
I'm sorry, where are you seeing "too much fog table"?

**Comment by lukebarone** [comment]
Sorry, I meant `DROP DATABASE fog;` in MySQL - My bad!

**Comment by DubbelF34140** [comment]
no sorry i have "drop fog table" no "too much fog table"

**Comment by lukebarone** [comment]
OK, let's try dropping the fog database, removing that settings file, and trying again

**Comment by DubbelF34140** [comment]
I tried but it does not work and I wanted to launch on another virtual machine still on debian 11 an installation in bransh master but even worries:

Master : "Failed to stop php-fpm.service: Unit php-fpm.service not loaded."

Dev :
![image](https://user-images.githubusercontent.com/57435130/211165620-fad27e32-92c7-4547-809c-d697c60797e8.png)

**Comment by lukebarone** [comment]
It's working for me on a fresh Debian 11 install. Can you check the following for me:

```bash
cat /etc/debian_version
cat /etc/apt/sources.list
cat /etc/apt/sources.list.d/*.list
php --version
sudo apache2ctl -v
mariadb --version
```

... and post the results here (as text, not as a picture)

**Comment by DubbelF34140** [comment]
cat /etc/debian_version : 11.6

cat /etc/apt/sources.list : 
# deb cdrom:[Debian GNU/Linux 11.6.0 _Bullseye_ - Official amd64 NETINST 20221217-10:42]/ bullseye main
#deb cdrom:[Debian GNU/Linux 11.6.0 _Bullseye_ - Official amd64 NETINST 20221217-10:42]/ bullseye main
deb http://ftp.fr.debian.org/debian/ bullseye main
deb-src http://ftp.fr.debian.org/debian/ bullseye main
deb http://security.debian.org/debian-security bullseye-security main
deb-src http://security.debian.org/debian-security bullseye-security main
# bullseye-updates, to get updates before a point release is made;
# see https://www.debian.org/doc/manuals/debian-reference/ch02.en.html#_updates_and_backports
deb http://ftp.fr.debian.org/debian/ bullseye-updates main
deb-src http://ftp.fr.debian.org/debian/ bullseye-updates main
# This system was installed using small removable media
# (e.g. netinst, live or single CD). The matching "deb cdrom"
# entries were disabled at the end of the installation process.
# For information about how to configure apt package sources,
# see the sources.list(5) manual.
deb http://ftp.fr.debian.org/debian stretch main

php --version : 
PHP 7.4.33 (cli) (built: Nov  8 2022 11:40:37) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.33, Copyright (c), by Zend Technologies

sudo apache2ctl -v : 
Server version: Apache/2.4.54 (Debian)
Server built:   2022-06-09T04:26:43

mariadb --version : 
mariadb  Ver 15.1 Distrib 10.5.18-MariaDB, for debian-linux-gnu (x86_64) using  EditLine wrapper

cat /etc/apt/sources.list.d/*.list : nothing

**Comment by lukebarone** [comment]
Why do you have a repo pointing to Stretch?

**Comment by DubbelF34140** [comment]
Because without the gettext package does not install.

**Comment by lukebarone** [comment]
I switched my `sources.list` to match yours (except the stretch part), and my install has gone all the way through.

![image](https://user-images.githubusercontent.com/6752278/211168791-e36033f0-3e2e-4487-a3f3-bcb7d22ee572.png)

What's interesting as well is that I do not see `php-gettext` trying to be installed. This is my list of installed packages after running the FOG installation:

![image](https://user-images.githubusercontent.com/6752278/211168935-2f5cfe78-bab7-4b57-9634-bf2c893ae709.png)

... but I do see `gettext` installed without Stretch:

![image](https://user-images.githubusercontent.com/6752278/211168956-542b21a7-88a5-44ec-aafe-09d7a1e4170f.png)

My suggestion at this point (especially since it's a blank server) is redo the server install with Bullseye only, then follow the install instructions:

```bash
sudo apt update && sudo apt install git
git clone --branch dev-branch https://github.com/FOGProject/fogproject
cd fogproject/bin
./installfog.sh
```

**Comment by DubbelF34140** [comment]
With Bullseye and a new virtual machine with just the commands sent: 

```
             └─28256 php-fpm: pool www

janv. 07 21:40:04 FogProject systemd[1]: Starting The PHP 7.4 FastCGI Process Ma                                                                                                                                                             nager...
janv. 07 21:40:04 FogProject systemd[1]: Started The PHP 7.4 FastCGI Process Man                                                                                                                                                             ager.

ERROR 1146 (42S02) at line 1: Table 'fog.globalSettings' doesn't exist
```
[fog_error_1.5.9.235.log](https://github.com/FOGProject/fogproject/files/10367140/fog_error_1.5.9.235.log)

**Comment by lukebarone** [comment]
Your log file is showing that `gettext` is installed (along with the PHP variant), so that part is fine. It seems like it is NOT creating the tables in the database though... I'll have to ask for some help on this one from one of the more seasoned contributors.

**Comment by DubbelF34140** [comment]
Ok but is it possible to know which version of debian you used for your test? So I can work on it?

**Comment by lukebarone** [comment]
I'm using 11.6, just as you are. I do the netinst, but that shouldn't make a difference.

**Comment by DubbelF34140** [comment]
Ok well I will test under debian 10 to see if it comes from my virtualization environment. When in doubt.

**Comment by Sebastian-Roth** [comment]
@DubbelF34140 I am pretty sure you just keep missing that one step the installer is asking you to do:

```
 * You still need to install/update your database schema.
 * This can be done by opening a web browser and going to:

   http://192.168.3.11/fog/management

 * Press [Enter] key when database is updated/installed.

 * Update fogstorage database password.........................Failed!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!! The installer was not able to run all the way to the end as   !!
!! something has caused it to fail. The following few lines are  !!
!! from the error log file which might help us figure out what's !!
!! wrong. Please add this information when reporting an error.   !!
!! As well you might want to take a look at the full error log   !!
!! in /root/fogproject-dev-branch/bin/error_logs/fog_error_1.5.9.235.log !!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

             └─22132 php-fpm: pool www

Jan 08 13:07:54 debian11-fog systemd[1]: Starting The PHP 7.4 FastCGI Process Manager...
Jan 08 13:07:54 debian11-fog systemd[1]: Started The PHP 7.4 FastCGI Process Manager.
ERROR 1146 (42S02) at line 1: Table 'fog.globalSettings' doesn't exist
```

Solution: Re-run the installer but this time open the URL as suggested, wait until the DB schema is created and then proceed with the installer by pressing ENTER.

**Comment by Sebastian-Roth** [comment]
Guess I was right here, closing. Let us know if you still need help with setting up FOG.
