### ISSUE TITLE
Bad links on website

### ISSUE THREAD

**Issue by Neustradamus** [FOGProject/fogproject#549]
On https://fogproject.org/, there is a bad link:
- Roadmap

On https://news.fogproject.org/, there is a bad link:
- DEVELOPER PORTAL

For example on https://news.fogproject.org/fog-1-5-9-officially-released/, there is a bad links:
- FOG Project -> https://news.fogproject.org/ must be https://fogproject.org/ and remove "HOME"

**Comment by Sebastian-Roth** [comment]
@Neustradamus Thanks for pointing this out! We definitely need to work on the website and the other online resources like news.fogproject.org more.

In the long run we really need to update the website and news.fogproject.org site as well. Just opened a new issue report to discuss #551.

> On https://fogproject.org/, there is a bad link:
> 
> * Roadmap

Removed for now as [waffle.io was shutdown some years back](https://projectmanagernews.com/general/what-happened-to-waffle-io/) and we don't have a new developer dashboard yet.

> On https://news.fogproject.org/, there is a bad link:
> 
> * DEVELOPER PORTAL
> 
> For example on https://news.fogproject.org/fog-1-5-9-officially-released/, there is a bad links:
> 
> * FOG Project -> https://news.fogproject.org/ must be https://fogproject.org/ and remove "HOME"

I myself am not an admin user on news.fogproject.org - either @mastacontrola might promote me to be an admin or can do the changes for us?

**Comment by Neustradamus** [comment]
@Sebastian-Roth: About the website, I have forgotten, at bottom, it is needed to update the ©.

About the forum, on https://forums.fogproject.org/, it is needed to update the menu at top "FOG Project" is the forum link, no link to https://fogproject.org/, at bottom, it is needed to update the © and maybe the forum software based.

About the wiki, it is needed to update maybe the mediawiki.

**Comment by Sebastian-Roth** [comment]
> About the website, I have forgotten, at bottom, it is needed to update the ©.

Good catch. I did change the date at he bottom of all the pages except the default index site. Fixed now.


> About the forum, on https://forums.fogproject.org/, it is needed to update the menu at top "FOG Project" is the forum link, no link to https://fogproject.org/

You are right, that can be confusing. I removed that link from the header altogether. People are in the forum already and don't need an extra link. For getting back to the fogproject.org website you can use the link at the bottom of each page.

> at bottom, it is needed to update the © and maybe the forum software based.

Copyright as well as forum software is updated now.

> About the wiki, it is needed to update maybe the mediawiki.

We are in the process of moving everything from the wiki to https://docs.fogproject.org/ and I have hardly enough time to look into updating the Mediawiki right now.


> For example on https://news.fogproject.org/fog-1-5-9-officially-released/, there is a bad links:
> * FOG Project -> https://news.fogproject.org/ must be https://fogproject.org/ and remove "HOME"

I think we'll move away from the old style news page soon - see #551.

**So I guess I can close this topic now. Feel free to re-open/post if you find more broken links.**

**Comment by Neustradamus** [comment]
@Sebastian-Roth: I think that "News" link must be added at the top of https://fogproject.org/ website.
Maybe other too like GitHub.

About "News", "DEVELOPER PORTAL", it is possible to remove it?

About "Forum", it is not possible to have "FOG Project" https://fogproject.org/ link at left top?

**Comment by Sebastian-Roth** [comment]
@Neustradamus said:
> I think that "News" link must be added at the top of https://fogproject.org/ website. Maybe other too like GitHub.

Those links are at the bottom of each page. Should be enough I reckon.

> About "News", "DEVELOPER PORTAL", it is possible to remove it?

I still don't have access to the news admin stuff. Maybe @mastacontrola can help us out here?

> About "Forum", it is not possible to have "FOG Project" https://fogproject.org/ link at left top?

I thought it might confuse people if the link pointed to https://forums.fogproject.org/ and is simply changed to https://fogproject.org/ at the same spot. Therefore I removed it. But yes, I can add this if you are sure it's a good idea and not confusing.
