### ISSUE TITLE
Run snapin on all associated hosts

### ISSUE THREAD

**Issue by osiktech** [FOGProject/fogproject#550]
Hi all

is there a way to run an associated snapin on all clients. I am looking for this feature to keep applications updated on all associated hosts. 

Let's say I have a software XYZ and I have 15 hosts. 5 hosts out of those 15 hosts have the snapin for XYZ associated. 

An updated version of XYZ was released, and now I want to up those 5 hosts with a single task instead of opening each of the 5 hosts, go to basic task, advanced task, single snapin, search for snapin, create snapin task. This is kind of tedious and the other way around would be super helpful for administrators.

Thanks in advance,

Osik

**Comment by darksidemilk** [comment]
If they're all in a group, you can do this with group task in the gui. You could even set it up in a schedule I'm pretty sure, but you'd need to update it as group membership changes

If that doesn't fit your needs, You could also do this with or without groups using the api. I have a powershell module https://www.powershellgallery.com/packages/FogApi/2302.5.26 to help get up and running with the api. I'm on a phone so can't really write out an example, but you could get all the hosts associated to the snapin and start a task to run that snapin. This could all be in a function/script you run at any time.

**Comment by osiktech** [comment]
@darksidemilk thank you very much, I was just looking in the wrong direction all the time. via basic task running on a group is exactly what I was looking for.

I'll have a look at your powershell module as well :)
