### ISSUE TITLE
LDAP Plugin - PHP 8 compatibility 

### ISSUE THREAD

**Issue by Rowlett** [FOGProject/fogproject#567]
LDAP Plugin currently not working with PHP 8.

Upgrade PHP to PHP 8.x

LDAP just provide authentication via AD.

 - FOG version: latest dev code
 - OS: Debian 12

**Comment by Neustradamus** [comment]
@Sebastian-Roth: Have you seen this ticket?

**Comment by Sebastian-Roth** [comment]
Sure I have, just don't have any time at the moment. Will take some weeks or anyone else needs to take care of this.


Am 19. Juli 2023 15:37:16 MESZ schrieb Neustradamus ***@***.***>:

**Comment by tomamplius** [comment]
I have issue with  PHP8.2

```
[Fri Jul 28 22:58:35.509195 2023] [proxy_fcgi:error] [pid 147938] [client 10.xx.xx.xx:36044] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught TypeError: ldap_unbind(): Argument #1 ($ldap) must be of type LDAP\\Connection, null given in /var/www/html/fog/lib/plugins/ldap/class/ldap.class.php:124\nStack trace:\n#0 /var/www/html/fog/lib/plugins/ldap/class/ldap.class.php(124): ldap_unbind()\n#1 /var/www/html/fog/lib/plugins/ldap/class/ldap.class.php(235): LDAP->__call()\n#2 /var/www/html/fog/lib/plugins/ldap/hooks/ldappluginhook.hook.php(126): LDAP->authLDAP()\n#3 /var/www/html/fog/lib/fog/hookmanager.class.php(86): LDAPPluginHook->checkAddUser()\n#4 /var/www/html/fog/lib/fog/user.class.php(139): HookManager->processEvent()\n#5 /var/www/html/fog/lib/fog/user.class.php(226): User->passwordValidate()\n#6 /var/www/html/fog/lib/fog/fogbase.class.php(2469): User->validatePw()\n#7 /var/www/html/fog/lib/pages/processlogin.class.php(151): FOGBase::attemptLogin()\n#8 /var/www/html/fog/management/index.php(31): ProcessLogin->processMainLogin()\n#9 {main}\n  thrown in /var/www/html/fog/lib/plugins/ldap/class/ldap.class.php o...', referer: http://fog.leolagrange-gestion.org/fog/management/index.php
```

**Comment by Sebastian-Roth** [comment]
@Rowlett @tomamplius Can you guys please pull the lates dev-branch to test and report back?

**Comment by imgurbot12** [comment]
@Sebastian-Roth 
I've updated and ran a test and came across a secondary error when trying to login over ldap using the FOG image on a workstation: ```
PHP message: PHP Fatal error:  Uncaught Error: LDAP connection has already been closed in /var/www/html/fog/lib/plugins/ldap/class/ldap.class.php:124\nStack trace:\n#0 /var/www/html/fog/lib/plugins/ldap/class/ldap.class.php(124): ldap_unbind()
```

I also noticed a quirk when logging in on the web-portal. If you press Enter to complete the login, the LDAP component is never triggered, but if you click the Login button it works which is quite confusing lol.

**Comment by imgurbot12** [comment]
I've managed to make it work by just avoiding the error altogether, but I'm not sure if this is the best way to handle things:
```php
        try {
            $this->unbind();
        } catch (TypeError $e) {
        } catch (Throwable $e) {}
```

**Comment by Sebastian-Roth** [comment]
@imgurbot12 Thanks for bringing this up. I guess ignoring all errors on `unbind` is not great but still fine.

@tomamplius Would you be able to send in another PR?

**Comment by tomamplius** [comment]
#573 thank you

**Comment by imgurbot12** [comment]
> I also noticed a quirk when logging in on the web-portal. If you press Enter to complete the login, the LDAP component is never triggered, but if you click the Login button it works which is quite confusing lol.

Is there any way to potentially solve this problem as well? I have no idea what would be causing the behavior difference but it does make it a little inconvenient when logging in
