### ISSUE TITLE
Random Hosts uncheck Service Settings

### ISSUE THREAD

**Issue by ODSMarcus** [FOGProject/fogproject#571]
**Describe the bug**
I've been unable to prove how this is occurring, but it happens to random hosts. Some new hosts, some that have been in place for many months. We will rename a host and notice it never renames, checking the log shows its HostNameChanger is disabled. Sure enough, if you check the Service Settings page, they are unchecked. It was imaged, registered itself properly, and named itself originally but now they are all unchecked

**Expected behavior**
These boxes should never uncheck themselves

**Software (please complete the following information):**
 - FOG version 1.5.10.5
 - OS: Centos 8

**Additional context**
I also have Groups enabled, and the services are and have been enabled for groups. These do not uncheck themselves.

**Comment by ODSMarcus** [comment]
I had one freshly imaged client. I did a full registration. It imaged fine and sat at login. None of the boxes were checked at full registration. Once I checked all the services boxes, it immediately renamed and restarted. The boxes unchecked themselves again. I checked the boxes again, it rebooted and joined AD.

Computer rebooted...guess what, all boxes unchecked again.

**Comment by mastacontrola** [comment]
Would you be willing to try out working-1.6?

This sounds to me to be potentially related to the FOG Client cycles and reboots that might be attempting to save the host. There may be a way to fix this but I cannot see all the potentials here.

While i'm not going to say that the issue you're describing here isn't present in working-1.6 (There was a period of time I forcibly introduced in that branch accidentally -- Trying to allow FOG CLient checkins to update the pingstatus of a machine.) And it made what you're describing ever more present in my head....

**Comment by darksidemilk** [comment]
I'm pretty sure this was also fixed in the dev-branch, but I can confirm for sure that it is fixed in working-1.6

**Comment by mastacontrola** [comment]
Please update to working-1.6. Closing this issue. While I'm unsure if it's fixed in dev-branch/1.5.10, I am certain it's working appropriately in working-1.6 as @darksidemilk as indicated.

Closing.

Thank you for reporting and if you can, let us know.
