### ISSUE TITLE
Install script ask for web port instead of accepting the default of 80

### ISSUE THREAD

**Issue by t3kg33k** [FOGProject/fogproject#574]
**Is your feature request related to a problem? Please describe.**
In an attempt to install FOG on a machine with an existing web server the install fails with the expectation that FOG will be running on port 80 when port 80 is already used on an existing service on the server.

**Describe the solution you'd like**
In the install script there should be an option to ask which port preference should be used for FOG web server.

**Describe alternatives you've considered**
An alternative could be to use a different web port other than port 80. Perhaps 8080

**Additional context**

**Comment by Neustradamus** [comment]
@FOGProject team: Have you seen this ticket?

**Comment by lukebarone** [comment]
Sorry for the late reply.

I'm not saying it can't be done, but FOG does expect to be ran on a fresh new server, not one that has already been configured for other use. There is an install option to not create the VirtualHost file in Apache2 (`--no-vhost`) during the installation - have you tried that one?

**Comment by t3kg33k** [comment]
I just ended up buying a Lenovo ThinkCentre M700 Tiny on Ebay and putting it on a standalone install of RHEL.
