### ISSUE TITLE
Rocky 8 install won't work

### ISSUE THREAD

**Issue by lukebarone** [FOGProject/fogproject#577]
**Describe the bug**
When im running through the installation setup I get the below error.
package remi-release-8* is not installed
error: Failed dependencies:
(redhat-release >=8.8 or centos-stream-release >=8) is needed by remi-release-8.8.1.el8.remi.noarch
Retrieving https://rpms.remirepo.net/enterprise/remi-release-8.rpm

Then nothing happens. I thought you did not need remi release for rocky8.7

**Expected behavior**
Install to succeed on Rocky 8.7

**Additional context**
[Add any other context about the problem here.
](https://forums.fogproject.org/topic/16990/fog-1-5-10-install-on-rocky-linux-8-7-installation-error)

** Created for @lukebarone to monitor**

**Comment by lukebarone** [comment]
So on a fresh Rocky 8.9 (the latest version in the 8.x stream) available, the install goes without a hitch.

**Comment by mastacontrola** [comment]
Is this still an issue? Was it more possible just some oddity with Rocky 8.7?

**Comment by lukebarone** [comment]
> Is this still an issue? Was it more possible just some oddity with Rocky 8.7?

Must've been. The user doesn't seem active anymore, and it worked for me. I'll close this one
