### ISSUE TITLE
Unable to register to the forum

### ISSUE THREAD

**Issue by pcnr-ma** [FOGProject/fogproject#591]
Good morning everyone and sorry if I'm in the wrong place, not really skilled on github
I can't register on the forum, I always get the Captcha not verified errore
Tested on 2 Windows PCs with 3 Chrome and Edge (also incognito), Chrome on android, Chromium on a Raspbian (this one doesn't even show the images for the captcha)
Do you have any ideas how I can fix that? I'd like to ask a few questions about my deployment on the forum

Thanks in advance!
Paolo

**Comment by mastacontrola** [comment]
I need to see more information to potentially be able to help.

If captcha is indeed causing an issue I can temporarily disable but lately we've been having spam issues.

**Comment by pcnr-ma** [comment]
I don't know if you already did something, but i retried now to give you some screenshots and now it worked
The only difference is that i used a simple password instead of a chrome long and complex generated password

**Comment by mastacontrola** [comment]
I have switched from using hCaptcha to trying to use Google Captcha, can you please try from there?

**Comment by pcnr-ma** [comment]
> I have switched from using hCaptcha to trying to use Google Captcha, can you please try from there?

Fastest fix ever, thanks!

**Comment by mastacontrola** [comment]
Closing then, thank you!
