### ISSUE TITLE
./install.sh script fails to install dhcp

### ISSUE THREAD

**Issue by SterlingGreeson** [FOGProject/fogproject#593]
**Describe the bug**
**./install.sh fails on centos 9 and ubuntu 24, 22, 20 versions.** 

error produced via script below

 * Backing up database.........................................Done

 * You still need to install/update your database schema.
 * This can be done by opening a web browser and going to:

   http://10.0.0.10/fog/management

 * Press [Enter] key when database is updated/installed.

 * Update fogstorage database password.........................OK
 * Granting access to fogstorage database user.................OK
 * Setting up storage..........................................OK
 * Setting up and starting DHCP Server.........................Failed!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!! The installer was not able to run all the way to the end as   !!
!! something has caused it to fail. The following few lines are  !!
!! from the error log file which might help us figure out what's !!
!! wrong. Please add this information when reporting an error.   !!
!! As well you might want to take a look at the full error log   !!
!! in /root/fogproject/bin/error_logs/fog_error_1.5.10.log !!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Jun 16 14:05:54 localhost.localdomain dhcpd[90510]:
Jun 16 14:05:54 localhost.localdomain dhcpd[90510]: exiting.
Jun 16 14:05:54 localhost.localdomain systemd[1]: dhcpd.service: Main process exited, code=exited, status=1/FAILURE
Jun 16 14:05:54 localhost.localdomain systemd[1]: dhcpd.service: Failed with result 'exit-code'.
Jun 16 14:05:54 localhost.localdomain systemd[1]: Failed to start DHCPv4 Server Daemon.

**upon review; I see that in the dhcp.conf files for BOTH redhat and debian flavors have the following errors inside their configs.** 

> #### Specify subnet of ether device you do NOT want service.
> #### For systems with two or more ethernet devices.
> #### subnet 136.165.0.0 netmask 255.255.0.0 {}
> subnet 10.0.0.0 netmask 255.0.0.0{
>     option subnet-mask 255.0.0.0;
>     range dynamic-bootp 10.0.0.10 **_Invalid IP Passed_**;
>     default-lease-time 21600;
>     max-lease-time 43200;
>     option routers 10.0.0.1;
>     option domain-name-servers 10.0.0.1;
>     next-server 10.0.0.10;
> 

**To Reproduce**
follow steps in the instructions on FOG website, seems to be a bug inside script. 
https://docs.fogproject.org/en/latest/installation/server/install-fog-server/#choosing-a-fog-version 

**Screenshots**
![image](https://github.com/FOGProject/fogproject/assets/49912786/e75c72ea-d07d-43d1-b52d-0e0d6sn2140c06)

![image](https://github.com/FOGProject/fogproject/assets/49912786/51310467-80d0-4cc6-9161-ededdce55593)
r
**Software (please complete the following information):**
FOG master branch
OS versions listed at top

**Additional context**
changing the config file to a valid IP does not fix FOG itself; I am unable to PXE boot to FOG server, and it seems that dhpd6.conf does not at all populate

**Comment by mastacontrola** [comment]
I'm assuming this wasn't really an issue?

Just trying to understand what this was about.
