### ISSUE TITLE
memtest and DBAN won’t boot from pxe

### ISSUE THREAD

**Issue by mentaluproar** [FOGProject/fogproject#594]
I keep getting an error when I try to use memtest or DBAN from the PXE boot menu. I followed the guide but this happened anyway. What’s wrong?

Could not select: Exec format error (https://ipxe.org/2008081)
Could not boot: Exec format error (https://ipxe.org/2e008081)
Could not boot: Exec format
Chainloading failed

also, there’s an issue with the forum where I can’t create a new account because it wants me to do a second captcha without showing it to me, across multiple browsers and even mobile.

**Comment by mastacontrola** [comment]
I'm not sure what's wrong but the forums would be a better place for this.

I confirmed the issue you were describing where capture shows a second captcha and have found and removed the secondary one.  Apologies for that oversite and hope that you can create your account now.

Thank you
