### ISSUE TITLE
FOG Integration in LTSP Menu

### ISSUE THREAD

**Issue by renatogfilhinho** [FOGProject/fogproject#595]
How can we help you?

Hello my friends, is it possible to create an entry in the LTSP menu pointing to Fog? Today, LTSP is working smoothly and I would like to include Fog on another server, but using LTSP.

**Comment by mastacontrola** [comment]
I'm just being honest here, but I don't know what LTSP is?

**Comment by darksidemilk** [comment]
I had to look it up too. It's a separate pxe boot menu it looks like https://ltsp.org/
I've never used it. 
I imagine there will be a wait to add a chainload pxe command to get to the fog boot menu but I don't know anything about how to configure that system

**Comment by renatogfilhinho** [comment]
LTSP is a terminal server service for Linux, very good by the way, I've been using it for a while. It allows stations without a hard drive to access the system via the network.

**Comment by darksidemilk** [comment]
It seems like LTSP either uses ipxe or can boot from LTSP to ipxe, you can chainload the fog pxe menu from pxe. I just don't know enough about the LTSP config to say where to put such a thing.

**Comment by renatogfilhinho** [comment]
Yes, the idea is to boot via pxe, go to LTSP and the Boot Menu, and choose FOG.

**Comment by darksidemilk** [comment]
I don't have an instance of LTSP setup so I can't test this, but I imagine you should be able to add a menu entry in LTSP that does a custom ipxe command?
And you can do a chain command like this one

```
chain http://<fog-server-ip>/fog/service/ipxe/boot.php
```
You might need params though, you could try just copying the whole contents of `/tftpboot/default.ipxe` from your fog server, which is where I took that snippet from.

**Comment by mastacontrola** [comment]
I'm really confused on what exactly is being asked here.

1. Are you asking us to add/figure out how to add LTSP to FOG's boot menu?
2. Are you asking us how we might add FOG's boot abilities into LTSP?

If it's the 1st one, I'm sure we could figure that part out though it would be incredibly low on the list of things at this point in time. Not that it couldn't be done and once figured out just post what you find either here or on the forums. (Note, this change/request could be done without a developement process as you can create your own iPXE menu's in FOG.

If it's the 2nd one, I'm afraid that's not something we can do. First, even though it may use iPXE as a base line, how their binaries are compiled and built may not have all the requirements rely on. Second, we don't control the development or requests for LTSP.

**Comment by renatogfilhinho** [comment]
I thank everyone for their extreme attention and time.
