### ISSUE TITLE
Unable to install FOG Server 1.5.10.47

### ISSUE THREAD

**Issue by abotzung** [FOGProject/fogproject#602]
Hello,

**Describe the bug**
I'm unable to install FOG Server on a fresh Debian installation.

**To Reproduce**
1. Download and install Debian 12.6
2. Install FOG from dev-branch

**Expected behavior**
Installer proceed to install FOG.

**Current behavior**
```
(...)
 * Resetting SSL Permissions...................................OK
 * Setting up Apache virtual host (SSL)........................OK
 * Starting and checking status of web services................OK
 * Changing permissions on apache log files....................chmod: impossible d'accéder à '/var/www/fog//fog_login_*.log': Aucun fichier ou dossier de ce type
Failed!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!! The installer was not able to run all the way to the end as   !!
!! something has caused it to fail. The following few lines are  !!
!! from the error log file which might help us figure out what's !!
!! wrong. Please add this information when reporting an error.   !!
!! As well you might want to take a look at the full error log   !!
!! in /root/fogproject-dev-branch/bin/error_logs/fog_error_1.5.10.47.log !!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

             ├─18918 "php-fpm: pool www"
             └─18919 "php-fpm: pool www"

août 03 02:53:52 fogserver systemd[1]: Starting php8.2-fpm.service - The PHP 8.2 FastCGI Process Manager...

```

**Software (please complete the following information):**
 - FOG version (dev-branch/latest)
 - OS: Debian 12.6

**Additional context**
I think the error comes from the last commit : 
https://github.com/FOGProject/fogproject/blob/c2d9d8ffda1a1299334e9a0d6ca2fb007f6e4b04/lib/common/functions.sh#L2403
In a fresh install, theses files "fog_login_*.log" dosent exist yet, so the install will fail. 
A workaround, is to create dummy files just before the line :
```
    (...)
    chmod +rx $apacheacclog
    chown -R ${apacheuser}:${apacheuser} $webdirdest
    touch $webdirdest/fog_login_accepted.log
    touch $webdirdest/fog_login_failed.log
    chmod 0200 $webdirdest/fog_login_*.log
    errorStat $?
    (...)
```

Also, this installation also failing on stable branch, and working1.6.
All builds for turnkey-fogserver (https://foguefi.botzung.fr/fog/) fails with the same error : 
![image](https://github.com/user-attachments/assets/3e66c45b-c03b-4f1c-a8b5-1db6b2ad5947)
![image](https://github.com/user-attachments/assets/d6fcfc76-199f-41bf-aa05-517596293d2e)

Cheers,
Alexandre

**Comment by asivre02** [comment]
Hello,

do you have solution on that problem???

**Comment by mastacontrola** [comment]
I just pushed 2 changes, both of which should address this issue. Please pull dev-branch again (you'll see it says 1.5.10.47.0 is the version, or 1.6.0-beta.1400.

Thank you.

**Comment by abotzung** [comment]
Hello,

FOG install successfully.

Thank you, have a nice day !

**Comment by asivre02** [comment]
Hi Fogproject Team,
Fog Installed Successfully

Thank you so much!


    On Saturday, August 3, 2024 at 08:18:21 PM GMT+8, Alex B. ***@***.***> wrote:  
 
 


Hello,

FOG install successfully.

Thank you, have a nice day !
