### ISSUE TITLE
Dashboard graph timeout

### ISSUE THREAD

**Issue by MilanKerslager** [FOGProject/fogproject#62]
The nice graph on the dasboard stops receiving updates after password expires (page authentication expires). It works again after page reload (pass resend) but shows graph from the beginning since then.
I have latest trunk (2015-09-17).

**Comment by mastacontrola** [comment]
I don't consider this an issue.  If the login session has expired, you shouldn't be seeing the data anyway, as the session expired.  I don't understand how this is an issue.
