### ISSUE TITLE
Unable to set password in Storage managment

### ISSUE THREAD

**Issue by MilanKerslager** [FOGProject/fogproject#63]
I was uploading my first image and after Partclone was done I have got an error message on the screen about bad FTP password when connecting to the client (non-resizeable whole disc).
I tried to change password at Storage management (I have only one node with storage & Fog web UI), but this password could not be changed.
The password could be changed at global FOG configuration - FOG Settings (FOG_TFTP_FTP_PASSWORD) and then Resizeable disc worked.
I made next try and it seems it does not work on Non-resizable-disc (wrong password again).
I recreated master node in Storage managment and the password could be set.
I wonder what both passwords are for...
I have latest trunk installed (2015-09-17).

**Comment by mastacontrola** [comment]
I believe you have what's known as auto fill in your window.  Have the browser either stop autofilling, or just get used to this.

FOG_TFTP_FTP_PASSWORD has nothing to do with uploads.
