### ISSUE TITLE
raspberry Pi 5 install script stop with the error there is a full log included

### ISSUE THREAD

**Issue by spamkutu** [FOGProject/fogproject#646]
cat /root/fogproject/bin/error_logs/fog_error_1.5.10.1593.log

/usr/bin/lsb_release
/usr/bin/systemctl
systemd
ln: '/lib/systemd/system/mysql.service' sembolik bağı oluşturulamadı: Dosya var
ln: '/lib/systemd/system/mysqld.service' sembolik bağı oluşturulamadı: Dosya var
ln: '/etc/systemd/system/mysql.service' sembolik bağı oluşturulamadı: Dosya var
ln: '/etc/systemd/system/mysqld.service' sembolik bağı oluşturulamadı: Dosya var
/usr/sbin/iptables
dpkg-query: mysql-server ile eşleşen bir paket bulunamadı
Paket listeleri okunuyor...
Bağımlılık ağacı oluşturuluyor...
Durum bilgisi okunuyor...
curl zaten en yeni sürümde (7.88.1-10+deb12u7).
0 paket yükseltilecek, 0 yeni paket kurulacak, 0 paket kaldırılacak ve 7 paket yükseltilmeyecek.
Testing DNS name resolution (neverssl.com)... OK
Testing HTTP connection (http://neverssl.com)... OK
Testing HTTPS connection (https://github.com)... OK
Aynı:  1 https://download.docker.com/linux/debian bookworm InRelease
Aynı:  2 http://deb.debian.org/debian bookworm InRelease
Aynı:  3 http://archive.raspberrypi.com/debian bookworm InRelease
Aynı:  4 http://deb.debian.org/debian-security bookworm-security InRelease
Aynı:  5 http://deb.debian.org/debian bookworm-updates InRelease
Yoksay:6 https://deb.nodesource.com/node_.x nodistro InRelease
Hata:  7 https://deb.nodesource.com/node_.x nodistro Release
  404  Not Found [IP: 172.67.10.205 443]
Paket listeleri okunuyor...
E: 'https://deb.nodesource.com/node_.x nodistro Release' deposunda Release dosyası yok.
ii  apache2        2.4.62-1~deb12u1 arm64        Apache HTTP Server
ii  bc             1.07.1-3     arm64        GNU bc arbitrary precision calculator language
ii  build-essential 12.9         arm64        Informational list of build-essential packages
ii  cpp            4:12.2.0-3   arm64        GNU C preprocessor (cpp)
ii  curl           7.88.1-10+deb12u7 arm64        command line tool for transferring data with URL syntax
ii  g++            4:12.2.0-3   arm64        GNU C++ compiler
ii  gawk           1:5.2.1-2    arm64        GNU awk, a pattern scanning and processing language
ii  gcc            4:12.2.0-3   arm64        GNU C compiler
ii  genisoimage    9:1.1.11-3.4 arm64        Creates ISO-9660 CD-ROM filesystem images
ii  gettext        0.21-12      arm64        GNU Internationalization utilities
ii  git            1:2.39.5-0+deb12u1 arm64        fast, scalable, distributed revision control system
ii  gzip           1.12-1       arm64        GNU compression utilities
ii  htmldoc        1.9.16-1     arm64        HTML processor that generates indexed HTML, PS, and PDF
ii  isolinux       3:6.04~git20190206.bf6db5b4+dfsg1-3 all          collection of bootloaders (ISO 9660 bootloader)
ii  lftp           4.9.2-2      arm64        Sophisticated command-line FTP/HTTP/BitTorrent client programs
ii  libapache2-mod-php 2:8.2+93     all          server-side, HTML-embedded scripting language (Apache 2 module) (default)
ii  libc6:arm64    2.36-9+rpt2+deb12u8 arm64        GNU C Library: Shared libraries
ii  libcurl4:arm64 7.88.1-10+deb12u7 arm64        easy-to-use client-side URL transfer library (OpenSSL flavour)
ii  liblzma-dev:arm64 5.4.1-0.2    arm64        XZ-format compression library - development files
ii  m4             1.4.19-3     arm64        macro processing language
mariadb-client-core
mariadb-client
ii  mariadb-client 1:10.11.6-0+deb12u1 arm64        MariaDB database client binaries
ii  mariadb-client 1:10.11.6-0+deb12u1 arm64        MariaDB database client binaries
mariadb-server
mariadb-server-core
mariadb-server-10.5
ii  mariadb-server 1:10.11.6-0+deb12u1 arm64        MariaDB database server binaries
ii  mariadb-server 1:10.11.6-0+deb12u1 arm64        MariaDB database server binaries
ii  net-tools      2.10-0.1     arm64        NET-3 networking toolkit
ii  nfs-kernel-server 1:2.6.2-4    arm64        support for NFS kernel server
ii  openssh-server 1:9.2p1-2+deb12u3 arm64        secure shell (SSH) server, for secure access from remote machines
ii  php            2:8.2+93     all          server-side, HTML-embedded scripting language (default)
ii  php-bcmath     2:8.2+93     all          Bcmath module for PHP [default]
ii  php-cli        2:8.2+93     all          command-line interpreter for the PHP scripting language (default)
ii  php-curl       2:8.2+93     all          CURL module for PHP [default]
ii  php-fpm        2:8.2+93     all          server-side, HTML-embedded scripting language (FPM-CGI binary) (default)
ii  php-gd         2:8.2+93     all          GD module for PHP [default]
ii  php-intl       2:8.2+93     all          Internationalisation module for PHP [default]
php-json-schema
php-json
ii  php-json       2:8.2+93     all          JSON module for PHP [default]
ii  php-ldap       2:8.2+93     all          LDAP module for PHP [default]
ii  php-mbstring   2:8.2+93     all          MBSTRING module for PHP [default]
php-mysql
ii  php-mysql      2:8.2+93     all          MySQL module for PHP [default]
php-mysql
ii  php-mysql      2:8.2+93     all          MySQL module for PHP [default]
ii  tar            1.34+dfsg-1.2+deb12u1 arm64        GNU version of the tar archiving utility
ii  tftpd-hpa      5.2+20150808-1.4 arm64        HPA's tftp server
ii  tftp-hpa       5.2+20150808-1.4 arm64        HPA's tftp client
ii  unzip          6.0-28       arm64        De-archiver for .zip files
ii  vsftpd         3.0.3-13+b2  arm64        lightweight, efficient FTP server written for security
ii  wget           1.21.3-1+b1  arm64        retrieves files from the web
ii  zlib1g:arm64   1:1.2.13.dfsg-1 arm64        compression library - runtime
Paket listeleri okunuyor...
Bağımlılık ağacı oluşturuluyor...
Durum bilgisi okunuyor...
apache2 zaten en yeni sürümde (2.4.62-1~deb12u1).
bc zaten en yeni sürümde (1.07.1-3).
build-essential zaten en yeni sürümde (12.9).
cpp zaten en yeni sürümde (4:12.2.0-3).
curl zaten en yeni sürümde (7.88.1-10+deb12u7).
g++ zaten en yeni sürümde (4:12.2.0-3).
gawk zaten en yeni sürümde (1:5.2.1-2).
gcc zaten en yeni sürümde (4:12.2.0-3).
genisoimage zaten en yeni sürümde (9:1.1.11-3.4).
gettext zaten en yeni sürümde (0.21-12).
git zaten en yeni sürümde (1:2.39.5-0+deb12u1).
gzip zaten en yeni sürümde (1.12-1).
htmldoc zaten en yeni sürümde (1.9.16-1).
isolinux zaten en yeni sürümde (3:6.04~git20190206.bf6db5b4+dfsg1-3).
lftp zaten en yeni sürümde (4.9.2-2).
libapache2-mod-php zaten en yeni sürümde (2:8.2+93).
libc6 zaten en yeni sürümde (2.36-9+rpt2+deb12u8).
libcurl4 zaten en yeni sürümde (7.88.1-10+deb12u7).
liblzma-dev zaten en yeni sürümde (5.4.1-0.2).
m4 zaten en yeni sürümde (1.4.19-3).
mariadb-client zaten en yeni sürümde (1:10.11.6-0+deb12u1).
mariadb-server zaten en yeni sürümde (1:10.11.6-0+deb12u1).
net-tools zaten en yeni sürümde (2.10-0.1).
nfs-kernel-server zaten en yeni sürümde (1:2.6.2-4).
openssh-server zaten en yeni sürümde (1:9.2p1-2+deb12u3).
php zaten en yeni sürümde (2:8.2+93).
php-bcmath zaten en yeni sürümde (2:8.2+93).
php-cli zaten en yeni sürümde (2:8.2+93).
php-curl zaten en yeni sürümde (2:8.2+93).
php-fpm zaten en yeni sürümde (2:8.2+93).
php-gd zaten en yeni sürümde (2:8.2+93).
php-intl zaten en yeni sürümde (2:8.2+93).
php-json zaten en yeni sürümde (2:8.2+93).
php-ldap zaten en yeni sürümde (2:8.2+93).
php-mbstring zaten en yeni sürümde (2:8.2+93).
php-mysql zaten en yeni sürümde (2:8.2+93).
tar zaten en yeni sürümde (1.34+dfsg-1.2+deb12u1).
tftpd-hpa zaten en yeni sürümde (5.2+20150808-1.4).
tftp-hpa zaten en yeni sürümde (5.2+20150808-1.4).
unzip zaten en yeni sürümde (6.0-28).
vsftpd zaten en yeni sürümde (3.0.3-13+b2).
wget zaten en yeni sürümde (1.21.3-1+b1).
zlib1g zaten en yeni sürümde (1:1.2.13.dfsg-1).
Yükseltme hesaplanıyor...
Aşağıdaki YENİ paketler kurulacak:
  linux-headers-6.6.47+rpt-common-rpi linux-headers-6.6.47+rpt-rpi-2712
  linux-headers-6.6.47+rpt-rpi-v8 linux-image-6.6.47+rpt-rpi-2712
  linux-image-6.6.47+rpt-rpi-v8 linux-kbuild-6.6.47+rpt
Aşağıdaki paketlerin mevcut durumları korunacak:
  chromium-browser chromium-browser-l10n rpi-chromium-mods
Aşağıdaki paketler yükseltilecek:
  linux-headers-rpi-2712 linux-headers-rpi-v8 linux-image-rpi-2712
  linux-image-rpi-v8
4 paket yükseltilecek, 6 yeni paket kurulacak, 0 paket kaldırılacak ve 3 paket yükseltilmeyecek.
70,5 MB arşiv dosyası indirilecek.
Bu işlem tamamlandıktan sonra 122 MB ek disk alanı kullanılacak.
İndir: 1 http://archive.raspberrypi.com/debian bookworm/main arm64 linux-headers-6.6.47+rpt-common-rpi all 1:6.6.47-1+rpt1 [8.225 kB]
İndir: 2 http://archive.raspberrypi.com/debian bookworm/main arm64 linux-image-6.6.47+rpt-rpi-2712 arm64 1:6.6.47-1+rpt1 [29,5 MB]
İndir: 3 http://archive.raspberrypi.com/debian bookworm/main arm64 linux-kbuild-6.6.47+rpt arm64 1:6.6.47-1+rpt1 [1.012 kB]
İndir: 4 http://archive.raspberrypi.com/debian bookworm/main arm64 linux-headers-6.6.47+rpt-rpi-2712 arm64 1:6.6.47-1+rpt1 [1.128 kB]
İndir: 5 http://archive.raspberrypi.com/debian bookworm/main arm64 linux-image-6.6.47+rpt-rpi-v8 arm64 1:6.6.47-1+rpt1 [29,5 MB]
İndir: 6 http://archive.raspberrypi.com/debian bookworm/main arm64 linux-headers-6.6.47+rpt-rpi-v8 arm64 1:6.6.47-1+rpt1 [1.128 kB]
İndir: 7 http://archive.raspberrypi.com/debian bookworm/main arm64 linux-headers-rpi-2712 arm64 1:6.6.47-1+rpt1 [1.164 B]
İndir: 8 http://archive.raspberrypi.com/debian bookworm/main arm64 linux-headers-rpi-v8 arm64 1:6.6.47-1+rpt1 [1.156 B]
İndir: 9 http://archive.raspberrypi.com/debian bookworm/main arm64 linux-image-rpi-2712 arm64 1:6.6.47-1+rpt1 [1.424 B]
İndir: 10 http://archive.raspberrypi.com/debian bookworm/main arm64 linux-image-rpi-v8 arm64 1:6.6.47-1+rpt1 [1.420 B]
apt-listchanges: Reading changelogs...
13 sn.'de 70,5 MB alındı (5.522 kB/s)
Daha önce seçili olmayan linux-headers-6.6.47+rpt-common-rpi paketi seçiliyor.
(Veritabanı okunuyor ... 286563 dosya veya dizin kurulu durumda.)
Paket açılacak: .../0-linux-headers-6.6.47+rpt-common-rpi_1%3a6.6.47-1+rpt1_all.deb ...
Paket açılıyor: linux-headers-6.6.47+rpt-common-rpi (1:6.6.47-1+rpt1) ...
Daha önce seçili olmayan linux-image-6.6.47+rpt-rpi-2712 paketi seçiliyor.
Paket açılacak: .../1-linux-image-6.6.47+rpt-rpi-2712_1%3a6.6.47-1+rpt1_arm64.deb ...
Paket açılıyor: linux-image-6.6.47+rpt-rpi-2712 (1:6.6.47-1+rpt1) ...
Daha önce seçili olmayan linux-kbuild-6.6.47+rpt paketi seçiliyor.
Paket açılacak: .../2-linux-kbuild-6.6.47+rpt_1%3a6.6.47-1+rpt1_arm64.deb ...
Paket açılıyor: linux-kbuild-6.6.47+rpt (1:6.6.47-1+rpt1) ...
Daha önce seçili olmayan linux-headers-6.6.47+rpt-rpi-2712 paketi seçiliyor.
Paket açılacak: .../3-linux-headers-6.6.47+rpt-rpi-2712_1%3a6.6.47-1+rpt1_arm64.deb ...
Paket açılıyor: linux-headers-6.6.47+rpt-rpi-2712 (1:6.6.47-1+rpt1) ...
Daha önce seçili olmayan linux-image-6.6.47+rpt-rpi-v8 paketi seçiliyor.
Paket açılacak: .../4-linux-image-6.6.47+rpt-rpi-v8_1%3a6.6.47-1+rpt1_arm64.deb ...
Paket açılıyor: linux-image-6.6.47+rpt-rpi-v8 (1:6.6.47-1+rpt1) ...
Daha önce seçili olmayan linux-headers-6.6.47+rpt-rpi-v8 paketi seçiliyor.
Paket açılacak: .../5-linux-headers-6.6.47+rpt-rpi-v8_1%3a6.6.47-1+rpt1_arm64.deb ...
Paket açılıyor: linux-headers-6.6.47+rpt-rpi-v8 (1:6.6.47-1+rpt1) ...
Paket açılacak: .../6-linux-headers-rpi-2712_1%3a6.6.47-1+rpt1_arm64.deb ...
Paket açılıyor: linux-headers-rpi-2712 (1:6.6.31-1+rpt1) üzerine (1:6.6.47-1+rpt1) ...
Paket açılacak: .../7-linux-headers-rpi-v8_1%3a6.6.47-1+rpt1_arm64.deb ...
Paket açılıyor: linux-headers-rpi-v8 (1:6.6.31-1+rpt1) üzerine (1:6.6.47-1+rpt1) ...
Paket açılacak: .../8-linux-image-rpi-2712_1%3a6.6.47-1+rpt1_arm64.deb ...
Paket açılıyor: linux-image-rpi-2712 (1:6.6.31-1+rpt1) üzerine (1:6.6.47-1+rpt1) ...
Paket açılacak: .../9-linux-image-rpi-v8_1%3a6.6.47-1+rpt1_arm64.deb ...
Paket açılıyor: linux-image-rpi-v8 (1:6.6.31-1+rpt1) üzerine (1:6.6.47-1+rpt1) ...
Ayarlanıyor: linux-image-6.6.47+rpt-rpi-2712 (1:6.6.47-1+rpt1) ...
/etc/kernel/postinst.d/initramfs-tools:
update-initramfs: Generating /boot/initrd.img-6.6.47+rpt-rpi-2712
'/boot/initrd.img-6.6.47+rpt-rpi-2712' -> '/boot/firmware/initramfs_2712'
/etc/kernel/postinst.d/z50-raspi-firmware:
'/boot/vmlinuz-6.6.47+rpt-rpi-2712' -> '/boot/firmware/kernel_2712.img'
Ayarlanıyor: linux-image-6.6.47+rpt-rpi-v8 (1:6.6.47-1+rpt1) ...
/etc/kernel/postinst.d/initramfs-tools:
update-initramfs: Generating /boot/initrd.img-6.6.47+rpt-rpi-v8
'/boot/initrd.img-6.6.47+rpt-rpi-v8' -> '/boot/firmware/initramfs8'
/etc/kernel/postinst.d/z50-raspi-firmware:
'/boot/vmlinuz-6.6.47+rpt-rpi-v8' -> '/boot/firmware/kernel8.img'
Ayarlanıyor: linux-kbuild-6.6.47+rpt (1:6.6.47-1+rpt1) ...
Ayarlanıyor: linux-headers-6.6.47+rpt-common-rpi (1:6.6.47-1+rpt1) ...
Ayarlanıyor: linux-headers-6.6.47+rpt-rpi-v8 (1:6.6.47-1+rpt1) ...
Ayarlanıyor: linux-image-rpi-2712 (1:6.6.47-1+rpt1) ...
Ayarlanıyor: linux-headers-6.6.47+rpt-rpi-2712 (1:6.6.47-1+rpt1) ...
Ayarlanıyor: linux-headers-rpi-2712 (1:6.6.47-1+rpt1) ...
Ayarlanıyor: linux-image-rpi-v8 (1:6.6.47-1+rpt1) ...
Ayarlanıyor: linux-headers-rpi-v8 (1:6.6.47-1+rpt1) ...
ii  apache2        2.4.62-1~deb12u1 arm64        Apache HTTP Server
ii  bc             1.07.1-3     arm64        GNU bc arbitrary precision calculator language
ii  build-essential 12.9         arm64        Informational list of build-essential packages
ii  cpp            4:12.2.0-3   arm64        GNU C preprocessor (cpp)
ii  curl           7.88.1-10+deb12u7 arm64        command line tool for transferring data with URL syntax
ii  g++            4:12.2.0-3   arm64        GNU C++ compiler
ii  gawk           1:5.2.1-2    arm64        GNU awk, a pattern scanning and processing language
ii  gcc            4:12.2.0-3   arm64        GNU C compiler
ii  genisoimage    9:1.1.11-3.4 arm64        Creates ISO-9660 CD-ROM filesystem images
ii  gettext        0.21-12      arm64        GNU Internationalization utilities
ii  git            1:2.39.5-0+deb12u1 arm64        fast, scalable, distributed revision control system
ii  gzip           1.12-1       arm64        GNU compression utilities
ii  htmldoc        1.9.16-1     arm64        HTML processor that generates indexed HTML, PS, and PDF
ii  isolinux       3:6.04~git20190206.bf6db5b4+dfsg1-3 all          collection of bootloaders (ISO 9660 bootloader)
ii  lftp           4.9.2-2      arm64        Sophisticated command-line FTP/HTTP/BitTorrent client programs
ii  libapache2-mod-php 2:8.2+93     all          server-side, HTML-embedded scripting language (Apache 2 module) (default)
ii  libc6:arm64    2.36-9+rpt2+deb12u8 arm64        GNU C Library: Shared libraries
ii  libcurl4:arm64 7.88.1-10+deb12u7 arm64        easy-to-use client-side URL transfer library (OpenSSL flavour)
ii  liblzma-dev:arm64 5.4.1-0.2    arm64        XZ-format compression library - development files
ii  m4             1.4.19-3     arm64        macro processing language
ii  mariadb-client 1:10.11.6-0+deb12u1 arm64        MariaDB database client binaries
ii  mariadb-server 1:10.11.6-0+deb12u1 arm64        MariaDB database server binaries
ii  net-tools      2.10-0.1     arm64        NET-3 networking toolkit
ii  nfs-kernel-server 1:2.6.2-4    arm64        support for NFS kernel server
ii  openssh-server 1:9.2p1-2+deb12u3 arm64        secure shell (SSH) server, for secure access from remote machines
ii  php            2:8.2+93     all          server-side, HTML-embedded scripting language (default)
ii  php-bcmath     2:8.2+93     all          Bcmath module for PHP [default]
ii  php-cli        2:8.2+93     all          command-line interpreter for the PHP scripting language (default)
ii  php-curl       2:8.2+93     all          CURL module for PHP [default]
ii  php-fpm        2:8.2+93     all          server-side, HTML-embedded scripting language (FPM-CGI binary) (default)
ii  php-gd         2:8.2+93     all          GD module for PHP [default]
ii  php-intl       2:8.2+93     all          Internationalisation module for PHP [default]
ii  php-json       2:8.2+93     all          JSON module for PHP [default]
ii  php-ldap       2:8.2+93     all          LDAP module for PHP [default]
ii  php-mbstring   2:8.2+93     all          MBSTRING module for PHP [default]
ii  php-mysql      2:8.2+93     all          MySQL module for PHP [default]
ii  tar            1.34+dfsg-1.2+deb12u1 arm64        GNU version of the tar archiving utility
ii  tftpd-hpa      5.2+20150808-1.4 arm64        HPA's tftp server
ii  tftp-hpa       5.2+20150808-1.4 arm64        HPA's tftp client
ii  unzip          6.0-28       arm64        De-archiver for .zip files
ii  vsftpd         3.0.3-13+b2  arm64        lightweight, efficient FTP server written for security
ii  wget           1.21.3-1+b1  arm64        retrieves files from the web
ii  zlib1g:arm64   1:1.2.13.dfsg-1 arm64        compression library - runtime
Yeni parola: Yeni parolayı tekrar girin: passwd: şifre başarıyla güncellendi
find: ‘/home//fog_web_1.5.10.1593.BACKUP/management/other/’: Böyle bir dosya ya da dizin yok
init.xz: Tamam
init_32.xz: Tamam
bzImage: Tamam
bzImage32: Tamam
FOGService.msi: Tamam
SmartInstaller.exe: Tamam
'bzImage' -> '/var/www/html/fog//service/ipxe/bzImage'
'bzImage32' -> '/var/www/html/fog//service/ipxe/bzImage32'
'init.xz' -> '/var/www/html/fog//service/ipxe/init.xz'
'init_32.xz' -> '/var/www/html/fog//service/ipxe/init_32.xz'
'FOGService.msi' -> '/var/www/html/fog//client/FOGService.msi'
'SmartInstaller.exe' -> '/var/www/html/fog//client/SmartInstaller.exe'
mysqlnd
You are about to be asked to enter information that will be incorporated
into your certificate request.
What you are about to enter is what is called a Distinguished Name or a DN.
There are quite a few fields but you can leave some blank
For some fields there will be a default value,
If you enter '.', the field will be left blank.
-----
Country Name (2 letter code) [AU]:State or Province Name (full name) [Some-State]:Locality Name (eg, city) []:Organization Name (eg, company) [Internet Widgits Pty Ltd]:Organizational Unit Name (eg, section) []:Common Name (e.g. server FQDN or YOUR name) []:Email Address []:You are about to be asked to enter information that will be incorporated
into your certificate request.
What you are about to enter is what is called a Distinguished Name or a DN.
There are quite a few fields but you can leave some blank
For some fields there will be a default value,
If you enter '.', the field will be left blank.
-----
192.168.0.66 []:Certificate request self-signature ok
subject=CN = 192.168.0.66
Site 001-fog disabled.
To activate the new configuration, you need to run:
  systemctl reload apache2
Enabling site 000-default.
To activate the new configuration, you need to run:
  systemctl reload apache2
yeniden adlandırıldı: '/etc/apache2/sites-available/001-fog.conf' -> '/etc/apache2/sites-available/001-fog.conf.1726310197'
/etc/apache2/sites-available/001-fog.conf ve /etc/apache2/sites-available/001-fog.conf.1726310197 dosyaları birbirinden farklı
ln: '/var/www/html/fog/fog' sembolik bağı oluşturulamadı: Dosya var
ERROR: Module php does not exist!
Considering dependency proxy for proxy_fcgi:
Module proxy already enabled
Module proxy_fcgi already enabled
Module setenvif already enabled
Module rewrite already enabled
Considering dependency setenvif for ssl:
Module setenvif already enabled
Considering dependency mime for ssl:
Module mime already enabled
Considering dependency socache_shmcb for ssl:
Module socache_shmcb already enabled
Module ssl already enabled
Enabling site 001-fog.
To activate the new configuration, you need to run:
  systemctl reload apache2
Site 000-default disabled.
To activate the new configuration, you need to run:
  systemctl reload apache2
● apache2.service - The Apache HTTP Server
     Loaded: loaded (/lib/systemd/system/apache2.service; enabled; preset: enabled)
     Active: active (running) since Sat 2024-09-14 13:38:33 +03; 48ms ago
       Docs: https://httpd.apache.org/docs/2.4/
    Process: 132931 ExecStart=/usr/sbin/apachectl start (code=exited, status=0/SUCCESS)
   Main PID: 132936 (apache2)
      Tasks: 6 (limit: 9247)
        CPU: 84ms
     CGroup: /system.slice/apache2.service
             ├─132936 /usr/sbin/apache2 -k start
             ├─132943 /usr/sbin/apache2 -k start
             ├─132944 /usr/sbin/apache2 -k start
             ├─132945 /usr/sbin/apache2 -k start
             ├─132946 /usr/sbin/apache2 -k start
             └─132947 /usr/sbin/apache2 -k start

Eyl 14 13:38:33 whiteflor systemd[1]: Starting apache2.service - The Apache HTTP Server...
Eyl 14 13:38:33 whiteflor apachectl[132935]: AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
Eyl 14 13:38:33 whiteflor systemd[1]: Started apache2.service - The Apache HTTP Server.

● php8.2-fpm.service - The PHP 8.2 FastCGI Process Manager
     Loaded: loaded (/lib/systemd/system/php8.2-fpm.service; enabled; preset: enabled)
     Active: active (running) since Sat 2024-09-14 13:38:33 +03; 9ms ago
       Docs: man:php-fpm8.2(8)
    Process: 132942 ExecStartPost=/usr/lib/php/php-fpm-socket-helper install /run/php/php-fpm.sock /etc/php/8.2/fpm/pool.d/www.conf 82 (code=exited, status=0/SUCCESS)
   Main PID: 132932 (php-fpm8.2)
     Status: "Ready to handle connections"
      Tasks: 6 (limit: 9247)
        CPU: 57ms
     CGroup: /system.slice/php8.2-fpm.service
             ├─132932 "php-fpm: master process (/etc/php/8.2/fpm/php-fpm.conf)"
             ├─132937 "php-fpm: pool www"
             ├─132938 "php-fpm: pool www"
             ├─132939 "php-fpm: pool www"
             ├─132940 "php-fpm: pool www"
             └─132941 "php-fpm: pool www"

Eyl 14 13:38:33 whiteflor systemd[1]: Starting php8.2-fpm.service - The PHP 8.2 FastCGI Process Manager...
Eyl 14 13:38:33 whiteflor systemd[1]: Started php8.2-fpm.service - The PHP 8.2 FastCGI Process Manager.
ERROR 1146 (42S02) at line 1: Table 'fog.globalSettings' doesn't exist

**Comment by rluzuriaga** [comment]
This seems to be an issue with fogproject not FOS, transferring it to the correct repository.

**Comment by rluzuriaga** [comment]
@spamkutu I haven't used a raspberry pi 5 with FOG, but a new stable version was release earlier today. Can you try installing the newest stable version, and let us know if it works or doesn't?

**Comment by spamkutu** [comment]
Of course, could you please provide the exact full link adress for the sake of accurary? Additionaly , I prefer loading directly as root, but if there's Docker supported compose.yaml that wouln't be bad either. Before I attemp the installation, I would also like the request the minimum full version number, along wiith the complete link, if possible. Thank you very much for your attention and assistance.

**Comment by darksidemilk** [comment]
If you can get git on the raspberry pi, then I would just follow the docs on installing from git.
https://docs.fogproject.org/en/latest/install-fog-server

The latest stable version is [1.5.10.1615](https://github.com/FOGProject/fogproject/releases/tag/1.5.10.1615)
You can download the zip from the release assets if git isn't an option.

**Comment by spamkutu** [comment]
Allright, I'm on the way, I think i can load and try it this evening. Thank you very much!!

**Comment by spamkutu** [comment]
I updated with "git pull" and reinstalled with "install.sh". I believe it was installed or upgraded without issues now, as I don't see any problems. Where can I find the most accurate documentation for usage right now? When taking an image, do I always have to use **Sysprep** to create a hardware-independent image? It’s important for me to preserve the current state, including the hardware and drivers. Also, I currently don't have any other than the capability to use PXE over Wi-Fi, and I couldn’t manage it via Ethernet either, because the computer from which I want to take the image is old and can only connect through an external Wi-Fi USB adapter there is no eth on board (-i could pay and get an eth adapter but thats for a last resort-) , and it doesn’t boot from that device. Maybe if a small program could recognize the Wi-Fi at startup and provide an additional option to connect via PXE, it would be better. Right now, I only need suitable and up-to-date source documentation.

Sincerely

**Comment by spamkutu** [comment]
I am going to close this issue since everything seems like work well.
