### ISSUE TITLE
Compiling iPXE binaries trusting your SSL certificate Failed

### ISSUE THREAD

**Issue by patrix87** [FOGProject/fogproject#649]
**Describe the bug**
Compiling iPXE binaries trusting your SSL certificate fails on CentOs 9 and Ubuntu 24 on Stable and Dev Branch.

**To Reproduce**
1. Install CentOs 9 or Ubuntu 24 server.
2. Pull stable or dev branch or fogproject
3. Run the install script and enable https

**Expected behavior**
The installation should complete.

**Screenshots**

![image](https://github.com/user-attachments/assets/8b774a3e-0d35-4a93-a659-56fec40cd86d)

**Software (please complete the following information):**
 - FOG version: 1.5.10.1615
 - FOS kernel ? Latest ?
 - OS: Ubuntu 24.04.1 and CentOs 9 Stream

**Additional context**

I think that the compilation fails because the GCC Compiler version is too recent.

**Comment by patrix87** [comment]
[fog_error_1.5.10.1615.log](https://github.com/user-attachments/files/17063183/fog_error_1.5.10.1615.log)
[fog_ipxe-build_1.5.10.1615.log](https://github.com/user-attachments/files/17063184/fog_ipxe-build_1.5.10.1615.log)
[foginstall.log](https://github.com/user-attachments/files/17063185/foginstall.log)

**Comment by xeebuc** [comment]
You need to install the package : gcc-aarch64-linux-gnu

**Comment by msawyer91** [comment]
> You need to install the package : gcc-aarch64-linux-gnu

This worked for me. I reran the installation and while the compilation step took a solid 5-6 minutes, it completed successfully and the remainder of the installation concluded successfully as well.

Much obliged!

**Comment by monsn0** [comment]
> You need to install the package : gcc-aarch64-linux-gnu

I also ran into this with a new FOG server deployment on Debian 12.
I wasn't using a cert in my case and no errors came up during the installfog.sh script. I noticed it when I ran buildipxe.sh later.
Simply installing this package and re running the buildipxe.sh script resolved it.
