### ISSUE TITLE
on install/upgrade it deletes the /var/www/fog/service/ipxe folder which contains items for the custom menu

### ISSUE THREAD

**Issue by vipconsult** [FOGProject/fogproject#65]
I want to run regular updates but the problem is that the installation script deletes the /var/www/fog folder 

so all custom iso files for the custom pxe menus get deleted as well
/var/www/fog/service/ipxe

is there any way to avoid this ?

**Comment by mastacontrola** [comment]
Yep, update please.

I've added code that moves the folder to the backup path and then copies it back.  It will then overwrite the files that have changed in the trunk, and leave any new files that aren't a "native" part of FOG.

**Comment by vipconsult** [comment]
Just updated the latest git and it didn't work as I expected
I had some custom iso images in 
/var/www/fog/service/ipxe/custom

and after the update the folder was empty.

No tracing down your code to see if I can find the culprit and submit a commit.

**Comment by mastacontrola** [comment]
Check the /home folder on your system.

My guess is the files you saw were from a prior update where they were already missing.

**Comment by mastacontrola** [comment]
trunk/lib/common/functions.sh lines 996 through 1014.  This is the "magic" that mv's the file to a backup location, then copies it back, then copies the new over the old files.

**Comment by vipconsult** [comment]
ok , let me check and will let you know.
