### ISSUE TITLE
Possible bug regarding arm64 in working-1.6 branch?

### ISSUE THREAD

**Issue by osiktech** [FOGProject/fogproject#656]
I am playing at the moment with [UTM](https://github.com/utmapp/UTM) trying to boot my arm64 virtual machine with FOG. When I fixed #655 for me iPXE booting  works fine and brought up the well known FOG iPXE menu. 

But when I tried to register, I noticed the VM was fetching `bzImage` and `init.xz` while I was expecting it to fetch `arm_Image` and `arm_init.cpio.gz`. 

I was going through the code and found `packages/web/lib/fog/bootmenu.class.php` being the file, doing the necessary stuff to build the `packages/web/service/ipxe/boot.php`.

While debugging I noticed that lines https://github.com/FOGProject/fogproject/blob/a77158c84ed3c8cdbd970d9a49e2797a4f6fec98/packages/web/lib/fog/bootmenu.class.php#L210 and https://github.com/FOGProject/fogproject/blob/a77158c84ed3c8cdbd970d9a49e2797a4f6fec98/packages/web/lib/fog/bootmenu.class.php#L347 are using `arm`.

My question, shouldn't this be `arm64`, since utils/FOGiPXE/buildipxe.sh is building only arm64 and not arm?

I changed it on my server instance and I am one step nearer booting my arm64 UTM VM.

**Comment by mastacontrola** [comment]
So 210, I think is correct.

All it's looking for is if arm is part of the request variable.

347 might need to be arm64, or changed to `stripos(($_REQUEST['arch'] ?? ''), 'arm'))` from `($_REQUEST['arch'] ?? '') == 'arm'`

I've pushed what I think should do this for both dev-branch and working-1.6

**Comment by osiktech** [comment]
Thanks, I will check out later the newest version and deploy it to see if it works. I will get back with a reply.

**Comment by osiktech** [comment]
Works like a charm
