### ISSUE TITLE
PHP 5 Compatibility

### ISSUE THREAD

**Issue by fr3d73r** [FOGProject/fogproject#66]
Group Management is broken as follows:
`&`  preceding objects was used in PHP 4 to reference them directly instead of copying. As of PHP 5 this is the default behavior and any case where it is used causes issues. Please make corrections.

**Comment by mastacontrola** [comment]
I don't know what you're talking about.

What makes you think group management is broken as you describe?

Just because you say something does not mean it is so.  Can you please be more descriptive?

**Comment by fr3d73r** [comment]
Please disregard. The issue was resolved in 5020
