### ISSUE TITLE
Host page does not utilize pagination and large number of hosts causes slow load times/server crashes

### ISSUE THREAD

**Issue by tailz303** [FOGProject/fogproject#666]
We are a small to medium school district that uses fog for our 50 schools. 
We looked into having one master server for everything and storage nodes at each location but quickly ran into the issue where the sheer number of hosts would cause major issues and make everything unusable. We ended up having to go by conesite and have 1 master at each. 

I believe this issue could be resolved by implementing Pagination on the hosts page which would save the php from having to generate every host line when doing anything. Is this something that can be done? Me and some other employees here have taken a day to try and figure out the code but the parts that render are referenced in such a way that we weren't quite able to make sense of it. Are we the only one that has this problem? Surely someone else out there has 20k machines that are all registered on their master etc.

**Comment by darksidemilk** [comment]
What version of fog are you using? Pagination is enabled in 1.6. If you install from the working-1.6 branch you can give the beta a try. I say beta but it's production ready, I use it in production and have for a year.

**Comment by tailz303** [comment]
Currently using 1.5.10.1622 but this is a test server so I'll give that a shot. Thanks for that information though, we couldn't figure out why it wouldn't have been added yet but that makes sense.

**Comment by tailz303** [comment]
The update was hard to figure out but thanks to chatgpt I found that the following works for anyone else that needs this too:
git clone https://github.com/FOGProject/fogproject.git
cd fogproject
git checkout working-1.6
cd bin
sudo ./installfog.sh

**Comment by darksidemilk** [comment]
Sorry, I should have linked the docs, I was just giving a quick reply from my phone
https://docs.fogproject.org/en/latest/installation/server/install-fog-server/ glad chat gpt can find that
