### ISSUE TITLE
upgrading kernel returns an error

### ISSUE THREAD

**Issue by vipconsult** [FOGProject/fogproject#68]
http://screencast.com/t/wAwAjRqf

I think the problem is that it tries to copy the new kernel to 
/var/www/fogservice/ipxe/bzImage

there should be a trailing slash after fog

/var/www/fog/service/ipxe/bzImage

**Comment by mastacontrola** [comment]
This is a known issue. I have not been able to figure out why it's happening at all.  That said, it gets this information from the database so is not a hard thing to correct for at least from your side.

Go to:

FOG Configuration->FOG Settings->TFTP Server->FOG_TFTP_PXE_KERNEL_DIR

You can change the path there and all will start to work.

**Comment by vipconsult** [comment]
thanks , that solved it,
