### ISSUE TITLE
latest git version seems to break PXE menu

### ISSUE THREAD

**Issue by terryb8s** [FOGProject/fogproject#71]
Previously (47## git version) I had no issues with the latest 5217 the PXE menu never appears either my computers freeze or boot into windows. seems to stop at the features listing list word is PXEXT

**Comment by mastacontrola** [comment]
Sorry it's taken so long to get back.

I was aware of it and it has since been fixed.

Appreciate the information, and just writing to ask you please to update and you should be good to go.
