### ISSUE TITLE
input/output error on PXE menu

### ISSUE THREAD

**Issue by terryb8s** [FOGProject/fogproject#72]
Thanks for fixing the previous issue so quickly, I am now getting an input/output error on my Dell desktops (Intel network adapters), though my HP desktops appear to be fine.

input/output error (http://ipxe.org/1d0c6539)

![img_20151109_085314](https://cloud.githubusercontent.com/assets/4591539/11022351/6a80810a-86c1-11e5-89f3-86eabf2abe56.jpg)

**Comment by mastacontrola** [comment]
If you update to latest, does this still occur?

I'm closing for now, but please feel free to add info as needed.
