### ISSUE TITLE
Add IPXE Host Parameter

### ISSUE THREAD

**Issue by tkrause** [FOGProject/fogproject#73]
It would be nice to have a host parameter variable similar to how Arch is set that can be used in the Advanced menu. This can be implemented by adding the code below on line 20 of lib/fog/BootMenu.class.php

```
        if ( $Host && $Host->isValid() ) {
            $Send['booturl'][] = 'set hostname '.$Host->get('name');
        }
```

**Comment by mastacontrola** [comment]
This can already be done with hooks.

**Comment by mastacontrola** [comment]
I'm going to close this "issue" as it is already capable of being done and an example exists in /var/www/{,html/}fog/lib/hooks/BootItem.hook.php,
