### ISSUE TITLE
Virtualbox 5.0.14

### ISSUE THREAD

**Issue by Ryuchen** [FOGProject/fogproject#85]
I has used Virtualbox 5.0.14 and fog 1.20 to clone Windows Xp, but I has a trouble to register a host to server. I use the quick registeration, but when I boot the virtualbox xp pc by PXE, the client was crashed down at the window display /bzimage32... between 6% to 17%, I had tried many many many times ,but I can't figure it out. please tell my why!

**Comment by mastacontrola** [comment]
Please use different boot files.

undionly.kpxe is only suggested as a starting point, and while it works for most, it does not ALWAYS work.  Particularly relating to 1.2.0, Virtual Box works best (from experience) with ipxe.pxe file.
