### ISSUE TITLE
Feature request - reboot with maximum time

### ISSUE THREAD

**Issue by msillence** [FOGProject/fogproject#88]
Hi,

Thanks for a great product, there is one thing that would be great to have - the option to delay the reboot of windows but with a maximum time limit. The force reboot is a bit brutal.

Thanks,
M

**Comment by mastacontrola** [comment]
The new client already has this available.  It's called the "GRACE Period Timeout"

It will not work on the "legacy client" which are what were shipped with FOG Versions 1.2.0 and below.  With the new client, not only can you specify the grace period timeout through the FOG GUI, you can also specify the check-in cycles and whether or not to enforce reboots right from the GUI.  And with 0.10.x versions of the FOG Client, you can even specify whether to enforce hostname/AD join's happen on boot or every check-in cycle.

I'd highly recommend taking a look at this.

Sorry it took so long to respond, I think I saw the title and was just not understanding the request fully.
