### ISSUE TITLE
libapache2-mod-php5 missing

### ISSUE THREAD

**Issue by abulhol** [FOGProject/fogproject#92]
I installed FOG on Ubuntu 14.04, but when I opened the fog/management page in the browser, there was a lot of PHP code showing up. So after googling I found I need to install libapache2-mod-php5, now it works fine. 
Is this maybe missing in the installer?

**Comment by mastacontrola** [comment]
What version of fog?

I'm aware there were potentially issues with this in 1.2.0, but the trunk versions actually do install this.

**Comment by abulhol** [comment]
Yes, I use fog 1.2.0 which I downloaded from https://sourceforge.net/projects/freeghost/files/
